### ISSUE TITLE
discussion: databinding setting a 'data-...' attribute - 2 methods

### ISSUE THREAD

**Issue by pke** [winjs/winjs#1001]
Which pattern is recommended by the WinJS team:
`data-win-bind="this['data-value']:value WinJS.Binding.setAttribute"`
vs
`data-win-bind="dataset.value:value"`

I prefer the latter. Any (performance) issues or side effects known with it?

**Comment by rigdern** [comment]
We don't have a preference of one over the other. We also do not know of any performance issues or side effect differences between those 2 patterns. So use whichever one you prefer. :smile:

**Comment by pke** [comment]
I prefer the one without the `WinJS.Binding.setAttribute`.

btw: Can I bind to an item in an array like `style.width:data.sizes[0]` Somehow it throws with an error when the binding happens.

**Comment by rigdern** [comment]
You cannot data bind to an array. You can see [here](https://github.com/winjs/winjs/blob/b57b16773a6b57fadc5efcdd54d80a055d34a07b/src/js/WinJS/Binding/_Data.js#L594) that `WinJS.Binding.as` doesn't hook arrays for observability.

**Comment by pke** [comment]
Yes for array binding I wrote a binding converter.

**Comment by pke** [comment]
A little follow up to this. Using 

```

```
<span class="permission" data-win-bind="this['data-level']:board.prefs.permissionLevel WinJS.Binding.setAttribute;textContent:board.prefs.permissionLevel"></span>
```

**Comment by rigdern** [comment]
If instead of doing data binding, you write JavaScript code which sets thru `dataset` does the bug repro?

Sounds like it could be an IE bug. You can report it at https://connect.microsoft.com/ie/

**Comment by pke** [comment]
created a bug report here https://connect.microsoft.com/IE/feedbackdetail/view/1235657/updating-an-elements-dataset-from-javascript-does-not-re-apply-css-styles-with-attribute-selectors

**Comment by rigdern** [comment]
I see you created a nice reduced repro. Thanks, we appreciate it! :smile:

**Comment by pke** [comment]
Yes, it was easily reproducible in IE11, have not tested it in Spartan yet though. Do you guys know already which browser engine will be the base in wwahost.exe for Win10?

**Comment by TheWrathOfConst** [comment]
WWAs will also use the new Project Spartan engine

**Comment by pke** [comment]
Great! ES6 ftw

**Comment by pke** [comment]
This issue has been fixed for Windows 10 in Edge. 
https://connect.microsoft.com/IE/feedback/details/1235657/updating-an-elements-dataset-from-javascript-does-not-re-apply-css-styles-with-attribute-selectors
Do any of you know if Edge will be also used on Windows 8.x to power WWAs there?

**Comment by soren121** [comment]
I tested my WP8.1 WinJS app in the W10 emulator a couple days ago with build 10240, and it ran with the Edge engine.
