### ISSUE TITLE
WinJS.UI.Hub: Can it be used on Windows Phone (WinJS 3.1)?

### ISSUE THREAD

**Issue by pke** [winjs/winjs#1002]
My app needs to use a Hub instead of a Pivot control for its data, cause my displayed data does not "wrap". I need a clear start and end, and no continuous scrolling, like the Pivot control offers.

**Comment by rigdern** [comment]
The design of Hub for 3.0 was targeting desktop rather than mobile. We recommend using Pivot on mobile instead.
