### ISSUE TITLE
ListView: <Project Reddit>

### ISSUE THREAD

**Issue by RecklessJaska** [winjs/winjs#1003]
Feature: ListView
Environment: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.71 Safari/537.36 Edge/12.0
Source: http://try.buildwinjs.com Play With ListView
Layout: List
Orientation: Vertical
Items Reorderable: False
Items Draggable: False
Tap Behavior: Direct Select
Selection Mode: Single
Item Template: Text With Image
Group Items: False
Group Header Template: Text With Image
Group Header Position: Top
Group Header Tap Behavior: None
Data Source: 100 Items

**Comment by omnoms** [comment]
What's the issue? =P

**Comment by rigdern** [comment]
Looks like this bug was opened without any repro information.
