### ISSUE TITLE
Extra head and body tag in ListView windows phone 8.1

### ISSUE THREAD

**Issue by tnevda** [winjs/winjs#1005]
Unsafe local function innerHTML inserts extra `<head>` and `<body>` in WinJS function `ListView_setupInternalTree()`  and throws an error. This issue shows only on WIndows Phone 8.1 (device and emulator).

##### WinJS :
```
...
_setupInternalTree: function ListView_setupInternalTree() {
	_ElementUtilities.addClass(this._element, _Constants._listViewClass);
	_ElementUtilities[this._rtl() ? "addClass" : "removeClass"](this._element, _Constants._rtlListViewClass);
	this._element.innerHTML =
		'<div tabIndex="-1" role="group" class="' + _Constants._viewportClass + ' ' + _Constants._horizontalClass + '">' +
			'<div></div>' +
			'<div class="' + _Constants._scrollableClass + '">' +
				'<div class="' + _Constants._proxyClass + '"></div>' +
			'</div>' +
			'<div></div>' +
			'<div></div>' +
		'</div>' +
	   '<div aria-hidden="true" style="position:absolute;left:50%;top:50%;width:0px;height:0px;" tabindex="-1"></div>';
	this._viewport = this._element.firstElementChild;
...
```
##### Output of this._element.innerHTML :	
```
<head></head>
<body>
	<div tabIndex="-1" class="win-viewport win-horizontal" role="group">
		<div></div>
		<div class="win-surface">
			<div class="_win-proxy"></div>
		</div>
		<div></div>
		<div></div>
	</div>
	<div aria-hidden="true" style="position:absolute;left:50%;top:50%;width:0px;height:0px;" tabindex="-1"></div>
</body>

```
I tried including [winstore-jscompat.js](https://github.com/MSOpenTech/winstore-jscompat) but the problem still persist

**Comment by tnevda** [comment]
I have to put winstore-jscompat in the  merge folder on my cordova app otherwise it won't work. Using the winstore-jscompat might impact on app perfomance though (e.g. delays between pages in WinJS Pivot)

**Comment by alxlu** [comment]
It looks like this should be fixed now: http://stackoverflow.com/a/29035134
>There was a bug in the jscompat shim previously that can cause extra HTML elements to be added to the DOM. The jscompat shim is included in VS templates by default and only is active for the Windows platform (not WP8), so this may be what you are running into. Grab the latest library from the link above and it should resolve your issue.
