### ISSUE TITLE
Pivot mouse swipe support

### ISSUE THREAD

**Issue by nikolafon** [winjs/winjs#1008]
Hi,
I've noticed that in current demo version (4.0 preview), mouse pointer "swipe gesture" works only in Safari for pivot control. Does it suppose to be like that? It works with touch devices but it would be nice that you can emulate swipe gestures with mouse pointer, cross platform.

**Comment by rigdern** [comment]
Mouse swipe isn't an intended feature. It happens to work in Safari as a side effect of our current touch implementation but our intention was to only support swipe for touch.

**Comment by nikolafon** [comment]
I understand. I guess I got used to Windows phone emulator which provides such feature.
