### ISSUE TITLE
WinJS.UI.SettingsFlyout.populateSettings(e) fails second time with different set of commands

### ISSUE THREAD

**Issue by pke** [winjs/winjs#1010]
As Kraig describes in [his blogpost](http://www.kraigbrockschmidt.com/2013/03/13/mixing-links-flyouts-settings-winjs/) you cannot populate the settings page with different combinations of flyouts and commands

> my previous statement about interspersing flyouts and commands by calling populateSettings multiple times with different contents in e.detail.applicationcommands doesn’t actually work. The problem is that the call to populateSettings stores the applicationCommands object you pass in another variable, and it uses this variable in its handler for the command to check if the command is valid. So although command from earlier calls to populateSettings appear in the Settings pane, they won’t do anything because WinJS won’t find that command.

Is there a fix for that already?

**Comment by rigdern** [comment]
I don't think this is fixed. `SettingsFlyout` is getting deprecated so its unlikely to get fixed. The reasoning for the deprecation is that in Win10 the UI design has changed such that we recommend having a settings page rather than putting settings into a flyout.
