### ISSUE TITLE
WinJS.UI.SearchBox: Cannot be created on Windows Phone 8.1

### ISSUE THREAD

**Issue by pke** [winjs/winjs#1012]
Using WinJS 3.1
0x80040154 - JavaScript runtime error: Class not registered
Exception was thrown at line 70271, column 21 in ms-appx://trello.windows/WinJS/js/WinJS.js
`if (this._inputElement.msGetInputContext && this._inputElement.msGetInputContext()) {`

**Comment by rigdern** [comment]
@jseanxu, check if this repros in WinJS 3.1 on a Phone 8.1 app.

**Comment by jseanxu** [comment]
Confirmed, repros in the emulator via VS 2013 and the 3.0.1 off the try-site.

**Comment by jseanxu** [comment]
Dupe of #686
This issue was fixed by 2e86e58
