### ISSUE TITLE
WinJS.Binding.List: itemmoved event how to get the value of the element that was replaced?

### ISSUE THREAD

**Issue by pke** [winjs/winjs#1014]
It seems when the `itemmoved` fired the underlying binding list has already changed and there is no way to get the value of the old item at the postion specified by the events "newIndex".
So what I want is: User drags and moves an item in a WinJS.UI.ListView from position 1 to position 0. That will also move the item that was on position 0 to position 1. I need to get the item that was at position 0.

also there is a doc bug: the docs say
> index: the index of the item in the list

but there is no such key in the events details.

**Comment by rigdern** [comment]
Thanks, I filed a doc bug.

When you call `move` on a `Binding.List`, no items are removed from the list. The item whose place the mover took is just shifted over by 1 (either to the left or right depending on the relationship between `oldIndex` and `newIndex`). In the `itemmoved` handler, you can find the item whose place the mover took like this:

```js
list.addEventListener("itemmoved", function (ev) {
    var oldIndex = ev.detail.oldIndex;
    var newIndex = ev.detail.newIndex;
    var prevItemAtNewIndex = list.getAt(newIndex + (newIndex > oldIndex ? -1 : 1));
});
```
