### ISSUE TITLE
Deprecate Settings Flyout

### ISSUE THREAD

**Issue by nizh914** [winjs/winjs#1016]
The settings flyout is no longer a part of the Windows design language and therefore is being deprecated in WinJS 4.0. Documentation and code needs to be updated. By the 4.1 release there will be no Settings Flyout in code.

**Comment by pke** [comment]
Where is the new way of doing the settings documented?

**Comment by nizh914** [comment]
The public documentation is not available quite yet. But our recommendation would be to integrate your app settings as its own page within your app.

**Comment by pke** [comment]
Could you please elaborate on the thought process to deprecate the settings pane?
