### ISSUE TITLE
SearchBox dropdown liast not showing

### ISSUE THREAD

**Issue by ThatsIT** [winjs/winjs#1017]
I can see in console log that sugestioncollection is populated but no dropdown shows. 
using Cordova blank JavaScript template VS 2013.
Thanks

**Comment by rigdern** [comment]
@jseanxu Can you try to repro this?

**Comment by ThatsIT** [comment]
http://jsfiddle.net/chzmh109/ 
Entering a Australian post code like 6073 will get a result from ajax call, you can see that suggestionCollection is populated but no dropdown

**Comment by jseanxu** [comment]
You are populating the suggestionCollection asynchronously, in which case you need the event detail's `setPromise` API. I see you already attempted it but put it in the wrong place - the `setPromise` API has to be called synchronously.

Here is how the `suggestionrequested` hander should look like:
```js
function suggestionsRequestedHandler(eventObject) {
    eventObject.detail.setPromise(new WinJS.Promise(function (c) {
        var queryText = eventObject.detail.queryText, query = queryText.toLowerCase(), suggestionCollection = eventObject.detail.searchSuggestionCollection;
        if (query.length > 2) {
            var p = new RemoteData().postData("http://api.secondyearvisajob.com.au/api/LocationViews/SearchLocationViews", { query: query });
            p.done(function completed(request) {
                var obj = JSON.parse(request.response);
                obj.forEach(function (item) {
                    console.log(suggestionCollection);
                    eventObject.detail.searchSuggestionCollection.appendQuerySuggestion(item.FormatedLocation);
                });
            }, function error(request) {
                console.log(request);
            });
        }
    }));
}
```

Let me know if this resolves your issue in your cordova app as well. Thanks!

**Comment by ThatsIT** [comment]
Thanks working now
