### ISSUE TITLE
WinJS.UI.ListView: Can it display group headers horizontally but the items in each group in ListLayout?

### ISSUE THREAD

**Issue by pke** [winjs/winjs#1019]
When the listview has set its layout to "GridLayout" it displays the groups horizontally next to each other. The items are then layout in a grid below the group header. I would like to have the same group header layout but the items in ListLayout.
If I remember correctly there was something like "headerPosition" where you could change the position the header was displayed at (beside the group or on top of it).

**Comment by rigdern** [comment]
Yes, the property is called `groupHeaderPosition`. You can interactively explore the ListView's API [on this page of our website](http://try.buildwinjs.com/pages/listview/options/default.html).

**Comment by pke** [comment]
I see. This would still layout the groups itself also vertically. I'd like them horizontally and the list items vertical.

**Comment by rigdern** [comment]
I don't believe the `ListView` has that kind of layout built into it.

In trying to achieve such a layout, my first question for you would be what capabilities of the `ListView` are you using and are you sure you need a `ListView`?

If `ListView` is unnecessary, you could try achieving this layout using nested `Repeaters` (one to stamp out the groups and one to stamp out the items within each group). You can use `ItemContainer`s to achieve the list item visuals.

**Comment by pke** [comment]
Well, maybe the listview is too heavy for what I want. I have no more than a couple of items in each list. I like the drag&drop capabilities of it though. I think repeaters do not offer such?

**Comment by rigdern** [comment]
Correct, `Repeater` doesn't have built-in drag and drop support. You would have to implement it on your own.

**Comment by pke** [comment]
> In trying to achieve such a layout, my first question for you would be what capabilities of the  ListView  are you using and are you sure you need a  ListView?

I want to build a [Trello](https://trello.com) app. It needs draggable lists (Hub Sections in my prototype) and drag&drop within and across lists. Check out the prototype package from http://1drv.ms/1C3yn8z

**Comment by rigdern** [comment]
Because `Hub` and `Repeater` don't have built-in support for drag and drop, you'll have to implement drag and drop support yourself on top of those controls. You can either use the HTML5 drag and drop APIs directly or find a drag and drop library that works for you.
