### ISSUE TITLE
Typescript version of PageControlNavigator (navigate.js) for SPA should be a part of WinJS library

### ISSUE THREAD

**Issue by PavelPZ** [winjs/winjs#102]
... maybe with some router for WinJS Single Page Application support (inspired by asp.net routing syntax: 
any_spa_url#/{controller}/{action}/{id}).

navigate.js file is now generated from Navigation App vs.net template.

(sorry if I miss some other mechanism for SPA support)

**Comment by jayrenn** [comment]
@PavelPZ This has been a topic of much debate. For the time being, we will close this as a won't fix, but we may revisit this in the future.
