### ISSUE TITLE
data-win-bind and data-win-res don't work with section:'secondary' WinJS.UI.Command

### ISSUE THREAD

**Issue by nhutquang97** [winjs/winjs#1020]
data-win-bind and data-win-res don't work properly with WinJS.UI.Command and WinJS.UI.AppbarCommand

```html
            <button data-win-control="WinJS.UI.AppBarCommand"
                    data-win-options="{ icon: 'clear',
                                        section:'secondary' }"
                    data-win-res="{ winControl: { label:'clear_history' } }"
                    data-win-bind="winControl.onclick: onclickClearHistory"></button>
```
For this code, the label and the onclick event don't work, but if I change section to 'primary', they will. I tested with WinJS.Binding.processAll in ready state of PageControl.

**Comment by rigdern** [comment]
This is probably a dupe of #841. If so, it's not a data binding specific problem.

**Comment by rigdern** [comment]
Confirmed dupe of #841.
