### ISSUE TITLE
Dynamically adding / removing a Pivot page results in bad layout until you manipulate the UI

### ISSUE THREAD

**Issue by Doogie90** [winjs/winjs#1024]
Dynamically adding / removing a Pivot page results in bad layout until you manipulate the UI.  I have a sample app where I remove a page from a Pivot control on phone.  The page is removed but the layout is off / out of sync.  After you touch the screen / manipulate the UI, the layout fixes itself but it's jarring.
Once I touch the screen the pivot section snaps down to the correct position in the second image and all is well.  This is what the image looks like when the app loads (after removing the first pivot page in the ready event for page.)
![pageopens](https://cloud.githubusercontent.com/assets/10854024/6985376/a683dfe4-da00-11e4-9e84-9bb3624561fe.jpg)
The UI "jumps" in place after touching the screen:
![touchpage](https://cloud.githubusercontent.com/assets/10854024/6985392/da487d26-da00-11e4-92d1-06b2e4cd86b8.jpg)

I can provide a sample app.  (RobCamer from MSFT)

**Comment by jseanxu** [comment]
Debugged the issue - the styling issue is due to hub.css styling the pivot's viewport's margins, which is not supported.
