### ISSUE TITLE
Ratings: Example in Playground is not working

### ISSUE THREAD

**Issue by SteveALee** [winjs/winjs#1027]
Feature: Ratings
Environment: Mozilla/5.0 (Windows NT 6.3; WOW64; Trident/7.0; Touch; .NET4.0E; .NET4.0C; Tablet PC 2.0; .NET CLR 3.5.30729; .NET CLR 2.0.50727; .NET CLR 3.0.30729; InfoPath.3; rv:11.0) like Gecko
Source: http://try.buildwinjs.com/#play

Ratings control is not visible.
The WinJS.Application.onready callback is not being invoked. Perhaps this only happens in the WInRT context and not browsers? I see the other samples do not use this mechanism, rather the code to run is a file scope.

In general I find no docs that clearly extract WInJS from WinRT. Also no clues how to web debug client code in VS.

**Comment by jangajack** [comment]
Accidentally duplicated this issue, but it's still open... since April? Are you for real?

**Comment by rigdern** [comment]
This is now fixed. You may need to click the "Reset" button to see the updated sample code because the "Playground" saves the code you are working on to local storage.
