### ISSUE TITLE
ListView: <title here>

### ISSUE THREAD

**Issue by baid90** [winjs/winjs#1028]
Feature: ListView
Environment: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/39.0.2171.71 Safari/537.36 Edge/12.0
Source: http://try.buildwinjs.com Play With ListView
Layout: Grid
Orientation: Vertical
Items Reorderable: True
Items Draggable: True
Tap Behavior: Direct Select
Selection Mode: Multi
Item Template: Text With Image
Group Items: False
Group Header Template: Text
Group Header Position: Top
Group Header Tap Behavior: Invoke
Data Source: 100 Items

**Comment by TheWrathOfConst** [comment]
No title/repro steps provided. Looks like this was opened by accident. Closing this issue.
