### ISSUE TITLE
WinJS.UI.Hub: How to add HTML attributes to each section?

### ISSUE THREAD

**Issue by pke** [winjs/winjs#1030]
Is there a smart way to add the `draggable=true` attribute to all created `HubSection` HTML elements?

**Comment by jseanxu** [comment]
Depends on how you are populating the Hub.

If you are creating each HubSection declaratively in markup, then just add `draggable=true` to each declarative section.

If you are creating each HubSection imperatively and then set `Hub.sections`, then after creating each HubSection, you could set `draggable` on the element: `hubSection.element.draggable = true`.

**Comment by pke** [comment]
Right, I am creating them in code actually. And there I have access to the `element` of each section
