### ISSUE TITLE
Appbar bug after closing keyboard (windows phone 8.1)

### ISSUE THREAD

**Issue by tnevda** [winjs/winjs#1032]
I'm using a global appbar on my single page app with WinJS 4.0.
 
Case 1 :
The home.html displays the appbar and a form.html (navigated from the home.html) doesn't display the appbar. If I focus on 2 or more input/textarea elements in the form.html without having the phone keyboard closed (by clicking other part of the page) and then I closed the phone keyboard by pressing phone back button, returning to previous page (home.html) doesn't show the appbar again.

Case 2 :
Both home.html and form.html displays the appbar. After running the same scenario as above, closing the keyboard with the phone back button will cause appbar to floats in the middle of the page (both form.html and home.html). Focusing on an input/textarea again will place the appbar back to the bottom of the page.

Tested on Windows Phone 8.1, this issue doesn't show on windows phone universal emulator.

**Comment by AmazingJaze** [comment]
Hi tnveda, can you provide a page/app that repros this bug? You can share the reduced repro on OneDrive as described on our wiki (look at the "Sharing Videos and full Code Samples" section).
