### ISSUE TITLE
WinJS.UI.ListView: [Phone 2.1] _createContainers broken with fast dataSource updates

### ISSUE THREAD

**Issue by pke** [winjs/winjs#1034]
My app (https://github.com/pke/trellomx) assigns a `BindingList` to a listview using `data-win-options`. This list is, at the beginning, empty. The items for the list are loaded async and pushed into the list when they arrive. This works well on WinJS 2.0 (Desktop). However, the same code on WinJS 2.1 Phone always displays an empty listview.
I found out several things:

1. The Phone WinJS does not seem to listen to iteminserted etc events of the datasource. I have to call `list.notifyReload()` after all items have been pushed to the list to get even a reaction from the listview code.
2. The listview code in `_createContainers` never completes the second time, if the number of items has changed from "0" to something else, because the `that._listView._layout.numberOfItemsPerItemsBlock` promise is in "Canceled" error state always. See this screen:
![image](https://cloud.githubusercontent.com/assets/164625/7043596/287482ae-ddeb-11e4-850e-2ac621975e5e.png)
The next continuation handler `}).then(function (blockSize) {` is never called a second time.

Maybe the promise is canceled because the changes in the list come in very fast, but that does not seem to be a problem on WinJS 2.0 (Desktop)

**Comment by mikewjackson** [comment]
We are discussing to see if this is feasible to backport the fix.

**Comment by mikewjackson** [comment]
Unfortunately, we aren't able to backport this fix
