### ISSUE TITLE
WinJS.UI.Pivot: How to swipe on headers too

### ISSUE THREAD

**Issue by pke** [winjs/winjs#1037]
I remember in WP7.x you could also swipe the Pivot control on the headers. Now in WinJS it seems you can only click the headers to switch between pivot sections but not do a swipe gesture on them.
Is there some setting/CSS style that enables that?

**Comment by TheWrathOfConst** [comment]
@pke Are you trying to swipe via touch, or mouse? Pivot (should) currently support swiping on headers via touch, but it does not work with mouse

**Comment by pke** [comment]
Touch I believe. I'll check again
