### ISSUE TITLE
Split WinJS into multiple files

### ISSUE THREAD

**Issue by LiangTheDev** [winjs/winjs#1038]
Currently, winjs is a single huge js file. While it has simplicity in it, it also causes some issues.

When including this single js file in a Windows Store app, it causes byte code generation process to use a lot of memory during application install, to the extend that it exceeds memory usage allowed by phone. Memory usage will easy when the code is split into multiple js files as byte code generation is 1 file at a time.

We should at least provide an option for apps/sites to include winjs as several js files instead of 1 js files. For sites, multiple js files should also improve perf as it allows compiling and running the first js file while we are downloading the 2nd js file, instead of waiting for the huge file to be downloaded and then compiled and executed.

**Comment by pke** [comment]
split into base functionality and ui/controls. If I don't use FlipView, SearchBox why should the code be in memory?

**Comment by TheWrathOfConst** [comment]
@pke That's our eventual plan. We're working on breaking WinJS down into smaller files

**Comment by gleborgne** [comment]
+1 on that. Every controls should be on a separate file

**Comment by phosphoer** [comment]
I have changes in code review to accomplish the initial version of this here: 03e9940574b9d77509d54252257ba3090cd86e38

For now is just base.js/ui.js, eventually we can move towards having one file per control.

**Comment by phosphoer** [comment]
Implemented in e37bdcc03076191207c5fad0bf35166f0ebd7d81
