### ISSUE TITLE
Side effect of using WinJS.UI.Pages.render for flyouts

### ISSUE THREAD

**Issue by pke** [winjs/winjs#1040]
I am (miss)using the `WinJS.UI.Pages.render` method to have html/css/js nicely coupled together in a fragment that is self contained. When I want to display the flyout I just call:
`WinJS.UI.Pages.render("/pages/_createBoardFlyout.html", document.body, anchor:event.target)`
And it is displayed. The logic inside `_createBoardFlyout.js` wires everything up:

```
WinJS.UI.Pages.define("/pages/_createBoardFlyout.html", {
    processed: function(element, options) {
      var flyout;
      flyout = document.querySelector(".addBoardFlyout").winControl;
      flyout.element.onsubmit = function(event) {
        trello.api.postAsync("/boards", {
          name: event.target.elements.title.value
        }).then(function(board) {
          trello.app.model.boards.push(board = new trello.app.model.Board(board));
          flyout.hide();
          return WinJS.Navigation.navigate("/pages/boardPage.html", {
            board: board
          });
        });
        return false;
      };
      flyout.show(options.anchor);
      return flyout.onafterhide = function() {
        return flyout.element.parentElement.removeChild(flyout.element);
      };
    }
  });
```

And it __seems__ to work. However are there any side-effects of using `WinJS.UI.Pages` instead of `WinJS.UI.Fragments`? The latter missing the ability to have the js-code coupled with its lifetime.

__edit__: Maybe I further describe my usecase for this. In my Universal app:

```
addBoard = function (event) {
if WinJS.Utilities.isPhone
    WinJS.Navigation.navigate("/pages/_addBoard.html")
  else
    WinJS.UI.Pages.render("/pages/_addBoard.html", document.body, anchor:event.target)
}
```

The appbar command in both apps has this function as click handler.

**Comment by jdalton** [comment]
I'm not aware of any side-effects of this so if it's working then great!
