### ISSUE TITLE
WinJS.Navigation: How to prevent a page from being part of the back history?

### ISSUE THREAD

**Issue by pke** [winjs/winjs#1041]
How can I prevent Page "B" from being part of the back history when I navigate like this:
`A -> B -> C`

I know I could call WinJS.Navigation.history.pop() in `B.unload` but is there an easier way like in the `WinJS.Navigation.navigate` method as an option to not add the page to the history?

**Comment by nhutquang97** [comment]
You can call
```
WinJS.Application.history.current.initialPlaceholder = true;
```
before you navigate.

**Comment by pke** [comment]
`WinJS.Navigation.history.current.initialPlaceholder = true;` works, thanks!
