### ISSUE TITLE
Cant add events to Search box

### ISSUE THREAD

**Issue by ThatsIT** [winjs/winjs#1043]
See jsfiddle http://jsfiddle.net/e28e3eat/ 
I have tried without namespace also

**Comment by rigdern** [comment]
Functions that you want to use declaratively have to be marked specially for security reasons. You can pass them thru [`WinJS.UI.eventHandler`](https://msdn.microsoft.com/en-us/library/windows/apps/hh967816.aspx).

See http://jsfiddle.net/pwaqkkew/.
