### ISSUE TITLE
WinJS.UI.AppBarCommand: setting hidden to true does not hide the command

### ISSUE THREAD

**Issue by pke** [winjs/winjs#1044]
Instead of using `AppBar.showOnlyCommands` I thought I could use the indivdual commands `hidden` property to toggle their visibility. But that merely sets the HTML elements `hidden` attribute but does not add/remove the command from the appbar.

**Comment by rigdern** [comment]
Can you elaborate on what you mean by "add/remove the command from the appbar"? Do mean:
  - The command remains in the AppBar's DOM?
  - The command doesn't animate?
  - Something else?

**Comment by pke** [comment]
Lets say I have a simple AppBar with one button with id `addBoard`. That means the command `addBoard` is globally available in `document.all.addBoard`. On pages where I don't want this button to appear I thought I could simply do `document.all.addBoard.hidden=true` and it would animate the button to hide in the appbar. But it doesn't. All it does is to change the DOM of the button to set its `hidden` attribute to an empty string. But the button is still visible, can be clicked as if its not hidden at all.

Maybe its possible to reproduce that in the WinJS playground?

**Comment by AmazingJaze** [comment]
Hi pke, can you tell us which version of WinJS are you using? If it is a newer version of WinJS I wonder if the behavior you are seeing is the same as described in #841

**Comment by rigdern** [comment]
You need to set the `hidden` property on the `winControl` rather than the DOM element. Like this: `document.all.addBoard.winControl.hidden=true`

**Comment by pke** [comment]
@rigdern aha! That seems to do what I want ;) :+1: Will further investigate.
