### ISSUE TITLE
Any one using the Starter Templates? Blank Angular-WinJS throws errors

### ISSUE THREAD

**Issue by MithunChopda** [winjs/winjs#1047]
Any one using the Starter Templates?

I extracted the Blank Angular-WinJS template and it throws errors when run without any modifications.
"Line:363
Angular is undefined".

Also there is no "WinJS.UI.processAll()" call in this template. 

The default.js looks quite different from what is documented at https://msdn.microsoft.com/en-us/library/windows/apps/hh465493.aspx

Why would it be so?

**Comment by jseanxu** [comment]
Can you give us the zip you downloaded? I just downloaded the Blank Angular off http://try.buildwinjs.com/#get and it works fine.

You should not need to use `WinJS.UI.processAll()` in the Angular template as you should just be using directives.

**Comment by MithunChopda** [comment]
Hi

I downloaded the templates from http://try.buildwinjs.com/downloads/releases/4.0.0-preview/winjs-templates.zip
I am trying the 4.0 preview templates.

The steps I followed are:
1. Extract the BlankAngular-WinJS folder.
2. Open this folder as "open website" and hit F5 in VS 2013 Express.
3. This will launch the default.html page in your default browser. For me it opens in IE.

Thanks

**Comment by jseanxu** [comment]
Followed your exact steps and was not able to reproduce your error. Here are some things you could try:
-Open the default.html file in a browser without going thru Visual Studio
-Try to reproduce your issue on another computer and/or browser
