### ISSUE TITLE
Unit test failures in AppBar, ToolBar, and CommadingSurface tests when run in Firefox

### ISSUE THREAD

**Issue by TheWrathOfConst** [winjs/winjs#1049]
Tested with clean enlistment on Firefox. These tests fail:
AppBar test failure:
CorsicaTests.AppBarTests: AppendToDomAfterConstruction

CommandingSurface failures:
CorsicaTests._CommandingSurfaceTests: KeyboardingWithCustomContent
CorsicaTests._CommandingSurfaceTests: OverflowDirectionProperty

ToolBar failure:
CorsicaTests.ToolBarTests: AppendToDomAfterConstruction

**Comment by AmazingJaze** [comment]
Firefox insists on giving elements in my test sub-pixel values, and these tests fail right now if the measurements are not pixel perfect. When we address this we should introduce an acceptable tolerance if the final result is within 1px deviation from the expected outcome.
