### ISSUE TITLE
WinJS.Promise.timeout: How to find out if promise canceled by timeout or user?

### ISSUE THREAD

**Issue by pke** [winjs/winjs#1050]
I have a server request that is wrapped in a timeout promise. `var pendingRequest = WinJS.Promise.timeout(5000, requestAsync)`. The user also has a "Cancel" button on the UI to actively cancel the request. However, there is no way to find out that the promise has been cancelled by the user or by the timeout.
It's too late in the game but the timeout promise should probably cancel itself with a different error than a call to `cancel()` would normally produce, something like "timeout". Then we could check in our error handler:
```
pendingRequest.then(null, function(error) {
  if (error.name === "Canceled") // by user
  if (error.name === "Timeout") // by timeout
}); 
```

Or the cancel method would optionally accept an `error` argument to use to set the promise into error state.

Any idea how to do that with the current state of Promises?

**Comment by pke** [comment]
A first proposal that replaces `WinJS.Promise.timeout`.

```
(function (P) {
    var oldTimeout = P.timeout
    P.timeout = function (t, promise) {
        var timeoutPromise = oldTimeout(t);
        if (promise) {
            timeoutPromise.then(function () {
                promise.timedout = true;
                promise.cancel();
            });
            return promise.then(function (result) {
                timeoutPromise.cancel();
                return result;
            }, function (error) {
                timeoutPromise.cancel();
                if (error.name === "Canceled" && promise.timedout) error = new WinJS.ErrorFromName("Timeout", "Timeout reached after " + t + "ms");
                return WinJS.Promise.wrapError(error);
            });
        } else {
            return timeoutPromise;
        }
    };
})(WinJS.Promise);
```

Usage:

```
WinJS.Promise.timeout(10000, getHttpAsync(url))
.then(function ondownload(result) {
}, function onerror(error) {
  if (error.name === "Timeout") {
    console.error("GET " + url + " timed out");
  } else if error.name === "Canceled") {
     console.error("GET " + url + " was cancelled by the user");
  } else {
     console.error("GET " + url + " failed with " + error.message);
  }
});
```

I've found only 2 places in the WinJS code that actually rely on `error.name === "Canceled"` for their operation. So if those could be adjusted then this should not be a breaking change and validate a pull request (with tests)?

**Comment by pke** [comment]
Another proposal: 

```
(function (P) {
        var oldTimeout = P.timeout
        P.timeout = function (t, promise) {
            var timeoutPromise = oldTimeout(t);
            if (promise) {
                return new WinJS.Promise(function (c, e, p) {
                    promise.then(c,e,p);
                    timeoutPromise.then(function () {
                        e(new WinJS.ErrorFromName("Timeout", "Timeout reached after " + t + "ms"));
                    });
                });
            } else {
                return timeoutPromise;
            }
        };
    })(WinJS.Promise);
```

This one does not cancel the timeout promise when the real promise is fullfilled/rejected.

Which version you guys think is the better one? I tend to favour the first one, as cancellation of the timeout promise saves a few CPU cycles and resources.

**Comment by jdalton** [comment]
Thanks again @pke! We've added this backlog.

**Comment by pke** [comment]
Glad I could help.
