### ISSUE TITLE
question: Date & Time Pickers for Windows Phone

### ISSUE THREAD

**Issue by pke** [winjs/winjs#1051]
I understand why the Win8 controls cannot be used on the Phone. Its because they use `select` elements and such elements result in full screen dialogs on the Phone.
However, have you thought about a replacement for the controls on the Phone that resembles the ones available for XAML?

**Comment by jayrenn** [comment]
See this comment for reference: https://github.com/winjs/winjs/issues/534#issuecomment-111626833
