### ISSUE TITLE
WinJS.UI.CellSpanningLayout: Can it be used for variable height vertical lists?

### ISSUE THREAD

**Issue by pke** [winjs/winjs#1052]
There seems to be a focus on horizontal layout in every single example of this layout I came across.
I need a variable height ListLayout. Rolling my own layout that supports drag&drop and re-order of items seems to fairly complex. So does the CellSpanningLayout support my usecase already?

**Comment by jdalton** [comment]
>  So does the CellSpanningLayout support my usecase already

CellSpanningLayout does not support your usecase and support is not planned at this time.
