### ISSUE TITLE
How to add a new method to WinJS.Promise.then

### ISSUE THREAD

**Issue by pke** [winjs/winjs#1053]
I want to have a new method available on the object returned by `promise.then`. From the code it seems there are different objects returned depending on the state of the promise. How would I add a method to each of the possible returned objects' prototype?

I tried: `Object.getPrototype(WinJS.Promise.as().then).myChainHandler = function() {}` but `myChainHandler` was not available when doing `promise.then(...).myChainHandler()`

**Comment by jdalton** [comment]
Try:
```js
Object.getPrototypeOf(WinJS.Promise.prototype).myChain = ...
```

**Comment by pke** [comment]
this doesn't work cause WinJS constructs different promise objects for success and error conditions.

**Comment by jdalton** [comment]
Hmm you're right. At first glance it looked like they all inherited from `PromiseStateMachine`, but this does not appear to be the case. It would be a good thing to do.

**Comment by pke** [comment]
The question is: Why was it composed like this in the first hand? I'd like to think there was some rationale behind it.

**Comment by jdalton** [comment]
Thanks @pke! We've added this to our internal tracker.
