### ISSUE TITLE
NavBar: hidden always returns false

### ISSUE THREAD

**Issue by rigdern** [winjs/winjs#1058]
NavBar's `hidden` property always returns `false`. This is because it's going thru the `Overlay`'s implementation.

Because NavBar's `opened` property replaces its `hidden` property, we should just override `hidden` to return `undefined` (so it's like it's not implemented). Or should we throw an exception or print a warning to help developer's realize they need to use `opened` instead?

**Comment by AmazingJaze** [comment]
I believe we should return undefined.
