### ISSUE TITLE
AutoSuggestBox behaves strangely when suggestion flyout opens above it

### ISSUE THREAD

**Issue by rigdern** [winjs/winjs#1059]
Here's what an AutoSuggestBox looks like when the flyout opens above it:

![screen shot 2015-04-18 at 10 04 04 am](https://cloud.githubusercontent.com/assets/199935/7216386/62b8f93a-e5b2-11e4-9f99-bdb1952af5b0.png)

Strange behaviors:
  1. The down arrow key moves the selection upwards in the flyout.
  2. The first result is drawn at the bottom of the flyout rather than at the top.
  3. When the flyout has a scroller, the first autosuggest result is scrolled offscreen (because the first autosuggest result appears at the bottom of the flyout and the flyout opens at scroll position 0).

**Comment by jseanxu** [comment]
1. is a bug
2 and 3 are working as intended. The best suggestion should appear closest to the input.

**Comment by nizh914** [comment]
Just confirming that @jseanxu is correct. 2 and 3 are not bugs. That's the intended behavior. 1 is a bug.

**Comment by rigdern** [comment]
Clarified with @jseanxu offline. 3 is a bug: the Flyout should be scrolled to the bottom but currently it opens scrolled to the top.
