### ISSUE TITLE
How to update a Windows 8 application to latest WinJS (4.0-preview)

### ISSUE THREAD

**Issue by fnicollet** [winjs/winjs#1061]
Hello,

I am having issues in my Windows 8 application, because of this issue:
https://github.com/winjs/winjs/issues/146

This is a strange race condition that was fixed by @rigdern in this commit:
https://github.com/winjs/winjs/commit/dbc7a96d53bbed9d68471d1b6a84b7a130e7dfec

In my Windows 8 application project, I have a reference to:
C:\Program Files (x86)\Microsoft SDKs\Windows\v8.1\ExtensionSDKs\Microsoft.WinJS.2.0\1.0\

And ui.js is currently located in:
C:\Program Files (x86)\Microsoft SDKs\Windows\v8.1\ExtensionSDKs\Microsoft.WinJS.2.0\1.0\DesignTime\CommonConfiguration\neutral\Microsoft.WinJS.2.0\js\ui.js

With this link (https://github.com/winjs/winjs/releases/download/release%2F4.0.0-preview/winjs.zip) I can get all the files for WinJS 4.0-preview but how exactly am I supposed to use this? 
Should I monkey patch what's in Program Files so that the new files will be packaged?
Should I remove the reference to WinJS 2.0 from my project and include the downloaded WinJS 4.0 files in my project directly and reference them in my head tags? Will that even work or does Visual Studio need to have a WinJS reference to be able to package my application?

Thanks for your help,
Fabien

**Comment by fnicollet** [comment]
I tried this in Nuget console:
```
Install-Package WinJS -Pre
```

Which copied a WinJS folder in my solution, containing the JS/CSS of WinJS 4.0 preview.

Then in default.html, I tried changing to:
```
    <link href="/WinJS/css/ui-dark.css" rel="stylesheet" />
    <script src="/WinJS/js/WinJS.js"></script>
```
But the result is completly wrong, styles are wrong, sticky toolbar is shown on startup and other stuff that break my application completly.

Is this project meant to be the future of WinJS for Windows 8 applications or some kind of fork to have WinJS runs in the browser and doesn't have any link to the original WinJS at all?

Thanks,
Fabien

**Comment by pke** [comment]
Since 4.x is still not final and such glitches are to be expected. I hope they manage to make the migration smoother in the future than it is right now.
Imho the focus on porting the WinJS lib to other OS/Browser left the origin of it, Windows Apps, completely in the dust, unfortunately.

**Comment by AmazingJaze** [comment]
Hi @fnicollet 

Thank you for your interest in WinJS 4.0 Preview. Like @pke has mentioned, you just need to include the WinJS 4.0 Preview files and replace the references to WinJS 2.0 inside your `<head>` tags

>Is this project meant to be the future of WinJS for Windows 8 applications or some kind of fork to have WinJS runs in the browser and doesn't have any link to the original WinJS at all?

WinJS 4.0 is being developed specifically for Windows 10. The design language between Windows 8 and Windows 10 has changed and this is likely the cause of some issues you are describing.

Check out this [blog post](http://blogs.windows.com/buildingapps/2015/03/27/a-preview-of-winjs-4-0/) on WinJS 4.0 preview for more information

>But the result is completly wrong, styles are wrong,

Can you provide screen shots on any the style issues you are experiencing? I'd like to make sure you aren't encountering any actual bugs.

> sticky toolbar is shown on startup and other stuff that break my application completely.

Note that ToolBar is actually a brand new control in WinJS 4.0 Preview. So I assume that the behavior you are encountering is with the AppBar. That is likely result of the new AppBar design in WinJS 4.0 Preview as a result of the convergence work with the former Windows Phone AppBar. 

Take a look at this sample on [AppBar Display Modes](http://try.buildwinjs.com/#appbar:displaymodes). The default AppBar.closedDisplayMode value in WinJS 4.0 Preview is `compact`. You can change it to "none" to get an experience closer to the WinJS 2.0 AppBar.

**Comment by fnicollet** [comment]
Thanks @pke and @AmazingJaze for your answers, very appreciated. I ended up copying my current version of ui.js in my project and monkey-patch the part of code where the fix was and referenced it in my <head> tags, which works.

I'll give WinJS 4.0 a go when I upgrade my app to Windows 10 and post the related issues, if any

Thanks!
Fabien
