### ISSUE TITLE
ListView: reorder/drag and drop supported on Phone

### ISSUE THREAD

**Issue by pke** [winjs/winjs#1062]
Feature: ListView
Environment: Mozilla/5.0 (Mobile; Windows Phone 8.1; Android 4.0; ARM; Trident/7.0; Touch; rv:11.0; IEMobile/11.0; NOKIA; Lumia 925) like iPhone OS 7_0_3 Mac OS X AppleWebKit/537 (KHTML, like Gecko) Mobile Safari/537
Source: http://try.buildwinjs.com

It seems that reorder and drag drop is not supported on the phone?

I couldn't get it to work on the try site.

**Comment by AmazingJaze** [comment]
Hi @pke you are correct that reorder and drag and drop has limited platform support at the moment as it relies on support for the HTML5 draggable attribute which was previously supported in IE 11 desktop but not on WP 8.1 IE.  Related: https://github.com/winjs/winjs/issues/774

I will try to find out the official news on whether or not this should just work on phones running Win 10.

**Comment by AmazingJaze** [comment]
@pke  I was unable to get HTML 5 drag and drop to work on phone using a recent preview build. I have followed up internally with the team that owns HTLM 5 drag and drop and filed a bug against them to get it working on phone.

Please comment or open another issue if there is anything else we can help you with in this area.
