### ISSUE TITLE
LinguisticDetails API on WP10 is broken

### ISSUE THREAD

**Issue by jseanxu** [winjs/winjs#1066]
`Windows.ApplicationModel.Search.SearchQueryLinguisticDetails` presence check succeeds but instantiation throws exception.

This prevents ASB/SB from being constructed on WP10
![classnotregistered](https://cloud.githubusercontent.com/assets/6741017/7287010/a9d9ef58-e905-11e4-8f39-f9384a313ba3.png)

**Comment by AmazingJaze** [comment]
This is a platform bug. We have a separate issue in VSO tracking it.
