### ISSUE TITLE
Dynamic assign html snippet to div broken the video element

### ISSUE THREAD

**Issue by yangj3848** [winjs/winjs#1067]
Create default WinJS Win8.1 Blank project and add below snippet to default.html.

    <div id="videoTest">
    </div>

    <script>
        var html =
        "                <div id=\"mp3href\">-</div>" +
        "            <video id=myVideo width=480 height=270 controls preload=auto >" +
        "                <source src=\"http://stream.51voa.com/201504/climate-change-blamed-for-disasters-in-syria-and-california.mp4\" type=\"video/mp4\">" +
        "            </video>";

        document.getElementById("videoTest").innerHTML = html;
    </script>

Run and check the result. The video can not play unless you use javascript to call it's play method.
Similar code tested on IE and it works nice!

**Comment by AmazingJaze** [comment]
Hi @yangj3848  I believe you are running into the Windows 8 App Security Model by setting innerHTML dynamically.

You can use [toStaticHTML](https://msdn.microsoft.com/en-us/library/hh466094.aspx) as a one off remedy for this type of thing, but we've also release a [safeHTML polyfill](https://github.com/msopentech/winstore-jscompat) that will make the rest of your App Building easier if you, or any javascript libraries you want to include in your app, will be setting innerHtml often.

Let us know if that doesn't solve this issue for you.

**Comment by yangj3848** [comment]
If my understanding is correct, toStaticHTML is method used to filter out some script in html snippet assigned to innerHTML attribute. In this case we assign a html without any script to innerHTML and there is no security alert when I run this. I meet alert before when I try to assign some html snippet with script.
btw, if you mean to change code to:
        document.getElementById("videoTest").innerHTML = toStaticHTML(html);
then the result is the same and problem still exists.

**Comment by AmazingJaze** [comment]
Thanks for clarifying. I will take a closer look.

**Comment by jdalton** [comment]
Hi @yangj3848. While the safeHTML polyfill may help with setting innerHTML inline scripts aren't allowed in Win 8.1 or 10.
