### ISSUE TITLE
WinJS.Resources.getString does not handle "?" in key well

### ISSUE THREAD

**Issue by pke** [winjs/winjs#1069]
When having 2 keys in my resjson file:

```
"key1": "value1",
"key1?": "value2",
```

Then this is the (wrong) result:
```
WinJS.Resources.getString("key1?").value == "value1"
```

Are "?" not supported in resource maps as keys?

**Comment by AmazingJaze** [comment]
Hi @pke I've spent some investigating this tonight, and I am able to repro the behavior you've called out by following the steps outlined in https://msdn.microsoft.com/en-us/library/windows/apps/hh943060.aspx and renaming my keys to match the yours ala `key1` and `key1?`

It seems like after invoking `WinJS.Resources.getString("key1?").value` , the "?" character is getting parsed out by this WinRT call:
```js
var mainResourceMap = Windows.ApplicationModel.Resources.Core.ResourceManager.current.mainResourceMap;
```

**Comment by pke** [comment]
Yes and it seems to be a quirk of the WinRT resource system. For some reason unknown to me, keys are treated as somewhat URI like elements. So therefore `?` and `#` are not allowed in them. The WinRT resource streams seems to use the key as part of an URI it forms to load the resource like this: `ms-appx:///resources/key`.

See: https://social.msdn.microsoft.com/Forums/windowsapps/en-US/d16b2fee-4d8a-4766-9f2d-948c04b15bab/are-in-resource-keys-supported?forum=winappswithhtml5
