### ISSUE TITLE
Can't keyboard tab to buttons in listview headers

### ISSUE THREAD

**Issue by caseyfaber** [winjs/winjs#1070]
If you have button elements in the header of a listview, you can't keyboard tab to them properly. Repros on try.buildwinjs.com. In IE, you have to tab a few times after the list is focused, and shift+tab won't get in there at all, and if you tab and click around enough on the page, eventually you can't keyboard focus the button at all.

In Chrome, you can focus the button, but it seems to be Chrome's highlight, rather than the dashed line from WinJS styles, and it focuses after the list items, instead of before.

Expected behavior: Tab should highlight the header elements first, then the listview items. And Shift + Tab should go backwards.

![image](https://cloud.githubusercontent.com/assets/2295203/7307949/1bff3dda-e9c5-11e4-80e8-5b97b57a076e.png)

**Comment by AmazingJaze** [comment]
@caseyfaber 

Regarding the behavior in chrome, are you only commenting on the focus rect, or are you suggesting that the tab behavior is different than in IE? 

Regarding the Tabbing Behavior in IE, this is actually working as intended, but we agree that it feels a little strange. Shift+Tab will move focus onto the header, but it requires an additional tab from that point to reach the interactive content.
