### ISSUE TITLE
Error when running Blank Windows JavaScript Universal App in VS:  0x800a1391 - JavaScript runtime error: 'define' is undefined

### ISSUE THREAD

**Issue by mikewjackson** [winjs/winjs#1072]
'WWAHost.exe' (Script): Loaded 'Script Code (MSAppHost/3.0)'. 
Exception was thrown at line 6, column 9 in ms-appx://13922fcd-f3fe-4fe3-a67b-bbebee3ba3d9/WinJS/js/WinJS.js
0x800a1391 - JavaScript runtime error: 'define' is undefined
The program '[8024] WWAHost.exe' has exited with code -1 (0xffffffff).

**Comment by AmazingJaze** [comment]
Please create a repro

**Comment by jseanxu** [comment]
This is a known issue being looked at by another internal team. The exception is non-fatal and safe to ignore in the meantime.
