### ISSUE TITLE
WinJS.xhr method document response type gives wrong encoding response

### ISSUE THREAD

**Issue by yangj3848** [winjs/winjs#1078]
Create default WinJS windows 8.1 app, add below code to default.html.

    <p>Content goes here</p>
    <script>
        WinJS.xhr({
            url: "http://www.51voa.com/", responseType: "document",
        }).then(function (xhr) {
            console.log(xhr.response.title);
        });
    </script>

  When responseType is document, the xhr.response.all['0'].innerHTML gives wrong encoding text:
<head>
<title>ç¾Žå›½ä¹‹éŸ³-VOAå¬åŠ›ä¸‹è½½,æ…¢é€Ÿè‹±è¯&shy;,å¸¸é€Ÿè‹±è¯&shy;,VOAè§†é¢‘</title>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8">
<meta name="robots" content="all">
<meta name="keywords" content="VOA,ç¾Žå›½ä¹‹éŸ³,æ…¢é€Ÿè‹±è¯&shy;,å¸¸é€Ÿè‹±è¯&shy;,VOAè§†é¢‘">
<meta name="description" content="VOA,ç¾Žå›½ä¹‹éŸ³,å¬åŠ›ä¸‹è½½.">
.....

===================================================
change responseType to text, the response is in correct encoding:

 <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<title>美国之音-VOA听力下载,慢速英语,常速英语,VOA视频</title>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="robots" content="all" />
<meta name="keywords" content="VOA,美国之音,慢速英语,常速英语,VOA视频" />
<meta name="description" content="VOA,美国之音,听力下载." />
<meta http-equiv="Cache-Control" content="no-siteapp" />
.....

**Comment by phosphoer** [comment]
Hi @yangj3848, the WinJS xhr method is a thin wrapper over `XMLHttpRequest`. It's unlikely that anything we are doing is affecting the response data you receive. 

I tried repro-ing your issue locally, but was unable to open a request to the URL you specified due to their cross-origin-request policy. Can you try making the same request using the vanilla `XMLHttpRequest` object to verify that WinJS is the problem here?

**Comment by yangj3848** [comment]
Yes, XMLHttpRequest same issue.

        var oReq = new XMLHttpRequest();
        oReq.onload = function (e) {
            var html = oReq.responseXML;
        }
        oReq.open("GET", "http://www.51voa.com/", true);
        oReq.responseType = "document";   // "text" type gives correct text
        oReq.send();

**Comment by yangj3848** [comment]
I checked the request and response for both "document" and "text" responseType, and confirm they are identical. Why this happen ?

**Comment by phosphoer** [comment]
@yangj3848 I've filed a bug internally with the IE team. Thanks for reporting this!
