### ISSUE TITLE
Add key mapping support for different controls

### ISSUE THREAD

**Issue by ricardosabino** [winjs/winjs#1085]
Similar to XYFocus, all controls should allow key mapping so that they would play well with devices that don't have mouse/keyboard/touch such as a remote control on a Samsung Smart TV.

**Comment by jayrenn** [comment]
@ricardosabino, I'm not sure I entirely understand what you are asking. You can already modify the keyCode mappings for XYFocus. If the remote control on a Samsung Smart TV fires event keyCodes, then you can add them to the mapping.
```javascript
// Wire XYFocus up to the arrow keys
WinJS.UI.XYFocus.keyCodeMap.up.push(WinJS.Utilities.Key.upArrow);
WinJS.UI.XYFocus.keyCodeMap.down.push(WinJS.Utilities.Key.downArrow);
WinJS.UI.XYFocus.keyCodeMap.left.push(WinJS.Utilities.Key.leftArrow);
WinJS.UI.XYFocus.keyCodeMap.right.push(WinJS.Utilities.Key.rightArrow);
```
Taken from this [Try Site sample](http://try.buildwinjs.com/#xyfocus:basics).

Is that what you  were asking, or are you referring to something different?

**Comment by ricardosabino** [comment]
@jayrenn I'm talking about other controls like the list view supporting the same kind of mapping that the XYFocus supports. Right now it's not possible to navigate a listview using the Samsung Smart TV remote control because there's no way of mapping the keys.

**Comment by jayrenn** [comment]
We are planning on updating all our WinJS controls to be compatible with XYFocus. This would allow a user to navigate a ListView if XYFocus is enabled. Once implemented, you can map the Samsung Smart TV remote keyCodes. Currently, XYFocus [fires a click event](https://github.com/winjs/winjs/blob/9e50af94c8acc7f51166bb9ed3f7695744433641/src/js/WinJS/XYFocus.ts#L568-569) when you press A on the Xbox gamepad (`WinJS.Utilities.Key.GamepadA`). You could wire up something similar when you press Enter on the Samsung remote.

Would that cover the scenario you are describing?

**Comment by ricardosabino** [comment]
Yes, if the navigation inside other controls would be done via the XYFocus then it would cover my scenario.

**Comment by jayrenn** [comment]
Great! Let me know if there is anything else I can help you with.
