### ISSUE TITLE
ContentDialog: Need sample for getting dialog result

### ISSUE THREAD

**Issue by rigdern** [winjs/winjs#1087]
We should add a sample to the Try Site which shows how to find out the reason the dialog was closed (e.g. primary button was pressed, secondary button was pressed, escape key was hit).

Something like this:

```js
dialog.show().then(function (dismissalResult) {
  // dismissalResult.reason indicates the reason the dialog was dismissed
});
```

**Comment by xiamx** [comment]
Please have this as an example. It took me a while to figure out that show() returns a promise
