### ISSUE TITLE
Pivot: Selected header clipped on Mac in Chrome

### ISSUE THREAD

**Issue by rigdern** [winjs/winjs#1088]
In the following screen shot, notice that the "Description" text is clipped. This is the selected header of a Pivot.

Repros in Chrome on a Mac.

![screen shot 2015-04-29 at 11 32 41 am](https://cloud.githubusercontent.com/assets/199935/7398377/74504c16-ee63-11e4-90ae-fb83d22a5ada.png)

Repros on details page of: https://github.com/phosphoer/winjs-store/tree/3e14eba5b27d3065fa5a5bddf0363a016513bd6b

**Comment by jseanxu** [comment]
With the updated Pivot styles from this change 89b87a56f37617aff3bff95fe8d49db53939ff0b, the Pivot headers should no longer get clipped as they do not get bolded when selected.
