### ISSUE TITLE
Should not fire itemInvoked() event when ListView is in multi-select mode.

### ISSUE THREAD

**Issue by derek1ee** [winjs/winjs#1092]
**Issue**
When ListView is in multi-select mode, each time an item is selected/deselected, ```itemInvoked()``` event is fired.

This causes problem when we need to automatically* exit multi-select mode, because ```itemInvoked()``` fires after  ```_updateSelection()```, causing app to navigate.

(We automatically enters multi-select mode, when user ctrl + click, and want to exit multi-select mode after user deselected the last item if we automatically entered.)

**Proposed fix***
```itemInvoked()``` should checks if the ListView is in multi-select mode, and not fire if so.

**Comment by JoeyChaps** [comment]
This change shouldn't have been implemented. It broke our multi-select listview that used itemInvoked to determine what was selected. itemInvoked is needed so we can get the item detail information from the event, which isn't available on selectionchanged.

derek1ee should have instead handled their problem by removing the iteminvoked event listener when ctrl selected and adding the listener back when ctrl unselected. That would have been a developer solution that would have avoided changing the API for everyone else.
