### ISSUE TITLE
ToolBar: Overflow menu items do not get recalculated on resize when menu is open

### ISSUE THREAD

**Issue by jseanxu** [winjs/winjs#1093]
### Repro
* Create a toolbar with a couple items without having it overflow on a full screen page
* Resize the window so that some/all items overflow
* Open the overflow menu
* Maximize the window

### Expected
All items are on the bar (no overflow menu, same as initial repro step)

### Actual
Layout did not change

**Comment by AmazingJaze** [comment]
Verified that this still repro's in WinJS 4.0. 
Also verified that it only repro's with the ToolBar, never with the AppBar
