### ISSUE TITLE
ToolBar/AppBar: Support for variable width spacer commands

### ISSUE THREAD

**Issue by rigdern** [winjs/winjs#1095]
Currently, all of the ToolBar/AppBar commands are aligned to the right. It'd be nice to be able to have content on both the left and right sides of the ToolBar/AppBar. Like this:

![screen shot 2015-04-29 at 5 04 06 pm](https://cloud.githubusercontent.com/assets/199935/7404013/e3cb8726-ee91-11e4-9a9a-501de6d2fa7e.png)

**Comment by rigdern** [comment]
The DataDVR/TweetDVR demo also ran into this problem. They wanted "DataDVR" to be written on the left side of the screen but that's not easy to do with the ToolBar/AppBar.

![image](https://cloud.githubusercontent.com/assets/199935/7424090/1f61d7d4-ef52-11e4-88b2-2717c383f2ff.png)

**Comment by nhutquang97** [comment]
This feature should be added ASAP as most of Windows universal app has page title and back button in the left side of appbar.

**Comment by jayrenn** [comment]
I have added this to our internal tracking.
