### ISSUE TITLE
ToolBar/AppBar: Animations don't clean up in Safari

### ISSUE THREAD

**Issue by rigdern** [winjs/winjs#1098]
After the close animation, the ToolBar/AppBar is clipped in Safari:

![screen shot 2015-04-29 at 10 27 48 pm](https://cloud.githubusercontent.com/assets/199935/7406863/ff9997c2-eebe-11e4-88e0-1d117c748304.png)

Repro from: https://github.com/phosphoer/winjs-store/tree/a0cc6553d1ac2500c216cbb805b80cb3928bbf79

### Cause

It looks like we should be using a platform-specific `transform` property (e.g. Safari needs `-webkit-transform`) instead of hardcoding the standard one here: https://github.com/winjs/winjs/blob/9444aaa8fe8c73cee294b72eead7ddcffd6c941b/src/js/WinJS/Controls/CommandingSurface/_CommandingSurface.ts#L414-L417

**Comment by TheWrathOfConst** [comment]
Fixed by commit abcd30d
