### ISSUE TITLE
trywinjs samples not working for winjs 3.00 or 4.0.0

### ISSUE THREAD

**Issue by ivanixgames** [winjs/winjs#1103]
Wondering if there is a separate sample repository that matches  versions 3.0.0 and 4.0.0?

**Comment by rigdern** [comment]
The trywinjs samples are using [WinJS 4.0.0-preview](http://try.buildwinjs.com/#get:preview). Which version of WinJS are you using and what problems are you running into?

**Comment by ivanixgames** [comment]
Hi rigdern,  
Thanks very much for clarifying about the version.  I was thrown off when I looked at the source of the rendered output, where  I see    <script src="/lib/winjs/js/WinJS.min.js?v1.0.141"></script>

At the moment I have trouble getting the first SplitView demo to work.
I started with the BlankWeb template then simply replaced the contents of default.js and default.css with those from http://try.buildwinjs.com/#splitview:create
For the html,  i copy and pasted the  <div id="app">..</div>  fragment into <body></body> of the BlankWeb default.html section.

I only see a square box at the top left followed by "Splitview Pane area" 
Then next line shows "SplitView Content Area" in a larger font size.
The side menu does not appear when clicking on the square box.

**Comment by ivanixgames** [comment]
I finally got the SplitView demo working, but I had to change the javascript code by removing WinJs.Binding.processAll from the WinJS.UI.processAll() code.
According to https://msdn.microsoft.com/en-us/library/windows/apps/br229846.aspx ,
WinJS.Binding.processAll requires  one or more DOM elements with data-win-bind attribute.
None of the elements in the html sample contain this attribute.
