### ISSUE TITLE
How to use a grouped BindingList with already grouped data?

### ISSUE THREAD

**Issue by pke** [winjs/winjs#1110]
I have an already grouped dataset like this:

```
var data = [
  '#': [...]
  'A': [...]
  'Z': [...]
]
```

How do I use that with a grouped list projection?

**Comment by jseanxu** [comment]
https://msdn.microsoft.com/en-us/library/windows/apps/hh700742.aspx

I'm assuming that `data` is an object literal and not an array? If so, you first want to turn that into an array of this sort:
```js
var arr = [
    { key: "#", data: [...] },
    { key: "A", data: [...] },
    { key: "Z", data: [...] }
];
```

Then you create a binding list using that array and created a grouped list:
```js
var list = new WinJS.Binding.List(arr);

var grouped = list.createdGrouped(function key(item) {
    // return the key of this group
    return item.key;
}, function data(item) {
    // return the data of this group
    return item.data;
}, function sort(left, right) {
    // compare the two groups
    return left.key.toUpperCase().charCodeAt(0) - right.key.toUpperCase().charCodeAt(0);
});
```

**Comment by pke** [comment]
Thanks. That should have been obvious from the docs already. Your sample contains a slight error in the sort method. `left` and `right` are already the keys ;) so it should be:
`return left.toUpperCase().charCodeAt(0) - right.toUpperCase().charCodeAt(0);`

Which changed to the more i18n ready: `return left.localeCompare(right);`
