### ISSUE TITLE
WinJS.UI.Pivot: How to simulate Windows Phone 7.5 background image scroll?

### ISSUE THREAD

**Issue by pke** [winjs/winjs#1113]
In Windows Phone 7.x apps the `Pivot control` could have a nice scrolling background that scrolled smoothly when you switched to the next pivot section and eventually wrapped when the maximum image width was reached.

In `WinJS.UI.Pivot` there is no such support for backgrounds anymore. But since its all HTML5/CSS3 I am sure there is a way to do the same there. I guess one would have to set the `background-image` of the `Pivot Viewport` element and translate-x it when the pivot section is changed? Can anyone of you reach out to the XAML team and ask them about the algo they used? ;)

**Comment by darkyen** [comment]
Well since its all javascript the simplest solution is having another element and translating it with % of its width depending on the sections as in if there are 4 sections then each logical progression will move translate-x to + 25%, in case of 10 each does an increment of 10%. Why this works ? translate-x with % uses the width of the element. The same reason why absolute centering with translate & % works.

**Comment by jseanxu** [comment]
Is that type of scrolling supported in the XAML Pivot? It sounds very much like the Panorama control...

I know that, in XAML, you can set the Pivot's background brush, or each individual PivotItem's background brush - both of these are supported by styling the `win-pivot-viewport` and `win-pivot-item` classes, respectively.

**Comment by pke** [comment]
Yeah I guess you are right, its the panorama control in WP7.5 XAML. It has been a while since I used it. Anyway the effect is very nice but I just cannot get it to work using CSS translate-x animations.

**Comment by jseanxu** [comment]
You could put the pivot into a wrapper div, and set the background image on the wrapper div. Then, in `onitemanimationstart` or `onitemanimationend`, you could apply the translation in code.

**Comment by pke** [comment]
aha! The Pivot sends such events, interesting :) I think I could even skip the wrapper div and apply the background to the `win-pivot-viewport` directly. Will try it out and report back.
