### ISSUE TITLE
WinJS Windows 10 Calendar control?

### ISSUE THREAD

**Issue by pke** [winjs/winjs#1114]
on //build/ they mentioned there will be an all new (XAML I assume) calendar control for WUA coming in Windows 10. Are there any plans to have one for WinJS apps as well?

**Comment by limefrogyank** [comment]
I hope so.  The default WinJS calendar picker is ugly.  I tried making a control that triggered the native implementations of the DatePicker for each OS using <input type="date" /> but the default and returned values vary (UTC vs local) based on OS and was making my head spin.

**Comment by pke** [comment]
Well the native date/time picker on Windows Phone were quite nice. Unfortunately there are no WinJS controls like that. And the telerik controls are too heavy on jquery that a page load takes several seconds.

**Comment by jseanxu** [comment]
Thanks for the feedback, we'll mark it as a feature request.

**Comment by jayrenn** [comment]
Thanks for the suggestion! I'll add the calendar control request to our internal tracking.

As for the new Windows 10 DatePicker control, see my comment here: https://github.com/winjs/winjs/issues/763#issuecomment-114594542
