### ISSUE TITLE
WinJS 4.x Hub CSS not suiteable for Phone

### ISSUE THREAD

**Issue by pke** [winjs/winjs#1115]
It seems the styles for the hub control are not yet ready for WUA. The padding on the left and top for the individual sections is way too big for the Phone form factor. Are there any plans to make the hub control play well on small width/height devices?

**Comment by jseanxu** [comment]
Yes, there are plans to update the Hub's styling in the near future.

**Comment by jseanxu** [comment]
Just had a chat with @jayrenn - The hub styles have actually been updated already, they just didn't make it in time for the 4.0-preview snap.

If you clone the repo and build WinJS today, you should see updated styles. Please let us know if you have feedback concerning the new styles!
