### ISSUE TITLE
Bring back Phone panorama control / endless hub control?

### ISSUE THREAD

**Issue by pke** [winjs/winjs#1116]
I understand the replacement for the old Windows Phone panorama control is the Hub control. However beside the hub control lacking the cool background image movement it also does not wrap like the panorama control did.
Are there any plans to make the hub control wrap?
Or should the Pivot control be used always when wrapping is required? Pivot control lacks the panorama controls "peek" feature of the next section though.

**Comment by limefrogyank** [comment]
I don't think they're going to budge on the Pivot control.  It was only ever supposed to be used as a filtering-mechanism, such as how the try.buildWinJS.com sample works for filtering mail.  In this case, a peek would not make sense.  I'm just as guilty of abusing it as the next person though...

I wouldn't mind seeing a Panorama style control though.  Not just the wrapping, but the snap points.  I know that we wouldn't be snapping to screen size with this new idea of writing apps for any screen size... but it would still be nice to snap to the content.  I.E. snapped to grouped data.  I think the Weather app would be easier to use that way.

**Comment by jseanxu** [comment]
Thanks for your feedback, we'll keep this open as a feature request.

**Comment by jayrenn** [comment]
See this comment for reference: https://github.com/winjs/winjs/issues/114#issuecomment-111254486
