### ISSUE TITLE
WinJS.UI.Repeater: using template with href throws sync render error

### ISSUE THREAD

**Issue by pke** [winjs/winjs#1117]
It seems the repeater cannot handle templates that reference external html code like this:

```
<div class="categoryItemTemplate" data-win-control="WinJS.Binding.Template" data-win-options="{href:'/pages/_categoryItem.html'}"></div>
  <div data-win-control="WinJS.UI.Repeater" data-win-options="{data:app.model.categories, template: select('.categoryItemTemplate')}">
</div>
```

It seems to use a sync render and therefore it throws: `WinJS.UI.Repeater.AsynchronousRender: Top level items must render synchronously`.

I am using external template html files to minimize duplication between pages. Is there a workaround to  "import" templates into pages that can be used by the repeater control as well?

Note: The same template works with listviews.

**Comment by jseanxu** [comment]
Repeater is designed to render synchronously and therefore does not support async renderers. One way you could work around this is to set the template in code after your templates have finished loading.

**Comment by pke** [comment]
Why was it designed that way (docs missing btw!)? Would you accept a pull-request for an optional async solution?

**Comment by jseanxu** [comment]
The sync-only is a requirement of the repeater control.

There are lots of edge cases that need to be handled if a list control is rendering async, which is one of the differentiating characteristics between a repeater and listview.

Examples:
* You will need to handle cancellations when a new datasource is set and the old one has not yet been resolved.
* APIs such as `length` and `elementFromIndex` need to be async and return promises as they can't be resolved until rendering is complete. And now you need to discuss whether that promise should error or complete with `null` when rendering was aborted but the API was called before rendering was aborted.
* If you want to write any code that immediately interacts with the contents of the repeater, such as setting focus on the first item, or scrolling to a particular location, they need to coordinate with the render state of the repeater.

This is a non-exhaustive list of new challenges that were addressed when we build the ListView.

**Comment by pke** [comment]
I understand the implications, thanks for explaining. Well then please update at least the docs that the `template` for repeaters must not be an async one, ie. not using the `href` attribute but contain the markup inline.

**Comment by jseanxu** [comment]
> I understand the implications, thanks for explaining. Well then please update at least the docs that the  template  for repeaters must not be an async one, ie. not using the  href  attribute but contain the markup inline.

Absolutely, marking this issue as a docbug to get the docs updated.

**Comment by jseanxu** [comment]
I've opened a bug internally on our doc team to update the msdn docs, closing this issue here.
