### ISSUE TITLE
BackButton: Integration with other navigation/routing systems

### ISSUE THREAD

**Issue by rigdern** [winjs/winjs#1119]
Currently, the `BackButton` is tied to `WinJS.Navigation` and doesn't offer any hooks to connect it to other navigation/routing systems. We should think about how to enable developers to hook it to other navigation systems. A couple of options are exposing hooks on `BackButton` or exposing hooks on `WinJS.Navigation`. Developers will want to control
  - Whether the `BackButton` is enabled. (today, it's only enabled when `WinJS.Navigation.canGoBack` is true)
  - What happens when the `BackButton` is triggered (today, it always calls `WinJS.Navigation.goBack()`

**Comment by jayrenn** [comment]
Added to our internal tracking.
