### ISSUE TITLE
Include test files in jshint linting

### ISSUE THREAD

**Issue by AmazingJaze** [winjs/winjs#112]
Currently "grunt lint" will run JSHint on grunt files and source files only. I am opening a separate issue for test files as they have never been linted, even by our previous internal tool. We might decide that they require their own separate .jshintrc file with a different level of strictness.

**Comment by brunobelarmino** [comment]
What configurations/strictness this .jshint file must have?

**Comment by xirzec** [comment]
You can look at our .jshintrc file here:

https://raw.githubusercontent.com/winjs/winjs/master/.jshintrc

Though this issue is a bit deprecated, since our test files have been migrated to TypeScript, so we'd have to set up something like tslint instead.

**Comment by jayrenn** [comment]
This is on our radar. We are considering adding TSLint (or similar) in the future.
