### ISSUE TITLE
question: Relate to Windows Phone Background audio

### ISSUE THREAD

**Issue by yangj3848** [winjs/winjs#1120]
hi Guys,

  Can we use pure Javascript to develop windows phone background audio like windows background audio. Same code not work on windows phone!
  I know there is a sample, but it is hybrid project and background part is in c#. I want to use html <audio> and only javascript. Can we ?

**Comment by limefrogyank** [comment]
Is this the class you're trying to use?  I don't think it's available in JavaScript apps.  It mentions only C# and VB.

https://msdn.microsoft.com/en-us/library/windows/apps/microsoft.phone.backgroundaudio.audiostreamingagent(v=vs.105).aspx

Are you writing a Universal app?  Because in that case it definitely won't be available.  

You should instead use this method for background audio.  It will work in HTML/JavaScript.
https://msdn.microsoft.com/en-us/library/windows/apps/xaml/jj841209.aspx

**Comment by yangj3848** [comment]
Thanks for reply.

Yes the second solution works well for Windows 8.1 App but not work for Windows Phone 8.1 App! What I want to achieve is the same behaviour in windows phone and windows.

using html tag audio to define a mediaelement, following instruction in your second link and achieve when windows phone app transfer to background, the audio can be automatically transfer to back ground play and continue to work.

But based on my study and investigate sample: https://code.msdn.microsoft.com/windowsapps/BackgroundAudio-63bbc319/
it looks like this is impassable! mediaplayer define by html audio tag can not automatically transfer to back player like windows app. we have to play audio in back player ONLY to achieve background audio playing (I think this is what this sample tell us). Also the background audio architecture: https://msdn.microsoft.com/en-us/library/windows/apps/xaml/dn642090.aspx
also proved my study.

For windows phone, we may do it manually. when app goto background move audio to be played by back player, when forground, move it back to mediaelement defined by htm audio tag. It looks crazy!

Am I right ?

**Comment by jseanxu** [comment]
Hi @yangj3848,
Currently, for Windows Phone apps, the only way to do background audio is thru a hybrid c# component. In Win10, this scenario will become possible with pure javascript.

**Comment by yangj3848** [comment]
Good. so even we use c# & javscript solution, we still can not achieve songs played by html audio element be automatically continued (after similar steps as windows app)  when windows phone app change to background, right?

**Comment by jseanxu** [comment]
Correct

**Comment by filfat** [comment]
@jseanxu so Windows 10 has been here a for a while now, how do we achieve background audio through JavaScript on Windows 10 Mobile? :)
