### ISSUE TITLE
WinJS.UI.Pivot: WinJS 4.x styles only with small font?

### ISSUE THREAD

**Issue by pke** [winjs/winjs#1121]
The key feature of the Pivot control on the Phone was its big header fonts. It seems now in WinJS 4.x preview this has changed:
![codecheck_pivot](https://cloud.githubusercontent.com/assets/164625/7452984/b2aded4c-f264-11e4-8a35-cdcdb3832a4f.png)

This comes straight from a WUA based on the VS templates. No styles have been touched, just WinJS 4.x dropped in.

**Comment by jseanxu** [comment]
Many controls are styled differently in 4.0 compared to 3.0. This is due to 4.0 aligning to the Win10 design while 3.0 followed Win8.1 design. The smaller pivot headers are intended.
