### ISSUE TITLE
WinJS ListView shouldn’t automatically play it's entrance animation

### ISSUE THREAD

**Issue by JohnAronson** [winjs/winjs#1122]
This bug came from an internal review.

**Comment by rigdern** [comment]
We thought about this some more. The `WinJS.UI.ListView`'s entrance animation currently plays by default and is opt-out. Modifying this behavior would be a breaking change and would require API changes.

An app can cancel a `ListView`'s entrance animation like this:

```js
myListView.addEventListener("contentanimating", function (eventObject) {
    if (eventObject.detail.type === "entrance") {
        eventObject.preventDefault();
    }
});
```
