### ISSUE TITLE
Delete ListViewComponents RestoringScrollPos unit test

### ISSUE THREAD

**Issue by TheWrathOfConst** [winjs/winjs#1123]
In desktop IE, setting the ListView's style.display to none would reset the ListView's scroll position to 0. The RestoringScrollPos test was built to verify that setting style.display to none and back would reset the scroll position to 0, and that calling forceLayout() would restore the ListView's scroll position back to whatever it was pre-style change. This was only an issue in IE -- neither Chrome nor Firefox would reset a viewport's scroll position when display = none was used -- and so we had this test disabled in other browsers.

Project Spartan has fixed the issue with display = none, and no longer resets a viewport's scroll position when used. It looks like we can delete the RestoringScrollPos unit test now.

**Comment by jseanxu** [comment]
We should update this test to check for the right behavior on IE11 vs MS Edge.
