### ISSUE TITLE
Delete CSS Ordering Tests

### ISSUE THREAD

**Issue by rigdern** [winjs/winjs#1124]
[CSS Ordering Tests](https://github.com/winjs/winjs/blob/dd41fc61805de3710870ae3bdf884c4b8bea596c/tests/CSS/CSSOrderingTests.js)

We should delete them because:
  - They aren't run regularly (too slow to run as part of every commit). Consequently, it's easy for them to fall out of date.
  - They're not as useful as they used to be. They were written by @phosphoer when he was modularizing the CSS to help find CSS ordering dependencies.

**Comment by jseanxu** [comment]
We should delete them!
