### ISSUE TITLE
Can we ship UWP apps with different WinJS versions?

### ISSUE THREAD

**Issue by sebagomez** [winjs/winjs#1127]
I have Windows 10 10074 and VS 2015 RC installed. When creating a new UWP app I noticed a new WinJS folder gets created and added to my project which now includes WinJS 4.0. Does that mean that I could use WinJS just as a regular JavaScript Framework and deploy the version I want to the target I want? 
I mean once WinJS 5 (or whatever) comes out, could I just replace the existing WinJS (4.0) folder in my project and deploy the app as a UWP app?

**Comment by jseanxu** [comment]
Yes - WinJS is just JavaScript that gets loaded via a `<script>` tag in your html. Even in previous versions of WinJS, in VS you could've removed the reference to WinJS and added loose files as part of your app.

**Comment by sebagomez** [comment]
That's awesome news! 
I know I could do it but now it's more explicit now that the whole WinJS framework get shipped.
Anyways.
Thanks
