### ISSUE TITLE
Disable NoKeyDSSimulateLiveMailSendListLayout test in Edge

### ISSUE THREAD

**Issue by TheWrathOfConst** [winjs/winjs#1128]
This test tests behavior that the Mail app used in Win 8.1, but this behavior is a desktop-IE specific quirk that doesn't repro in Firefox, Chrome, and now in Edge. The test is doing this:
```js
                listView.element.querySelector(".win-surface").focus();
```
The win-surface element has no tab index, so .focus() calls to it are ignored outside of IE

**Comment by jseanxu** [comment]
We should disable this test for Edge.
