### ISSUE TITLE
Disabling type to search seems to crash in WinJS with the stack below

### ISSUE THREAD

**Issue by jkochhar** [winjs/winjs#1131]
>             Application_TypeToSearch_updateKeydownCaptureListeners [WinJS.js] Line 14117        Script
               Application_TypeToSearch_frameLoadCaptureHandler [WinJS.js] Line 14098      Script

Looks like the event.target.contentWindow is null and the if check for win.frames errors out. This happened for the case when we had an iframe being shown up. The fix is simple enough to add null check for win along with win.frames in _updateKeydownCaptureListeners

**Comment by jseanxu** [comment]
Hi @jkochhar 
Thanks for reporting the issue. Could you provide a bit more information - what code is your app running that is causing this issue?

**Comment by jseanxu** [comment]
The issue appears to be when an iframe without a src is placed into the DOM.

**Comment by jkochhar** [comment]
Thanks Sean. Please let me know if you have questions.
