### ISSUE TITLE
CommonJS Support

### ISSUE THREAD

**Issue by alxlu** [winjs/winjs#1132]
Is it possible for us to provide CommonJS support? A common workflow is to do ```npm install --save winjs@4.0.0-preview``` and then include WinJS with something along the lines of ```var WinJS = require('winjs');```. An even more ideal scenario would be to be able to ```require``` individual components.

Apparently there was some support for the former in the past, but it has since been removed: https://github.com/winjs/winjs/issues/571

[Browserify](https://www.npmjs.com/package/browserify) is typically the go-to tool for bundling CommonJS modules and it essentially provides node.js style support for modules on the front-end. It's fairly popular as well. As of today it has:
>70,384 downloads in the last day
334,727 downloads in the last week
1,411,783 downloads in the last month

Furthermore, pretty much every major library/framework has some level of support for this: Angular, jQuery, React, Underscore, etc. From personal experience, if it's available on npm, it typically has support for CommonJS.

**Comment by jseanxu** [comment]
Keeping this issue as a feature request for Browserify integration. Opened a separate issue for making `var winjs = require("winjs")` work. See #1133

**Comment by jayrenn** [comment]
This has been fixed. https://github.com/winjs/winjs/commit/a7e365ddb71694f4c4a90b2d520e074974dc6702
