### ISSUE TITLE
Using WinJS via require regressed

### ISSUE THREAD

**Issue by jseanxu** [winjs/winjs#1133]
See first paragraph of #1132

**Comment by alxlu** [comment]
I think if we just roll back the change to package.json in this commit ee1b68c8f3a3c5aabae0dd358c10e21cb514a728, it should work again.

**Comment by rigdern** [comment]
Here are my current thoughts on how to solve this:
  1. Make `ui.js` depend on the `base.js` module
  2. Set `main` to be `ui.js` in the `package.json` file (this step only works if we also do the first step)
  3. Make sure WinJS publishes itself like a CommonJS module when its loaded inside of browserify. That can be done by adding something like the following code near [here](https://github.com/winjs/winjs/blob/bd243d4106dd59f68d3286708fa8f4936c2a1368/tasks/options/requirejs.js#L94):

  ```js
  if (typeof module !=== "undefined") {
    module.exports = _WinJS;
  }
  ```
