### ISSUE TITLE
hub load promise in page.Ready fails on phone (whether concatinating data load promises or not)

### ISSUE THREAD

**Issue by RobCamer** [winjs/winjs#1135]
I have an app that hosts a hub control on a page.  The hub control needs a lot of data for the hub sections so I create a data loading WinJS Promise to track when data loading completes:
// load data

var syncHubandDataLoadPromises = [];
syncHubandDataLoadPromises.push(new WinJS.Promise(function (complete, error) {
    var dataLoadingComplete = function (ev) {
        if (ev.detail &&
            ev.detail.loadingState === WinJS.UI.Hub.LoadingState.complete) {
            this._hubElement.removeEventListener("loadingstatechanged", dataLoadingComplete);
            complete();
        }
    }.bind(this);
    this._hubElement.addEventListener("loadingstatechanged", dataLoadingComplete, false);
}.bind(this)));

I then add all of the data loading promises to a new promise array:
this._pagePromises = [];
this._pagePromises.push(MyApp.Services.Queue.getQueueData().then(function (results) {
    this._queueData = results;
}.bind(this)));
...and so on for all the data

At the end I concat the this.pagePromises with the syncHubandDataLoadPromise to ensure that the app waits for the hub and the data to load before proceeding to bind data and templates in handleLoadingStateChangedBind:

syncHubandDataLoadPromises = WinJS.Promise.join(syncHubandDataLoadPromises.concat(this._pagePromises));

// Remove the splash screen once the data is loaded
syncHubandDataLoadPromises.then(
    function success() {
        this._handleLoadingStateChangedBind();
        MyApp.Utilities.SplashScreen.remove();
}.bind(this),
function error() {
    // TODO: Show error UI
}).then(function () {
    MyApp.Utilities.hideSpinner();
});

When I run on PC it works fine.  When I run on a device or the emulator, it hangs and is stuck in WinJS function startRunning(priority) function in an endless loop.

If I remove the syncHubandDataLoadPromises and instead just complete on the data loading promises in this._pagePromises, it no longer hangs but fails to run on PC or phone because the code attempts to data bind to the hub before the hub is ready.  So it is necessary to contact the hub loading and data loading promises in order to work on PC, but this hangs when run on Windows Phone

**Comment by Doogie90** [comment]
Quick follow-up, the issue phone appears to be with the hub loading promise I create above:
var syncHubandDataLoadPromises = [];
syncHubandDataLoadPromises.push(new WinJS.Promise(function (complete, error) {
    var loadingState = function (ev) {
        if (ev.detail &&
            ev.detail.loadingState === WinJS.UI.Hub.LoadingState.complete) {
            this._hubElement.removeEventListener("loadingstatechanged", loadingState);
            complete();
        }
    }.bind(this);
    this._hubElement.addEventListener("loadingstatechanged", loadingState, false);
}.bind(this)));

If I ignore the data loading promises and do this instead at the end:
syncHubandDataLoadPromises = WinJS.Promise.join(syncHubandDataLoadPromises);

// Remove the splash screen once the data is loaded
syncHubandDataLoadPromises.then(
    function success() {
        this._handleLoadingStateChangedBind();
        MyApp.Utilities.SplashScreen.remove();
}.bind(this),
function error() {
    // TODO: Show error UI
}).then(function () {
    MyApp.Utilities.hideSpinner();
});

it still hangs on phone.  It appears to be an issue in the Hub control on phone.

**Comment by rigdern** [comment]
What do these lines of code do?

```js
this._handleLoadingStateChangedBind();
MyApp.Utilities.SplashScreen.remove();

MyApp.Utilities.hideSpinner();
```

Are they all required to trigger the bug?

It would be very helpful if you could share a page/app with us that repros the bug. You can attach it to OneDrive as described [on our wiki](https://github.com/winjs/winjs/wiki/How-to-share-repros-of-issues-with-WinJS#sharing-videos-and-full-code-samples).

**Comment by Doogie90** [comment]
You don't need the splashscreen / spinner code to cause the bug.  this._handleLoadingStateChangedBind() is never called.  The app hangs and get stuck in "runner" in WinJS for the promise per above.  I provided two simpler repros in email but will add you directly to the thread.

**Comment by rigdern** [comment]
It looks like there is a bug in `MSApp.isTaskScheduledAtPriorityOrHigher` which is tracked by 2916874.

On phone, after scheduling a high priority job with `MSApp.execAsyncAtPriority`, `MSApp.isTaskScheduledAtPriorityOrHigher` always reports that there is work at a priority of normal or higher. This prevents the WinJS Scheduler from ever running any of its idle jobs and the Hub is waiting on an idle job before reporting that it has finished loading.
