### ISSUE TITLE
listview item invoked used on web not working when accessed from phone

### ISSUE THREAD

**Issue by ThatsIT** [winjs/winjs#1138]
I have copied your sematic zoom example to show the problem.
When used in a website and accessed using windows phone 10, oniteminvoked does not work.
http://jsfiddle.net/5ak9du1c/

**Comment by TheWrathOfConst** [comment]
I ran your sample on windows phone 10, and was getting iteminvoked events from the zoomed out listview (which is the only one set to be invokable) whenever I tapped one of its items. 

Couple questions for you:
- What ListView are you expecting to fire iteminvoked events?
- Could you specify what you mean by "oniteminvoked does not work"? Do you have an iteminvoked event handler that isn't being called when you're expecting it to be? Are you finding items aren't invokable when you expect them to be?

**Comment by ThatsIT** [comment]
I just tried the jsfiddle with a windows 8.1 phone and it works, but with windows 10 phone, with IE or Spartan it does not.
The sample has a 2 list views in a semantic zoom when clicking on one it should show the other, but does not in windows 10 phone
Thanks

**Comment by TheWrathOfConst** [comment]
I took a look at this on my 8.1 phone, and the behavior was mostly similar to Windows 10. The one difference I saw was that when i tapped on items in the zoomed in, those items lit up briefly. This is a bug - the items in the zoomed in listview are static (meaning they have no select or invoke behavior), so they should do nothing when tapped. Everything else worked the same on 8.1 as it did on 10 for me, but I'm not sure if I'm even looking at the right thing.

Could you define what you mean by "works"? Namely, what actions are you taking, what actions to you expect to occur in response to the actions you have taken, and what is actually happening when you take these actions?

**Comment by ThatsIT** [comment]
When I tap on the zoomed OUT (the letters only) tiles, nothing happens on windows 10 phone, but on windows 8.1 it zoomed in.
Thanks

**Comment by rigdern** [comment]
This appears to be fixed in the latest internal builds of Windows Phone 10. If you still see this issue in a future flight, please open a new bug and reference this one.
