### ISSUE TITLE
.win-pivot-item-content wrong width calculation

### ISSUE THREAD

**Issue by nhutquang97** [winjs/winjs#1142]
I don't know correctly, but I tested WinJS on UAP, the .win-pivot-item-content width is longer than expected, causing the scrollbar to be hidden. I checked the code and I think the problem is the calc formula of the element: instead of 28px, I use 38px and everything works correctly.

Before: 
 ```
.win-pivot-item .win-pivot-item-content {
   ...
    width: ~"calc(100% - 28px)";
}
```

After: 
 ```
.win-pivot-item .win-pivot-item-content {
   ...
    width: ~"calc(100% - 38px)";
}
```

Hope you guys can check on this and find a solution.

**Comment by jseanxu** [comment]
Hi @nhutquang97,

Thanks for reporting this issue, we are already tracking this issue and it is scheduled to be fixed as a high priority bug: #1094
