### ISSUE TITLE
Add class to globally opt-in to WinJS intrinsic styles

### ISSUE THREAD

**Issue by rigdern** [winjs/winjs#1164]
The change to make intrinsic styles opt-in on a per element basis causes quite a lot of work for apps that want to migrate to WinJS 4.0. For the benefit of apps that are migrating, we should enable developers to declare that they would like to globally opt-in to WinJS's intrinsic styles.

**Comment by jseanxu** [comment]
Closed via 1bdb0fd30c9283b96c111f70dd4e698253eacb8a
