### ISSUE TITLE
XYFocus doesn't add win-xbox class on Xbox

### ISSUE THREAD

**Issue by rigdern** [winjs/winjs#1168]
This is because `_ElementUtilities.hasWinRT` is always undefined. This property is actually on `_BaseCoreUtils`. The `_ElementUtilities.d.ts` file has to be updated to remove the `hasWinRT` property.

**Comment by jseanxu** [comment]
Talked to the Xbox folks and they said that they would like us to make no changes for 1505.

**Comment by jseanxu** [comment]
This change is no longer needed - we are generating a TV specific stylesheet that a developer can opt into using, instead.
