### ISSUE TITLE
Contribute the d.ts file back to DefinitelyTyped

### ISSUE THREAD

**Issue by rigdern** [winjs/winjs#1169]
We should do this for `winjs.d.ts`. Should we also do that for our WinRT d.ts file or do we have somebody else who will take care of that?

**Comment by rigdern** [comment]
When doing this work, also fix the issues tagged with `feature: winjs.d.ts`. For example: #1105.

**Comment by mikewjackson** [comment]
We are tracking this internally as a planned task.
