### ISSUE TITLE
ListView header/footer too strictly typed?

### ISSUE THREAD

**Issue by rigdern** [winjs/winjs#1182]
The ListView [header and footer are currently typed](https://github.com/winjs/winjs/blob/ffcb549d334c4d45cc5ae0bac696131f47266b30/typings/winjs/winjs.d.ts#L5965-L5973) as `HTMLDivElements` in the d.ts file. Do they need to be divs or should this be loosened to `HTMLElement`?

**Comment by mikewjackson** [comment]
We are tracking this internally as a planned task.
