### ISSUE TITLE
Non critical debug errors raised when debugging

### ISSUE THREAD

**Issue by mikewjackson** [winjs/winjs#1184]
I get a couple of errors for this code:

    (function (factory) {
        if (typeof define === 'function' && define.amd) {
            // amd
            define([], factory);
        } else {
            globalObject.msWriteProfilerMark && msWriteProfilerMark('WinJS.4.0 4.0.0.winjs.2015.5.22 base.js,StartTM');
            if (typeof module !== 'undefined') {
                // CommonJS
                factory();
            } else {
                // No module system
                factory(globalObject.WinJS);
            }
            globalObject.msWriteProfilerMark && msWriteProfilerMark('WinJS.4.0 4.0.0.winjs.2015.5.22 base.js,StopTM');
        }
    }(function (WinJS) {

Error example:

      Exception was thrown at line 11, column 9 in ms-appx://foo/WinJS/js/base.js
      0x800a1391 - JavaScript runtime error: 'define' is undefined

They are non-critical errors and I can continue on but is there a way to have it so that all exceptions are enabled but the code not throw any errors?

**Comment by rigdern** [comment]
These exceptions are due to a Chakra bug (2257991) which is fixed in the latest internal Win10 builds.
