### ISSUE TITLE
Pull to Refresh

### ISSUE THREAD

**Issue by maheshvemuri** [winjs/winjs#1186]
Hello Team,

Progressive Loading of listview is synchronous and not working with Ajax calls. SO, please make it synchronous and also put pull to refresh in WinJS 4.0

**Comment by TheWrathOfConst** [comment]
Hi @maheshvemuri. Thanks for opening this issue. Could you provide us with code snippets that reproduce the issue you're encountering? You can find [instructions on sharing a repro on our wiki](https://github.com/winjs/winjs/wiki/How-to-share-repros-of-issues-with-WinJS)
