### ISSUE TITLE
Semantic Zoom group headers are not clickable with mouse or touch

### ISSUE THREAD

**Issue by DanarchyX** [winjs/winjs#1188]
There seems to be a regression with the group headers in recent builds where they now appear un-clickable.  Turns out you can click/tap them if you do so above the header.  There seems to be an offset currently for the hit target.

**Comment by TheWrathOfConst** [comment]
I tried to repro this behavior but wasn't able to. Could you provide us with a repro for this issue? You can find [instructions on sharing a repro on our wiki](https://github.com/winjs/winjs/wiki/How-to-share-repros-of-issues-with-WinJS)

**Comment by DanarchyX** [comment]
Open Music app on Windows 10.  Change the "Sort by" to "A to Z".  This will show you a grouped albums view.  Now try to click on any header.  If you click on the text nothing happens.  If you click/tap anywhere else on the header then it works fine.  Looks like the text portion of the group header isn't invoking the element.

**Comment by DanarchyX** [comment]
Looking at DOM explorer it looks like the div used to render the group hint is swallowing the click.  Normally the button wrapping that div would get the click.  Not sure why this div is now doing this.  I'm now calling the button on the div click and things are working again.  Closing this issue but still feels like there was a regression here. Thanks.
