### ISSUE TITLE
Flyout Command throws exception after resizing ToolBar/AppBar

### ISSUE THREAD

**Issue by rigdern** [winjs/winjs#1198]
### Repro Steps

1. Download and unzip repro.zip from http://1drv.ms/1G6VKof
2. Open repro/index.html
3. Under "Repro 1", click "Toggle ToolBarSize"

**Unexpected result**: An exception is thrown

### Cause and Fix

The exception is thrown [here](https://github.com/winjs/winjs/blob/b4cb8026b4fdb485d5ac4f2308a8bb68d9b9d22b/src/js/WinJS/Controls/Menu/_Command.js#L362) because `this._flyout` refers to the Flyout's DOM element instead of the Flyout winControl.

To fix this, we could reference `this.flyout` instead of `this._flyout`.

**Comment by pke** [comment]
Any chance this will be back-ported into 3.0?
