### ISSUE TITLE
Elements may be rendered on top of closed AppBar/NavBar

### ISSUE THREAD

**Issue by rigdern** [winjs/winjs#1203]
![image](https://cloud.githubusercontent.com/assets/199935/7978728/bc37ecb8-0a4d-11e5-80fc-4c1e14e42ae2.png)

This can happen when a DOM element occurs after the AppBar/NavBar in the DOM. The fix is to add a  static `z-index` to the AppBar/NavBar. Currently, it only has a `z-index` when it is opened. This is because when it's open, it is light dismissable so the LightDismissService assigns it a z-index.

We should check if the SplitView pane is affected by this and look to see if there are any other light dismissable controls which can be visible while they aren't in the LightDismissService -- such controls would be susceptible to this bug.
### Repro

```html
<!doctype html>
<html>
<head>
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <title></title>

    <link href="winjs/css/ui-light.css" rel="stylesheet" />
    <script src="winjs/js/base.js"></script>
    <script src="winjs/js/ui.js"></script>
</head>
<body>
	<div data-win-control="WinJS.UI.AppBar">
		<button data-win-control="WinJS.UI.AppBarCommand" data-win-options="{
			icon: 'accept',
			label: 'accept'
		}"></button>
	</div>

	<br /><br /><br /><br /><br /><br />
	<div data-win-control="WinJS.UI.Rating"></div>

	<script>
		WinJS.UI.processAll();
	</script>
</body>
</html>

```

**Comment by AmazingJaze** [comment]
Looked at WinJS controls with @rigdern, we believe that only NavBar and AppBar need this fix.
