### ISSUE TITLE
Some accent color rules for intrinsics don't work in Firefox

### ISSUE THREAD

**Issue by rigdern** [winjs/winjs#1204]
[This rule](https://github.com/winjs/winjs/blob/b4cb8026b4fdb485d5ac4f2308a8bb68d9b9d22b/src/js/WinJS/Controls/IntrinsicControls.js#L19-L24) doesn't work in Firefox. If you remove the `::selection` selector, it starts working.

The result is that the following things don't have the appropriate background color in Firfefox:
  - primary button elements (i.e. buttons with `win-button-primary` class)
![image](https://cloud.githubusercontent.com/assets/199935/7991730/35d5a086-0aaf-11e5-8ccc-48448a39fefc.png)
![image](https://cloud.githubusercontent.com/assets/199935/7991737/4ccfccda-0aaf-11e5-9d16-81661adbc2b7.png)

  - checked drop down options
  - selected text

**Comment by AmazingJaze** [comment]
Confirmed that it doesn't work with the global intrinsics file either.
http://winjs-jessesh.azurewebsites.net/intrinsics/global.html
