### ISSUE TITLE
AppBar Unusable on Lumia Icon/IE11

### ISSUE THREAD

**Issue by SamuelEnglard** [winjs/winjs#1205]
I've started to use WinJS for my blog and on my phone, a Lumia Icon, the app bar is simply unusable. They are about a quarter of an inch square. Trying to tap them is impossible!

![Screen Shot](https://cloud.githubusercontent.com/assets/1119883/7993034/4cfe998a-0ad1-11e5-882e-792d457a7979.png)

**Comment by AmazingJaze** [comment]
Hi @SamuelEnglard, I believe including the following HTML5 meta tag inside of your page's `<head>` tag should rectify this issue by [preventing initial zoom-out](http://www.javascriptkit.com/dhtmltutors/cssmediaqueries3.shtml) on mobile devices.
```html 
<meta name="viewport" content="width=device-width, initial-scale=1">
```
[This test page](http://winjs-jessesh.azurewebsites.net/appbar/index.html) uses a WinJS Appbar and looks fine on my Lumia device. Feel free to copy additional attributes from its meta viewport tag if the above doesn't solve your issue.

**Comment by SamuelEnglard** [comment]
That fixed it! thanks!
