### ISSUE TITLE
Pivot does not work well inside of a Flyout

### ISSUE THREAD

**Issue by SamuelEnglard** [winjs/winjs#1206]
To use a Pivot inside a flyout I'm currently having to recreate the pivot on every open of the flyout, otherwise the layout is messed up making the pivot unusable.

**Comment by AmazingJaze** [comment]
Hi @SamuelEnglard, 

Can you 
1) provide a screen shot of the issue 
2) Tell me a little bit more your scenario for putting a pivot control inside of a flyout?

**Comment by SamuelEnglard** [comment]
Once I'm home I'll take a screen shot of it not working but the reason I'm putting a Pivot in a flyout is on my blog I'm showing what podcasts I listen to using a pivot in a flyout. I looks really nice I think but if I declare the pivot in HTML and let it be created during `processAll` it doesn't work.

Off the top of my head the issue was that the positioning of the inner container calculations would be grossly off, pushing the content out of view.

**Comment by AmazingJaze** [comment]
I think the appropriate solution here is to listen the the Flyout's "onbeforeshow" event and call forceLayout() on the pivot like so:
```JS
flyout.addEventListener("beforeshow", function(){
   flyout.element.querySelector(".win-pivot").winControl.forceLayout()
}
```
Let us know if that resolves the issue for you.

**Comment by SamuelEnglard** [comment]
That only sometimes fixes it

**Comment by AmazingJaze** [comment]
Strange that it only sometimes fixes it. Can you provide a page/app which repros this behavior, along with the steps to have it reproduce even after pivot.forceLayout() is called? You can share it using OneDrive as described [on our wiki](https://github.com/winjs/winjs/wiki/How-to-share-repros-of-issues-with-WinJS).

**Comment by SamuelEnglard** [comment]
Environment: Mozilla/5.0 (Windows NT 6.3; WOW64; Trident/7.0; .NET4.0E; .NET4.0C; .NET CLR 3.5.30729; .NET CLR 2.0.50727; .NET CLR 3.0.30729; rv:11.0) like Gecko

In https://onedrive.live.com/redir?resid=4b38cdd7b38bb7f%21475 there's a Bugs.htm file that repros the issue.

**Comment by SamuelEnglard** [comment]
Just wanted to add that to see the pivot click on the microphone icon in the app bar

**Comment by AmazingJaze** [comment]
Thanks. From my quick investigation it appears to work correctly the first time the flyout is opened, as well as each subsequent time the flyout is opened, until I pivot to a new section header. 

Once I've done that I see that the pivot headers render correctly but that the initial section content is completely blank, when the flyout opens.

Is this the same behavior you are experiencing?

**Comment by SamuelEnglard** [comment]
Yup

**Comment by AmazingJaze** [comment]
Thanks, the problem is with forceLayout, i've filed #1225 for this. @jseanxu  Do you know a better work around in the meantime other than just re creating the pivot control each time?

**Comment by SamuelEnglard** [comment]
Ah. Ok. Good to know. Thanks for the quick responses

**Comment by jseanxu** [comment]
I think recreating the pivot is the best workaround at this time.

**Comment by mikewjackson** [comment]
We are using #1225 to track this issue. Thanks for reporting it!
