### ISSUE TITLE
WinJs 4.0 ListView doesn't render past 100 items

### ISSUE THREAD

**Issue by mtycholaz** [winjs/winjs#1211]
I have a Binding list datasource with an array of 192 items. When I use it with my listview, it will only render the first 100 items. How do I render the rest? I looked at the progressive example, but I'm not adding new data to my datasource. It already has all the items that I will show.

**Comment by AmazingJaze** [comment]
Hi @mtycholaz can you tell us a little more about how you are configuring the Listview in your scenario?

Additionally, can you link me to the particular progressive example are you referring to? ListView _did_ support incremental loading at one point, but that was deprecated beginning with WinJS 2.0.

The ListView only uses random accesss virtualization. It should render items as you scroll to them, and release items on pages you have scrolled away from, but you're saying its only ever rendering the first 100, is that correct? 

---

How many pages ahead the ListView renders, and how many pages behind it retains, is an automatic behavior, but if you need granular control over it you can modify the ListView maxTrailingPages and maxLeadingPages [properties](https://msdn.microsoft.com/en-us/library/windows/apps/dn921742.aspx)

---

If none of the above helps you resolve the issue, can you provide a page/app which repros this behavior? You can share it using OneDrive as described [on our wiki](https://github.com/winjs/winjs/wiki/How-to-share-repros-of-issues-with-WinJS).

**Comment by mtycholaz** [comment]
I'm going to look into providing more details for you. Off the top of my head, here is what I'm doing.

- Using Winjs 4 with angular-winjs
- Setting the dataSource to a `new WinJs.Binding.List( [Array of 190 items])`
- The array comes from a WinRT Portable C# component accessed via Javascript
- Scrolling to the bottom of the list only displays up to item 99
- Debugging shows the datasource having 190 items. 

More to come later

**Comment by mtycholaz** [comment]
Well, after sitting down to setup a project, to reproduce the problem...I haven't been able to reproduce the problem. I know this is cliché, but I'm starting to sound like a QA tester. It happened, I swear, but it's working now.

**Comment by AmazingJaze** [comment]
Glad this is no longer an issue for you. Please let us know if you see it again.

**Comment by peryton** [comment]
@mtycholaz I believe I may be encountering this problem as well and maybe I could make the issue show up in your project. Can you please share the project you set up?   

I have noticed that if I set the dataSource to a list of > 100 items and try to "ensureVisible" one of the items with an index of > 99, then "ensureVisible" fails silently.
