### ISSUE TITLE
Add a item-detail-template to the ListView control

### ISSUE THREAD

**Issue by mtycholaz** [winjs/winjs#1212]
This would be very handy to select an item in the list, and have it animate open/expand to show a detailed template.

**Comment by AmazingJaze** [comment]
Hi @mtycholaz is this a feature request specifically for a new visual studio template, or some sort of ListView scenario sample in general?

**Comment by mtycholaz** [comment]
This is a ListView scenario. You have a list of items, and when you tap on one of them, it would expand to show child related data template.

**Comment by jseanxu** [comment]
Are you talking about something similar to what the mail app does when clicking on a threaded mail conversation, see #192.
