### ISSUE TITLE
What's the correct way of checking for security access?

### ISSUE THREAD

**Issue by sebagomez** [winjs/winjs#1213]
So I have in my app a security environment where when the user wants to go to some pages I need to check for his credentials. If he's not properly authenticated I need to redirect him to a login page.
I was doing this check in the `init` method of the Page, set flag to the page (`needsAuthentication`) and then checked that flag on the `processed` method and if present I throw an exception handled by the `error` method of the page.

So far is the best I've come with... is there anything else or better I can/should do? 

FYI: its a WinPhone app with WinJS 2.1

**Comment by jseanxu** [comment]
We don't have any particular pattern for this scenario - what you are doing sounds like correct leverage of the lifetime events of a PageControl so I would just go with that :)

**Comment by sebagomez** [comment]
Unfortunately it is not working in some scenarios :(
Seems like the second page ready executes before the first page processed, so I get messed up controls (AppBar) for example. Will try to create a small repo project.
