### ISSUE TITLE
WinJS.d.ts file still includes API for ListView incremental loading scenarios

### ISSUE THREAD

**Issue by AmazingJaze** [winjs/winjs#1216]
Any reason we are holding on to these? Incremental loading has been disabled since WinJS 2.0, right?

https://github.com/winjs/winjs/blob/85f3681bdd48b816ab73cab6532746ea4f31a4fb/typings/winjs/winjs.d.ts#L5990-L5998

**Comment by mikewjackson** [comment]
We are tracking this internally as a planned task.
