### ISSUE TITLE
NuGet Package: Please install files in corresponding folder

### ISSUE THREAD

**Issue by NCC1701M** [winjs/winjs#1217]
When I install WinJS via nuget it's installed in the top directoy of the VS-Solution. It should be installed in the Scripts folder and in the Content Folder.

**Comment by jseanxu** [comment]
This is consistent with how WinJS was shipped in previous versions of VS. The project template for WinJS apps would have a standalone folder in the root of the project.

We also do not want to make assumptions about the file structure of __your__ project; some people may call their source folder `src` or `source` or `sources`, etc. The content folder may be called `content` or `contents` or `assets`, etc.

**Comment by NCC1701M** [comment]
Ok, but other nuget projects has this abillity and it's the default structure for VS ASP.NET Web Applications.

**Comment by jseanxu** [comment]
WinJS is typically used in a UWP project where the structure is different.

**Comment by NCC1701M** [comment]
Yes it is, but it's no longer only for UWP projects. As you can read on the official site "Use WinJS not only for your Universal Windows apps with HTML/JS, but also for your websites"[https://dev.windows.com/en-us/develop/winjs]

**Comment by jseanxu** [comment]
What change are you proposing that will satisfy both default UWP project folder structure and default ASP.NET project folder structure?

**Comment by NCC1701M** [comment]
I don't know the nuget infrastructure but isn't there something like placeholders for the folders like %script% and %styles%

**Comment by jayrenn** [comment]
Thanks for the suggestion! You can control which folder the package is installed into. Read more about [this here](http://stackoverflow.com/a/4197201/3942177).

If this doesn't solve your problem, feel free to re-open the issue!
