### ISSUE TITLE
What's the proposed migration path for WinJS.UI.SettingsFlyout?

### ISSUE THREAD

**Issue by pke** [winjs/winjs#1219]
While I am very unhappy for scraping the charms bar in Windows 10, its nothing that user-voice could have prevented it seems. Maybe usability tests inside MSFT proved the Charms bar to be to advanced/awkward for most Users out there. I believe it was poorly promoted and explained. It was unique to hold common functionality of/for all apps there, especially in tablet mode. In Desktop mode it would have been enough to move the charms to each windows' titlebar/system menu.

Anyway, that train(wreck) is moving now and I wonder what are the recommended steps to move from setting panes to whatever is the new hotness in Windows 10? Where is the entry point for settings supposed to be now? Is each settings pane just a new page in the app? Are settings still supposed to be applied instantly or do we have to reintroduce an "apply" button?
Where is the new Windows 10 UX Guideline? It seems the current UWP Design Guidelines is a wild mixture of new and old content. https://msdn.microsoft.com/en-us/library/windows/apps/hh770544.aspx still contains the settings pane.

**Comment by jseanxu** [comment]
Hey @pke,

Sorry to hear about that you are upset with the deprecation of the Charms. This is a decision made on a UX level and made based on usability data. I personally like the Charms myself :)

As for the mitigation story for the SettingsPane, I believe the guideline is that settings should go on a dedicated page in the app. Whether settings should be applied instantly or whether there should be an apply button would be up to the developer - I'm not sure if there will be official guidance on these finer details. Also, keep in mind that UWP and Win10 and their related designs are not yet final, so expect the UWP Design Guidelines to be a live document until the official release.

**Comment by pke** [comment]
Good to know I am not the only one who found the Charms idea good and useful. I wonder if MSFT will ever release a video about the decision to scrap it. They released a video about why they introduced the Ribbon control in the Office suite and it was quite interesting what kind of research went into it. Yet, people bashed it from the beginning and do so till today. So maybe some day we will know what kind of user data let the Charms control die so quickly.

I also liked it cause the system gave us (with 8.1) some unified options for managing user accounts within the settings pane. Now everybody has to code that again themselves. It's really a huge step backwards!

**Comment by jseanxu** [comment]
>>About the new design in Windows 10. Currently the settings pane also holds the permissions and package infos. Where are those suppose to go in new Windows 10 apps. And are we really back to hide app settings in each apps menus again?

The app developer is expected to include this information themselves if they want to display it.

**Comment by pke** [comment]
A clear step backward, imho. I hope in Windows 10.x some of those mistakes are revisited again if more developers complain about how much more work we are expected to put into basic things (again).
