### ISSUE TITLE
Question: What is the progressive enhancement story

### ISSUE THREAD

**Issue by SteveALee** [winjs/winjs#1221]
Congrats on getting 4.0 out. You have a great responsive set of controls and containers that appear to be a great match for my requirements. ive watched this steadily improving since 1.0, at least for native win apps where the context is well known.

As a potential user of WinJS for a web app I aspire to providing a good progressive enhancement experience. For example older browsers (even opera mini) or on devices or in contexts where JS and CSS errors occurs.

What is your attitude to and current status for supporting PE? Certainly some controls build on standard controls and could fail safe with some work. But others are not so clear. 

How about a blog post on this topic which appears to back in the spotlight in response to so many javascript heavy Frameworks.

Forgot I'll probably stick to JQuery Mobile whuch explicitly supports PE, though the UX might not be as compelling as winJS on fully capable devices.
I know @Codepo8 is hot on thus and now works for Microsoft.

**Comment by jdalton** [comment]
Hi @SteveALee! Thanks for the encouragement. A blog post or clarification on PE may be in our future.
