### ISSUE TITLE
WinJS 4.0 seems to behave incorrectly on Windows 10 Mobile 

### ISSUE THREAD

**Issue by huhubun** [winjs/winjs#1222]
I made a demo app using WinJS 4.0 release version and deploy it on a Lumia 1520 with Window 10 mobile(Ver:10.12562.84). When running the app, ui.js(line 7599, column 9) will throw exception 0x80004002 - JavaScript runtime error: No such interface supported.
![js_error](https://cloud.githubusercontent.com/assets/5095184/8063366/ee487c1e-0f06-11e5-8f5c-1ab6ede7fb13.png)
However, if I switch WinJS to verison 4.0 preview, or deploy to a Windows Phone 8.1 emulator, it can run without any problem.
Is there anything that should be taken care of when using WinJS on Windows 10 Mobile?

**Comment by jseanxu** [comment]
Hi @huhubun,

This is a known issue with WinJS 4.0 on today's Windows Phone 10 Preview build and has been fixed via 6164967b6a93d84719d3d2fa0caefb0312bcccf4 which is staged in our release/4.0.1 branch.

**Comment by huhubun** [comment]
I downloaded and compiled 4.0.1 branch and add it to my app today. It works as promised. Thanks a lot.
