### ISSUE TITLE
Pivot forceLayout() needs to update scroll positions.

### ISSUE THREAD

**Issue by AmazingJaze** [winjs/winjs#1225]
If the pivot is hidden with display:none and then later reshown (or if the pivot were hosted in a WinJS.Flyout ) calling force layout doesn't update scroll positions.

__Repro__
1) http://winjs-jessesh.azurewebsites.net/pivotrepro/index.html
2) show the pivot
3) pick a new pivot header
3) hide the pivot
4) show the pivot

_Note: the page is calling pivot.forceLayout() each time its element's display is restored as part of showing the pivot_

__Expected:__ pivot section should be visible
__Actual:__ pivot section is off sceen and not visible

**Comment by jseanxu** [comment]
Fixed via Pivot animation redesign: 1015aea442b23a6a0971977091978fb58f92f9a1
