### ISSUE TITLE
Flyouts with iframes in them hide when you interact with the iframe

### ISSUE THREAD

**Issue by caseyfaber** [winjs/winjs#1226]
For flyouts that have an iframe in the content, it dimisses the flyout if you click in the iframe (to scroll for example).

**Comment by rigdern** [comment]
I wasn't able to repro this. Can you provide a page/app which repros this? You can share it using OneDrive as described [on our wiki](https://github.com/winjs/winjs/wiki/How-to-share-repros-of-issues-with-WinJS).

**Comment by caseyfaber** [comment]
Hmm, actually it works fine in Spartan, original repro was in IE. My app doesn't need to support IE 11 so I guess it's not actually a problem for me. You can repro it in IE here -http://osgdesigntools/styleguides/services/oobe/dev/onecol.html - Click Flyout 3

**Comment by rigdern** [comment]
I was able to repro the bug in your app even in Spartan/Edge. In Edge, the Flyout doesn't close when clicking on the scrollbar but it does close when clicking inside of the Flyout.

Your app was using WinJS 4.0.0-preview so I updated it to [WinJS 4.0.0](http://try.buildwinjs.com/#get) and the bug no longer reproed.

**Comment by caseyfaber** [comment]
Ah, that's great, thank you!
