### ISSUE TITLE
AutoSuggestBox forgets content set with queryText when losing focus

### ISSUE THREAD

**Issue by rigdern** [winjs/winjs#1227]
1. Download and unzip repro.zip from http://1drv.ms/1HtkCrs
2. Open repro/index.html
3. Click the "Change Text" button
4. Put focus into the AutoSuggestBox
5. Move focus out of the AutoSuggestBox

**Unexpected result:** The AutoSuggestBox's queryText is empty

**Expected result:** The AutoSuggestBox's queryText is "Here's some text"

**Comment by WolfspiritM** [comment]
Is this also the reason why I'm unable to get Autosuggestbox to work correctly?
I'm using react-winjs, but the issue I have is also available in the normal winjs showcase.

Reproduce:
1. Open the AutoSuggestBox Sample on the buildwinjs site.
2. Enter "S"
3. Choose "Shanghai" from the dropdown (or any other)
4. The box will display "Shanghai"
5. Click outside of the Box to make it lose focus

Unexpected result: Box displays "S"
Expected result: Box displays "Shanghai" as choosen from the dropdown

This is (for me) a complete showstopper having a big form.

**Comment by rigdern** [comment]
@WolfspiritM As a work around, you could register for the `focusout` event on the AutoSuggestBox's element and then set `queryText` in that handler.

**Comment by rcbyrne** [comment]
I am also struggling with this issue, are there any plans to resolve it?

**Comment by BodFerris** [comment]
To work around this issue, I attached to the 'resultsuggestionchosen' event and set the _prevQueryText to the queryText value.
Pseudo code: 
            autoSuggestBox.addEventListener('resultsuggestionchosen', () => {
                autoSuggestBox._prevQueryText = autoSuggestBox.queryText;
            });
