### ISSUE TITLE
electron.io and winjs base.js and ui.js 

### ISSUE THREAD

**Issue by Gi972** [winjs/winjs#1228]
Hello, I try the last version of winjs 4.0.0 with electron.io(0.28) but I have this message: "Cannot find module './base' " when I insert  base.js tag and  ui.js in a script's tag.

It 'is possible make a one file like the winjs-4.0.0.0-preview.js file ?  
thx

**Comment by jseanxu** [comment]
Hi @Gi972 
Can you share a project that demonstrates this issue? How would consolidating WinJS back into a single file solve this issue?

Thanks

**Comment by Gi972** [comment]
Hello Jseanxu, I find a solution, it's maybe specific to electron.io.
So just put in index.html this code:
<code>
<script>
<script>
  window = require('./lib/base.js');
  window = require('./lib/ui.js');  
</script>
<script>
<code>
