### ISSUE TITLE
SearchBox: Text entered in the search field dips down when you hide and show the search box

### ISSUE THREAD

**Issue by jkochhar** [winjs/winjs#1230]
![image](https://cloud.githubusercontent.com/assets/12311031/8124546/8e644f80-1091-11e5-97e5-c7ce3ca5c8e6.png)

**Comment by jseanxu** [comment]
I can't repro this issue by just toggling the display style on the SearchBox.

**Comment by jseanxu** [comment]
Closing this until there is a reasonably sized repro project.
