### ISSUE TITLE
Inputs are no longer displayed in corporate design

### ISSUE THREAD

**Issue by NCC1701M** [winjs/winjs#1231]
With WinJS 3 and even with WinJS 4 preview inputs looks like that:

![image](https://cloud.githubusercontent.com/assets/7260053/8126099/a4ca4608-10eb-11e5-897a-a73f0fff432d.png)

I could also use the icons from Symbol.ttf by using &amp;#xE1xx; but now with WinJS 4.0.1 the styles are not correct anymore. Now it looks that way. (I only uninstalled WinJS 3.0.1 with the package manager and installed the current version with Install-Package WinJS I didn't change anything in the html file)

![image](https://cloud.githubusercontent.com/assets/7260053/8126174/69126130-10ec-11e5-8ca7-9c13ccc23a3f.png)

Please fix this ASAP

**Comment by jseanxu** [comment]
Hi @NCC1701M 
This is an intentional breaking change, see our [change logs](https://github.com/winjs/winjs/wiki/Changelog#v401), under 4.0 styling.

**Comment by NCC1701M** [comment]
Hi @jseanxu,

so I have a big SPA with a lot of inputs an now I have to modify each control so that it looks like it did before. That's great *thumps up*

Why have you done such a big change instead of creating another class file where you put the removed styles in so that every developer could decide for themself to use the default layout or the WinJS layout?

**Comment by jseanxu** [comment]
There is a way to globally (re)enable WinJS styling - if you build WinJS, you should see `intrinsics.js` under `/bin/Microsoft.WinJS.4.0/js` and `ui-theme-intrinsics.css` under `/bin/Microsoft.WinJS.4.0/css`. Include the `css` and `js` files after the regular WinJS files and it should apply styles globally.

Note that these files were specifically created for compat reasons, if you are porting an existing app forward, then this is method should aid you with the port, but it is not recommended to start a new app with these files.
