### ISSUE TITLE
Question: Windows 8.1 and wp8.1 shared app support

### ISSUE THREAD

**Issue by Alphapage** [winjs/winjs#1232]
Hello,

Is it possible to use Winjs 4.0 to build Windows 8.1 and wp8.1 shared app ?

For now, I use native winjs like this:

    <link href="//Microsoft.WinJS.2.0/css/ui-dark.css" rel="stylesheet" />
    <script src="//Microsoft.WinJS.2.0/js/base.js"></script>
    <script src="//Microsoft.WinJS.2.0/js/ui.js"></script>

I know I can use winjs 4.0 in UWP, but what about WinRT8.1 and wp8.1 ?

Thanks in advance for your help.

**Comment by davidezordan** [comment]
Hi,
yes, it works. Just remove the references to WinJS 2 and add WinJS 4. 

Thanks,
Davide

**Comment by Alphapage** [comment]
Will give it try. Thank you.
