### ISSUE TITLE
ListView. Executing recalculateItepPosition/forceLayout inside loadingstatechanged "complete" causing infinite loop.

### ISSUE THREAD

**Issue by andrii-morozov** [winjs/winjs#1236]
Not sure that you need to fix that, probably just update documentation would be enough. However if I want to update the ListView after all the items have been loaded  it causes the infinite loop. 

 var loadingStateChanged = (event: any) => {
                    // Set empty block if necessary.
                    if (listViewControl.loadingState === "complete" && value.emptyListViewTemplate) {
                        toggleEmptyGridTemplate(listViewControl.itemDataSource.list.length);
                    } else {
                        listViewControl.recalculateItemPosition();
                    }
                };

**Comment by jseanxu** [comment]
This behavior is to be expected. Calling any of the two functions above will cause ListView to go thru its loading cycle which ultimately will end on `loadingState === "complete"`. Why do you need to forceLayout on `loadingState === "complete"`?

**Comment by andrii-morozov** [comment]
We need to update the win list view when it becomes visible. We were doing it on item loading. It was not a right way to do it I fixed it. Just wanted to let you know about the possibility of infinite loop.
