### ISSUE TITLE
WinJS.UI.SearchBox deprecated?

### ISSUE THREAD

**Issue by pke** [winjs/winjs#1239]
According to the ChangeLog its deprecated. Yet in the example code in the MSDN 4.0 release blog its still used (https://gist.github.com/jayrenn/8e965aec53d17302692d#file-pivot-custom-headers-html) . Its also still part of `ui.js`. So what's the status?

**Comment by rigdern** [comment]
The `SearchBox` is deprecated. Instead, you should use `AutoSuggestBox`.

For now, `SearchBox` works and is still in ui.js but using it results in a deprecation warning in the console. `SearchBox` may not be available in future versions of WinJS.

**Comment by pke** [comment]
I guess now that this custom control is deprecated `<input style="search"/>` will finally render properly in die Windows 10 native controls (ie: with a looking glass)?

**Comment by jayrenn** [comment]
@pke, thank you for pointing out that mistake! I have [updated](https://gist.github.com/jayrenn/8e965aec53d17302692d#file-pivot-custom-headers-html-L2) the gist to use the AutoSuggestBox.

**Comment by pke** [comment]
Current MSDN UWP Guidelines still mention the `WinJS.UI.SearchBox`
https://msdn.microsoft.com/en-us/library/windows/apps/hh465233.aspx
