### ISSUE TITLE
WinJS.UI.Hub: Back to chevron in interactive headers

### ISSUE THREAD

**Issue by pke** [winjs/winjs#1240]
Another change that makes less sense to me, imho. The chevron has been part of the Windows UI from the beginning in (popup) menus. So whenever the user sees ">" she knows something more is hidden behind this. It actually doesn't matter what exactly that is.
Now you have introduced a text, that looks awful lost between the hub headers, off-aligned, and needs to be translated to make it even worse.

Is there an easy way to revert that behaviour? At least it should be an option to let the developer decide if he want this interactive header decorated with a (custom) text or chevron (or any other symbol).

Interestingly I never saw this change coming, despite closely watching the WinJS development. Would have raised concerns from an API usage side before.

This again makes me wonder: Is WinJS actually used by anyone inside MSFT or big app developers at the moment? It seems some of the changes come out of nowhere and make it particular difficult to update old WinJS apps. They seem to come from a highly theoretically viewpoint and not real world usage of the lib in apps.

**Comment by jdalton** [comment]
The changes to hub align with metro 2.0 styles. We're not pursuing a compat path to older styles at this time.

**Comment by pke** [comment]
@jdalton Do you have a link to the reference UX docs for "metro 2.0"? Do you still call it like that internally?

**Comment by jayrenn** [comment]
Hi @pke, take a look [here](https://dev.windows.com/en-us/design). This was the best resource I could find.
