### ISSUE TITLE
ItemContainer: Throws exception when invoked

### ISSUE THREAD

**Issue by rigdern** [winjs/winjs#1243]
Instead of playing an animation, the ItemContainer throws an exception when invoked. This started happening in 50619e1be1d06f7d5fdc30309f2445243649f4de when we disabled the pointer down animation in ListView. A new function was added and this same function needed to be added to the ItemContainer.

Affects 4.0.x but not master.

**Comment by mikewjackson** [comment]
What's your recommendation for this bug?

Sent from my Windows Phone
________________________________

**Comment by jseanxu** [comment]
Fixed via 61d854da2388777e11b94d69c743c868c5b51464
