### ISSUE TITLE
Use minified file on cdnjs.

### ISSUE THREAD

**Issue by PeterDaveHello** [winjs/winjs#1245]
Hi there, I'm the main maintainer of cdnjs project, I saw you provide the link to cdnjs on this page: http://try.buildwinjs.com/#get, actually, we provide minified files, which can be loaded faster, would you like to point to the minified version? Thanks!

**Comment by PeterDaveHello** [comment]
Any updates?

**Comment by mikewjackson** [comment]
Hi @PeterDaveHello - since we've revamped the try.buildwinjs.com site, I've moved applicable issues over to its repro, instead of tracking them here.
