### ISSUE TITLE
Source for playground (http://try.buildwinjs.com)

### ISSUE THREAD

**Issue by blackjyn** [winjs/winjs#1247]
The WinJS Playground site **http://try.buildwinjs.com/** is nice.
Where is the source, so we can use it offline?

**Comment by jdalton** [comment]
We'll consider this. We're  in the process of updating the site. Let us know the things you liked or didn't like about the site.

**Comment by blackjyn** [comment]
Here are my suggestions:
1.Add more samples 
2.Create samples based on category. i.e. "Controls", "Data Management", "Custom Styling", etc.
3.Add dedicated documentation to WinJS that is **specific to the Web Development Only** OR part of WinJS that is **neutral from specific Windows API**. 
I read the API on [MSDN] (https://msdn.microsoft.com/en-us/library/windows/apps/br211377.aspx). In short, its too subtle to understand "which is which ", because that contains API for Desktop, UWP, Windows Phone, Windows Store etc. There is no something like "filter" to sort the doc based on specific platform only.
We want WinJS API independently. 

Thank you. :)

**Comment by jayrenn** [comment]
Thanks for the feedback! I have logged your suggestions internally. This is definitely an area we look to improve in the future.

Related: https://github.com/winjs/winjs/issues/52#issuecomment-111244093

**Comment by xerz-one** [comment]
Well, now that WinJS is inactive, it would be pretty useful to release the playground source code for archival purposes. The [Wayback Machine](http://winjsdevelop.azurewebsites.net/playground/) cannot load it as intended!
