### ISSUE TITLE
AutoSuggestBox: Should have optional search icon

### ISSUE THREAD

**Issue by rigdern** [winjs/winjs#1248]
We deprecated SearchBox in favor of the AutoSuggestBox. Unlike the SearchBox, the AutoSuggestBox doesn't have a search icon:

![image](https://cloud.githubusercontent.com/assets/199935/8216943/c7d41a50-14ee-11e5-9415-41de3e82ea8f.png)

We should enable developers to optionally add the search icon. The XAML AutoSuggestBox has a `QueryIcon` property which can be used to include an arbitrary icon on the right side of the AutoSuggestBox. Perhaps we should consider a feature like that.

**Comment by SamuelEnglard** [comment]
This is the only reason I'm still using the SearchBox so I +1 this

**Comment by jayrenn** [comment]
I have added this request to our internal tracking.

**Comment by kusog** [comment]
I would like to see this.  It is now 4 months later.  Is this done, planning to be done, etc?

**Comment by cordasfilip** [comment]
This issue appears to be closed but is it working or not can someone say if it's done or not and will it be done at all?
