### ISSUE TITLE
Missing icons

### ISSUE THREAD

**Issue by quanglam2807** [winjs/winjs#1252]
I cannot some icons like handwriting, fingerprint,... like in the MSDN documents https://msdn.microsoft.com/en-us/library/windows/apps/hh770557.aspx

**Comment by jdalton** [comment]
Hi @quanglam2807! Could you provide a code sample and screenshots.

**Comment by quanglam2807** [comment]
@jdalton Here is it.
```
<button data-win-control="WinJS.UI.Command"
             data-win-options="{ label:'handwriting',
                                            section:'primary',
                                            type:'button',
                                            icon: 'handwriting'}"></button>
```
As stated in the document, I can use 'handwriting' for icon; but currently, it's not available with WinJS 4.0.1. I check icon.js, Symbols.ttf and I don't think it have been included in this build.

**Comment by jdalton** [comment]
Do you know if it's included in previous builds?

**Comment by quanglam2807** [comment]
@jdalton No, it's not. But I think if it's in the document, you guys should add it. I'm not sure but these icons can be use with XAML, so why not with WinJS?

**Comment by jdalton** [comment]
> But I think if it's in the document, you guys should add it. I'm not sure but these icons can be use with XAML, so why not with WinJS?

I agree, we'll look in to this.

**Comment by SPDoctor** [comment]
I have also noticed that the Symbols.ttf icon set is very limited. No "info" icon for example, which is pretty basic. Thanks.

**Comment by jayrenn** [comment]
Thanks for the heads-up! This certainly needs to be fixed. I'm going to mark this as a codebug, and we can hopefully resolve this soon.

**Comment by quanglam2807** [comment]
Just some updates:
The current font has different look with the font from http://modernicons.io/segoe-mdl2/cheatsheet/ and  https://msdn.microsoft.com/en-us/library/windows/apps/hh770557.aspx

I generate the TTF font from modernicons.io and I have found that the icons look different and fit better with Microsoft's Windows 10 apps. You can download the font here: http://s000.tinyupload.com/index.php?file_id=07911967908685393889

**Comment by AmazingJaze** [comment]
Assigning back to @jayrenn until we've closed with design and LCA to get the new web font.

**Comment by cthedot** [comment]
Just noticed today that included symbols.ttf (which actually include WOFF and WOFF2 formats?) are the "old" Windows 8/8.1 style icons. I assumed these are already the new Segoe MDL2 Icons. Is this a problem of permission to include the MDL2 font?
