### ISSUE TITLE
WinJS throws exception in hidden iframe in Firefox

### ISSUE THREAD

**Issue by rigdern** [winjs/winjs#1253]
### Impact
The Try Site hit this bug which created the symptom described by #1251. The Try Site resolved its symptom by working around the issue.

It only affects WinJS when running in Firefox in an iframe that is `display: none`.

### Details

In Firefox, `getComputedStyle` returns null within an iframe which is `display:none`. This appears to be against the speced behavior which states that `getComputedStyle` always returns a `CSSStyleDeclaration`:
  - [CSS spec](http://www.w3.org/TR/DOM-Level-2-Style/css.html#CSS-ViewCSS)
  - [MDN](https://developer.mozilla.org/en-US/docs/Web/API/Window/getComputedStyle)

There's a Firefox issue from 2010 tracking this: https://bugzilla.mozilla.org/show_bug.cgi?id=548397

This Firefox bug affects [this line](https://github.com/winjs/winjs/blob/8f7e215fab216f079bf19aecc798438986a5cb80/src/js/WinJS/_Accents.ts#L154) of the Accent color code which runs during WinJS's initialization. This was the cause of #1251 on the Try Site.

The question is: should WinJS work around this Firefox bug or should we tell developers who hit it to not run WinJS while the iframe is `display:none`? Some challenges with working around it:
  - `getComputedStyle` in this case is used to figure out if we are in the dark or light theme for generating the accent color. We could pick a theme since our detection failed but we might pick the wrong theme.
  - WinJS uses `getComputedStyle` in other places and none of them assumed that it could return `null`. Would we also consider fixing it in those locations?

**Comment by mikewjackson** [comment]
Let's use this issue to track fixing the start up code path. We should certainly consider a broader fix via a VSO task.
