### ISSUE TITLE
WinJS 4.0.1 - Missing undefined check in function applyDownVisual(transform) of ui.js

### ISSUE THREAD

**Issue by davidezordan** [winjs/winjs#1255]
Hi,
sometimes applyDownVisual() is called when that._site.isInSelectionMode is undefined, causing an exception. I've been able to fix it checking if isInSelectionMode() is defined:

                    function applyDownVisual(transform) {
                        if (that._site.isInSelectionMode && that._site.isInSelectionMode()) {
                            return;
                        }

                        if (that._site.animatedElement.style[transformNames.scriptName] === "") {
                            that._site.animatedElement.style[transformNames.scriptName] = transform;
                            that._site.animatedElementScaleTransform = that._site.animatedElement.style[transformNames.scriptName];
                        } else {
                            that._site.animatedElementScaleTransform = "";
                        }
                    }

Thanks,
Davide

**Comment by mikewjackson** [comment]
Thanks for the report. We believe this is a dupe of #1243

**Comment by davidezordan** [comment]
Thanks!
