### ISSUE TITLE
Make SplitViewCommands work great when put inside a SplitView pane

### ISSUE THREAD

**Issue by jayrenn** [winjs/winjs#1258]
There are some problems with the current styling of NavBarCommands in a SplitView pane.
• There’s no keyboard focus visual
• No resized keyboard focus visual surrounding the command’s icon and label when the pane is peaking (you really want it to only surround the icon). 

One of the possible regressions of NavBar control if we make NavBarCommands own the keyboard focus visual instead of NavBarContainer owning it is that we would have 4 event listeners per command instead of 4 event listeners for the whole NavBarContainer.

**Comment by AmazingJaze** [comment]
@rigdern. did you say there was something missing from this bug, From the description alone this doesn't feel like a P1 issue to me.

**Comment by AmazingJaze** [comment]
Updating the title to apply to WinJS.UI.SplitViewCommand only, which is the replacement for WinJS.UI.NavBarCommand starting in WinJS 4.2
