### ISSUE TITLE
Pivot headers animate when animations are disabled

### ISSUE THREAD

**Issue by rigdern** [winjs/winjs#1262]
The Pivot headers animate when in overflow mode when animations are disabled.

This is due to this code: https://github.com/winjs/winjs/blob/9ac7a6aee12bfcf61f70335eb0a7e0e75a247e7f/src/js/WinJS/Controls/Pivot.js#L432-L437

We should either:
  - Use PVL animations (e.g. `executeTransition`) to get this behavior for free
  - Update this code to account for animations being disabled

**Comment by jayrenn** [comment]
@rigdern, can you provide repro steps?

**Comment by jseanxu** [comment]
Fixed via 63f6140543dfac828229025f9baa6198bf78deb5
