### ISSUE TITLE
Pivot: Can't interact with custom headers with touch in IE/Edge

### ISSUE THREAD

**Issue by rigdern** [winjs/winjs#1263]
1. Create a Pivot with a custom left or right header which is interactable (e.g. a button, textbox)
2. View the Pivot in IE/Edge
3. Try to interact with the custom header with touch

**Unexpected result:** The custom header doesn't respond to touch input

**Comment by lamuertepeluda** [comment]
It may be unrelated, but on Windows Universal apps if the device is touch (tablet or phone), the touch event on the normal header is messed up (see #1285).
