### ISSUE TITLE
We should remove classList usage from our codebase

### ISSUE THREAD

**Issue by jseanxu** [winjs/winjs#1265]
We use `classList` in many place in our codebase that could result in crashes if the element in question is, for example, an SVG element.

See example issue: #1254

**Comment by jdalton** [comment]
You can checkout the Modernizr wiki for `classList` shim to base the utility method replacement on here:
https://github.com/Modernizr/Modernizr/wiki/HTML5-Cross-Browser-Polyfills#classlist
