### ISSUE TITLE
Pivot w/ animations disabled: headers don't update when resizing

### ISSUE THREAD

**Issue by rigdern** [winjs/winjs#1266]
1. On the Try Site, open the Pivot sample
2. In the JS, disable animations: `WinJS.UI.disableAnimations();`
3. Run the sample
4. Click "Toggle Pivot Width". Make sure the window is wide enough so that all of the headers fit.

**Expected result:** "inbox" is the first header

![image](https://cloud.githubusercontent.com/assets/199935/8366306/b17bbfdc-1b48-11e5-94db-8ffdb840a21f.png)

**Actual result:** "flagged" is the first header

![image](https://cloud.githubusercontent.com/assets/199935/8366302/a72e4a04-1b48-11e5-9fdc-2f3f0da61c39.png)

If you click on another header, you'll see that "inbox" finally becomes the first header.

**Comment by jseanxu** [comment]
This issue has been fixed via 1015aea442b23a6a0971977091978fb58f92f9a1
