### ISSUE TITLE
UIColorType is undefined [win 8.1]

### ISSUE THREAD

**Issue by darkyen** [winjs/winjs#1272]
OS : Windows Phone 8.1
Device : Lumia 640

https://github.com/winjs/winjs/blob/a045428815cda2f6b005e1590af64598c07ff972/src/js/WinJS/_Accents.ts#L109

Debugging in Visual Studio throws error at that line, with UIColorType (Which is windows 10 only) being undefined.

I have used the following code on windows 8.1 since forever 
```javascript
    var tempEl = document.createElement('div');
    tempEl.style.background = 'Highlight'; // no js api ? no problem, we will just use the css one.
    var accentColor = window.getComputedStyle(tempEl).backgroundColor
```
Can it be added as a shim for now ?

**Comment by jdalton** [comment]
Hi @darkyen! Could you clarify what your issue is? How does the snippet provided relate to the `UIColorType` being `undefined`?

**Comment by darkyen** [comment]
UIColorType is a windows 10 only api (or as the docs say), hence when debugging with VS it threw an exception (which was caught), I believe that if possible we should detect the base colors since the app is running in WP where it is possible, the snippet i provided creates a temporary DOM element applies the style (as exposed in CSS) and gets back the accent color by a hack i have been using with windows 8.1
