### ISSUE TITLE
Vertical Hub: Scrolling broken on initial load in Chrome

### ISSUE THREAD

**Issue by rigdern** [winjs/winjs#1273]
### Impact

Upon loading of a vertical Hub in Chrome, neither touch nor mouse scroll wheel can scroll the Hub. After you've resized the window, these scroll mechanisms begin working.

This does not repro when WinJS animations are disabled.

### Repro Steps

1. Download and unzip repro.zip from http://1drv.ms/1JaVlBg
2. Open repro/index.html in Chrome
3. Try to scroll the Hub either with touch or mouse scroll wheel

**Unexpected result:** Hub doesn't scroll

**Comment by jseanxu** [comment]
This is a Chrome bug, it can be repro'd on a page without WinJS... opened a bug on Chromium:
https://code.google.com/p/chromium/issues/detail?id=515674

We should still work around this issue to enable Chrome users to scroll a vertical hub.
