### ISSUE TITLE
base.js missing from main section of .bower.json

### ISSUE THREAD

**Issue by sondreb** [winjs/winjs#1275]
Using Gulp to concat, uglify, etc. the bower components relies on using the main section of the .bower.json file in the package. It should include base.js before ui.js, like in the example below:

```
"main": [
    "js/base.js",
     "js/ui.js",  
     "css/ui-dark.css",
    "fonts/Symbols.ttf"
  ]
```
I wanted to make a pull request for this, but it appears that the bower.json and .bower.json files are not part of the repo. Are they in some seperate branch, or are these files only available at the computer for those who publish the package?

**Comment by jayrenn** [comment]
Yes, there are in a separate branch. A [similar issue](https://github.com/winjs/winjs-bower/issues/2) was filed there.

**Comment by jayrenn** [comment]
Hi @sondreb, it would appear other people are having this same problem. Could you provide more information and/or a small sample gulp file that could repro this bug in [this thread](https://github.com/winjs/winjs-bower/pull/3)?
