### ISSUE TITLE
Option to persist cookies between app launches

### ISSUE THREAD

**Issue by AdamPflug** [winjs/winjs#1276]
I'm using cookies along with an iframes and Content URI to manage login state for my application (which uses XMLHTTPRequests to query a remote API server). Everything works fine, except that it clears the cookies every time the app is shut down for some reason. Would love an option to persist the cookies for Content URI's.

Or am I missing something?

**Comment by jdalton** [comment]
Hi @AdamPflug. Could you provide a bit more info like by way of a gist and we'll redirect to the appropriate product team.

**Comment by AdamPflug** [comment]
The basics of my log-in setup are like this:
https://gist.github.com/AdamPflug/a2d86d934c810b2aba49

... then other parts of my application can query the web services at `example.examplecrm.com` just fine. The trick is when I close my app and open it again, I need to re-authenticate because my session cookie has been discarded.

**Comment by jdalton** [comment]
Thanks @AdamPflug! While this is outside the scope of WinJS we'll forward this request on to VS.

**Comment by jdalton** [comment]
Have you tried leveraging a "keep me logged-in" option via a persistent cookie?
