### ISSUE TITLE
Rejections are not being thrown.

### ISSUE THREAD

**Issue by darkyen** [winjs/winjs#1277]
While debugging and even in development unhandled hooks make the overall debugging process easy, as seen winjs/react-winjs#19 winjs does not throws unhandled rejections and many exceptions are lost by the way winjs handles rejections.

Most promise libraries support a hook for unhandled rejection

https://gist.github.com/benjamingr/0237932cee84712951a2

Maybe add a similar feature to WinJS.Promise or perhaps use a better promise library like bluebird ?

**Comment by rigdern** [comment]
For now, we have a couple of non-standard ways of achieving this:
  - If you call `WinJS.Application.start()`, among other things, it will monitor unhandled promise exceptions. When it detects one that wasn't handled within the tick of the event loop in which it was thrown, it will call [terminateApp](https://github.com/winjs/winjs/blob/288cffca8d5e09f92e9d3cca05251abf032fd5f4/src/js/WinJS/Application.js#L265-L275) which has a `debugger` statement to give you the opportunity to detect and debug the issue. If you're developing a Windows Store App, this will also cause the app to exit.
  - If don't want to use `WinJS.Application.start()`, you can manually detect unhandled promise exceptions using the `WinJS.Promise.onerror` event. Here's a snippet of code for managing a list of unhandled promise exceptions (based on the [implementation in WinJS.Application](https://github.com/winjs/winjs/blob/master/src/js/WinJS/Application.js#L578-L625)):

  ```js
  var outstandingPromiseErrors = [];
  WinJS.Promise.addEventListener("error", function (e) {
    var details = e.detail;
    var id = details.id;
    // If the error has a parent promise then this is not the origination of the
    //  error so we check if it has a handler, and if so we mark that the error
    //  was handled by removing it from outstandingPromiseErrors
    //
    if (details.parent) {
      if (details.handler) {
        delete outstandingPromiseErrors[id];
      }
      return;
    }
    
    outstandingPromiseErrors[id] = details;
  });
  ```

Note that this is related to #1086.
