### ISSUE TITLE
Autocomplete

### ISSUE THREAD

**Issue by varghesep** [winjs/winjs#1284]
I'm so excited about **WinJS** because I was looking for an alternative for the **Angular Material**. I currently use **Angular Material** and is a great UI framework.

I would like to make a feature request for **Autocomplete** similar to [Angular Material Autocomplete](https://material.angularjs.org/latest/#/demo/material.components.autocomplete).

**Comment by jayrenn** [comment]
Hey @varghesep, glad to hear you're excited! Take a look at our [AutoSuggestBox control](http://try.buildwinjs.com/#searchbox). Does that fulfill your UI scenarios?
