### ISSUE TITLE
Pivot header touch devices

### ISSUE THREAD

**Issue by lamuertepeluda** [winjs/winjs#1285]
I think the pivot header is not properly responding on touch events.

On WIndows touch devices:

If I touch or swipe an header, the selected page changes (as expected). However if I navigate to another page (WinJS.navigate) and then go back, the header touch won't work anymore (will work swipe only). The animations aren't really smooth (Lumia 925)

On Android devices this does not happen and animations are smooth.

Looking at the sources I think you messed up something when dealing with touch events https://github.com/winjs/winjs/blob/master/src/js/WinJS/Controls/Pivot/_Pivot.ts lines 55-56

I wish I could choose to have both swipe and touch behaviors by setting some property and not being constrained by the pointer event detection (which seem to fail, indeed).

Visual Studio 2013
WinJS 4.0.1
Cordova 4.3.0

**Comment by jseanxu** [comment]
Hi @lamuertepeluda,

Do you have a simple repro project that captures this issue?

Thanks

**Comment by lamuertepeluda** [comment]
Hi, can't share all my app code currently but I'll try to provide an
example asap
Il 06/lug/2015 09:31 PM, "Sean Xu" <notifications@github.com> ha scritto:

**Comment by jayrenn** [comment]
We are going to close this for the time being. Feel free to re-open when you have a simple repro to provide!
