### ISSUE TITLE
Binding.Template.renderItem is documented incorrectly

### ISSUE THREAD

**Issue by AmazingJaze** [winjs/winjs#1290]
Both the inline doc comment. and the [msdn documentation](https://msdn.microsoft.com/en-us/library/windows/apps/hh701308.aspx) are incorrect for this method. The WinJS.d.ts is missing an entry for this method, and that should be updated once we have it correctly documented.

#### Inaccuracies
- The return value:
According to the documentation this is the HTML element. This is incorrect. It is actually an object in the form of 
```ts
{
  element: WinJS.Promise; // this is the item promise
  renderComplete: WinJS.Promise;
}
```

- The item parameter: 
According to the documentation this is an object in the form of 
``` js
{data: { ... }}
``` 
however the implementation code is expecting a item to be an item promise rather than an object with a data property, so attempting to call this function results in the ```element``` promise on the return value having already entered the error state.

---
Currently ListView is the biggest consumer of this API, which is probably the only reason it was made public to begin with. I don't expect any external consumers would be using it as the Binding.Template.render() API is much cleaner.

**Comment by jdalton** [comment]
Note: @jayrenn is on the hook for the documentation update.
