### ISSUE TITLE
AutoSuggestBox does not fire onquerychanged when queryText is programatically updated

### ISSUE THREAD

**Issue by yildirimcagri** [winjs/winjs#1293]
Changing AutoSuggestBox queryText programatically is possible, however this should also cause querychanged event to fire, which is documented to fire when queryText is changed by the user or app https://msdn.microsoft.com/en-us/library/windows/apps/dn919950.aspx

**Comment by rigdern** [comment]
After making this fix, the following test should be enabled in knockout-winjs:
  - AutoSuggestBox.js it("should use the querychanged event")
