### ISSUE TITLE
CorsicaTests.AppBarTests: LightDismissWithClose Assert Passes:0/1

### ISSUE THREAD

**Issue by mikewjackson** [winjs/winjs#1294]
Test case "CorsicaTests.AppBarTests: LightDismissWithClose " in "winjs/bin/tests/AppBar/test.html" failed in the latest Protractor run. Protractor determined that this failure is a regression from mshtml or a previous build of edgehtml (based on historical data). Please investigate why this test has begun failing.

**Comment by AmazingJaze** [comment]
This regression was caused by a change I made. I have opened https://github.com/winjs/winjs/issues/1300 to track this.
