### ISSUE TITLE
Unable to scroll on mobile webkits and descendents

### ISSUE THREAD

**Issue by darkyen** [winjs/winjs#1299]
Multiple browsers act differently when there are multiaxial scroll components (IE works the best and as expected) but iPhone 6 Safari 8 doesn't lets me scroll the list in the Hub basic demo, In chrome devtools I can scroll vertically on the list but cannot pan horizontally on the the hub component if i try to pan horizontally on the list view.

Since we are using native scroll these inconsistencies should be irrelevant as the browsers work perfectly on desktops with touch and trackpads.

Any workaround to fix this ?

**Comment by alxlu** [comment]
Might be related to https://github.com/winjs/winjs/issues/587#issuecomment-113577634

**Comment by darkyen** [comment]
There is a hacky fix for webkit if you are using native scroll components then simply adding -webkit-transform (or in other words giving it a different rendering layer makes it work on android and iOS)
