### ISSUE TITLE
Class win-progress-bar doesn't work in chrome

### ISSUE THREAD

**Issue by NCC1701M** [winjs/winjs#1302]
When you add the win-progress-bar to a &lt;progress /&gt;, the progress isn't shown in chrome.

**Comment by jdalton** [comment]
The indeterminate state of the progress bar is not displayed by our styles. The animation seen in MS Edge is specific to the MS Edge browser control.

**Comment by NCC1701M** [comment]
Nonetheless, if you add win-progress-bar to a progress it is not shown in Chrome you can test this here:
http://jsfiddle.net/14bwrqny/1/

Version of Chrome I'm using: 43.0.2357.134 m

**Comment by jdalton** [comment]
> Nonetheless, if you add win-progress-bar to a progress it is not shown in Chrome

You'll need to add a `max` or `value` attribute for it to be displayed.

**Comment by NCC1701M** [comment]
But that's not what it's supposed to be. It should be an indeterminate progress bar which is shown no matter what browser is used. If the browser can't display the flying dots ok, but there should be an indeterminate progress and not nothing

**Comment by jdalton** [comment]
@NCC1701M That seems reasonable. I've marked this as a code bug.
