### ISSUE TITLE
Commands in the AppBar overflowarea are hidden from view

### ISSUE THREAD

**Issue by AmazingJaze** [winjs/winjs#1303]
This only repro's in Edge when there are enough commands in the overflow area to force a scroll bar.
The overflow area will become scrollable once its content height >= 50% of the viewport height.
This only impacts the AppBar as it is related to -ms-device-fixed positioning.

When this occurs, Edge renders the height of the overflowarea incorrectly and it clips outside of its content element causing 1 or two commands at the bottom of the element to become unreachable.

The problem is exacerbated by the browser zoom factor. At 100% the element is the correct size. I have filed a bug internally against the edge team, but it may still be possible for us to work around this issue or at least fail gracefully and draw the entire element at the incorrect height rather than clipping it.

**Comment by jdalton** [comment]
Because this seems a bit edge (no pun) and we've filed a bug let's close it as won't fix and let it shake out or until we get an external bug report.

**Comment by cthedot** [comment]
Seems a quite simple change fixes this:

.win-commandingsurface .win-commandingsurface-overflowarea,
.win-commandingsurface .win-commandingsurface-overflowareacontainer {
  /* ui-dark.css #4280: wm10 fails to scroll if set to 50vh but cannot overwrite?!
  SO REMOVE 
    max-height: 50vh;
  */
}

/* add it only during opening and calc of height */
.win-commandingsurface-opening .win-commandingsurface-overflowarea,
.win-commandingsurface-opening .win-commandingsurface-overflowareacontainer {
  max-height: 50vh; /* actually I'd prefer 55vh but don't care too much ;) */
}

This is tested on Windows 10586 both Windows desktop app in a number of window sizes and on Windows 10 mobile 10586.36 on Lumia 930 in which the appbar was totally useless (I do have quite a few actions in there)
