### ISSUE TITLE
pivot tests are failing in edge

### ISSUE THREAD

**Issue by AmazingJaze** [winjs/winjs#1307]
![image](https://cloud.githubusercontent.com/assets/6732159/8741687/840dcebc-2c11-11e5-93e4-ba2e258cd362.png)

Quickly verified that these all pass in chrome, ie, and ff

**Comment by jseanxu** [comment]
Looked into this failure - it is caused by our eventTranslation shim in ElementUtilities where it incorrectly renames pointer events such as `pointerdown` to `mspointerdown`.

@rigdern
