### ISSUE TITLE
Break dependency on mselementresize

### ISSUE THREAD

**Issue by boggydigital** [winjs/winjs#1308]
For Edge Layout performance work we'd want this event removed, so that we can proceed to perform further performance optimizations for the web we've planned.

Looking at the discussions here, it has been desirable to break dependency for quite some time and the current design around this event unsurprisingly has been causing cross-browser problems:
-          https://github.com/winjs/winjs/issues/95
-          https://github.com/winjs/winjs/issues/125 
-          https://github.com/winjs/winjs/issues/675
-          https://github.com/winjs/winjs/issues/850 

With https://github.com/winjs/winjs/commit/531fc882a75027a267b04288299d20dfee9ce12d we were not sure whether this event was still required or not anymore.

**Comment by rigdern** [comment]
We have already implemented a fallback for browsers that do not support `mselementresize`. So if Edge removes `mselementresize`, we should fallback to that behavior. The fallback is:
  - Controls listen to the `window` `resize` event to handle cases of the window resizing.
  - Apps must call `forceLayout` on controls when they change size to handle cases where an element resizes without the window changing size.

Without `mselementresize`, there will be some regressions in WinJS in Edge that we might be able to do something about. For example, if you put a `ListView` inside of a `Flyout` everything just works in Edge today. However, if `mselementresize` isn't supported, the `ListView` will be blank when the `Flyout` is opened. The workaround is for developers to call `forceLayout` on `ListView` when showing the `Flyout`. However, we could update the WinJS Flyout to trigger the `window` `resize` handler of each control inside of the `Flyout` when the `Flyout` is shown. This will give this scenario a closer experience to what we see in Edge today.

**Comment by AmazingJaze** [comment]
@jdalton, if we want to sign up for the work @rigdern calls out above we should open a separate task for that. 

I'm not sure if there is any work to be done right now. Once msElementResize has been removed from Edge we should verify that our scenarios still work in Edge as well as they do in other browsers that don't support msElementResize, which was first introduced in IE11.

**Comment by jdalton** [comment]
\cc @jayrenn

**Comment by boggydigital** [comment]
I can't really add anything from WinJS perspective, however from the Edge engine perspective we'd really want this event out sooner rather than later. Per our investigation this is currently the only known blocking item standing in our way - so the sooner you confirm this is ok to remove - the sooner we're going proceed with actual removal.

**Comment by jdalton** [comment]
I've marked the [remaining work](https://github.com/winjs/winjs/issues/1308#issuecomment-122991889) as a feature request & tracking internally.

**Comment by jdalton** [comment]
I'll also work to put this on our public [changelog](http://dev.modern.ie/platform/changelog/) at the appropriate time.
