### ISSUE TITLE
Compiling WinJS files with gulp?

### ISSUE THREAD

**Issue by varghesep** [winjs/winjs#1318]
For a production website, it is better not to use  **WinJS.UI.processAll()** on every page, but compile the WinJS scripts to pure JavaScript. The **ASP.NET MVC6** has a gulpfile.js where the compilation can be done.

The following script is to compile the typescript files to javascript files.

```javascript

var tsc = require("gulp-tsc");

gulp.task("tsc", function () {
    gulp.src("./Scripts/*.ts")
        .pipe(tsc({}))
        .pipe(gulp.dest(paths.webroot + "js/"));
});
```
Is there an equivalent package like **gulp-tsc** can be used to compile the WinJS files to JavaScript files?

**Comment by jayrenn** [comment]
@rigdern What do you think about this?
