### ISSUE TITLE
ListView: Clicking the edge of an item only invokes item every other click

### ISSUE THREAD

**Issue by caseyfaber** [winjs/winjs#1319]
I have a bug that icons on the left of my listview (in non-select mode) are only clickable every other click, especially if you are trying to use touch.

It sounds like the same bug as #1215, only not in select mode. You can repro on http://try.buildwinjs.com/#listviewinteractions

•	In Selection Scenarios, go to Output, then click the Single tab.
•	Click the very left of the image.
•	It pushes down the first click. The second it actually selects.

**Comment by andriniaina** [comment]
so... ListViews are not animated anymore? Is this in line with the UWP C# framework?
