### ISSUE TITLE
When I using ListView to binding to a datasource,

### ISSUE THREAD

**Issue by lygstate** [winjs/winjs#1320]
How to notify ListView to update when the datasource's
items changed(Insert, Delete,Update).

**Comment by AmazingJaze** [comment]
Hi @lygstate, just so to be clear, are you asking how to have an edit to the datasource be reflected in the ListView UI? That behavior should be happening automatically. 

If you take a look at this [interactive ListView tool](http://try.buildwinjs.com/pages/listview/options/default.html) you can see how the documentation section updates with the relevant code snippets any time you change any of the configuration options on the left.

For example, the documentation section for adding an item reads:
```js
// data is the WinJS.Binding.List that you assigned to
// itemDataSource of your ListView
data.splice(index, 0, newItem);
```

**Comment by lygstate** [comment]
@AmazingJaze That's amazing, But I am using a datasource like indexdb.
And I want the ListView response to the external datasource's changes(Update,Added,Change)

**Comment by AmazingJaze** [comment]
@lygstate, how are you currently populating the listview from indexdb? 

For example, are you creating a Binding List and then putting the data from indexdb into the binding list?

**Comment by lygstate** [comment]
I want to do the things that 
http://stephenwalther.com/archive/2012/07/10/creating-an-indexeddbdatasource-for-winjs does,
except I want to monitoring the changes of the indexdb and update the ListView in RealTime.

**Comment by AmazingJaze** [comment]
Hi @lygstate, I'm not sure I understand what you mean, isn't the example of the remove method that the author of that article provides, already updating the ListView in real time? 

I believe you should be able to achieve your scenario by implementing a [CustomDataSource](https://msdn.microsoft.com/en-us/library/windows/apps/hh770849.aspx), 

@rigdern, @TheWrathOfConst do you agree?

**Comment by lygstate** [comment]
Tanks @AmazingJaze, I've seen this demo before, but my `Custom Data Source` would `changing time to time`,
I want ListView to response to the changes of the `Custom Data Source`
including `Update Add Remove`

**Comment by AmazingJaze** [comment]
@lygstate I see now that the page I linked to only walks you through creating a read only data source. 
To create a custom data source that supports write access to update the ListView in real time you will need to implement the IListDataAdapter API's specific to a write access custom data source. 

If you search the [IListDataAdapter](https://msdn.microsoft.com/en-us/library/windows/apps/br212603.aspx) page for the string  `Ways to support write access` you will find the section that describes the APIs you need to implement on your CustomDataSource's IListDataAdapter to enable write access.

Additionally, I believe the example you linked to http://stephenwalther.com/archive/2012/07/10/creating-an-indexeddbdatasource-for-winjs also implements just enough of a writeable custom data source to support the remove() and insertAtEnd() APIs in pretty good detail. If you copy his example I would expect that removing items from the indexdb data source, for example, should cause the ListView to update its UI accordingly. Are you saying that you don't see remove() working as expected if you follow his complete example?

**Comment by lygstate** [comment]
@AmazingJaze Yes, I look into the indexdb demo, but it's lost the `update` and
'insert in the middle` demo.

**Comment by lygstate** [comment]
Thanks a lot, I am about to understanding how to deal with this issue, when
external data source are changed, always calling to invalidateAll is a good choice.
