### ISSUE TITLE
SearchBox is missing onreceivingfocusonkeyboardinput event property

### ISSUE THREAD

**Issue by AmazingJaze** [winjs/winjs#1322]
SearchBox correctly, fires the "receivingfocusonkeyboardinput" and it can be listened to with addEventHandler(), but the DOM Level 1 event property ```onreceivingfocusonkeyboardinput``` is not exposed on the winControl. 

Surprisingly we do already have it defined in the WinJS.d.ts, which is how this bug was identified.

**Comment by mikewjackson** [comment]
SearchBox is a depreciated control.
