### ISSUE TITLE
WinJS.Application should fire "backclick" for the Win10 AppView back button

### ISSUE THREAD

**Issue by BrandonLive** [winjs/winjs#1323]
I've made this change in my local copy and can submit a PR if others agree this is a good improvement.

Today, WinJS.Application registers for the Windows.Phone.UI.Input.HardwareButtons "backpressed" event, and triggers its own "backclick" in response. This also triggers navigation for anyone using the WinJS.Navigation helper.

On Windows 10, this API is superceded by Windows.UI.Core.SystemNavigationManager, which fires for hardware back buttons, the back button app developers can enable in the upper-left corner of the app window (in the non-client area), and the back button on the taskbar in Tablet Mode.

My proposed change checks for SystemNavigationManager and registered for "backrequested" there instead of "backpressed" on the Phone API. If SystemNavigationManager is not present, it then proceeds to check for the Phone HardwareButtons API as it does today.

**Comment by mikewjackson** [comment]
@BrandonLive sounds like a great change to have. Please submit a PR.

**Comment by BrandonLive** [comment]
@mikewjackson Hey Mike, I submitted the PR yesterday. The automated test run failed during the saucelabs portion, but apparently because of timeouts? Doesn't look like that has anything to do with my change, but if I'm reading that wrong, please let me know.

**Comment by mikewjackson** [comment]
@BrandonLive Thanks for the PR - appreciate it.

**Comment by CensoredUser** [comment]
This change causes problems for apps running on Windows 10 as a Windows 8.1 app. The  `_WinRT.Windows.UI.Core.SystemNavigationManager.getForCurrentView()` method will throw and cause the app to crash. 

Any idea whether we can detect if an app is running as a Windows 8.1 app or as a Universal Windows app (Win10)?

**Comment by BrandonLive** [comment]
This namespace doesn't exist on 8.1, so it shouldn't do anything at all. It could detect the version but doesn't need to, this is feature detection.

Sent from my Windows Phone
________________________________

**Comment by CensoredUser** [comment]
The namespace does indeed not exist on 8.1 - but it _does_ exist on Win 10. And you _can_ run a Windows 8.1 app in Win 10. Calling the method while running a Windows 8.1 app on Windows 10 will cause the method to throw an exception.

**Comment by BrandonLive** [comment]
And the same is true for 8.1 apps on Win10 (I forget if the namespace doesn't exist or the API does nothing, but I'm pretty confident it does one of those, and doesn't throw, otherwise I'd have seen it by now in Tweetium).

**Comment by BrandonLive** [comment]
That doesn't sound right. What build of Win10 did you see this on?

**Comment by CensoredUser** [comment]
I'm on Windows 10 Build 10240. 
The minimum steps to repro are to create a new blank Windows 8.1/WP 8.1 universal app, add WinJS 4.3 and run. It'll crash for me when the `register` method is called (so basically when calling `app.start()`) 
Doing the same on a Windows 10 Universal app works just fine for me.

**Comment by BrandonLive** [comment]
Hmm, I'll have to give that a try soon. Weird that the API would throw, huh.

**Comment by CensoredUser** [comment]
I've created issue #1448 to track this.

**Comment by lakichemole** [comment]
Hi,

This issue is created by the line 15199 :
var navManager = _WinRT.Windows.UI.Core.SystemNavigationManager.getForCurrentView();
the namespace exist : _WinRT.Windows.UI.Core.SystemNavigationManager
but the call to getForCurrentView() raise an exception (even if we add try and catch).
For now in my project I defned a platform version, then I added : 
if (Platform.version>=10 && _WinRT.Windows.UI.Core.SystemNavigationManager) {

as a temporary fix.

Romain
