### ISSUE TITLE
WinJS.Application.local can not be read in the next startup in Firefox.

### ISSUE THREAD

**Issue by lygstate** [winjs/winjs#1331]
We have no way to storage configuration or other related things in WinJS.

**Comment by jdalton** [comment]
Hi @lygstate. Would you provide a bit more info. A repro would be awesome.

**Comment by lygstate** [comment]
@jdalton Thanks, I wanna to change my question, does WinJS.Application.local
are based on localStorage

**Comment by jdalton** [comment]
\cc @rigdern

**Comment by lygstate** [comment]
I am directly using localStorage now

**Comment by rigdern** [comment]
@lygstate No, WinJS.Application.local is not based on localStorage.

In Windows Store Apps, WinJS.Application.local is based on `Windows.Storage.ApplicationData.current.localFolder` when WinRT is available.

In other cases, it's based on an in-memory object: https://github.com/winjs/winjs/blob/30eabf1a0b3272fb49a46f3521f74a8b75dbb184/src/js/WinJS/Application/_State.js#L184-L200

**Comment by lygstate** [comment]
@rigdern So we can not use WinJS.Application.local to storage preferences.

**Comment by rigdern** [comment]
No, if WinRT is available, it's probably best to use one of these:
  - Windows.Storage.ApplicationData.current.roamingSettings
  - Windows.Storage.ApplicationData.current.localSettings

If WinRT is not available, it's up to you to decide how you want to save settings. WinJS doesn't have anything to help in this area.
