### ISSUE TITLE
using the splitview/hamburger toggle in WinJS 3.x?

### ISSUE THREAD

**Issue by pke** [winjs/winjs#1341]
Is that possible, or does it doing on way to much new code and styles?

**Comment by jayrenn** [comment]
I'm not sure if it's possible, but it's certainly not a supported scenario. The SplitView and the SplitViewPaneToggle were designed for WinJS 4.0 and Windows 10, specifically. I'll leave it up to @rigdern to comment on the feasibility of using it in WinJS 3.x.

**Comment by rigdern** [comment]
I wouldn't recommend it -- it seems like tedious error prone work. Even if you got it running, there might be some glitches. For example, you won't be able to have the SplitView opened in overlay mode and a Flyout opened at the same time.

If you really want to try, you could take ui.js from WinJS 4 and copy the SpiltView module out into WinJS 3's ui.js. Try running it and see what modules are missing then copy those modules from WinJS 4's ui.js into WinJS 3's. Repeat until you've gotten all of the modules.

Some modules may be missing methods. For example, we added the [`_resizeTransition` method to the `Animations` module](https://github.com/winjs/winjs/blob/30eabf1a0b3272fb49a46f3521f74a8b75dbb184/src/js/WinJS/Animations.js#L2678-L2689) in WinJS 4. You'll have to copy these methods and all of their dependencies in. If we changed the contracts (e.g. parameters, return values) of any of these internal methods between WinJS 3 and 4, you'll have to figure out how to resolve the conflicts.
