### ISSUE TITLE
Better Pages.define API

### ISSUE THREAD

**Issue by toddpi314** [winjs/winjs#1343]
We need to create a new spec on how to extend pages in WinJS.Pages.define created control constructors.

Principle Use-case:
- Consumer wants to use "BaseView" class definition as the prototype for WinJS.Pages.define created control constructors
- Consumer does not have the ability to override the "BaseView" definition with mutated type

Ideas:
- Expose page Base Class and let consumers use WinJS.Class.derive
- Accept parent constructor on WinJS.Pages.define for a  derive call in the define impl.
- Make WinJS.Pages._viewmap a first-class citizen (since its an angle of override)

The workaround right now is a proxy pattern:
1. Call WinJS.Pages.define with an empty member closure
2. Manually find the parent prototype (highest base prototype) of Custom class constructor and mutate with WinJS.Class.derive call
3. Manually edit the WinJS.Pages._viewmap constructor instance (respective to template)

Anyone up for this type of enhancement?

**Comment by toddpi314** [comment]
Here is a code sample of the full work-around on 4.1.0:

```
            var templateUri = "/all/your/base.html";
                var pageClassDef = WinJS.UI.Pages.define(templateUri);
                var baseViewDef = WinJS.Class.define(
                    function() {
                        pageClassDef.apply(this);
                    }, {
                        init: function(element, options) {
                            return pageClassDef.prototype.init.apply(this, arguments);
                        }
                    });
                var pageClassDeriveDef = WinJS.Class.derive(pageClassDef, baseViewDef, baseViewDef.prototype);
                WinJS.UI.Pages._viewMap[templateUri] = pageClassDeriveDef;

                // create the instance for testing
                var pageClassInstance = new pageClassDeriveDef();
                pageClassInstance.init();
                pageClassInstance.ready();
```

**Comment by toddpi314** [comment]
Here is an example of the work-around with the `_super` reference:

```
                var baseViewDef = WinJS.Class.define(
                    function() {
                        this._super.apply(this);
                    }, {
                        init: function(element, options) {
                            return this._super.prototype.init.apply(this, arguments);
                        }
                    });

                var templateUri = "/all/your/base.html";
                var pageClassDef = WinJS.UI.Pages.define(templateUri);
                baseViewDef.prototype._super = pageClassDef;
                var pageClassDeriveDef = WinJS.Class.derive(pageClassDef, baseViewDef, baseViewDef.prototype);
                WinJS.UI.Pages._viewMap[templateUri] = pageClassDeriveDef;

                // create the instance for testing
                var pageClassInstance = new pageClassDeriveDef();
                pageClassInstance.init();
                pageClassInstance.ready();
```

This allows the class definition to be separate from the derive, but requires a non-standard property.

**Comment by toddpi314** [comment]
Here is a good portable work-around:

```
exports.define = function(template, viewClassDef) {
  function abs(uri) {
    var a = document.createElement("a");
    a.href = uri;
    return a.href;
  };

  var absTemplateUri = abs(template);
  var pageClassDef = WinJS.UI.Pages.define(absTemplateUri);
  viewClassDef.prototype._super = pageClassDef;
  var pageClassDeriveDef = WinJS.Class.derive(pageClassDef,
    viewClassDef, viewClassDef.prototype);
  WinJS.UI.Pages._viewMap[absTemplateUri] = pageClassDeriveDef;
  return pageClassDeriveDef;
};
```

**Comment by jayrenn** [comment]
Hey @toddpi314. Great idea! I'll add this to our internal tracking of feature requests, and keep the thread open for discussion for the time being.

**Comment by toddpi314** [comment]
Please also note that the current WinJS.Class.derive treats properties like methods.

My recommendation is to extend the derive to do the following:
1. Discovery Properties on base using [getOwnPropertyNames](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/getOwnPropertyNames)
2. Discovery getter/setters of each property using [getOwnPropertyDescriptor](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/getOwnPropertyDescriptor)
3. Either 'copy by reference' if extend class doesn't override, or 'replace by reference' favoring the extend class on the destination class definition 

This would allow Getter/Setter extension while still supporting the various ES5 property definition patterns (`get  key(){...}`, `key: { get(): function(){...}}`, `Object.defineProperty(...)`)

Want me to file a new issue for this?

**Comment by toddpi314** [comment]
Obviously the source attempts to handle this at https://github.com/winjs/winjs/blob/9e50af94c8acc7f51166bb9ed3f7695744433641/src/js/WinJS/Core/_Base.js#L11-L39

But, it looks like with the presence of either a getter/setter, the entire property is overwritten. 
So, in the case someone wants to override the getter only, there is no reason to clobber the setter since its an inherited behavior.

The caveat here is that some people might be using the existing behavior to force read-only on properties; in that case, they should provide an empty setter to override.

**Comment by toddpi314** [comment]
Here is a test case for the expected behavior:

```

                var getOverrideCalled = false;
                var getBaseCalled = false;
                var setBaseCalled = false;
                var baseViewDef = WinJS.Class.define(
                    function() {}, {
                        sampleProperty: {
                            get: function() {
                                getBaseCalled = true;
                            },
                            set: function(val) {
                                setBaseCalled = true;
                            }
                        }
                    });
                var concreteViewDef = WinJS.Class.derive(
                    baseViewDef,
                    function() {
                        baseViewDef.apply(this, arguments);
                    }, {
                        sampleProperty: {
                            get: function() {
                                getOverrideCalled = true;
                            }
                        }
                    });
                var instance = new concreteViewDef();

                // act
                instance.sampleProperty;
                instance.sampleProperty = "yo";

                // assert
                getOverrideCalled.should.be.ok();
                setBaseCalled.should.be.ok();
                setBaseCalled.should.not.be.ok();
```

**Comment by toddpi314** [comment]
Better portable SHIM that allows opt-in on existing API:

``` javascript
function abs(uri) {
  var a = document.createElement("a");
  a.href = uri;
  return a.href;
};

WinJS.UI.Pages.define = function(uri, members, baseClassDef) {
  var absUri = abs(uri);
  var pageClassDef = _pageDefine(absUri, members);
  if (baseClassDef) {
    baseClassDef.prototype._super = pageClassDef;

    // migrate props that are not override
    var propertyNames = Object.getOwnPropertyNames(pageClassDef.prototype);
    for (var i = 0; i <= propertyNames.length - 1; i++) {
      var key = propertyNames[i];
      if (!baseClassDef.prototype[key]) {
        baseClassDef.prototype[key] = pageClassDef.prototype[key];
      }
    }

    WinJS.UI.Pages._viewMap[absUri] = baseClassDef;
  }
  return baseClassDef || pageClassDef;
};

```
