### ISSUE TITLE
ListViews: Drag and Drop items between listviews

### ISSUE THREAD

**Issue by topeDev** [winjs/winjs#1345]
Hi guys,

Is this possible in the current version _(drag and drop items between listviews)_ ? 
I did a bit of searching but I did not find anything related.

Thanks

**Comment by pke** [comment]
No that is currently not possible out of the box. But I think there was already an issue about that.

**Comment by jayrenn** [comment]
As @pke mentioned, that is not currently possible out-of-the-box. Thanks!
