### ISSUE TITLE
Have styles been removed?

### ISSUE THREAD

**Issue by ThatsIT** [winjs/winjs#1358]
When using Winjs 4.0.0-preview form controls such as text-box and button were styled nicely that matched Winjs theme , upgrading to Winjs 4.1.0 the styling has been removed. Is this an oversight or by design?
I myself liked the styles
Thanks

**Comment by jdalton** [comment]
Hi @ThatsIT! This changed in WinJS 4.0 (stable). See our wiki page for styling controls [here](https://github.com/winjs/winjs/wiki/Styling-HTML-Controls).
