### ISSUE TITLE
ListViewItem - Set controls within the template to writeable

### ISSUE THREAD

**Issue by P4trik** [winjs/winjs#1360]
Is there any supported way to avoid that the controls within the win-item-template are read only? 
I need this property, if exists, especially in the angular wrapper too.
Or do I have to use jQuery for something like this?

**Comment by rigdern** [comment]
@P4trik Is this a question specifically about angular-winjs? If so, is your question "how do I switch my ListView between 2 different item templates?"

**Comment by P4trik** [comment]
@rigdern All Items in the win-item (for example an plain textbox) are read only by default. So there is a mouse button up event handler that prevents editing the contents of the item.

**Comment by rigdern** [comment]
If I understand your question, you'll need to put the win-interactive CSS class on any elements in your ListView items that are interactive (e.g. button, text box, WinJS Rating control) so that the ListView doesn't handle events which occur on those elements.
________________________________

**Comment by P4trik** [comment]
Works fine for me, thank you!
