### ISSUE TITLE
Narrator says "end of line" when using keyboard if user moves away from current item then back quickly

### ISSUE THREAD

**Issue by PaulWells** [winjs/winjs#1363]
Feature: ListView
Environment: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/42.0.2311.135 Safari/537.36 Edge/12.10240
Source: http://try.buildwinjs.com Play With ListView
Layout: Grid
Orientation: Vertical
Items Reorderable: False
Items Draggable: False
Tap Behavior: Invoke Only
Selection Mode: Multi
Item Template: Text With Image
Group Items: False
Group Header Template: Text
Group Header Position: Top
Group Header Tap Behavior: Invoke
Data Source: 100 Items

In Edge.  When using grid layout, quickly pressing down, right, up, left so that the focus returns to the original item, the narrator will sometimes say the wrong content.  You can see the blue narrator focus box moves to another item on the screen and says that instead.  In my case it was saying "end of line"

**Comment by PaulWells** [comment]
In IE, the narrator will instead say "space"

**Comment by jdalton** [comment]
@AmazingJaze this sounds like a Narrator bug. Could you investigate to see if there's more to it.
