### ISSUE TITLE
Text color of DatePIcker incorrect in high contrast mode

### ISSUE THREAD

**Issue by PaulWells** [winjs/winjs#1366]
The colors for DatePIcker are incorrect in high contrast mode in rest and hover state.  Referencing this design doc:
 
![datepickerhighcontrastdesign](https://cloud.githubusercontent.com/assets/321353/9310657/f31f9408-44c5-11e5-8b69-1d5df85d3d9d.PNG)

**Comment by jdalton** [comment]
Since we're still using the legacy date picker control we need to compare the high contrast red lines to the select-menu/combo-box. Can you look into that for us?
