### ISSUE TITLE
Confused about AppBar and ToolBar

### ISSUE THREAD

**Issue by sebagomez** [winjs/winjs#1370]
We used to have the AppBar and although a little buggy, it worked. Now (WinJS 4.0) there's a ToolBar. What's the difference between them? what are the scenario for each? couldn't find info or samples about it.

**Comment by jdalton** [comment]
There is usually 1 appbar on a page (at the top or bottom) where as there may be multiple toolbars on a page associated with different page components.

With the appbar actions apply to the entire page where toolbars apply to the component they are scopped in (like a wysiwyg editor).
