### ISSUE TITLE
Enhancement Request: data-win-binding auto getter/setter binding

### ISSUE THREAD

**Issue by toddpi314** [winjs/winjs#1371]
_It would be helpful if the data-win-bind attribute auto detected generated getter/setters and bound to the underlying field respectively._

**Reasoning:**
When extending classes, the  WinJS.Class.derive api does not allow real polymorphic getter/setter overrides without clobbering the entire property definition. e.g. BaseClass.getter/setter will be overridden if ConcreteClass.getter (only) is supplied in the *.derive.

This forces Domain Models to follow the getProperty()/setProperty(val) pattern, since that allows override in subclasses,

The issue is once you go down this path, the data-win-bind api doesn't allow function value bindings. This pretty much cold stops the entire binding API without writing a auto binding-context transforms of the getter/setter properties.

```
Does work:
  <div class="imagetile-title" data-win-bind="innerText: item.title"></div>

Doesn't work:
  <div class="imagetile-title" data-win-bind="innerText: getItem().title"></div>
```

**Work-arounds in the field:**
- Monitor the binding context (at the right phases) and auto generate non-function-based properties using the defineProperty API
 - Con: Keeping the data context scope in 'sync' with the property def is hard to nail down for all view architectures
- Create a BindingConverter and pass binding expression in as a object selector. e.g. "data-win-bind="innerText: 'item.title' propertyConverter"
 - Con: developer has to find a clever way of injecting the binding context scope into the converter, which isn't supported using the standard converter API

Thanks for the hard work everyone!
Todd

**Comment by jdalton** [comment]
I'm not super familiar with WinJS data binding. Have you tried ES5 getter/setters? \cc @rigdern.

**Comment by toddpi314** [comment]
ES5 Getter/Setter's work just fine (when manually listed as enumerable) on base models but are not honored during WinJS.Class.derive composition. 

This is an enhancement specific to data-win-bind attribute binding and the use of ES5 getter/setter usage during class inheritance.

**Comment by rigdern** [comment]
Alternatively, when defining a subclass which only wants to override the getter, you could implement the subclass's setter to call the super class's setter using `Object.getOwnPropertyDescriptor`.

Here's a full example:

```js
var BaseClass = WinJS.Class.define(function (name) {
    this._name = name;
}, {
    name: {
        get: function () {
            return this._name;
        },
        set: function (value) {
            this._name = value;
        }
    }
});
var ConcreteClass = WinJS.Class.derive(BaseClass, function (name) {
    BaseClass.call(this, name);
}, {
    name: {
        get: function () {
            return this._name + "!";
        },
        set: function (value) {
            var superSetter = Object.getOwnPropertyDescriptor(BaseClass.prototype, "name").set;
            superSetter.call(this, value);
        }
    }
});
```

**Comment by toddpi314** [comment]
Thanks for the workaround @rigdern 

We have used this approach before but it is very challenging for larger architectures, since this requires either external-to-code UML to reveal the getter/setter usage or the user has to "walk" the composition chain to figure out what is auto-clobbered by the derive.

Given how easy it is to discovery the getter/setter at derive definition time, I think we should just:

- extend the binding API to attempt discovery of getter/setter properties on bind
- extend the WinJS.Class.derive to auto associate missing subclass getter/setters
