### ISSUE TITLE
Textarea issues with flyouts in store app

### ISSUE THREAD

**Issue by mfosker** [winjs/winjs#1373]
I have found a number of ways to crash an app using textarea in a page if there are also flyout controls present.
The error message is : Unable to get property 'top' of undefined or null reference in line 40938 of ui.js

The simplest app I can reproduce this in has a page containing a textarea and an empty flyout on a page that is loaded into a  `<div class="renderingPageControls-renderedControl"></div>`
using `WinJS.UI.Pages.render`

When on this page in the simulator or on a touch device, if I touch in the textarea and drag my finger up, the textarea starts to move towards to the top of the screen before then hitting the above exception.
The same steps with the flyout removed from the HTML do not result in a crash. The flyouts can be either in the page that contains the textarea, or in the default.html

The app has been set to use WinJS 4.1 by installing WinJS into my app in VS2013 via the package manager and then updating paths to the js and css files in default.html.

I initially found a similar problem with a textarea in a page that is set to adjust it's height to the available vertical space. When focussing on the textarea too soon after showing it (Win 8.1) or any time after showing it (win 10) I would see the same error.

I can attach a basic VS solution that exhibits this issue if it helps.

**Comment by mfosker** [comment]
I have found a similar issue on a page without a textarea.
This page contains a listview with draggable items and also has a flyout. Dragging an item from the listview to the edge of the screen results in the same exception as above.
Removing all flyouts from the DOM appears to avoid the issue.

**Comment by AmazingJaze** [comment]
Hi @mfosker, the basic VS solution that you offered would be very helpful. One easy way to share it isusing OneDrive as described [on our wiki](https://github.com/winjs/winjs/wiki/How-to-share-repros-of-issues-with-WinJS).

**Comment by mfosker** [comment]
Hi @AmazingJaze Here's a link to download a VS2013 solution.
http://1drv.ms/1LkGkOq
To repro the issue easily run the app from VS on the Simulator, ensure that touch mode is enabled on the simulator.
After tapping the button a page control containing a textarea should appear, tap in the text area to show the onscreen keyboard, then touch and drag up within the textarea until the textarea starts to move off the top of the screen. That is when I see the exception.

I have tried and failed to create a simple example project that shows the same exception with dragging listview items. However within my main app I have found that when I drag a listview item off the edge of the screen that I see the same exception if there are also Flyout Elements within the DOM.

Removing all Flyout elements from the DOM prior to loading the listview seems to avoid this issue, but is a cludge as I need to reinstate them later.

**Comment by Guadzilah** [comment]
Hey

**Comment by Guadzilah** [comment]
been done what's seem to be the problem

**Comment by Guadzilah** [comment]
hey how are you doing
