### ISSUE TITLE
New playground site doesn't let you use controls on iOS well

### ISSUE THREAD

**Issue by pag3** [winjs/winjs#1402]
In the previous WinJS playground/sample site I was able to test out and evaluate how controls worked on Safari/iOS by clicking the button to view the sample fullscreen.  Now the samples seem to only be available inline in an iframe where they don't work right when I tried to access from Safari on iOS.

**Comment by mikewjackson** [comment]
Thanks for the feedback. I've moved this issue to our GitHub repository for the new site.
