### ISSUE TITLE
ListView Header - Always on top

### ISSUE THREAD

**Issue by P4trik** [winjs/winjs#1404]
Is it by default possible, to set the header of the ListView Control always on top of the list while scrolling through the items? 

I realized that all items are wrapped by a scrollable div-container and inside it, there is the header div with its content.

Best regards

**Comment by jdalton** [comment]
Have you tried setting the position of the `.win-headercontainer` header to `fixed` combo'ed with a large `z-index` value?

**Comment by P4trik** [comment]
Unfortunataly, nothing happened :-( 

The container disappeared on the screen.

`<div class="win-headercontainer" style="height: 50px; position: fixed; z-index: 9999;">Content
</div>`

**Comment by jdalton** [comment]
Could you provide a simple repro.
