### ISSUE TITLE
WinJs Unstable Behaviour

### ISSUE THREAD

**Issue by ekambarrao** [winjs/winjs#1405]
https://onedrive.live.com/?id=463D607901FE1563%21114&cid=463D607901FE1563&group=0
  
 I have uploaded the images to the following location. Please check if they are accessible.
  
 Problem details are as follows.
  
 in One image, you can find extended band below header at the top where I used Winjs 4.1 or 4.2
  
 in one image you can find "smallest" "tiny" display of button or blocks...where I used WinJS 4.0.
  
 in one image you can see appearance of footer appbar at the bottom. This when I use Winjs 4.0 preview where instead of base.js, winjs.js is there in the folder and I am using ui-dark.css then I am able to see the appbar.
  
 But it disappears and comes up as its wish later.
  
 Also if I use this combination winjs and ui-dark then only my scroll is finely working.
  
 if I use any other combination, scroll is also not working, in such case, Scroll doesn't work in windows 8.1 as well.
  
 I have uploaded the ui-dark.css as well.
  
 I have been desperately struggling to see a stable footer with scroll.
  
 Devices I was using, Android 4.4.2 and Windows 8.1.

**Comment by jdalton** [comment]
Hi @ekambarrao.

The images are not accessible.
You could drag them into the comments directly. Can you also provide repro steps.

**Comment by ekambarrao** [comment]
![wp_20150825_17_23_58_pro 1](https://cloud.githubusercontent.com/assets/8529317/9488885/94e75c40-4bfa-11e5-9e19-ea1dce6f2177.jpg)
