### ISSUE TITLE
Update outdated links in README

### ISSUE THREAD

**Issue by rigdern** [winjs/winjs#1407]
These links in the README are out of date:
  - Roadmap – page no longer exists
  - Contribute – page has been moved to [here](https://github.com/winjs/winjs/blob/master/CONTRIBUTING.md)
  - http://try.buildwinjs.com/#status – page moved with the old Try Site
  - Playground – need to update URL to use new site

**Comment by jayrenn** [comment]
Closed via https://github.com/winjs/winjs/commit/38ea100677169574a659f02c1c0b73867ad005ef
