### ISSUE TITLE
WinJS.UI.MenuCommand.dispose broken with flyout by id

### ISSUE THREAD

**Issue by pke** [winjs/winjs#1409]
I have this setup of a `WinJS.UI.MenuCommand` 

```
<button data-win-control="WinJS.UI.MenuCommand" class="discard" data-win-options="{type:'flyout', flyout:'discardFlyout'}" data-win-res="{winControl: { label:'inspection/discard'}}"></button>
<div id="discardFlyout" data-win-control="WinJS.UI.Flyout></div>
```

When I transition to a new page, I get an exception in 

```
WinJS.UI.MenuCommand.dispose:
   if (this._flyout) {
     this._flyout.dispose();
   }
```

The `this._flyout` is of course still the `string` id, handed in the options, so there is no `dispose` method on it. Shouldn't that be `this.flyout.dispose()` cause this would actually fetch the flyout element/winControl via the flyout getter.

This is WinJS.3.0 3.0.0.winjs.2014.9.15 from nuget.

**Comment by jdalton** [comment]
\cc @AmazingJaze

**Comment by AmazingJaze** [comment]
Hi @pke your assertion is correct. Verified this doesn't repro in the latest version of WinJS because MenuCommand was overreaching by taking responsibility of disposing controls that it doesn't host, or directly instantiate.
