### ISSUE TITLE
How to: Prevent list selection loss when refreshing

### ISSUE THREAD

**Issue by pke** [winjs/winjs#1410]
Is there a way to force the listview to keep its selection index (and re-evaluate it by calling the selection changed listeners) when its datasource content is refreshed?
Otherwise I would have to do a diff of new/old items and not a `@items.splice(0, @items.length, newItems...)`

**Comment by jdalton** [comment]
Hi @pke! 

It's not baked into the list view. You might try using local storage or a hidden form element.

**Comment by pke** [comment]
Hmm... Is that not a common use-case in apps? Losing the selection during listview updates can be really annoying. Oh if the Listview only finally would support custom keys, then it could easily remember the selection based on the custom key and restore it after refresh.

My workaround looks like this:

```
      listView.onloadingstatechanged = function() {
        if (listView.loadingState === "complete" && listView.lastSelection >= 0) {
          return listView.selection.set(listView.lastSelection);
        }
      };
      listView.onselectionchanged = function() {
        var indices;
        if (listView.loadingState === "complete") {
          indices = listView.selection.getIndices();
          if (indices.length) {
            listView.lastSelection = indices[0];
          } else {
            listView.lastSelection = -1;
          }
        }
      };
```
