### ISSUE TITLE
Cleanup IsXbox variables from MediaPlayer.

### ISSUE THREAD

**Issue by srinivasdandu** [winjs/winjs#1412]

**Comment by srinivasdandu** [comment]
As per CR feedback, we need to clean up following code

if (_WinRT.Windows.Xbox)

**Comment by rigdern** [comment]
List of platform detection patterns we want to replace with feature detection:
  - `if (_WinRT.Windows.Xbox)`
  - `if (this._isXbox)`
  - `if (_WinRT.Windows.System.Profile.AnalyticsInfo && _WinRT.Windows.System.Profile.AnalyticsInfo.versionInfo.deviceFamily === "Windows.Xbox")`
