### ISSUE TITLE
Refactor Animations in the MediaPlayer

### ISSUE THREAD

**Issue by srinivasdandu** [winjs/winjs#1413]
Usually to avoid Performance issue with current implementation

**Comment by srinivasdandu** [comment]
We should at least add a keyframe
otherwise executeAnimation will have to generate it on the fly which is expensive because it requires the browser to recalculate CSS formatting for the whole page
our keyframes are in
https://github.com/winjs/winjs/blob/9e50af94c8acc7f51166bb9ed3f7695744433641/src/less/animation-library.less.
Suggestion to use using executeAnimation but specifying a keyframe
to avoid the performance issueall of the other WinJS code that uses executeAnimation specifies a keyframe
for example: http://bit.ly/1EnYzmB uses this keyframe: https://github.com/winjs/winjs/blob/9e50af94c8acc7f51166bb9ed3f7695744433641/src/less/animation-library.less#L4

**Comment by rigdern** [comment]
Ideally, we switch from `executeAnimation` to `executeTransition` to avoid the performance issue but adding a CSS keyframe as described by @srinivasdandu also works.
