### ISSUE TITLE
MediaPlayer Compact mode doesn't work properly

### ISSUE THREAD

**Issue by srinivasdandu** [winjs/winjs#1414]

**Comment by srinivasdandu** [comment]
If you enable the MediaPlayer in the compact mode. Icon are not swapping like play/pause and fullscreen. Even on click on the MediaPlayer Controls , video get paused.

Repro steps.

<div id="mediaPlayer" class="mediaPlayer" data-win-control="WinJS.UI.MediaPlayer" data-win-options="{
         chapterSkipBackButtonVisible: false,
         chapterSkipForwardButtonVisible: false,
         fastForwardButtonVisible: true,
         nextTrackButtonVisible: false,
         playFromBeginningButtonVisible: false,
         playPauseButtonVisible: true,
         playbackRateButtonVisible: true,
         previousTrackButtonVisible: false,
         rewindButtonVisible: true,
         stopButtonVisible: false,
         timeSkipBackButtonVisible: false,
         timeSkipForwardButtonVisible: false,
         zoomButtonVisible: false,
         goToLiveButtonVisible: false,
         fullscreenButtonVisible: true,
         castButtonVisible: true,
         muteButtonVisible: false,
         volumeButtonVisible: true,
         compact: true,
         thumbnailEnabled: true
         }">
		
		<video id="video" src="http://video-js.zencoder.com/oceans-clip.mp4" loop="loop" autoplay="autoplay" controls="controls">

**Comment by rigdern** [comment]
In `compact` mode, the icons of the `MediaPlayer` buttons do not match the functionality of the buttons. For example, the button with the play icon should cause the video to begin playing when clicked. Instead, clicking it causes the video to move ahead by 1 frame.

This bug makes `compact` mode too broken for users to be able to use it.
