### ISSUE TITLE
How to getting the visible row count of a listview

### ISSUE THREAD

**Issue by lygstate** [winjs/winjs#1416]
I am trying to getting the visible row count to do math.

**Comment by jdalton** [comment]
@rigdern Is there a way to access this programmatically?

**Comment by rigdern** [comment]
I don't think it's quite what you are looking for but the ListView has the [`indexOfFirstVisible`](https://msdn.microsoft.com/en-us/library/windows/apps/hh700691.aspx) and [`indexOfLastVisible`](https://msdn.microsoft.com/en-us/library/windows/apps/hh700698.aspx) properties. Also, GridLayout has the [`maximumRowsOrColumns`](https://msdn.microsoft.com/en-us/library/windows/apps/dn255114.aspx) which you can use the limit the numbers of rows/columns (depending on the layout's orientation) rendered.

A few questions for you:
  - Why do you need this information? What are you trying to do with it?
  - What layout are you using?
  - What is the orientation of the layout (vertical or horizontal)?

**Comment by lygstate** [comment]
@rigdern I am currently using WinJS in thunderbird, and it's lower level data structure is
nsITreeView and need the value that I requested:)
Anyway, current time I am using indexOfLastVisible - indexOfFirstVisible to do the work and works well.
The orientation is vertical.
The layout is list

**Comment by lygstate** [comment]
Consider it's works, I mark this closed.
