### ISSUE TITLE
WinJS controls are not instantiated when using WinJS.UI.Hub with WinJS.UI.Pages for sections

### ISSUE THREAD

**Issue by pke** [winjs/winjs#1425]
Using this code the `WinJS.UI.*` controls contained in the templates are not instantiated when the pages ready/processed functions are called.
It seems this only happens once the section is pushed into the hub.
But I need to connect event listeners inside my page, and I don't want to do it in the hub pages control, but on the individual section pages.

```
      hub = element.querySelector(".hub").winControl;
      sections[this.model.inspection.vehicularGroup].reduce((function(_this) {
        return function(promise, section) {
          return promise.then(function() {
            return WinJS.UI.Pages.render("/pages/templates/_" + section + ".html", null, {
              model: _this.model
            }).then(function(result) {
              var hubSection;
              hubSection = result.element.querySelector("div[data-win-control='WinJS.UI.HubSection']");
              hub.sections.push(hubSection.winControl);
              WinJS.Binding.processAll(hubSection, _this.model);
              return WinJS.Resources.processAll(hubSection);
            });
          });
        };
      })(this), WinJS.Promise.as());
```

and that is an example section page:

````
<script src="_obligations.js"></script>
  <div class="dialog obligations jumpToOverview"
       data-win-control="WinJS.UI.HubSection"
       data-win-res="{ winControl: {header: 'pages/inspectionPage.obligations'} }"
    >
    <div data-win-bind="style.display:inspection.readOnly WinJS.Ext.Binding.displayBlockIfNot">
      <div data-win-control="WinJS.UI.SearchBox" class="obligationInput" data-win-options="{
          chooseSuggestionOnEnter: true,
          searchHistoryDisabled: true
        }"
        data-win-bind="winControl.disabled:inspection.readOnly">
      </div>
    </div>
    <div style="overflow-y:auto;height:94%">
      <table>
        <thead>
          <tr data-win-bind="style.display:sortedObligations.length WinJS.Ext.Binding.displayRowIf">
            <th data-win-res="{textContent:'app/code'}">Code</th>
            <th data-win-res="{textContent:'app/text'}">Text</th>
          </tr>
        </thead>
        <tbody data-win-control="WinJS.UI.Repeater" data-win-bind="winControl.data:sortedObligations">
          <tr class="win-disposable win-itemcontainer win-container" _data-win-control="WinJS.UI.ItemContainer" data-win-options="{tapBehavior: 'toggleSelect', swipeBehavior:'none'}">
            <td data-win-bind="textContent:code"></td>
            <td><pre data-win-bind="textContent:text"></pre></td>
          </tr>
        </tbody>
      </table>
    </div>
  </div>
```

The repeater and search box all work, but they do not exist during the pages `processed` and `ready` callbacks, So I cannot set a special type on the search box input field like this from within the pages callbacks: `element.querySelector(".obligationInput input.win-searchbox-input").type = "tel"`. Cause "input.win-searchbox-input" in only created when WinJS.UI.processAll has been called on the pages content, and I thought that has happened when `processed` is called. It seems the hub does something strange (optimization?)

**Comment by jseanxu** [comment]
Is this issue related to #32?

**Comment by pke** [comment]
Yes that could be.

**Comment by jseanxu** [comment]
Does the suggested workaround in #32 resolve your issue?

**Comment by pke** [comment]
No, I tried it already.

**Comment by jseanxu** [comment]
>>But I need to connect event listeners inside my page, and I don't want to do it in the hub pages control, but on the individual section pages.

Could you clarify this? Why exactly can't you just hook up event listeners after processing the Hub?

**Comment by pke** [comment]
by that I mean that the code to hook up the event listener are in the individual page files
`section1.html`
`section1.js`
and they are unaware of the fact, that they are part of a hub. They could also be displayed just as single pages.
The hub page code simply puts the sections into hub, as you can see on my first code snippet.
It should not contain code to wire up event listeners for the individual pages it loads into sections. And it cannot, it has no idea what the pages does and what listeners need to be hooked up.
And how would I know anyway if the section has been inserted into the hub fully?

This whole hub thing, with dynamic sections, is not well thought through it seems.

**Comment by pke** [comment]
It seems the WinJS.UI.Pages processed method is called without having processed the the win controls inside the element first. This only happens when the page is loaded in a section of the Hub. Loading the page standalone, everything works just fine. So what is the hub doing there? And can this crazy optimization be turned off?

**Comment by jseanxu** [comment]
The Hub is a declarative control container - this means it subscribes to a contract where when the Hub gets processed, processAll won't process its children. Let me think about your scenario some more and I'll get back to you.

**Comment by pke** [comment]
>  this means it subscribes to a contract where when the Hub gets processed, processAll won't process its children

And that is ok, since there are no children when my hub is first processed. The sections are only filled after the hub has already been processed. The problem is that sections cannot be loaded and inserted using `WinJS.UI.Pages`. Because the processing inside those pages does not work anymore, when the page is part of the hub. `WinJS.UI.Pages` usually calls `processAll` before it calls the `processed` callback that I defined in `WinJS.UI.Pages.define`. But when I check any `.winControl` property on the ' `element` of my page fragments, they are all undefined. Meaning `processAll` has not been properly run.

**Comment by pke** [comment]
I have created this simple project http://1drv.ms/1PRe07m for you test the behaviour. My expectation would be, that it does instantiate the `WinJS.UI.SearchBox` and not print an error message to the console.

**Comment by pke** [comment]
So, @jseanxu have you thought about it and decided to close this bug?

**Comment by jdalton** [comment]
@pke There will be bugs. Our main focus is on regressions at the moment. Other kinds of bugs tend to become stale and fall off our radar.
