### ISSUE TITLE
How to disable ListView's pressed down effect.

### ISSUE THREAD

**Issue by lygstate** [winjs/winjs#1431]
I wanna to disable ListView's pressed down effect, is there any hint for this?

**Comment by jdalton** [comment]
Hey @lygstate! What usage scenario are you interested in?

**Comment by lygstate** [comment]
@jdalton  Thanks jdalton, the pressed down effect is too much of fuzzy under firefox, so I wanna to disable it or just changing the background of the ListView's item.

**Comment by jdalton** [comment]
Hi @lygstate. If you'd like to disable the transform you can overwrite it with one that's more `!important`.
```css
.win-pressed {
    transform: rotateY(0) !important;
}
```
