### ISSUE TITLE
Why are input elements styled with fixed width?

### ISSUE THREAD

**Issue by pke** [winjs/winjs#1432]
Everytime my -ms-grid layout is not working with `input` and that's because they have a fixed size, thanks to WinJS CSS. I have to style them with `width: auto` to get rid of the fixed size and them properly expanding in a "1fr" space in my grid layout.

Question: Why are they fixed size in the first place?

**Comment by jdalton** [comment]
When we converged the PC and Phone UI we had a choice between fixed and variable width. We chose a fixed width to give developers a consistent and expected behavior across form factors.

**Comment by pke** [comment]
How does this fit into responsive design? Fixed width is awful. Sometimes I really wonder if there are other "developers" out there actually using WinJS and having to fight such issues on a daily basis.

**Comment by sebastienC974** [comment]
+1 pke:
It is a pain! We try to make W8.1 app to look like other platforms. Adding exceptions that creates exceptions...

**Comment by pke** [comment]
I run into this every time I start a new WinJS app. It's time for a winjsfixes.css that corrects all those painful defaults.

> We chose a fixed width to give developers a consistent and expected behavior across form factors.

More like give developers a clueless face across form factors.
