### ISSUE TITLE
MediaPlayer: Can't adjust volume in full screen mode in web browser

### ISSUE THREAD

**Issue by rigdern** [winjs/winjs#1434]
1. Download and unzip `repro.zip` from http://1drv.ms/1Epq3I5
2. Open `repro\index.html` in a browser
3. Click the "full screen" button in the ToolBar
4. Click the volume adjustment button in the ToolBar

**Expected:** Volume adjustment Flyout shows.

![image](https://cloud.githubusercontent.com/assets/199935/9613432/31374bb0-50a0-11e5-9255-034495190d72.png)

**Actual:** Nothing happens

**Comment by srinivasdandu** [comment]
This is fixed in the srinivasdandu/MediaPlayer branch.
