### ISSUE TITLE
Consider lowercase letters for the Gamepad enum keys

### ISSUE THREAD

**Issue by payzer** [winjs/winjs#1435]
The keys defined in _ElementUtilities.js for the gamepad have an uppercase 'G'.

It'd be ideal if those keys used lowercase 'g's to be consistent with the rest of the enumeration and apps that may have coded to a version of the enum with a lowercase.

**Comment by jseanxu** [comment]
This would be technically a breaking change which we wouldn't take until the next major release of WinJS.

**Comment by payzer** [comment]
I'm going to re-activate this since it looks from the history it only got closed because it was "stale"

**Comment by jdalton** [comment]
Hi @payzer! Because this is a pri 2 and would be a breaking change you can consider this a won't fix.
