### ISSUE TITLE
WinJS 4.0.0 preview error "SCRIPT 1012: Expected '/'" in IE10

### ISSUE THREAD

**Issue by rutgerl** [winjs/winjs#1436]
Hi,

We have our large application tested against https://cdnjs.cloudflare.com/ajax/libs/winjs/4.0.0-preview/js/WinJS.js.

According to https://github.com/winjs/winjs/wiki/Browser-Support, WinJS supports Microsoft Internet Explorer 10+.

Some of our users use IE10 and submitted an issue that pages having WinJS UI, looked strange or empty. Having reproduced this issue in an HyperV VM with Windows 7 and IE10, it turned out that this version of WinJS.js has five JavaScript comments <code>/&#42;@empty&#42;/</code> (without spaces), causing the IE10 console errors <code>SCRIPT 1012: Expected '/'</code> in WinJS.js and <code>SCRIPT 5009: 'WinJS' is undefined</code> in our application.
Copying WinJS.js local, replacing <code>/&#42;@empty&#42;/</code> (without spaces) by <code>/&#42; @empty &#42;/</code> (with spaces) and referencing this local version, resolved the issue.

Could you fix this issue in a CDN version of 4.0.0-preview, so we can reference the CDN version of 4.0.0-preview again?

Kind regards,

Rutger Luijken
Matchcare

**Comment by rigdern** [comment]
Thanks for the bug report.

As a workaround, you could use the minified version of WinJS (https://cdnjs.cloudflare.com/ajax/libs/winjs/4.0.0-preview/js/WinJS.min.js).
