### ISSUE TITLE
Has WinJS support of ModernIE browser on tablet device with Windows 8.1?

### ISSUE THREAD

**Issue by greybax** [winjs/winjs#1438]
In ModernIE browser on tablet device with Windows 8.1 I have strange behavior. My webpage shows in modern IE by 150% of zoom by default. But if I reduce zoom until 125% after that touch input not works properly. For example I have grid from some input controls. And when I touch one of the inputs another one which placed near activates. 
I use WinJS 2.0

**Comment by jdalton** [comment]
@rigdern Are you familiar with WinJS behavior in the modern IE app.

**Comment by rigdern** [comment]
I do not know why WinJS would exhibit the behavior described in ModernIE.

@greybax Can you provide a page that repros this bug and repro steps?

**Comment by greybax** [comment]
Guys, looks like the same issue can be repro on iPad Air device.
My repro steps
1. Goes to http://try.buildwinjs.com/playground/
2. Select FlipView
3. Increase zoom
4. Click on next picture button.

Expected result:
Picture should be changed

Actual result:
Couldn't click to next picture button
