### ISSUE TITLE
Export a function to change the accent color for non-WinRT environment

### ISSUE THREAD

**Issue by g1b3t** [winjs/winjs#1439]
The namespace WinJS.UI._Accents offers no write access to the user interface accent colors.
If WinJS isn't in WinRT environment there is only a hard-coded rgb(0, 120, 215) accent color.
WinJS/_Accents should at least export function like this:

    function setAccentColor(_r, _g, _b) {
        var uiColor = { r: _r, g: _g, b: _b };
        var accent = colorToString(uiColor, 1);
        if (colors[0] === accent) {
            return;
        }
        // Establish colors
        // The order of the colors align with the ColorTypes enum values
        colors.length = 0;
        colors.push(accent, colorToString(uiColor, (isDarkTheme ? 0.6 : 0.4)), colorToString(uiColor, (isDarkTheme ? 0.8 : 0.6)), colorToString(uiColor, (isDarkTheme ? 0.9 : 0.7)), colorToString(uiColor, (isDarkTheme ? 0.4 : 0.6)), colorToString(uiColor, (isDarkTheme ? 0.6 : 0.8)), colorToString(uiColor, (isDarkTheme ? 0.7 : 0.9)));
        scheduleWriteRules();
    }

to overwrite the hard-coded blue value

**Comment by jdalton** [comment]
Thanks, @jayrenn will pass this request along internally.

**Comment by lamuertepeluda** [comment]
+1
As an alternative, you could provide a "base accent" color property from which the other colors are generated, as for current color rules 
```javascript
["rgb(0, 120, 215)", "rgba(0, 120, 215, 0.6)", "rgba(0, 120, 215, 0.8)", "rgba(0, 120, 215, 0.9)", "rgba(0, 120, 215, 0.4)", "rgba(0, 120, 215, 0.6)", "rgba(0, 120, 215, 0.7)"] 
```
I noticed they are all generated from the same base color rgb(0, 120, 215).
This is a urge on non-windows environments. Thanks
