### ISSUE TITLE
How to adjust listview item's width by scrollbar's display or not?

### ISSUE THREAD

**Issue by apwh7550** [winjs/winjs#1443]
When using listview, some contents are covered like this: 
![image](https://cloud.githubusercontent.com/assets/8054714/9789559/72a5f6e0-5803-11e5-9e81-36e5c2cfe222.png)

then I used " .win-vertical .win-container{margin: 0 12px 0 0;} " to let them out: 
![image](https://cloud.githubusercontent.com/assets/8054714/9789563/7a8cd1a8-5803-11e5-83b9-4d4e27697880.png)

But problems come, when the scrollbar disapeared, there's a space of 12px in the right:
![image](https://cloud.githubusercontent.com/assets/8054714/9789567/8151cfac-5803-11e5-8c40-06036a770ad4.png)

Is there any solution to this? That's to say, the width can change with the scrollbar's display or not, and with contents not covered. Thank you.

**Comment by jdalton** [comment]
Would you give us a snippet of your css/html to show how you've set up your list view items?

**Comment by AmazingJaze** [comment]
Also what environment and OS are you encountering this on?
