### ISSUE TITLE
WinJS 4.3 fails with Cordova 5.1.1

### ISSUE THREAD

**Issue by limefrogyank** [winjs/winjs#1445]
Something changed in WinJS from version 4.2 to 4.3 such that my Cordova app is throwing an error on load.  It might have something to do with how Cordova tries to load WinJS 2.0 (or 1.0) if it does not find WinJS attached to window.  

In any case, you *can* get 4.3 to load if you make the winjs libraries load *after* cordova.js loads.  However, this allows cordova to load the base.js from WinJS 2.0 from the system itself. 

Yet, when you load winjs 4.3 *before* cordova.js, it throws a WWA error immediately.  

I downgraded to WinJS 4.2 and I get normal behavior again.

**Comment by jdalton** [comment]
@limefrogyank Can you try the latest winjs (master) and see if it resolves your issue.

**Comment by limefrogyank** [comment]
Yes, it does resolve it.  Thanks!

**Comment by jdalton** [comment]
Rock!
