### ISSUE TITLE
WinJS ListView invalidateAll cause repeat itemsFromIndex call, is this the normal state?

### ISSUE THREAD

**Issue by lygstate** [winjs/winjs#1446]
itemsFromIndex: function (requestIndex, countBefore, countAfter) {
        console.log("Fetching count is:", requestIndex, countBefore, countAfter);
     }

[info] invalidate
[info]
[info] Fetching count is: 0 0 35
[info] Fetching count is: 1 1 34
[info] Fetching count is: 2 2 33
[info] Fetching count is: 3 3 32
[info] Fetching count is: 4 4 31
[info] Fetching count is: 5 5 30
[info] Fetching count is: 6 6 29
[info] Fetching count is: 7 7 28
[info] Fetching count is: 8 8 27
[info] Fetching count is: 9 9 26
[info] Fetching count is: 10 10 25
[info] Fetching count is: 11 11 24
[info] Fetching count is: 12 12 23
[info] Fetching count is: 13 13 22
[info] Fetching count is: 14 13 21
[info] Fetching count is: 15 13 20
[info] Fetching count is: 16 13 19
[info] Fetching count is: 17 13 18
[info] Fetching count is: 18 13 17
[info] Fetching count is: 19 13 16
[info] Fetching count is: 20 13 15
[info] Fetching count is: 21 13 14
[info] Fetching count is: 22 13 13
[info] invalidate done

**Comment by jdalton** [comment]
\cc @rigdern

**Comment by lygstate** [comment]
@jdalton @rigdern This is not a question, this most like be a issue,
It's repeating request for interval [0,35] until the middle.

**Comment by rigdern** [comment]
@lygstate Can you share a sample which repros this? You can share it with OneDrive [as described on our wiki](https://github.com/winjs/winjs/wiki/How-to-share-repros-of-issues-with-WinJS).

**Comment by lygstate** [comment]
@rigdern  OK, I found why this happening, the real issue is that the datasource are changed. and all the things are different, but invalidateAll unable to response to such a change. the resolve is to assign a new itemDataSource
