### ISSUE TITLE
I wanna to implement customized dragstart event on ListView, how to do that.

### ISSUE THREAD

**Issue by lygstate** [winjs/winjs#1447]
At the current time, ListView always disable the drag events and implement it's own drag handling, how to disable it and implement customized drag drop handler.

**Comment by jdalton** [comment]
Any ideas @AmazingJaze?

**Comment by AmazingJaze** [comment]
@jdalton @lygstate 

Off the top of my head, I'm not aware of any way to enable this.

@lygstate  can you share a little more about the scenario you are trying to accomplish?
