### ISSUE TITLE
WinJS 4.3 app fails to start when in a W8.1 Universal app running on W10

### ISSUE THREAD

**Issue by CensoredUser** [winjs/winjs#1448]
The PR #1323 introduced this issue. The underlying issue seems to be that the Windows API throws an exception, however we will need to either catch that exception or do additional checks as to which context the application is running in (W8.1 mode or W10 mode).

More info/discussion on issue #1323

**Comment by limefrogyank** [comment]
Is this related? [issue 1445](https://github.com/winjs/winjs/issues/1445)

**Comment by jdalton** [comment]
Fixed by https://github.com/winjs/winjs/pull/1490.
