### ISSUE TITLE
MediaPlayer - Remove basic overlay content

### ISSUE THREAD

**Issue by ghost** [winjs/winjs#1451]
Related to this issue: https://github.com/winjs/winjs/issues/1449

The Overlay renders by default the content shown in the **green box**  in the below screen capture.  I believe it is pulled from the data passed into MediaPlayer.setContentMetadata.  The MediaPlayer should not have a default overlay unless it is overrideable / can be turned off.  Recommend turning off as a minimum for this release.  

<img width="1217" alt="mediaplayeroverlay" src="https://cloud.githubusercontent.com/assets/10854024/9947334/58c1de42-5d67-11e5-8dff-e08f3129e66a.png">

**Comment by srinivasdandu** [comment]
This is design issue. Currently you can use CSS for hide default overlays.

.win-mediaplayer-mediatitle,
.win-mediaplayer-mediadescription {
    display: none;
}
