### ISSUE TITLE
MediaPlayer: Black line always present at start of seekbar

### ISSUE THREAD

**Issue by rigdern** [winjs/winjs#1455]
1. Download and unzip `repro.zip` from http://1drv.ms/1Qo5YTB
2. Open a command line in the `repro` folder and run:
  - `npm install`
  - `npm start`
3. Open `http://localhost:8080/` in Chrome
4. Move the mouse to the MediaPlayer's controls to reveal them

**Unexpected result:** There's always a black line near the beginning of the seekbar:

![image](https://cloud.githubusercontent.com/assets/199935/9974279/50a3bdc2-5e3c-11e5-9c54-6e88aad8dd34.png)

**Comment by srinivasdandu** [comment]
By Design buffering progressing color......by the time media loads..buffering Starts
