### ISSUE TITLE
WinJS.UI.ListView error (Container missing after updateContainers)

### ISSUE THREAD

**Issue by omnoms** [winjs/winjs#146]
VS2013Pro, WinJS 2.1 for Windows Phone project;

*This issue only arises ON DEVICE and not on the emulator. Using a Nokia Lumia 920 with the latest Dev Image for Windows Phone 8.1*

**TLDR-version**; When navigating back to a view with a ListView, the app crashes with the message "Container missing after updateContainers"

**Long version**
I have a view which has a ListView and another view that has some settings relevant to that listView.

The ListView is populated by an asynchronous WinJS.xhr call on the page onready statement.

The data is defined in a Data namespace;
```javascript
    WinJS.Namespace.define("Data", {
        ResourceLogs: new WinJS.Binding.List(null, { binding: true }),
        ....
    });
```
..converted into a grouped listview on the page with the following definition..

```javascript
    WinJS.Namespace.define("resourceLogView", {
        data: Data.ResourceLogs.createGrouped(
            function (item) { return item.FromDate },
            function (item) { return { FromDate: moment(item.FromDate).format('ddd, DD MMMM YYYY') }},
            function (left, right) { return Date(right) - Date(left) }
            ),
       ....
   });
```

Then displayed in this list;

```html
      <div id="smallListIconTextTemplate" data-win-control="WinJS.Binding.Template">
        <div class="smallListIconTextItem" style="height: 80px;">
            <div class="listIconBoxNoFloat">
                <span class="listIcon" data-win-bind="innerText: icon"></span>
                <span style="width:40px; text-align: center;"><strong data-win-bind="innerText: Units"></strong></span>
                <span style="width: auto;" data-win-bind="innerText: Contract.Organisation.Description"></span>
                <!--<span style="width: auto;" data-win-bind="innerText: FromDate"></span>-->
            </div>
            <div class="smallListIconTextItem-Detail">
                <h4 data-win-bind="textContent: rlDescription"></h4>
                <h6 data-win-bind="textContent: Description"></h6>
            </div>
        </div>
    </div>
    <div id="listLayoutTopHeaderTemplate" data-win-control="WinJS.Binding.Template">
        <div class="listLayoutTopHeaderTemplateRoot">
            <div data-win-bind="innerHTML: FromDate"></div>
        </div>
    </div>
.... 
           <div id="rlLogsList"
                 class="win-selectionstylefilled"
                 data-win-control="WinJS.UI.ListView"
                 data-win-options="{
                    itemTemplate: smallListIconTextTemplate,
                    groupHeaderTemplate: listLayoutTopHeaderTemplate,
                    selectionMode: 'single',
                    swipeBehavior: 'select',
                    oniteminvoked: resourceLogView.editItem,
                    onselectionchanged: resourceLogView.selectedItem,
                    layout: { type: WinJS.UI.ListLayout, groupHeaderPosition: 'top' }
            }"></div>
```

All fine so far. These bits never seem to have been an issue (except that swipebehaviour doesn't work in the emulator nor on device), however... I think there might be something strange with either how I update the view or how i populate the list or the onready statement initialization....

the page's onready has these lines to bind the datasource. I noticed that binding directly in the markup to the datasource and I got weird issues when the list was instantiated with an empty array or null;

```javascript
                var el = document.querySelector("#rlLogsList").winControl;
                el.itemDataSource = resourceLogView.data.dataSource;
                el.groupDataSource = resourceLogView.data.groups.dataSource;
                resourceLogView.pageInitialized = true;
                el.forceLayout();
```

not having forceLayout there and it didn't render the list either...

next up is how I populate the list. It's on a callback that WinJS.xhr sends the response object to, after some custom validations, the jist of it is the following;

```javascript
        storeResourceLogs: function (parsedObject) {
            var t_Val;
            Data.ResourceLogs.length = 0;
            ....
            /// some data manipulation of the parsedObject that results in a logs Array variable
            ....
            logs.forEach(function (item, i) {
                    Data.ResourceLogs.push(item);
                });
            WinJS.Binding.processAll();
            WinJS.UI.processAll();
        }
```

not having Binding.processAll() and UI.processAll() makes for an updated list in the back-end, but the displayed list is not updated.
Using Data.ResourceLogs.notifyReload() crashes the app on-device.

So the problem? Besides having to use Binding.processAll() and UI.processAll() to update the view, when navigating to the calendar view and pressing back, the App crashes. Either with nothing stopping the app in the debugger and just simply hangs, OR the debugger stops at the terminateAppHandler function with the following message;

```JSON
"{"exception":"Container missing after updateContainers.","error":null,"promise":{"_value":"Container missing after updateContainers.","_isException":true,"_errorId":2},"id":2}"
```

**Edit:** I should clarify that this doesn't happen every time, just a large majority of the times (90-95%). I hypothesize that the listview controller crashes if it gets an updated datasource in the middle of drawing the current datasource since at the time it crashes, it has drawn maybe 2-4 items before it dies.

**Comment by pke** [comment]
Will this eventually be backported to WinJS Phone 2.1?
