### ISSUE TITLE
MediaPlayer: Wrong set of commands shown after resizing while commands are hidden on in chrome

### ISSUE THREAD

**Issue by rigdern** [winjs/winjs#1466]
1. Download and unzip `repro.zip` from http://1drv.ms/1Qo5YTB
2. Open a command line in the `repro` folder and run:
  - `npm install`
  - `npm start`
3. Open `http://localhost:8080/` in Chrome
4. Move the mouse onto the MediaPlayer to reveal the controls and resize the window to be thin such that some commands overflow:

  ![image](https://cloud.githubusercontent.com/assets/199935/9974444/c2bd9278-5e43-11e5-9fd9-96ab776d5a1e.png)

5. Move the mouse outside of the window and wait for the commands to hide. **Make sure the commands remain hidden until you reach step 8.**
6. Move the mouse next to the window so it shows the resize window pointer/cursor.
7. Resize the window to make it much wider
8. Move the mouse onto the window to reveal the commands

**Expected result:** All of the commands are rendered:

![image](https://cloud.githubusercontent.com/assets/199935/9974448/44601fbc-5e44-11e5-8ff0-1256bb9f76a5.png)

**Actual result:** A small number of commands is rendered as though the window were still very thin:

![image](https://cloud.githubusercontent.com/assets/199935/9974447/3a02cef2-5e44-11e5-8109-424ff3c73cf8.png)

**Comment by srinivasdandu** [comment]
This is reproing only in chrome. SO removing platformall tag
