### ISSUE TITLE
The time complexity of Binding.List.splice is o(n)

### ISSUE THREAD

**Issue by lygstate** [winjs/winjs#1475]

**Comment by jdalton** [comment]
@lygstate Do you have any suggestions on how to optimize this?

**Comment by lygstate** [comment]
About this, I implemented a data structure to cope with this problem.
https://github.com/mail-apps/javascript-algorithms/blob/master/src/data-structures/size-balanced-tree.js

**Comment by jdalton** [comment]
Thanks @lygstate! We'll keep an eye on reports of perf and reevaluate if there's demand.
