### ISSUE TITLE
WinJS causes wwahost to crash

### ISSUE THREAD

**Issue by gleborgne** [winjs/winjs#1479]
With WinJS 4.3, when running a Windows 8.1 application on Windows 10, wwahost is crashing at startup when calling getForCurrentView on SystemNavigationManager. Looks like when running in "Windows 8 compat" mode, Windows 10 exposes forbidden APIs.

Here is the guilty code :
```js
if (_WinRT.Windows.UI.Core.SystemNavigationManager) {
                    // On Win10 this accomodates hardware buttons (phone), 
                    // the taskbar's tablet mode button, and the optional window frame back button.
                    var navManager = _WinRT.Windows.UI.Core.SystemNavigationManager.getForCurrentView();
                    navManager.addEventListener("backrequested", hardwareButtonBackPressed);
                } 
```
For your info, as a workaround, I added a check on user agent (must have "Edge" in it) in addition to verify existence of SystemNavigationManager. Can't find a cleaner solution
```js
if (_WinRT.Windows.UI.Core.SystemNavigationManager && _Global.navigator && _Global.navigator.appVersion.indexOf("Edge") >= 0) {
                    // On Win10 this accomodates hardware buttons (phone), 
                    // the taskbar's tablet mode button, and the optional window frame back button.
                    var navManager = _WinRT.Windows.UI.Core.SystemNavigationManager.getForCurrentView();
                    navManager.addEventListener("backrequested", hardwareButtonBackPressed);
                }
```

**Comment by BrandonLive** [comment]
That's a really annoying behavior of SystemNavigationManager. It's not unusual for WinRT APIs to be accessible to Win8.1 JS apps, but they normally either work (like the titlebar colorization APIs) or do nothing. This API should either return null from getForCurrentView (which we could then check to accommodate this case) or it should work (or at the very least, appear to work even if it never fires the event).

I haven't tested this myself yet, but if it's really throwing an exception (and not returning null) then this is very annoying. I guess the UI check is fine. Though I wonder if checking the WWA version (i.e. I think it says MSAppHost/3.0 or something) would be better?

**Comment by jdalton** [comment]
Hi @gleborgne!

Can you try the changes in PR #1490 and see if that addresses the issue.

**Comment by gleborgne** [comment]
Think I have (unsuccessfully) tried That before. Will try tomorrow

**Comment by jdalton** [comment]
I tested this locally and you're right the exception cannot be caught.
I have tweaked the inference in the PR.

**Comment by gleborgne** [comment]
That way to infer availabitly is working for me

**Comment by jdalton** [comment]
Fixed via https://github.com/winjs/winjs/commit/e39dc3b243ad10a8a28f07217a0fa694e55e35f1.
