### ISSUE TITLE
SeachControl: UI flashes when clicking on the search button

### ISSUE THREAD

**Issue by jkochhar** [winjs/winjs#1485]
We are using WinJS 4.0 in our app and we are seeing the search suggestions panel flashes when you click on the search button again after you have hit it once. So the scenario is in the Music app on Win 10, 
Search for something in the search box (top right corner)
Hit the Search glyph to see the results
Hit the search glyph again - this seems to try and show and the suggestions and then hides it causing a flash.
I think the issue is that the search button tries to show the suggest panel on click and hide it when the click is released resulting in a flasg

**Comment by jdalton** [comment]
@jkochhar Would you be up for creating a PR to fix this?

**Comment by humale** [comment]
@jkochhar, is this still a problem that you encounter? Feel free to reopen the issue if it is.
