### ISSUE TITLE
SplitView Pane should automatically change display modes

### ISSUE THREAD

**Issue by NCC1701M** [winjs/winjs#1486]
Give use an option where we can decide if we would change the display mode of the SplitViewPane programatically or if it should do this automatically when the screen is of a specific size.

For example: 

On small screens (Smartphones etc.) the closedDisplayMode could be automatically switch to none and the openedDisplayMode could be overlay

On medium screens (Tablets etc.) the closedDisplayMode could be automatically switch to inline and the openedDisplayMode could be overlay.

On large screens the closedDisplayMode could be automatically switch to inline and the openedDisplayMode could be inline as well or it would be great, if you could implement a new display mode where the split view is always expanded

**Comment by rigdern** [comment]
Thanks for the suggestion.

The [code in this post on MSDN](https://social.msdn.microsoft.com/Forums/en-US/a26aa496-42e6-4977-a609-a13c7b950c18/uwpwinjs-splitview-closeddisplaymode-on-small-screens?forum=wpdevelop#9679f568-6343-4785-9dda-dbb7f22332fa) should be helpful in achieving this scenario without having the functionality built into the `SplitView`.

> it would be great, if you could implement a new display mode where the split view is always expanded

Can you elaborate on why it'd be helpful to have this as a separate display mode? This can already be achieved by configuring the `openedDisplayMode` to `inline` and calling `openPane()` on the `SplitView`. As long as you don't call `closePane()` on the `SplitView` or change the `openedDisplayMode`, it should remain in that configuration.

**Comment by NCC1701M** [comment]
Well, I find it useful to fill some space, when you have a big screen and the content don't looks very well when it's spread over the whole screen. So you can show always the splitview and you don't waste so much space by showing void.

When you do this by set `openedDisplayMode` to `inline` the user can always click on the toggle and close it. To prevent this you have to disable the toggle, but there is no way within the `WinJS.UI.SplitViewPaneToggle` to `disable` it.

> The code in this post on MSDN should be helpful in achieving this scenario without having the functionality built into the SplitView.

Yeah but you can do all this just by using css and there is no need for javascript doing this for you. So why must I use JavaScript to achieve this behaviour?

**Comment by rigdern** [comment]
> When you do this by set openedDisplayMode to inline the user can always click on the toggle and close it. To prevent this you have to disable the toggle, but there is no way within the WinJS.UI.SplitViewPaneToggle to disable it.

Do you have a preference between hiding the `SplitViewPaneToggle` and disabling it? If not, you could hide the button.

If you prefer to disable it, you make a good point that `SplitViewPaneToggle` doesn't have a `disabled` API on it. You should file an issue about this. As a workaround, you can grab the `element` of the toggle and set disabled on it: `splitViewPaneToggle.element.disabled = true`.

> Yeah but you can do all this just by using css and there is no need for javascript doing this for you. So why must I use JavaScript to achieve this behaviour?

You may be able to get close to replicating the SplitView's functionality with CSS media queries but you can't quite do everything with CSS. For example, you can't inform the SplitView that it should be opening in overlay mode vs inline mode without JavaScript.

**Comment by jdalton** [comment]
@NCC1701M If you have specific API additions feel free to create a new issue with those outlined.
