### ISSUE TITLE
WinJS 4.2 Menu throws exception when scrolling while Soft Keyboard is shown

### ISSUE THREAD

**Issue by limefrogyank** [winjs/winjs#1488]
I'm not quite sure why the WinJS.UI.Menu control is doing this but I'm getting an exception when my app is showing the Soft Keyboard **and** I actually scroll the window, i.e. try to see what the keyboard has overlapped, on WP81 using WinJS 4.2 (4.3 doesn't work at all right now).  

Specifically, in ui.js, within the "var Flyout = _Base.Class.derive(_Overlay._Overlay,..." section, there's a function called _checkScrollPosition(Flyout_checkScrollPosition). It seems to me that the very beginning of this function checks if the menu is hidden (yes, it is on mine) and that a parameter called "showing" is false.  If this evaluates to true, then the function returns with nothing done.  However, for some reason the "showing" parameter is not a Boolean but instead seems to be the document itself.  

So the first if statement is skipped and then the _currentPosition variable is checked on the Menu.  However, this is undefined and where the exception occurs.

Can anyone explain what is happening and how to correct this problem?  My Menu is set as a direct child of the body element and is *not* being displayed when this error occurs.  Thanks!

**Comment by limefrogyank** [comment]
Tried WinJS 4.3 with the latest commit included and it still gives this error.

**Comment by AmazingJaze** [comment]
Hi @limefrogyank, is this the code in question? 
https://github.com/winjs/winjs/blob/fdada16d361cbc88a9704e237c5f2bc8bb243b31/src/js/WinJS/Controls/Flyout.js#L1292-L1294

If so it appears that the variable `showing` is a passed in parameter, but the only place I can see that function being called is here, where its clearly passing a boolean: https://github.com/winjs/winjs/blob/fdada16d361cbc88a9704e237c5f2bc8bb243b31/src/js/WinJS/Controls/Flyout.js#L1267

If you check the call stack, where is _checkScrollPosition being called from, and what is the value being passed to it?
