### ISSUE TITLE
Listview: add support for the win-container to be height of "auto"

### ISSUE THREAD

**Issue by vajnorcan** [winjs/winjs#1493]
I'm not exactly sure why the listview items "must" be of the same height, possibly due to some height, calculation logic, but would it be possible to add the support for the win-container for the listview to be "height=auto" ?

Currently if I set the "height=auto" to the "win-container" class, the scrolling goes haywire. If this is not possible, please advise a workaround to achieve the "autosizing items" in listview

Here is the sample
https://www.dropbox.com/sh/rvbhl4nurk457ix/AABSkfznfDFHbqqd3ynrzn5ta?dl=0

The style to play with is in "default.css", rule ".nswtraffic .win-listview .win-container", remove/add height to see the difference. Make sure you always scroll to the bottom of the whole listview to see what I'm talking about.

In the sample, to avoid https://github.com/winjs/winjs/issues/1327 , add the following into the "home.js" on ready event

```javascript
this._hub.addEventListener("itemanimationstart", function (args) {				
				if (cameras && camerasElement) {
					camerasElement.itemDataSource = cameras.dataSource;
					camerasElement.forceLayout();
				}
			});
```

Thanks for all your support!

**Comment by vajnorcan** [comment]
I can also report that on IE10 and Edge it works all good. Chrome is showing all signs mentioned here

**Comment by vajnorcan** [comment]
so what is the recommendation for this as it's been closed without any response given?!

**Comment by jdalton** [comment]
Hi @vajnorcan! Sorry for closing it out. Unfortunately there's lots of stale issues across the WinJS projects and commenting on all of them is impractical. It's my hope that it's better to close an issue as stale than leave it open with a false sense of tackling.

Knowing what goes into a listview (virtualization et all) I'd say support for auto-height would not be intended.  If you've gotten a workaround for IE10 and Edge you may want to try v4.4 to see if your Chrome issue is resolved.
