### ISSUE TITLE
Regression: ListViews don't render inside of a Pivot

### ISSUE THREAD

**Issue by rigdern** [winjs/winjs#1497]
### Repro Steps

1. Open https://jsfiddle.net/7za476fL/ in Chrome

**Expected result**: There's a ListView rendered inside of the Pivot

![image](https://cloud.githubusercontent.com/assets/199935/10237724/9a943316-686a-11e5-8978-8f144a988f89.png)

**Actual result**: There's no ListView rendered inside of the Pivot

![image](https://cloud.githubusercontent.com/assets/199935/10237717/85356c1a-686a-11e5-9e9d-5db8b6ca3aaf.png)

### Cause

This is a regression introduced in the WinJS 4.1 Pivot.

The problem is that the Pivot runs processAll on the PivotItem while the PivotItem is `display:none`. Consequently, the content inside of the Pivot cannot measure (e.g. the ListView) which is why the ListView ends up not rendering.

**Comment by AmazingJaze** [comment]
Thanks for the detailed investigation. This is related to #1327, @jdalton I recommend keeping this as the master branch since it contains rigdern's root cause investigation.

**Comment by staxmanade** [comment]
:+1: Thank for the quick fix!
