### ISSUE TITLE
.win-backdrop css class

### ISSUE THREAD

**Issue by guiyens** [winjs/winjs#1498]
Some ".win-container" items appear with ".win-backdrop" class, it looks like a grey  rectangle with no info inside loaded. So, how does  .win-backdrop class work?
I had so many ".win-container" items with ".win-backdrop" and I thought the problem comes from my CSS rules but I removed every own CSS rules less  ".win-container" width and the problem was still there. 

``` html
<div class="win-itemsblock">
	<div class="win-container win-container-even"></div>
	<div class="win-container win-container-even"></div>
	<div class="win-container win-container-even"></div>
	<div class="win-container win-container-even"></div>
	<div class="win-container win-container-even"></div>
	<div class="win-container win-container-even"></div>
	<div class="win-container win-container-even"></div>
	<div class="win-container win-container-even"></div>
	<div class="win-container win-container-even win-backdrop"></div>
	<div class="win-container win-container-even win-backdrop"></div>
	<div class="win-container win-container-even win-backdrop"></div>
</div>
```

**Comment by jdalton** [comment]
Hi @guiyens! This is related to virtualization that is the elements not yet visible in the viewport.
