### ISSUE TITLE
New Pivot behaviour of not showing the next section when swiping is confusing

### ISSUE THREAD

**Issue by pke** [winjs/winjs#1505]
I know I complain a lot about the latest design decisions for Windows 10. Now I wanted to use the once great Pivot control in my Cordova app but nobody I gave the app understood why the swipe gesture does not show the next section (like the old pivot did).

Is there a special style to bring this behaviour back?

You can try the behaviour yourself using the newest Visual Studio Tools for Cordova
https://github.com/pke/evopark

**Comment by AmazingJaze** [comment]
@jseanxu I believe you are the expert here.

**Comment by jseanxu** [comment]
What platform are you running your Cordova app on? Swiping should work. Depending on the platform, the Pivot contents may not follow your finger but a swipe gesture should still navigate the Pivot.

**Comment by pke** [comment]
The faulty behaviour we can see on Android and iOS devices. The touch on the title works (although its slow in reacting, I guess that can be fixed with fast-click though). The content does not follow the finger which is highly confusing. Because then all of the sudden, the content changed.

Please take a look at the facebook app how everybody (on Android) is expecting the pivot control to work. I mean, Windows Phone 7 had the most beautiful pivot control of all OS, no doubt about that. With Windows 10 the whole metro approach was changed (clearly) to please Android users. Yet, the controls WinJS provides do not behave like their Android equivalents.

**Comment by jdalton** [comment]
> Is there a special style to bring this behaviour back?

WinJS 4.0 is tied to the Windows 10 design so there's no way to bring back the old behavior.

**Comment by AmazingJaze** [comment]
I believe the Pivot control uses standardized HTML5 Drag APIs to achieve the effect that @pke is referring to in IE and Edge. @jseanxu can correct me if I'm wrong, but once these API's have been implemented in the Android and iOS Browser, the effect of the Pivot following your finger should begin to work automatically, like it does in Edge and IE today.
