### ISSUE TITLE
Emoji variations no longer displayed correctly.

### ISSUE THREAD

**Issue by jdalton** [winjs/winjs#1509]
As mentioned [on twitter](https://twitter.com/BrandonLive/status/651903695420944385) via @BrandonLive

**Comment by jdalton** [comment]
@jseanxu Who's the approp dev to handle css related issues?

**Comment by BrandonLive** [comment]
Thanks, meant to come post this here myself.

What's interesting is that it looks like Segoe UI Emoji is included in the different language/locale-specific font-family specifications, but is no longer there in the default one we get for English. Should be a really easy change (I fixed it in my app by just overriding .win-type-body's font-family specification to add "Segoe UI Emoji" at the end).

**Comment by jdalton** [comment]
Would you be up for creating a pull request?
