### ISSUE TITLE
http://winjs.azurewebsites.net/#get stils redirects to v4.1

### ISSUE THREAD

**Issue by sebagomez** [winjs/winjs#1510]
The samples and download buttons are still pointing to the 4.1 version.
Shouldn't they all be at the latest release (v4.4 as of today)?

**Comment by jdalton** [comment]
Hi @sebagomez! The official doc site has moved to http://try.buildwinjs.com :D

**Comment by sebagomez** [comment]
Yes, but there's no way of going full screen with the code and I really like the other site better. It also still reachable from the "old playground" link.
Don't know why you changed to this one, but if you guys still give access to the old/better site it should bu up to date with the latest version.
Hope you guys find something in between, as good looking and functional as the old one and as "what ever you were looking for" as the new one.

**Comment by jdalton** [comment]
The old site is around for historical reference but will no longer be updated.

**Comment by sebagomez** [comment]
good to know... I hope you keep the new one updated.
It's a really useful reference
