### ISSUE TITLE
Consider lowercase letters for the Gamepad enum keys

### ISSUE THREAD

**Issue by payzer** [winjs/winjs#1511]
I filed another version of this bug, but it was closed as "stale" so I'm re-opening it. Previous comments in the history I read to indicate the bug would be fixed in a future release.

---------- here's the text -----------

The keys defined in _ElementUtilities.js for the gamepad have an uppercase 'G'.

The key enums should use lowercase 'g's to be consistent with the rest of the enumeration and apps that may have coded to a version of the enum with a lowercase.

**Comment by jdalton** [comment]
The follow up is appreciated but unnecessary (no need to create a duplicate issue).
I'll defer to the resolution of #1435.
