### ISSUE TITLE
WinJS.UI.SplitViewCommand on Windows Phone 8.1 let user select text on click

### ISSUE THREAD

**Issue by pke** [winjs/winjs#1512]
Instead of providing a non-selectable touch experience the `WinJS.UI.SplitViewCommand` on Windows Phone 8.1 are selecting their text when touched. No visual feedback of the touch is shown. Just the text selected.
Works on desktop

**Comment by jdalton** [comment]
Hey @pke, by works on desktop you mean doesn't select the text, right?

**Comment by pke** [comment]
Yes on the desktop it shows the selection background bars.
On the playground it works also. So it must be a problem with wwahost hosted apps I guess.

**Comment by jdalton** [comment]
Thanks!

**Comment by pke** [comment]
Dead project. Closing this issue.
