### ISSUE TITLE
Inspecting the WinJS.UI.BackButton with VS2015 crashes wwahost.exe

### ISSUE THREAD

**Issue by pke** [winjs/winjs#1513]
While debugging my Cordova app and inspecting the `WinJS.UI.BackButton` in the DOM Explorer the apps host process wwahost.exe crashes at:

```bash`
>	mshtml.dll!CDocument::Doc(void)	Unknown
 	mshtml.dll!CAttribute::GetNSAtomTable()	Unknown
 	mshtml.dll!CAttribute::NamespaceURI(void)	Unknown
 	mshtml.dll!CAttribute::get_namespaceURI()	Unknown
 	mshtml.dll!CAttribute::get_ie9_nodeValue()	Unknown
 	mshtml.dll!CAttribute::get_ie9_value(unsigned short * *)	Unknown
 	mshtml.dll!CFastDOM::CAttr::Trampoline_Get_value()	Unknown
 	jscript9.dll!amd64_CallFunction()	Unknown
 	jscript9.dll!Js::JavascriptExternalFunction::ExternalFunctionThunk()	Unknown
 	jscript9.dll!amd64_CallFunction()	Unknown
 	jscript9.dll!Js::JavascriptFunction::CallFunction<1>(class Js::RecyclableObject *,void * (*)(class Js::RecyclableObject *,struct Js::CallInfo,...),struct Js::Arguments)	Unknown
 	jscript9.dll!Js::HelperOrLibraryMethodWrapper<1,class <lambda_f3fb5c5fabf75a41a43766851a4fc31b> >(class Js::ScriptContext *,class <lambda_f3fb5c5fabf75a41a43766851a4fc31b>)	Unknown
 	jscript9.dll!Js::ScriptContext::ProfileModeThunk_DebugModeWrapper(class Js::JavascriptFunction *,class Js::ScriptContext *,void * (*)(class Js::RecyclableObject *,struct Js::CallInfo,...),struct Js::Arguments &)	Unknown
 	jscript9.dll!Js::ScriptContext::DebugProfileProbeThunk(class Js::RecyclableObject *,struct Js::CallInfo,...)	Unknown
 	jscript9.dll!<lambda>(void)()	Unknown
 	jscript9.dll!Js::DictionaryTypeHandlerBase<unsigned short>::GetProperty()	Unknown
 	jscript9.dll!Js::DynamicObject::GetProperty(void *,int,void * *,class Js::PropertyValueInfo *,class Js::ScriptContext *)	Unknown
 	jscript9.dll!Js::CustomExternalObject::GetPropertyImpl<1>()	Unknown
 	jscript9.dll!Js::CustomExternalObject::GetProperty(void *,int,void * *,class Js::PropertyValueInfo *,class Js::ScriptContext *)	Unknown
 	jscript9.dll!Js::JavascriptOperators::PatchGetValue<Js::InlineCache>()	Unknown
 	000000307ad461c4()	Unknown
 	jscript9.dll!Js::InterpreterStackFrame::OP_ProfiledLoopBodyStart<0,1>()	Unknown
 	jscript9.dll!Js::InterpreterStackFrame::Process()	Unknown
 	jscript9.dll!Js::InterpreterStackFrame::InterpreterThunk<1>()	Unknown
 	0000003074c70823()	Unknown
 	jscript9.dll!amd64_CallFunction()	Unknown
 	jscript9.dll!Js::InterpreterStackFrame::Process()	Unknown
 	jscript9.dll!Js::InterpreterStackFrame::InterpreterThunk<1>()	Unknown
 	0000003074c7085b()	Unknown
 	jscript9.dll!amd64_CallFunction()	Unknown
 	jscript9.dll!Js::InterpreterStackFrame::Process()	Unknown
 	jscript9.dll!Js::InterpreterStackFrame::InterpreterThunk<1>()	Unknown
 	0000003074c70793()	Unknown
 	jscript9.dll!Js::JavascriptArray::EntryForEach()	Unknown
 	jscript9.dll!amd64_CallFunction()	Unknown
 	jscript9.dll!Js::InterpreterStackFrame::Process()	Unknown
 	jscript9.dll!Js::InterpreterStackFrame::InterpreterThunk<1>()	Unknown
 	0000003074c707b3()	Unknown
 	jscript9.dll!Js::JavascriptArray::EntryMap()	Unknown
 	jscript9.dll!amd64_CallFunction()	Unknown
 	jscript9.dll!Js::InterpreterStackFrame::Process()	Unknown
 	jscript9.dll!Js::InterpreterStackFrame::InterpreterThunk<1>()	Unknown
 	0000003074c707bb()	Unknown
 	jscript9.dll!amd64_CallFunction()	Unknown
 	jscript9.dll!Js::JavascriptFunction::EntryApply()	Unknown
 	jscript9.dll!amd64_CallFunction()	Unknown
 	jscript9.dll!Js::InterpreterStackFrame::Process()	Unknown
 	jscript9.dll!Js::InterpreterStackFrame::InterpreterThunk<1>()	Unknown
 	0000003074c70973()	Unknown
 	jscript9.dll!amd64_CallFunction()	Unknown
 	jscript9.dll!Js::InterpreterStackFrame::Process()	Unknown
 	jscript9.dll!Js::InterpreterStackFrame::InterpreterThunk<1>()	Unknown
 	0000003074c70983()	Unknown
 	jscript9.dll!amd64_CallFunction()	Unknown
 	jscript9.dll!Js::JavascriptFunction::CallFunction<1>(class Js::RecyclableObject *,void * (*)(class Js::RecyclableObject *,struct Js::CallInfo,...),struct Js::Arguments)	Unknown
 	jscript9.dll!Js::BoundFunction::NewInstance()	Unknown
 	jscript9.dll!amd64_CallFunction()	Unknown
 	jscript9.dll!Js::InterpreterStackFrame::Process()	Unknown
 	jscript9.dll!Js::InterpreterStackFrame::InterpreterThunk<1>()	Unknown
 	0000003074c7098b()	Unknown
 	000000307ad3442b()	Unknown
 	jscript9.dll!amd64_CallFunction()	Unknown
 	jscript9.dll!Js::JavascriptFunction::CallFunction<1>(class Js::RecyclableObject *,void * (*)(class Js::RecyclableObject *,struct Js::CallInfo,...),struct Js::Arguments)	Unknown
 	jscript9.dll!Js::JavascriptFunction::CallRootFunction()	Unknown
 	jscript9.dll!ScriptSite::CallRootFunction(class Js::JavascriptFunction *,struct Js::Arguments,struct IServiceProvider *,void * *)	Unknown
 	jscript9.dll!ScriptSite::Execute()	Unknown
 	jscript9.dll!ScriptEngineBase::Execute()	Unknown
 	mshtml.dll!CEventDispatcher::_Invoke(struct IActiveScriptDirect *,struct CallInfo const &,void * *)	Unknown
 	mshtml.dll!CEventDispatcher::_Dispatch(void * const *)	Unknown
 	mshtml.dll!CDiagnosticsExternal::OnMessage(unsigned short const * *,unsigned short const * *,unsigned long)	Unknown
 	mshtml.dll!CDiagnosticsScriptEngine::FireScriptMessageEvent(unsigned short const * *,unsigned short const * *,unsigned long)	Unknown
 	DiagnosticsTap.dll!EngineSite::OnMessage(unsigned short *,unsigned short *)	Unknown
 	DiagnosticsTap.dll!IPCChannel::PipeHelper::OnIPCMessage(struct IPCChannel::IPCPacketBase const * const)	Unknown
 	DiagnosticsTap.dll!std::for_each<class std::_Vector_iterator<class std::_Vector_val<struct std::_Simple_types<class std::shared_ptr<struct IPCChannel::IPCPacketBase> > > >,class <lambda_afbc501b184325eea3385817e7b3d4e0> >(class std::_Vector_iterator<class std::_Vector_val<struct std::_Simple_types<class std::shared_ptr<struct IPCChannel::IPCPacketBase> > > >,class std::_Vector_iterator<class std::_Vector_val<struct std::_Simple_types<class std::shared_ptr<struct IPCChannel::IPCPacketBase> > > >,class <lambda_afbc501b184325eea3385817e7b3d4e0>)	Unknown
 	DiagnosticsTap.dll!IPCChannel::PipeMultiplexor::ThreadCallHandler(unsigned __int64,unsigned __int64,unsigned __int64)	Unknown
 	DiagnosticsTap.dll!IPCChannel::PipeMultiplexor::ProcessWindowMessage(struct HWND__ *,unsigned int,unsigned __int64,__int64,__int64 &,unsigned long)	Unknown
 	DiagnosticsTap.dll!ATL::CWindowImplBaseT<class ATL::CWindow,class ATL::CWinTraits<1442840576,0> >::WindowProc(struct HWND__ *,unsigned int,unsigned __int64,__int64)	Unknown
 	user32.dll!UserCallWinProcCheckWow()	Unknown
 	user32.dll!DispatchMessageWorker()	Unknown
 	Windows.UI.dll!Windows::UI::Core::CDispatcher::WaitAndProcessMessages(void * hEventWait) Line 321	C++
 	Windows.UI.dll!Windows::UI::Core::CDispatcher::ProcessEvents(Windows::UI::Core::CoreProcessEventsOption options) Line 390	C++
 	WWAHost.exe!CoreWindowDispatcher::RunMessageLoop(struct Windows::UI::Core::ICoreWindow *)	Unknown
 	WWAHost.exe!WebInstance::Run(void)	Unknown
 	twinapi.appcore.dll!Windows::ApplicationModel::Core::CoreApplicationView::Run(void)	Unknown
 	twinapi.appcore.dll!Windows::ApplicationModel::Core::CoreApplicationView::Uninitialize(void)	Unknown
 	SHCore.dll!StrRetToBSTR()	Unknown
 	kernel32.dll!BaseThreadInitThunk()	Unknown
 	ntdll.dll!RtlUserThreadStart()	Unknown
```

### This is my env on Win 8.1 Pro:

```bash
Microsoft Visual Studio Community 2015
Version 14.0.23107.0 D14REL
Microsoft .NET Framework
Version 4.6.00081

Installed Version: Community

Visual Basic 2015   00322-20000-00000-AA476
Microsoft Visual Basic 2015

Visual C# 2015   00322-20000-00000-AA476
Microsoft Visual C# 2015

Visual C++ 2015   00322-20000-00000-AA476
Microsoft Visual C++ 2015

Windows Phone SDK 8.0 - ENU   00322-20000-00000-AA476
Windows Phone SDK 8.0 - ENU

Application Insights Tools for Visual Studio Package   1.0
Application Insights Tools for Visual Studio

ASP.NET and Web Tools   14.0.20626.0
ASP.NET and Web Tools

ASP.NET Web Frameworks and Tools 2013   5.2.30624.0
For additional information, visit http://www.asp.net/

Chutzpah Test Adapter for Visual Studio 2012   4.1.0
Chutzpah adapter for the Visual Studio 2012 Unit Test Explorer. Chutzpah is an open source JavaScript test runner which enables you to run JavaScript unit tests from the command line and from inside of Visual Studio.

Common Azure Tools   1.5
Provides common services for use by Azure Mobile Services and Microsoft Azure Tools.

GenerateUnitTest   1.0
Generates unit test code for methods in classes under test.

GitHub.VisualStudio   1.0
A Visual Studio Extension that brings the GitHub Flow into Visual Studio.

Microsoft Azure Mobile Services Tools   1.4
Microsoft Azure Mobile Services Tools

Multilingual App Toolkit   3.1.1250.0
Multilingual App Toolkit helps you localize your Windows Store app by providing file management, pseudo and machine translation, translation editor, and build integration. http://go.microsoft.com/fwlink?linkid=245767

Node.js Tools   1.1.30716.01
Adds support for developing and debugging Node.js apps in Visual Studio

Node.js Tools - Profiling   1.1.30716.01
Profiling support for Node.js projects.

NuGet Package Manager   3.2.0
NuGet Package Manager in Visual Studio. For more information about NuGet, visit http://docs.nuget.org/.

PreEmptive Analytics Visualizer   1.2
Microsoft Visual Studio extension to visualize aggregated summaries from the PreEmptive Analytics product.

SQL Server Data Tools   14.0.50616.0
Microsoft SQL Server Data Tools

Visual Studio Tools for Universal Windows Apps   14.0.23309.00 d14oob
The Visual Studio Tools for Universal Windows apps allow you to build a single universal app experience that can reach every device running Windows 10: phone, tablet, PC, and more. It includes the Microsoft Windows 10 Software Development Kit.

Web Compiler   1.6.217
Compiler for LESS, Sass and CoffeeScript files

Web Essentials 2015   0.5.175
Adds many useful features to Visual Studio for web developers.
```

**Comment by jdalton** [comment]
Thanks @pke, I'll pass this along to the VS team.
