### ISSUE TITLE
[Promise] Will they eventually make use of ECMA Promises?

### ISSUE THREAD

**Issue by pke** [winjs/winjs#1516]
I wonder if there are any plans to make the transition to ECMA Promise/A easy for WinJS developers or should we already just use `Promise` now instead of `WinJS.Promise`?

I know that `Promise` is missing the progress callback of `WinJS.Promise` but aside from that they do not seem to differ much?

**Comment by jdalton** [comment]
I believe there is a bit of difference between the two implementations regarding resolving promises.
If you can I'd recommend going with native promises whenever possible.
