### ISSUE TITLE
[WinJS 4.4.0] All text always selected on Windows Phone

### ISSUE THREAD

**Issue by pke** [winjs/winjs#1517]
Running my app on Windows Phone I noticed that all text is always selected when touched. I never experienced that on previous WinJS versions. Is that CSS related?
I have set the required `win-type-body` style on my `body` element.

**Comment by jdalton** [comment]
It may be CSS related. Have a look at the [release diff](https://github.com/winjs/winjs/compare/release/4.3...release/4.4) and let me know if something jumps out.

**Comment by pke** [comment]
Nothing jumps out in that regard. Have you guys actually tested the versions on phones?

**Comment by jdalton** [comment]
@jseanxu Can you look into this?

**Comment by BrandonLive** [comment]
Which OS version?

**Comment by pke** [comment]
Tested it on Windows Mobile 10.0.10536.1004 and Windows Phone 8.1

I had to add a `body { -ms-user-select: none;}` to make the apps hamburger menu working.

**Comment by humale** [comment]
Hi @pke, did you ever find another workaround or did you end up going with the one you mentioned above?

**Comment by pke** [comment]
I used the solution mentioned above.
