### ISSUE TITLE
[Bug] WinJS.xhr does not send user/password as documented in MSDN

### ISSUE THREAD

**Issue by pke** [winjs/winjs#1518]
According to MSDN we should be able to use the `user` and `password`fields of `WinJS.xhr(options)` hash to specify user credentials. However, those credentials are never sent to the server.
I have to manually construct a `Authorization` header with the users credentials to make a valid call to the server.

**Comment by jdalton** [comment]
I'm seeing them being sent https://github.com/winjs/winjs/blob/0540950eff991ad92efb38901195a5d053023a79/src/js/WinJS/Utilities/_Xhr.js#L70-L78.

**Comment by pke** [comment]
But not sent by the XHR implementation. A simple nodejs server showed that and the original target server also does not see credentials.

**Comment by jdalton** [comment]
Since it's not using anything other than the built-in `XMLHttpRequest` object can you try a simple repro of it working to compare to.

**Comment by jdalton** [comment]
Closing for now as this looks to be a non-winjs issue.

**Comment by llvinhll** [comment]
Please re-open.
While the code looks like it is taking in user and password, I walked it and req.withCredentials is set to false, when req is being sent.
