### ISSUE TITLE
XYFocus: Input element toggle mode behavior should support override

### ISSUE THREAD

**Issue by jseanxu** [winjs/winjs#1526]
Opening on behalf of an internal Xbox Dev:
>While input elements accepting text have a cursor, for which the movement of the cursor must be distinguishable from element navigation, this distinction on Xbox is already handled by the virtual keyboard. In this environment the toggle mode behavior interferes with the showing of the keyboard, as the press of the A button on the gamepad is handled by the code while in the ToggleModeRestState.

>To handle the variety of environments in which XYFocus might be used, input elements should not be hardcoded to be toggle mode elements, but rather have the option of a global opt-out.

>For reference, see method _isToggleMode in XYFocus.

**Comment by Guadzilah** [comment]
So what' s the solution of this problem
