### ISSUE TITLE
How to deploy and run a WinJS app on iPad?

### ISSUE THREAD

**Issue by varghesep** [winjs/winjs#1528]
I created an ASP.NET 5 MVC6 app and uses **winjs-angular** and Angular2 controls. Currently I use **DNX** and sometimes **IISExpress** to run the app locally on my desktop.

The app is responsive so it can work in various device dimensions. How can I get this app to work in apple iPad with any other solution than hosting in Azure and accessing as a website?

**Comment by elliott-parkinson** [comment]
Hi I believe what you are looking for is called manifoldjs. This tool allows you to create a package for android, chromeos, ios, and windows 10 universal apps out of any website (as a hosted app).

Take a look:
http://www.manifoldjs.com/
