### ISSUE TITLE
ES6 Binding of Getter/Setter

### ISSUE THREAD

**Issue by toddpi314** [winjs/winjs#1531]
Group,

ES6 marks getter/setters as enumerable:false by default. 

This pretty much breaks availability for WinJS.Binding usage for declarative binding  (data-win-bind) because that implementation is relying on Object.keys to honor binding subjects.

Just wanted to call out that WinJS binding is kind of use-less right now for the ES6 recommended composition patterns with getter/setters.

Recommendation is to re-write the WinJS.Binding to not rely on reflective object lookup; rather, allow the provided binding context details to directly bind to properties on the subject.

Thanks!
Todd

**Comment by toddpi314** [comment]
The work around is pretty simple client-side.

Write your own Binding Initializer like so:

``` javascript
  return WinJS.Binding.initializer(function(source, sourceProps, dest, destProps) {
      var eventSource = dest;
      var command = source;
      var sourceItems = destProps.length;
      var destItems = sourceProps.length;
      dest[destProps[0]] = source[sourceProps[0]];
    });
```
Add that in your `data-win-bind` block:

``` html
<div data-win-bind="innerHTML: sampleData WinJSRocks.Binding.Mode.Property"></div>
```
This will allow the ES6 getter to bind non-enumerable properties:

``` javascript
  get sampleData(){
    return this._sampleData;
  }
```

Todd

**Comment by Guadzilah** [comment]
im confused don't really know how to use github

**Comment by toddpi314** [comment]
?

**Comment by staxmanade** [comment]
@toddpi314 I bumped into this one myself a while back - manually created properties with `Object.defineProperty` - but not ideal. This would be great to fix in the core...

**Comment by jdalton** [comment]
Hi @toddpi314!

We aren't looking to expand support to non-enumerable properties.
