### ISSUE TITLE
WinJS 2.1 Phone: appbar beforeshow/aftershow event not fired

### ISSUE THREAD

**Issue by pke** [winjs/winjs#1534]
I also tried to set the `Windows.UI.WebUI.Core.WebUICommandBar.getForCurrentView()` "menuopened" listener myself, but its also never fired. Tested it in a Windows 8.1 app on Windows 8.1 Phone and Windows 10 Mobile.

**Comment by Guadzilah** [comment]
Did you come to a conclusion

**Comment by pke** [comment]
I saw it being hit yesterday once, but I could not really find out the reason why. I will have to investigate further. I guess WinJS 2.1 is no longer officially supported here.

**Comment by Guadzilah** [comment]
Stay updated thanks

**Comment by toddpi314** [comment]
Ignore @Guadzilah, he's a bot

**Comment by jdalton** [comment]
Correct.

**Comment by pke** [comment]
Gone are the times when MS supported old API for years... ;)
