### ISSUE TITLE
addDynamicCssRule does not recalculate

### ISSUE THREAD

**Issue by P4trik** [winjs/winjs#1537]
I use the ListView control with the angular wrapper.

All rows inside my ListView have the correct height and width for the first page call.
If I rezise my browser window, the height if my rows isn't recalculated.

With uncomment the addDynamicCssRule function inside of _createContainerStyleRule, erverything works fine for me.

**Comment by jdalton** [comment]
Hi @P4trik! Please open this over at https://github.com/winjs/angular-winjs/issues.
