### ISSUE TITLE
WYSIWYG editors not working on content rendered with WinJS.UI.Pages.render

### ISSUE THREAD

**Issue by limefrogyank** [winjs/winjs#1545]
I've been trying to get a rich text editor to work in my web app and I couldn't get any of them to work in my single-page navigation app. I've tried CKEditor, TinyMCE, and NicEdit.  I've narrowed it down to something that WinJS.UI.Pages.render does when creating the content.  When you place the elements you need for the 3rd party editor directly on the main page outside of the PageControl, then it works fine.

I have a limited workaround for my app which is to just use a pivot control and remove page navigation functionality.  However, this is far from ideal.  I'd really like to use a SplitView, but I'm not sure how to render the content without using WinJS's render function...

**Comment by toddpi314** [comment]
@limefrogyank My experience investigating your situation almost always results in finding race conditions between the editors the page layout cycle. 

Verify that your editor is being constructed *after* the ready method is called on your base view (to assure the view has rendered) and after you have called called process on the appropriate contexts to kick off any declarative binding:

``` javascript
 return WinJS.UI.processAll(that.element).then(function() {
      return WinJS.Binding.processAll(that.element, that.viewModel).then(function() {
        return WinJS.Resources.processAll(that.element);
      });
    });
```

Tell us how that goes.

**Comment by Guadzilah** [comment]
My editors are being constructed   already extended visual studio thanks

**Comment by limefrogyank** [comment]
I'll have to try it again then because I thought I had done that.  In one trial, I was putting textareas in my view and calling CKEDITOR.replace('editor1') on them after the WinJS.Binding.processAll promise completed.  Aside from the auto-adding of ckeditor to contenteditable div's, I'm pretty sure I waited until binding completed for all my attempts at the different editors.

But, I'll give it another shot later.

**Comment by Guadzilah** [comment]
Okay thanks I'm all for it

**Comment by toddpi314** [comment]
That is a pretty custom framework and you might want to do the due-diligence to verify that it isn't something internal to that dependency. For instance, can you just create a straight-up File->New Project and verify the editor is compatible with delayed load phase?

In the case of that particular MVVM setup, I am guessing from the samples that the creator is expecting the ViewModel event dispatcher to notify view of binding async from the processAll. If that is the case, you might try building your own Binding Initializer (https://github.com/DeepElement/winjsrocks/blob/master/src/binding/mode.js#L10-L31). This would allow you to use declarative markup to force the editors to setup *after* the `WinJS.Binding.processAll` cruises through the visual tree. 

Also, make sure you are capturing the promise chain errors:

``` javascript
WinJS.Promise.onerror = function(event) {
  console.log(e);
};

WinJS.Application.onerror = function(e) {
  console.log(e);
  return true;
};
```
