### ISSUE TITLE
Next release

### ISSUE THREAD

**Issue by dak0rn** [winjs/winjs#1556]
Hey ho 

Me and my team are waiting for a bug fix assigned to [Milestone 1510](https://github.com/winjs/winjs/issues/1361).

Are you already able to estimate the date of the next release?

Thanks in advance!

**Comment by cycore** [comment]
Any news on this? Not much going on here since october

**Comment by humale** [comment]
@dak0rn thanks for the question! Refer to this thread for the answer :) https://github.com/winjs/winjs/issues/1622#issuecomment-213136589
