### ISSUE TITLE
Listview scroll doesn't work after semantic zoom on ipad 

### ISSUE THREAD

**Issue by lelezeus88** [winjs/winjs#1565]
Hi,
I have a page with two ListView (Listview1 and Listview2) inside a SemanticZoom div.
From Listiview1 the scroll works, but if I go to Listiview2 (with pinch) and go back to Listview1 (tapping on an item), the Listview1 doesn't scroll anymore.
This happens only on iPad with WinJs 4.4 version. With winjs 3.3 this sample works.
Here there is a sample fiddle: http://jsfiddle.net/T87cT/11/
Thank you for support

Emanuele

**Comment by lelezeus88** [comment]
Is there any workaround? Thank you

**Comment by humale** [comment]
Hi @lelezeus88, thanks for your question. Did you end up finding a workaround/fix? Let me know!

**Comment by lelezeus88** [comment]
Hi! I'm sorry, I didn't fix the bug and not even found a workound. I simply roll back to 3.3 version because I need to go into production asap.

**Comment by humale** [comment]
Hi @lelezeus88, going to close this issue and re-open it when we decide to tackle the 'Future' milestone.
