### ISSUE TITLE
Byte-order marker (BOM) in single page app causes layout issues

### ISSUE THREAD

**Issue by limefrogyank** [winjs/winjs#1569]
This problem is not necessarily a WinJS problem, nevertheless, it affects the use of WinJS in multiple browsers.

When loading a page within a PageControl in a single-page navigation style web app AND when that page was created using Visual Studio, the byte-order marker (BOM)  is **not** interpreted correctly in both Edge and Chrome.  You get whitespace that pushes the margins of any other elements in your page down slightly.  In Firefox, the BOM is not converted to whitespace.

It's a simple workaround to open the HTML files in Notepad++ and change the encoding to UTF8 without BOM.  However, I wonder if the BOM is something that can be cut out in the page render process?  (since the root page should still have the BOM)

**Comment by jdalton** [comment]
The BOM is designed to enable bytecode caching in Windows Apps.
Your workaround looks like a good solution.
