### ISSUE TITLE
Windows.Services.Maps.MapLocationFinder not found

### ISSUE THREAD

**Issue by c-ni** [winjs/winjs#1585]
According to the documentation, it should exist. Shows undefined at Windows.Services.Maps.MapLocationFinder. Just curious if I'm missing an API reference somewhere?

https://msdn.microsoft.com/en-us/library/windows.services.maps.maplocationfinder.findlocationsatasync.aspx

Using WinJS version 4.4

**Comment by jdalton** [comment]
Ping @jayrenn. Should this be closed out?

**Comment by niallatms** [comment]
It looks like the documentation is incorrect; the API is actually marked with the WebHostHidden attribute, so it isn't available in WinJS.  You can try filing a suggestion on that doc page ("Any Suggestions?" link) or through the Windows Feedback app under Developer Platform -> Documentation and Samples.
