### ISSUE TITLE
Exceptions accessing members of undefined symbol in ui.js

### ISSUE THREAD

**Issue by convey-gilbert** [winjs/winjs#1603]
Some unverified members are accessed in function VirtualizeContentsView_realizePageImpl()
(around line 18130 ff.)
the missing verification can lead to exceptions, so better correct the code like this:

...

function viewPortPageRealized() {
    that._listView._hideProgressBar();
    // GS 2016-02-19: now check for existence of that._state.setLoadingState
    that._state.setLoadingState && that._state.setLoadingState(that._listView._LoadingState.viewPortLoaded);
    if (that._executeAnimations) {
	that._setState(RealizingAnimatingState, renderingCompleteSignal.promise);
    }
}

function pageRealized(count) {
    that._updateAriaMarkers(count === 0, that.firstIndexDisplayed, that.lastIndexDisplayed);
    that._state.setLoadingState && that._state.setLoadingState(that._listView._LoadingState.itemsLoaded);
}

function finish(count) {
    that._listView._clearInsertedItems();
    that._listView._groups.removeElements();
    viewPortPageRealized();
    pageRealized(count);
    complete();
}
// GS 2016-02-19: now check for existence of that._state.setLoadingState
that._state.setLoadingState && that._state.setLoadingState(that._listView._LoadingState.itemsLoading);
if (that._firstLayoutPass) {
    that._listView._showProgressBar(that._listView._element, "50%", "50%");
}
// GS 2016-02-19: now check for existence of that.containers
var count = (that.containers && that.containers.length);

...

**Comment by niallatms** [comment]
If you want to submit a pull request, we can take these fixes.

**Comment by humale** [comment]
Hi @convey-gilbert, just wanted to see if you wanted to make a pull request for this. Let me know!

**Comment by humale** [comment]
@convey-gilbert, feel free to re-open this when you submit a PR - I've taken note of the problem and will fix it after going through other issues/PR's
