### ISSUE TITLE
Need help with a more concrete example on binding

### ISSUE THREAD

**Issue by xiamx** [winjs/winjs#1605]
Suppose I have a ToggleSwitch, declared in html

```
    <div data-win-control="WinJS.UI.ToggleSwitch" data-win-options="{title: 'sample'}"></div>
```

and I want to bind the `checked` property of ToggleSwitch to some javascript variable, how should I code it?

**Comment by niallatms** [comment]
Have you already looked at the tutorial site: http://www.buildwinjs.com/tutorial/2WinJS_Binding/bindingInit/

Or the MSDN documentation: http://www.buildwinjs.com/tutorial/2WinJS_Binding/bindingInit/

**Comment by xiamx** [comment]
Yes I did. It's not very selfcontained, as it didn't say what I can pass in as sourceProperty. And the second page's example is broken.

![capture](https://cloud.githubusercontent.com/assets/643911/13260764/039626b2-da2b-11e5-9162-bb5584fb7e71.PNG)


After searching for quite a bit of time, I figured out how to do it. But still, It would be nice that the tutorial be written with more step by step examples

**Comment by niallatms** [comment]
The '____________________' text represents a place where you're expected to enter in some content to demonstrate what the tutorial is explaining.  You need to look through all the tabs (JS, CSS, HTML) and fill those in where you find them.

You can click on the 'Get Solution' button to fill those all in for you, after which it should work.

**Comment by xiamx** [comment]
Oh.. my bad. sorry for not reading carefully.
