### ISSUE TITLE
Bug: Exception in DatePicker when submitting undefined value

### ISSUE THREAD

**Issue by convey-gilbert** [winjs/winjs#1607]
Better don't allow to set the _currentDate member of DatePickjer to null or undefined.
Change Code around line 29299 ff. like this:

current: {
                    get: function () {
                        var d = this._currentDate;
                        var y = d.getFullYear();
                        return new Date(Math.max(Math.min(this.maxYear, y), this.minYear), d.getMonth(), d.getDate(), 12, 0, 0, 0);
                    },
                    set: function (value) {
                        var newDate;
                        if (typeof (value) === "string") {
                            newDate = new Date(Date.parse(value));
                            newDate.setHours(12, 0, 0, 0);
                        } else {
                            newDate = value;
                        }
                        // GS 2016-02-29: don't set _currentDate member to empty value
                        if (newDate) {
                            var oldDate = this._currentDate;
                            if (oldDate !== newDate) {
                                this._currentDate = newDate;
                                this._updateDisplay();
                            }
                        }
                    }
                },

**Comment by humale** [comment]
Hi @convey-gilbert, thanks for the fix! Can you make this into a PR? We'll look at it from there :)

**Comment by humale** [comment]
@convey-gilbert, if we do this fix, then the DatePicker control allows an app to set null dates. @llongley correct me if I'm wrong, but I feel like we want an app to crash if it is incorrectly trying to set a DatePicker's date to be a null value. Is there a specific scenario you're trying to implement @convey-gilbert? Also, what would the value displayed in the DatePicker if we allowed it to have null dates?

**Comment by convey-gilbert** [comment]
Hello Humale,

the Problem is: if you assign a null/undefined value to the member _currentDate
Then, next time on call of DatePicker.current.get()
it will Crash!

**Comment by convey-gilbert** [comment]
Hello Humale,

you've written: "but I feel like we want an app to crash"
But, I'm sure, that opinion ist mistaken, since you want to build a reliable library, as we all want. Isn't it?!

Especially in this case, where the Crash will happen sometime later when accessing the member and you can't find out the reason was a wrong value in an assignment somewhere else.
Please, discuss this matter with your colleagues and rethink about "want to crash an application" - just randomly...
Some more hints: 
- the Desktop DateTimePicker control supports a checkbox to display null values!
- I proposed to ignore a null/undefined setting. if you don't want the control to do so, you can assign current date if null value is set

;)

**Comment by convey-gilbert** [comment]
Hello Humale,

sorry, again. But I think I should state this out:
- Make your library operate predictible and stable. 
- Ensure operation at all parameter values. Document the results, depending on all values.
- Invoking a crash is no option. Never. This only leads to bad UX!

**Comment by convey-gilbert** [comment]
Okay, finally - sorry.
If someone will find the time, maybe it's necessary:
Review all control settings for correct null/undefined value handling of "not nullable" controls. 
Either:
- ignore
or
- set to a documented default value

but, never: crash!

**Comment by humale** [comment]
@convey-gilbert thanks for the feedback. I'll definitely look at this and get back to you. Can you make a pull request for this? Also, if you get a chance, a PR for this issue as well: https://github.com/winjs/winjs/issues/1603 Let me know! If not, I can go ahead and make the changes.

**Comment by humale** [comment]
Closed by https://github.com/winjs/winjs/commit/0874ad396bfa149839de29e3381b34c029d62bdf
