### ISSUE TITLE
WinJS 4.4.0 wrong AppBar position when switching the on-screen keybord

### ISSUE THREAD

**Issue by mesju** [winjs/winjs#1612]
I noticed a problem with the AppBar when switching between the different types of on-screen keybords. On some point the AppBar is shown in the middle of the screen or other unusual positions. Here a screenshot:

https://onedrive.live.com/redir?resid=141BD40B8366079C!27412&authkey=!ACGvMzuvID0prWA&v=3&ithint=photo%2cpng

I fixed thr problem modifing the following method from

        AppBar.prototype._handleHidingKeyboard = function () {
            // Make sure AppBar has the correct offsets since it could have been displaced by the IHM.
            this._adjustedOffsets = this._computeAdjustedOffsets();
            this._commandingSurface.deferredDomUpate();
        };

to

        AppBar.prototype._handleHidingKeyboard = function () {
            // Make sure AppBar has the correct offsets since it could have been displaced by the IHM.
            var _this = this;
            var duration = keyboardInfo._animationShowLength + keyboardInfo._scrollTimeout;
            Promise.timeout(duration).then(function () {
                _this._adjustedOffsets = _this._computeAdjustedOffsets();
                _this._commandingSurface.deferredDomUpate();
            });
        };

**Comment by cthedot** [comment]
great, I seen this too esp on phone but only from time to time. Would be great to have this added in a general release. Maybe it is easier for the maintainers if you did a proper PR?

(I fixed one or two litte things myself so probably should do this myself first, hope I get around to it next week ;)

**Comment by humale** [comment]
Hi @mesju, thanks for the fix! @cthedot is right; could you make this into a pull request? Thanks :)

**Comment by mesju** [comment]
Here is the pull request:

Fix, wrong AppBar position when switching the on-screen keybord #1628

**Comment by humale** [comment]
Will close this and make further comments on the PR :)
