### ISSUE TITLE
React JS

### ISSUE THREAD

**Issue by spruzzer** [winjs/winjs#1614]
I would like to ask you if there is any update about the integration of winjs with React.js0.14+/Angular2? On the WinJS webpage are listed both React and Angular adapters, but they refer to pretty old version of the library/framework. Moreover, on the git page of the adapters there are no news about updates and current dev status. The projects seems to be  abandoned.

WinJS seems to be an extremely interesting UI library, I really hope that support to real-world library/frameworks that enable devs to build serious SPAs will be provided/continued. In the worst case a guide in how to integrate wins UI component into React/Angular components will be a must.

**Comment by xdvarpunen** [comment]
Look at react-winjs and angular-winjs. There is said to be plan ongoing for support Angular2 and React.JS 0.14+

**Comment by xdvarpunen** [comment]
Look at react-winjs and angular-winjs. There is said to be plan ongoing for support Angular2 and React.JS 0.14+

**Comment by xdvarpunen** [comment]
@spruzzer Look at react-winjs and angular-winjs. There is said to be plan ongoing for support Angular2 and React.JS 0.14+

**Comment by spruzzer** [comment]
Thanks for the reply. I wrote here, in the main project issue, because even though on both winsj-react and angular-react there are support requests, the projects are not receiving updates from November/December. Moreover, the repos have react/angular-related-issues that are still open.

**Comment by xdvarpunen** [comment]
Angular2 is not yet production ready and [beta](https://github.com/angular/angular), which means there could be big breaking changes in the API. 

> Angular 2 is currently in Beta.

 Also react 0.15 is still on [release candidate](https://facebook.github.io/react/blog/2016/03/07/react-v15-rc1.html). That's why it is logical why no updates yet :D

**Comment by GiedriusGrabauskas** [comment]
[react-winjs](https://github.com/winjs/react-winjs) currently support only React **0.13** version.

**Comment by jdalton** [comment]
Please direct React Adapter questions to the https://github.com/winjs/react-winjs repo.
