### ISSUE TITLE
Suggestions for future release

### ISSUE THREAD

**Issue by xdvarpunen** [winjs/winjs#1616]
Hi,

These are my suggestions for WinJS:

### Toolkit/Guide for missing/desired/wanted controls composed from WinJS

WinJS could have similar to [MyToolkit](https://github.com/MyToolkit/MyToolkit) of project which shows how to use the different controls in order to create controls that is not ready available and could be smoothly done by one him/herself. 

For instance sortable table is one of the popular controls that would be nice to have. CRUD is one of the things done in browser. In MyToolkit sortable table called [datagrid](https://github.com/MyToolkit/MyToolkit/wiki/DataGrid) is done with listview that has layout datagrid in .NET XAML/C# and same could be possibly done in/for WinJS?

### Navigation with URL

WinJS was used to create Windows app at start so URL bar was not visible. Navigation works with shim that comes in VS template from Windows 8 times. It would be good to introduce the routing system with URL since webapps are usually bookmarked. 

### Controls as components

React and Angular wrappers have the BackButton and SemanticZoom controls that depend on WinJS libraries. Removing dependency of WinJS libraries from controls would smooth the start of using React or Angular wrappers on WinJS libraries. 

-XDVarpunen

**Comment by humale** [comment]
@xdvarpunen thanks for the suggestions. Refer to my comments about feature requests here: https://github.com/winjs/winjs/issues/1622#issuecomment-213136589
