### ISSUE TITLE
Is the WinJS development frozen?

### ISSUE THREAD

**Issue by SaschaNaz** [winjs/winjs#1619]
https://github.com/winjs/winjs/graphs/contributors?from=2015-10-04&to=2016-03-26&type=c

I'm not seeing any active development or maintenance since Oct 4, 2015. Is WinJS being deprecated? Do I have to consider a transition to other UI framework? Are you just making a new framework in secret?

**Comment by xdvarpunen** [comment]
Soon in Build2016 might see some news over there. I am guessing they are making possibly Angular2 with Typescript rewrote WinJS propably :smile:

**Comment by xdvarpunen** [comment]
Nothing mentioned in [Channel 9](https://channel9.msdn.com/Events/Build/2016?sort=status&direction=asc&term=winjs#tab_sortBy_status) :walking: patience?

**Comment by anteloe** [comment]
To me it seems that WinJS and all its adapters (like [react-winjs](https://github.com/winjs/react-winjs)) have been given up. Not one session in Build 2016 exclusively to WinJS, no active Development since Oct 2015...
Kinda sad...

**Comment by xdvarpunen** [comment]
Nothing mentioned during Build 2016. What's going on?

**Comment by humale** [comment]
@SaschaNaz your question has been answered here: https://github.com/winjs/winjs/issues/1622#issuecomment-213136589
