### ISSUE TITLE
getRelativeLeft is bugged

### ISSUE THREAD

**Issue by mquandalle** [winjs/winjs#1621]
The `getRelativeLeft` does an incorect calculation in case there are multiple nested `position: static` elements. This is a pretty common situation, as illustrated by the following minimal reproduction:

> https://jsfiddle.net/t0wuj879/3/

The bug comes from an error in the recursive calculation of the `getRelativeLeft` loop. It should rely on `element.offsetParent` instead of `element.parentNode`.

**Comment by humale** [comment]
Hi @mquandalle, can you make a pull request for this?

**Comment by mquandalle** [comment]
No, I’m sorry. I’m not a user of this library and I don’t plan to spend time fixing it—especially considering that it is not a trivial fix and that the library is in low maintenance mode. If other people encounter this bug I hope this issue will save them some investigation time and that the reproduction I provided will help anyone interested in fixing the bug, but that’s all I can do.

**Comment by humale** [comment]
@mquandalle sounds good we'll look into it. Thanks for outlining the reproduction steps. :)

**Comment by llongley** [comment]
This should be fixed now.
