### ISSUE TITLE
DatePicker needs further optimization for small phones

### ISSUE THREAD

**Issue by DonWesley** [winjs/winjs#1625]
The DatePicker is not displaying well enough in small-width phones (read: 4in). The date is getting compressed and user's can't see their selections in layouts from 280 pixels to 320 pixels wide.

**Comment by llongley** [comment]
Hi,

Are you by any chance able to repro the issue you're seeing if you just set the width of a DatePicker to a small value and then view it on a desktop?  I was wanting to have a look at this bug, but I don't have a small-width phone available to test on, so an alternate repro would be super helpful.

Thanks!

**Comment by humale** [comment]
@DonWesley, feel free to re-open this if you find yourself still having this problem!
