### ISSUE TITLE
ListView: <title here>

### ISSUE THREAD

**Issue by Valenchak** [winjs/winjs#1634]
Feature: ListView
Environment: Mozilla/5.0 (Windows NT 10.0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/48.0.2564.82 Safari/537.36 Edge/14.14352
Source: http://try.buildwinjs.com Play With ListView
Layout: List
Orientation: Vertical
Items Reorderable: False
Items Draggable: False
Tap Behavior: Invoke Only
Selection Mode: Multi
Item Template: Text With Image
Group Items: False
Group Header Template: Text
Group Header Position: Top
Group Header Tap Behavior: Invoke
Data Source: 100 Items

**Comment by humale** [comment]
Closing as duplicate of https://github.com/winjs/winjs/issues/1635
