### ISSUE TITLE
Promises: queue

### ISSUE THREAD

**Issue by CKGrafico** [winjs/winjs#165]
Feature: Promises
I tried some methods to do a queue of promises but I didn't found the best method, you provide a function WinJS.Promise.join, but this only start n+i promises after n and call then() when n promises are completed. But if n+2 Promise depends of the results of n+1 promise, this function is inadequate.

Any similar in your roadmap to WinJS.Promise.queue() ?

**Comment by pke** [comment]
@spankyj  I think this code will break if any of the operations runs into an error condition?

```
WinJS.Promise.sequence = function (operations) {
    return operations.reduce(function (p, op) {
        return p.then(op);
    }, WinJS.Promise.as());
};
```

**Comment by jayrenn** [comment]
@CKGrafico I think a better approach could be to eventually adopt built-in promises. This would allow users to specify their own promise library with custom extensions. We may consider this work in the future.
