### ISSUE TITLE
WinJS 4.4.1 on NuGet

### ISSUE THREAD

**Issue by mallocation** [winjs/winjs#1656]
I noticed the latest release of 4.4.1 is available here, but is not listed on NuGet. Could you please upload 4.4.1 to NuGet?

**Comment by diegosa06** [comment]
Actually is not mention anywhere else besides here, not good at all. Can something be done. Not even  on main winjs site.

**Comment by rogersachan** [comment]
@mallocation @diegosa06 This is fixed as of 4.4.3
