### ISSUE TITLE
Can't use Sliders inside ListView with touchscreen (insider preview only)

### ISSUE THREAD

**Issue by VictorOdukoya** [winjs/winjs#1661]
Hello, I found another listView bug which I already posted on the MSDN forum and it has already been report. Basically, when you create a listview and put a slider inside an item, you won't be able use the slider. the slider will be highlighted but it won't move. Here is my [forum post](https://social.msdn.microsoft.com/Forums/windowsapps/en-US/1effd980-0aa0-4db6-b245-6dc6bd948016/uwpwinjsinsider-bug-sliders-are-not-working-inside-a-listview?forum=wpdevelop)

and here is a sample: https://1drv.ms/u/s!ArNSvnSslEHXgoYd_kXzOX3npfEDZg

Also, because of this [issue ](https://github.com/winjs/winjs/issues/1654) I may have already found a fix, but I'm not sure if it will cause any other bugs since I only found the "fix" by trial and error and not really understanding what was going on. I saw the solution here https://github.com/winjs/winjs/commit/a48a12e33e08fccdea7879af877b2cc3a7cb8ec3 and tried to to set the PointerDown event from `modeHandler("PointerDown"),` to `modeHandler("PointerDown", true),` and it seemed like it worked. I can now use the sliders in the insider preview. Can somebody please look into this? Thank you.

edit: ok now that I changed the pointerdown event I cannot invoke any items anymore, so that didn't work.

**Comment by AmazingJaze** [comment]
Hi VictorOdukoya, can you try adding the class name "win-interactive" to the root element of the slider. Its been a while but I believe that is the recommended way to address this scenario. 

Search for the section of [this page](https://msdn.microsoft.com/en-us/library/windows/apps/hh700705.aspx) that describes using "win-interactive"  with ListView for more details.

**Comment by VictorOdukoya** [comment]
It worked! Thank you! I remember win-interactive, I've used it before, but I kind of forgot about  it because it also worked when I didn't use it. So I just never used it again. Thank you
