### ISSUE TITLE
WinJS Grouped ListView Failure on Touch Events

### ISSUE THREAD

**Issue by gkoehler** [winjs/winjs#1694]
The grouped ListView loses binding on touch-based input on Windows 1803 and above. I created a minimal example here: https://github.com/gkoehler/WinJS-binding-failure-example

Steps to Recreate:
1. Launch sample on a touch-based machine
2. Scroll around and touch some tiles (make sure you use touch input -- the problem doesn't manifest using a mouse)
3. Observe the timestamp at the bottom update with every tile touch
4. Expected result: the timestamp always updates, no matter how much you scroll around

Actual result: at some point, the timestamp stops updating and won't register any more tile touches

Platforms Affected: Windows 1803 and above, on HP tablet and Microsoft Surface Pro

Platforms Not Affected: Windows 1703, on HP tablet and Microsoft Surface Pro

**Comment by llongley** [comment]
Fixed in v4.4.5.
