### ISSUE TITLE
The fragments loader needs to go through the Xhr code path (vs iframes) for Cordova iOS/Android apps

### ISSUE THREAD

**Issue by banguero** [winjs/winjs#209]
The fragmentloader.js currently supports two techniques:

``` javascript
if (global.document && document.implementation.createHTMLDocument && document.location.protocol !== "file:") {
        WinJS.Namespace.define("WinJS.UI.Fragments", {
            _populateDocument: populateDocumentXHR,
            _cleanupDocument: cleanupDocumentXHR
        });
    }
    else {
        WinJS.Namespace.define("WinJS.UI.Fragments", {
            _populateDocument: populateDocumentIFrame,
            _cleanupDocument: cleanupDocumentIFrame
        });
    }
```

The iframe path is currently mainly use for local pages (file://) in IE where doing an XHR could would generate a security error (the iframe technique however does not work in any other browser). Cordova apps (iOS/Android) also use the file:// protocol, and that iframe technique does not work there. We verified the XHR technique works in those cases. 

We need to figure out what is the best way to go through the XHR path in the Cordova case, without regressing the IE local pages (file://) iframe scenario.

**Comment by jayrenn** [comment]
Thanks for the discussion. See my comments on this other thread: https://github.com/winjs/winjs/issues/424#issuecomment-111625834
