### ISSUE TITLE
ListView w/ Binding.Template unhandled exception and no rendering in Chrome Packaged App

### ISSUE THREAD

**Issue by david-risney** [winjs/winjs#235]
The ListView fails with an unhandled exception when used in a Chrome Packaged App and does not seem to render at all. To try and narrow the repro I used just the first ListView sample from http://try.buildwinjs.com in a Chrome Packaged App and I see the issue. The unhandled exception in the console is:

    Refused to evaluate a string as JavaScript because 'unsafe-eval' is not an allowed source of script in the following Content Security Policy directive: "default-src 'self' chrome-extension-resource:". Note that 'script-src' was not explicitly set, so 'default-src' is used as a fallback.
    base.min.js:6

It sounds like WinJS is using eval or new Function or some other function that turns a string into script, which Chrome Packaged Apps disallow. According to their docs [the restriction on eval cannot be loosened](https://developer.chrome.com/apps/contentSecurityPolicy). If that's the issue then I expect (though I haven't tried it) this will also be a problem in [Firefox OS apps which have the same eval restriction](https://wiki.mozilla.org/Apps/Security#Default_CSP_policy).

Anyway not totally sure you intend to support WinJS in Chrome Packaged Apps, but I thought I'd describe this issue here just in case since I ran into it porting my app to a Chrome Packaged App.

**Comment by ziaukhan** [comment]
Has this been solved in WinJS 4?

**Comment by jayrenn** [comment]
We have written our controls for the web and Windows 10 default CSP policy, which allows safe-eval. I am aware there are workarounds for Chrome extensions. You might check for Chrome Packaged App CSP workarounds.
