### ISSUE TITLE
Add SASS Support

### ISSUE THREAD

**Issue by srsgores** [winjs/winjs#246]
I would like to see a SASS version of winjs styles.  Using LESS is great for cutting-edge projects that don't need to worry about browser support (better now due to the ``&:extends()`` directive), but developers who still want to maintain legacy support might benefit from libraries like compass or burbon.  LESS does not have this, aside from LESSHat, which is known to be buggy and is inconsistent with vendor prefixes.

I would be willing to contribute a better SASS version of the WinJS styles, using proper variables and the ``@extends`` directive, along with either configurable browser support with [autoprefixer](https://github.com/ai/autoprefixer) and tools like [gulp autoprefixer](https://github.com/Metrime/gulp-autoprefixer) or compass or burbon.  Also, I would user proper nesting, rather than what you guys are doing like bootstrap, which makes code far less readable:

For example:

Instead of [this](https://github.com/winjs/winjs/blob/master/src/less/styles-pivot.less#L105):

```
.win-pivot-item {
    position: absolute;
    top: 28px;
    bottom: 0;
    width: 1%;
}

.win-pivot-column4 .win-pivot-item {
    -ms-grid-column: 4;
}

.win-pivot-item .win-pivot-item-content {
    height: 100%;
    overflow-y: auto;
    -ms-overflow-style: -ms-autohiding-scrollbar;
    width: ~"calc(100% - 28px)";
    padding: 0px 19px;
}
```

How about:

```
%pivot-item {
    position: absolute;
    top: 2em;
    bottom: 0;
    width: 1%;
   &.win-pivot-item-content {
   height: 100%;
    overflow-y: auto;
    -ms-overflow-style: -ms-autohiding-scrollbar; // needs mixin
    width: ~"calc(100% - 2em)";
    padding: 0 2em;
   }
}

// Should use a generated mixin here
.win-pivot-column4 %pivot-item {
    -ms-grid-column: 4; // needs mixin
}
```

**Comment by jayrenn** [comment]
@srsgores If you're still into this, re-open the issue and we can discuss further. Or you can submit a pull request directly!
