### ISSUE TITLE
Pivot: Clicking headers too fast causes unexpected navigations

### ISSUE THREAD

**Issue by jseanxu** [winjs/winjs#255]
Steps:
Click 2 headers back-to-back

Expected:
2 navigations

Actual:
3 navigations

Note: this only happens on IE since, the no-snap fallback implementation for the header track does not have this issue.

**Comment by fretman92** [comment]
I got a similar bug while clicking the back button fast and repeatedly (in a subview of 3rd level) 
On a IE desktop, it causes a trigger in a random appbar command (which is at the bottom while the back button is upper left), on a tablet, it crashes the application (history.current is undefined at one point). 
Does your fix contain something more generic than for the Pivot Item?
