### ISSUE TITLE
How to create a filteredList with only 10 items (out of hundreds)

### ISSUE THREAD

**Issue by pke** [winjs/winjs#313]
I know I can use Binding.List.createFiltered to create size limited list. The problem I have is that I need to save the counter of the already included items somewhere and need to reset it, when the base list changes, correct?

```
var count = 0;
limitedList = source.createFiltered(function(item) {
  if (count++ < 10) return item;
});
```

So when the source list changes, my filter function will be called again but count is not reset.

btw: Do you guys know about the Java list transformation library http://www.glazedlists.com/. I used to work with it in my Eclipse days and it was a blast. You could chain all kind of filtered lists together and they all updated live when one of the filter criteria changed. WinJS.Binding too often feels a bit limited still.

**Comment by jayrenn** [comment]
Thank you for your feedback. We are not looking to pursue this feature in the future.
