### ISSUE TITLE
WinJS Repeater not rendering in dynamically loaded template

### ISSUE THREAD

**Issue by AndrewGaspar** [winjs/winjs#32]
This is on Windows 8.1 Store app specifically.

I have an HTML file, say /templates/tableSection.html:

``` html
<!DOCTYPE html>
<html>
  <head>
    <title>Table Section</title>
  </head>
  <body>
    <div data-win-control="WinJS.UI.HubSection" data-win-options="{ header: 'Important Table' }" >
      <h3 data-win-bind="textContent: title"></h3>
      <table>
        <tbody data-win-control="WinJS.UI.Repeater" data-win-bind="winControl.data: listOfThings">
          <tr>
            <td data-win-bind="innerText: name"></td>
            <td data-win-bind="innerText: value"></td>
          </tr>
        </tbody>
      </table>
    </div>
  </body>
</html>
```

Using winControl.data to bind the item list is in line with the example located here: http://code.msdn.microsoft.com/windowsapps/HTML-Repeater-control-da22d278/sourcecode?fileId=86617&pathId=1418094029

I have js code that loads and renders this template similar to:

``` js
var tableTemplate = new WinJS.Binding.Template(null, { href: "/templates/tableSection.html", extractChild: true });

tableTemplate.render({
  title: "Boss Table",
  listOfThings: new WinJS.Binding.List([{ name: "Dave", value: 2 }, { name: "Erika", value: 11 }])
}).then(function(sectionDiv) {
  hub.sections.push(sectionDiv.winControl);
}).done();
```

The h3 element will properly bind to the title value, but the Repeater will not render at all. Even looking at the element using the dom query selector for the WinJS.UI.Repeater shows that it does not even have a winControl attribute. Do I have a code bug, or is there a bug in the Repeater or Template controls?

**Comment by pke** [comment]
@spankyj Using this code the `obj` is not used for binding. Is this bug still open?
