### ISSUE TITLE
Wiki for WinJS tips&tricks

### ISSUE THREAD

**Issue by pke** [winjs/winjs#337]
It would be nice to host a page here in the wiki with tips&tricks and code snippets, related to WinJS/HTML Windows Apps.
One things that often gets asked is how to find out if the WinJS App was built for release or debug/dev mode and on which git branch.
I combined some tips from all over the net in a MSBuild .targets file that everybody can easily include in her WinJS/HTML app projects.
https://gist.github.com/pke/e1d2c5061d535be48d75

Is there any place such things could be contributed to, except stackoverflow? ;)

**Comment by jayrenn** [comment]
Great idea. We have now opened our wiki for contributions. Feel free to contribute!
