### ISSUE TITLE
Navbar not hidden when navigating?

### ISSUE THREAD

**Issue by pke** [winjs/winjs#338]
Is it true, that when a href in a NavCommand is followed, the navbar itself stays open even when its not sticky?
It feels like an additional burden on the programmer to close it using a "navigating" listener.
Same goes for the app bar. Executed commands will not close the appbar, but I guess thats ok in regard to commands that show flyouts or menus. But normal commands, shouldn't the hide the appbar after execution?

**Comment by mkjunior19** [comment]
I've created a task to track this feature request: deliverable 1683301.
