### ISSUE TITLE
Re-enable listView tests and make them pass for IE11

### ISSUE THREAD

**Issue by jseanxu** [winjs/winjs#342]
Splitting #134 into smaller tasks.

* Win8.1/IE11
    * EditsDonotCreateAllContainersWithGroups  (fails in saucelabs only - sometimes) - disabled
    * ExpandItemsContainerForReflowNeeded - disabled
    * ExpandItemsContainerForReflowNotNeeded - disabled
    * DeleteDoesNotLoseFocusRectangle - disabled
    * testDeleteAllAndInsertInGridLayout_VirtualDataSource_Async (fails in saucelabs only) - disabled

**Comment by mikewjackson** [comment]
Won't Fix
