### ISSUE TITLE
Proposal: WinJS.Utilities.indexOf(element)

### ISSUE THREAD

**Issue by pke** [winjs/winjs#353]
```
indexOf = function(element) {
  var i = 0;
  while ((element = element.previousElementSibling)) {
    ++i;
  }
  return i;
};
```
I use that quite often, would make a good fit in WinJS.Utilities, what you think?

**Comment by jayrenn** [comment]
Due to the prevalence of this method, we are not going to add it to the Utilities namespace.

Try this:
```js
lib.indexOf(parent.children, element);
```
Where `lib` can be your library of choice.

**Comment by pke** [comment]
>prevalence
Will WinJS.Utilities.data be removed for the same reason in the future then? After all, we don't even need a library to access DOM data attributes

    element.dataset

will do.
