### ISSUE TITLE
ListViewIntegration unit tests failures in WWAHost

### ISSUE THREAD

**Issue by banguero** [winjs/winjs#373]
-Open \projects\WWAUnitTestsApp\WWAUnitTestsApp.jsproj in Visual Studio
-Select ListViewIntegration 
-Press the Start button

-Expected:
All tests pass

-Actual:
Failures:
WinJSTests.ListViewDragDropTest: UncontiguousSelectionReorderListLayoutBindingList_ltr 
WinJSTests.ListViewDragDropTest: UncontiguousSelectionReorderGridLayoutBindingList_ltr 
WinJSTests.ListViewDragDropTest: UncontiguousSelectionReorderListLayoutBindingList_rtl 
WinJSTests.ListViewDragDropTest: UncontiguousSelectionReorderGridLayoutBindingList_rtl
WinJSTests.ListViewDragDropTest: UncontiguousSelectionReorderListLayoutVDS_ltr
WinJSTests.ListViewDragDropTest: UncontiguousSelectionReorderGridLayoutVDS_ltr
WinJSTests.ListViewDragDropTest: UncontiguousSelectionReorderListLayoutVDS_rtl
WinJSTests.ListViewDragDropTest: UncontiguousSelectionReorderGridLayoutVDS_rtl

**Comment by mikewjackson** [comment]
Won't Fix - test time out under the debugger
