### ISSUE TITLE
Try WinJS: Searchbox Sample snippet is not displaying São Paulo correctly

### ISSUE THREAD

**Issue by banguero** [winjs/winjs#420]
![image](https://cloud.githubusercontent.com/assets/1873511/3629397/feee02ea-0e9f-11e4-87ee-f6ae22fc5a7a.png)

**Comment by xirzec** [comment]
The question mark is actually in the data - probably because the powershell script that bundles the sample sources is run from a command prompt that doesn't support unicode characters.

**Comment by rigdern** [comment]
São Paulo was removed from the sample.
