### ISSUE TITLE
Make official fragment loader extensibility point

### ISSUE THREAD

**Issue by xirzec** [winjs/winjs#424]
Per this comment: https://github.com/winjs/winjs/issues/209#issuecomment-45960181

We should consider having `WinJS.UI.Fragments._getFragmentContents` become `WinJS.UI.Fragments.getFragmentContents` and be officially supported as an alternative loading mechanism for fragment contents.

**Comment by jayrenn** [comment]
At the moment, we do not want to take on additional support for exposing this method.
