### ISSUE TITLE
ListView: Scroller height isn't always recalculated when sizing larger

### ISSUE THREAD

**Issue by spankyj** [winjs/winjs#516]
1) Launch Music App
2) Go to Explore page
3) go to 'top albums'
4) make application small enough to only see one column
5) scroll to ~125th album
6) resize app full screen

[Expected]
I see items

[Actual]
I don't see any items, and as I scroll up & down, I have ~1 screen full of empty dead space at the bottom

![image](https://cloud.githubusercontent.com/assets/4666791/3897889/a96da3dc-2265-11e4-8235-2dae1c25b6b7.png)

**Comment by xirzec** [comment]
Closing for now unless app author gives feedback.
