### ISSUE TITLE
Make WinJS.UI.DatePicker available in Windows Phone

### ISSUE THREAD

**Issue by sebagomez** [winjs/winjs#534]
There's no easy way to pick a Date or Time on Windows Phone. Something like the one we have for Windows Store apps is good enough. Also, I believe there are a couple of full screen controls on xaml that would also work.
I don't know why aren't they available for Windows Phone, I would volunteer myself for doing them if that's ok with the team.
Attached are a couple of screenshots of the controls used by the calendar app.
![wp_ss_20140816_0002](https://cloud.githubusercontent.com/assets/1637983/3943654/7d86031e-25bb-11e4-9b82-139da5bd88d4.jpg)
![wp_ss_20140816_0001](https://cloud.githubusercontent.com/assets/1637983/3943655/7d8d704a-25bb-11e4-930a-38e23615b2c2.jpg)

**Comment by pke** [comment]
The WinJS platform really needs those. :+1:

**Comment by jayrenn** [comment]
This is an old design from Windows Phone 8.1. The time picker has since been redesigned for Windows 10. We are looking to update the date and time pickers to the new designs in the near future.
