### ISSUE TITLE
Adding WinJs to Web Page

### ISSUE THREAD

**Issue by aminubakori** [winjs/winjs#57]
Hey Guys, i have been trying since morning to add the WinJs library on my web pages, styling is ok, but javascript is not working and don't know why. Any idea?

**Comment by jeevanthespark** [comment]
i have tried the same as mentioned in your above post. but couldnt get the desired result...
first i have downloaded the winJS 4.2 rar file from winJS official website...
i extracted it to winjs folder and added that folder to my website directory...
My code is as follows

<html>
    <head>
        <title>WinJS Website</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        
         
        <link href="/winjs/css/ui-light.css" rel="stylesheet" />
        <script src="/winjs/js/base.js"></script>
        <script src="/winjs/js/ui.js"></script>
        <script>
            WinJS.UI.processAll();
        </script>
    </head>
    <body>
        <div>Rating</div>
        <div id="myRating" data-win-control="WinJS.UI.Rating"></div>
    </body>
</html>

Why is it not working... PLZ help me...

**Comment by jseanxu** [comment]
Try putting the `<script>` block after the line where you declare the rating control.

**Comment by jeevanthespark** [comment]
I will try and let u know bro...

**Comment by jeevanthespark** [comment]
nothing happened... :( Can u kindly provide me the details of how to add WinJS to a website... do i need to install nodejs?? or is there any other installation procedures or simply link the downloaded WinJS files??? Please give me a detailed procedure friends... Thanks in advance...

**Comment by jeevanthespark** [comment]
i am not using any other versions of javascript such as angularJS... am just adding WinJS to the website... it is just a html page with WinJS...

**Comment by jseanxu** [comment]
You only need base.js/ui.js and ui-dark.css or ui-light.css. Make sure your reference paths are correct and that `WinJS.UI.processAll` is called after you have declared the WinJS controls.
