### ISSUE TITLE
Request: enable Browserify style module exports

### ISSUE THREAD

**Issue by joewood** [winjs/winjs#571]
Could the WinJS.js file use `module.exports`, in line with CommonJS conventions?  Plus use the existing `require` if it's already defined, for import dependencies?
- [Browserify](http://browserify.org)
- [Browserify and UMD](http://dontkry.com/posts/code/browserify-and-the-universal-module-definition.html)

**Comment by gautamsi** [comment]
I am working on a partial support for commonjs module. check this out here - https://github.com/gautamsi/winjs/tree/_gautamsi_TypScriptPromises

I had preference to use WinJS.Promise for my other project. could not test my code working in node. Applied simple Typescript transform on core modules and got some of the namespace working. 

WinJS.Class                 WinJS.ErrorFromName         WinJS.Namespace             WinJS.Promise
WinJS.Utilities

This fork still contains lot of other code WinJS repo has. Once I get into point where I have most of functionality (except UI and WinRT specific) I may move it to its own repo.
