### ISSUE TITLE
Add SettingsFlyout to trysite

### ISSUE THREAD

**Issue by AmazingJaze** [winjs/winjs#575]
We should consider adding a Settings Flyout example to the trysite. We can't integrate with the settings charm without WinRT, but we can still wire up showing the SettingsFlyout through a simple on screen `<button>`

Here is an example of simple markup and how it looks running in Chrome browser:
![settingsmarkup](https://cloud.githubusercontent.com/assets/6732159/4142240/ae00e8c0-33b6-11e4-8799-f9e1a682c121.png)
![settingsinchrome](https://cloud.githubusercontent.com/assets/6732159/4142245/b5b1e54c-33b6-11e4-933f-a4c55aec08fa.png)

**Comment by mkjunior19** [comment]
Since we're planning to deprecate this control, we should not add them to the Try site.
