### ISSUE TITLE
Interaction between search to type and Overlays

### ISSUE THREAD

**Issue by rigdern** [winjs/winjs#579]
How should the SearchBox's search to type feature interact with light dismissables/Overlays (e.g. AppBar, Flyout, SettingsFlyout)?

You can see what happens today: http://1drv.ms/1nz90G2

1. Download the linked file and open typeToSearch/index.html in your browser.
2. Click the "Open Flyout" button
3. Type the letter "a"

Today's behavior: The Flyout dismisses and the SearchBox receives the typed character.

Alternative behavior: The Flyout receives the typed character because SearchBox's type to search behavior is automatically disabled while a light dismissable is showing.

Which is the desired behavior?

**Comment by xirzec** [comment]
Tracked by LightDismiss work.
