### ISSUE TITLE
ListView: Should we change our uniform layouts to only use flexbox?

### ISSUE THREAD

**Issue by TheWrathOfConst** [winjs/winjs#585]
Right now the ListView uses CSS3 grid where available, and falls back to flexbox if grid isn't available. The flexbox layouts look and behave the same, and so far the performance measurements we've taken show no major changes when a ListView using -ms-grid is compared to another using flex. 

We could simplify a good chunk of our layout code if we just used display:flex in our layouts (excluding multisize layout), instead of keeping the fallback approach we have now.

**Comment by xirzec** [comment]
Moved to icebox
