### ISSUE TITLE
ListView flickers occassionaly when overbounce pan on iOS

### ISSUE THREAD

**Issue by pag3** [winjs/winjs#587]
Occasionally I see a flicker where the first item appears to get re-painted twice if I overpan a ListView in Safari on iOS 7.

Here is a relatively consistent repro:
1. WinJS stocks app
2. Pan to top of watch list
3. Drag down to overpan once more
Observe: flicker
4. Now pan down to the bottom of the watch list
5. Drag up once more to overpan the bottom
Observe: flicker
6. Go back to step 2 and the cycle continues

**Comment by xirzec** [comment]
@pag3 Are you still seeing this? Does it happen on the try site?

**Comment by dougestey** [comment]
@xirzec I just reproduced this bug on the try site on iOS 8 and can confirm that this is still happening. Please reopen this issue.

**Comment by mikewjackson** [comment]
@alxlu  can you please confirm this still reproes and if so, assign back to dev?

**Comment by alxlu** [comment]
The ListView on the try site seems to have another problem on iOS8:
![WinJS ListView on iOS8](http://alxlu.github.io/static/ListView.gif)
