### ISSUE TITLE
WinJS.Utilities.IsPhone

### ISSUE THREAD

**Issue by lahloumehdi** [winjs/winjs#601]
Hello

When I use WinJS 3.0 in a WP8.1 project, the property isPhone in WinJS.Utilities is always false.

Mehdi.

**Comment by pke** [comment]
What do I do if I want to use the Pivot on the phone and the Hub on the other devices?

**Comment by xirzec** [comment]
@pke - You could detect on window width instead of platform. It turns out if someone resizes your Windows app to be 320px wide, you probably have the same layout problems that phone does and want a similar UX, much like responsive websites.

**Comment by pke** [comment]
I needed to know, cause on Windows Phone I would use the Pivot control for data display and on other devices the Hub control. Or can I use the Hub on the phone too? see #1002

**Comment by xirzec** [comment]
As of 4.0, Hub is expected to work on Phone, though it might not have the exact UX you are looking for.
