### ISSUE TITLE
Hub>Add Semantic Zoom demo fails in Chrome 36 and later

### ISSUE THREAD

**Issue by phistuck** [winjs/winjs#604]
Feature: Hub
Environment: Mozilla/5.0 (Windows NT 6.1; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/37.0.2062.120 Safari/537.36
(Also in Chrome 36.0.1985.143)
Source: http://try.buildwinjs.com

The Hub>Add Semantic Zoom demo does not work right in Chrome. Click on Output to see the demo, wait for it to load and click on the minus button at the right bottom corner. Instead of nice tiles, there is a narrow and high rectangle that reads "Fo" (or "Eo").

Internet Explorer shows the tiles just fine.

**Comment by xirzec** [comment]
Seems to be fixed on latest Chrome.
