### ISSUE TITLE
Semantic Zoom Pinch Gestures Not Working on IE 11 (Metro) / Win 8

### ISSUE THREAD

**Issue by CalvinDale** [winjs/winjs#607]
The Semantic Zoom [demo](http://try.buildwinjs.com/#semanticzoom) is not responding to pinch gestures on IE Metro version 11.0.9600.17278.  It is however working on IE 11 Desktop.  Currently on our kitchen Lenovo *ideacentre* all-in-one.  But I've also experience this on my office desktop workstation and Surface Pro machines.

**Comment by xirzec** [comment]
Closing this bug as the version of IE affected by it is deprecated in Windows 10. All hail Spartan.
