### ISSUE TITLE
Running unit tests in wwa/WinRT environment not documented

### ISSUE THREAD

**Issue by harriha** [winjs/winjs#61]
Part of the code is targeted only to wwa environment where WinRT APIs are available, meaning Windows Store apps. Also, some of the tests target this environment specifically. However, the current "How to run tests" (https://github.com/winjs/winjs/wiki/How-to-run-Tests) document doesn't take this into account, instructing only how to run tests in a standard browser.

Based on the grunt scripts, it looks like there might even be a way to run the tests in wwa environment from command line, but it's not clear how to setup the dev environment to support this.

**Comment by staxmanade** [comment]
Hello,

I am curious as how this was resolved. Are there examples or guidance on how to get tests up and running? There is some good insights here and discussion, but I'm not sure why @spankyj closed this issue.

Thoughts?

**Comment by TheWrathOfConst** [comment]
Let's document how to run unit tests in WWAs

**Comment by TheWrathOfConst** [comment]
Added a note on how to run tests in WWAs to the wiki: https://github.com/winjs/winjs/wiki/How-to-run-Tests :
* Open WWAUnitTestsApp.sln in winjs/projects/WWAUnitTestsApp/ with Visual Studio 2013
* Start debugging via F5
