### ISSUE TITLE
Feature request: Make tests able to run while browser is set to stop on all exceptions

### ISSUE THREAD

**Issue by TheWrathOfConst** [winjs/winjs#621]
The unit test framework we currently use throws exceptions under normal use when you set the browser to stop on any thrown error. It's always from this code:

```javascript
function sourceFromStacktrace( offset ) {
	try {
		throw new Error();
	} catch ( e ) {
		return extractStacktrace( e, offset );
	}
}
```
I've had a number of bugs that give me great stack traces if I break on all exceptions. I'm almost always brought right to the faulting line of code. The same bugs give me really useless stack traces if I'm set to break only on uncaught exceptions. By the time that finally rolls around, the stack trace has been mucked up by async stuff, Promise callstacks, etc.. The information you end up getting is questionable and involves a lot of detective work just to get what you originally wanted to know. 

It'd be really nice if I could just run the unit tests with my browser set to break on all exceptions and not get bombarded by unexceptional exceptions.

**Comment by jayrenn** [comment]
This is an issue for QUnit to tackle.
