### ISSUE TITLE
Inconsistency with documentation for WinJS.UI.ListView?

### ISSUE THREAD

**Issue by omnoms** [winjs/winjs#639]
Still following this guide to add a drag-n-drop feature between two listviews; 
http://msdn.microsoft.com/sv-se/library/windows/apps/bg182879.aspx

Now.. the documented two logical events I could listen to when a user actually releases an item ontop of a listview are onitemdragdrop and onitemdragend. Binding a simple function to log the eventobject passed to the function results in the handler never having been called when releasing an item on it.

WinJS Doc: http://msdn.microsoft.com/sv-se/library/windows/apps/xaml/br211837.aspx

Now in the guide, it mentions that I need to handle the dragover event and do preventDefault. The documentation doesn't even mention that "dragover" or "ondragover" is an option. But it is. I can assign a handler to it and for every move over the listivew it spams the log with the dragged item event info.

However the "drop" event they mention I can't assign with addEventListener (due to previous issues with accessing the winControl object in the hub's ready-statement) and "ondrop"'s handler isn't being called when declared in the data-win-options for the listView...

So ... how do I do this?

**Comment by pgills** [comment]
Yes, unfortunately you will have to do some fine tuning to have the exact same styling across phone and pc, however a bulk of the styling is controlled with the `win-selectionstylefilled`. However in our next release we are working to converge the selection styling across PC and Phone in the ListView.

I'm going to close this issue, if you need help styling the checkbox please open another issue and we will help with that.
