### ISSUE TITLE
NavBarCommand icons are too large

### ISSUE THREAD

**Issue by rigdern** [winjs/winjs#646]
In the NavBarCommand, the div containing the icon is 24x24 but the icon is larger. I changed the div's background color to red and took a screenshot:

![navbarcommand](https://cloud.githubusercontent.com/assets/199935/4619552/4e85620c-5316-11e4-9f49-07560ecc70e3.png)

As you can see, the icon hangs outside of the div.

**Comment by xirzec** [comment]
We should do this when we update the font to the new glyphs.

**Comment by phosphoer** [comment]
This was fixed in fc5c89e99d8f4e06bd1a2bc692a130ca9cfbaea0
