### ISSUE TITLE
Icons: Would it be possible to add icons only useful in webapps as well?

### ISSUE THREAD

**Issue by borgdylan** [winjs/winjs#657]
I was looking at what symbols are available (as described by the pdf file beside symbols.ttf) and could not find suitable icons for login/logout. Also there is a symbol for retweet which has not been assigned an AppBarIcon enum value. Would it be possible to add these?

**Comment by jayrenn** [comment]
Check out [this page](https://msdn.microsoft.com/en-us/library/windows/apps/hh770557.aspx) and see if the icons listed satisfy your needs. Otherwise, reopen the issue and we can re-evaluate then.
