### ISSUE TITLE
Create a version of WinJS based on web components

### ISSUE THREAD

**Issue by domenic** [winjs/winjs#658]
I think it's time.

WinJS is an absolutely perfect match for web components technologies; much of the framework is based on duplicating that kind of functionality. (Of course, you had to, because WinJS was created way before web components were ready for use.)

For example, the `<div data-win-control="">` syntax is crying out for custom tag names. The `.winControl` property, and all the interfaces it hides behind, could be easily integrated with custom element prototypes. The fact that it all gets initialized by the browser automatically would avoid the need for `WinJS.UI.processAll()` and its dynamic-markup-insertion friends. And of course, the div-soup and prefixed-class-names-galore that gets generated by complex controls like ListView would be beautifully hidden inside a shadow DOM and sped up by `<template>`.

As a small taste, consider converting

```html
<button data-win-control="WinJS.UI.AppBarCommand" data-win-options="{id:'cmdAdd',label:'Add',icon:'add',section:'primary',tooltip:'Add item'}"></button>
```

into

```html
<winjs-appbarcommand id="cmdAdd" icon="add" section="primary" tooltip="Add item">Add</winjs-appbar-command>
```

The specifics of how to do this right would be tricky! It would be a whole project. But it would be so, so worth it. I've never seen a widget toolkit that is a better fit for web components than WinJS.

**Comment by gleborgne** [comment]
Would love tout sée this happening too

**Comment by RichiCoder1** [comment]
:+1:

**Comment by SteveALee** [comment]
+1 to this. It clearly seems the next logical step for WinJS.

**Comment by gleborgne** [comment]
For those interested, we just run an extension for that in WinJS Contrib :
http://mcnextpost.com/2015/04/26/using-winjs-controls-as-webcomponents/

**Comment by damnhandy** [comment]
+1 for W3C web components, although I wouldn't be upset with Polymer either. Bonus points if you get the Microsoft Edge team to start supporting the specs natively in the browser. I'd much rather see Edge have native support for the Web Component specs rather than relying on polyfils or resort to Chrome.

**Comment by RichiCoder1** [comment]
Having researched this, I would actually sympathize with the team if they went polymer or held of on this issue wholesale until web components was settled. [There's a reason Edge doesn't have web components support.](https://hacks.mozilla.org/2015/06/the-state-of-web-components/)

**Comment by jayrenn** [comment]
Thanks everyone for the discussion! We will defer until web components have settled.

**Comment by gaurav21r** [comment]
@jayrenn @RichiCoder1 If we read the comments on the article, one would agree there is a lot of stuff to object. Eg: The case the author is making against HTML Imports in favour of ES6 modules is being heavily challenged!

I think **WinJS** should take an independent stand on this. IBM and the Dojo Community has created [delite](https://github.com/ibm-js/delite) as a Web Component Library minus a lot of features from the spec (Like Shadow DOM, HTML Imports etc). Can WinJS take an incremental approach to this?

I know Edge is going to support Web Components really soon! https://blogs.windows.com/msedgedev/2015/07/15/microsoft-edge-and-web-components/

I think you should re open this for a discusison. Why not time the release of a WebComponetized version of WinJS with the release of features in Edge?

**Comment by SaschaNaz** [comment]
We already have React/Angular/Knockout-WinJS, so why not Polymer-WinJS, if we are just worrying about any potential spec change? A WinJS version that works well with latest version of Polymer will make devs happy until the spec completes.

**Comment by gaurav21r** [comment]
@jayrenn @RichiCoder1 Any updates please?

**Comment by Guadzilah** [comment]
Visual studio has been extended

**Comment by SaschaNaz** [comment]
@Guadzilah I've seen you also in #1542, are you a human or a bot?

**Comment by Guadzilah** [comment]
I'm a human not a robot self explanatory

**Comment by toddpi314** [comment]
The "Visual studio has been extended" has shown up on multiple issues so far. 99.999% likely a bot.

**Comment by toddpi314** [comment]
+1 since WebKit added support in Oct '15. http://jonrimmer.github.io/are-we-componentized-yet/

However, I am not in support of a 'conversion' in the baseline, since there are a variety of interesting ways people utilize existing data-attributes (extending WinJS controls, query selection, etc). If there was a webcomponent build, it would need to be separate, and would open up what I would guess would be a huge refactor based on the shadow-dom.

Does anyone have an extra million dollars laying around to fund this? ;)

**Comment by SaschaNaz** [comment]
Shadow DOM will be good but I think we can first support `document.registerElement` and then cover others incrementally as @gaurav21r said.

**Comment by gaurav21r** [comment]
Webcomponents v1 is out and there has almost **TOTAL** browser adoption. Lets start this! @domenic @jayrenn @RichiCoder1

**Comment by SaschaNaz** [comment]
The WinJS development is stopped :( We are still using some WinJS components so I will be happy to see that happen, anyway.
