### ISSUE TITLE
Change the order of elements in WinJS.UI.DatePicker?

### ISSUE THREAD

**Issue by omnoms** [winjs/winjs#666]
How do I change the order of the controls both how they're rendered and shown? (since tabbing between fields would tab from one field to the next in the order they're rendered in the DOM?)

I came across this: http://answers.flyppdevportal.com/categories/metro/html5jscript.aspx?ID=fe067bd9-0b8d-4940-bbd8-f34bcf2ac10f

which mentions the same kind of issue that I have. I can forcibly set a new -ms-grid display on the date-picker parent and then set -ms-grid-column to reorder them, however, they then no-longer respond properly to the width-CSS-property and don't fill out the full width of the space that is given to the fractions and their parent grid.

The documentation at http://msdn.microsoft.com/sv-se/library/br211681.aspx mentions the following;

"You can also customize the DatePicker by determining the order of the day/month/year elements. Use the win-order CSS class to specify the order. For example, to specify that the year control should appear first, you would specify win-order0."

I tried to do the following;

```HTML
                <div class="win-datepicker" data-win-control="WinJS.UI.DatePicker" style="width: 80%">
                    <div class="win-datepicker-year win-order0"></div>
                    <div class="win-datepicker-month win-order1"></div>
                    <div class="win-datepicker-date win-order2"></div>
                </div>
```

But that did nothing. Nor adding the class win-order0 directly onto the datepicker control's div with no child-divs.

**Comment by jayrenn** [comment]
The solution @pgills proposed is sufficient for the time being. We are looking into a better long term solution.
