### ISSUE TITLE
NavBarCommand icon repeats when size smaller than 40px x 40px

### ISSUE THREAD

**Issue by anishchandwani** [winjs/winjs#68]
When WinJS.UI.NavBarCommand.icon is set to a source image smaller than the size of the containing div, the image repeats to fill the div.

Setting the backgroundRepeat and backgroundSize properties fixes the issue:
    this._imageSpan.style.backgroundRepeat = "no-repeat";
    this._imageSpan.style.backgroundSize = "cover";

**Comment by jayrenn** [comment]
@anishchandwani Thank you for your feedback! This is by design. 40x40 is the smallest we support.
