### ISSUE TITLE
Incrementally loading items in a ListView with asynchronous data source is impossible

### ISSUE THREAD

**Issue by lamuertepeluda** [winjs/winjs#690]
Hi there,

I know that the ['incremental' loading behavior](http://msdn.microsoft.com/en-us/library/windows/apps/br211835.aspx) for ListViews has been deprecated, however there is not much documentation around the web on how to work around this issue using a real paged service request!
(So, issue #1: **please** update the documentation).

When using loadingBehavior:'incremental', I get a nice warning on Visual Studio that tells me that this behavior is deprecated and that I should have a look at [this example here - scenario #2](https://code.msdn.microsoft.com/windowsapps/ListView-loading-behaviors-718a4673). However that sample is almost useless, since it is using a WinJS.Binding.List as data source, which wraps an array where new randomly generated item are pushed synchronously.

In a real life scenario, I'd get items from an asynchronous source, i.e. with promises/callbacks, for instance using a xhr request, pretty much like in the [Custom Data Source Example](https://code.msdn.microsoft.com/windowsapps/ListView-custom-data-4dcfb128/). 

Well, using this approach ends up in firing all data source requests one after the other, regardless whether the user has scrolled the list or not.

I think the ListView should provide some 'scrollend' event or some similar mechanism in order to allow to load the next page.

Platform: Universal App + Cordova 4.0 + WinJS 3.0.1

I appreciate very much the effort you're putting in this framework.
Thanks

**Comment by xirzec** [comment]
We now have a sample for showing progressive loading with custom footer:

http://try.buildwinjs.com/#listview

Scroll down to "Progressive Loading"

**Comment by sebagomez** [comment]
The sample noted here has now moved to http://winjs.azurewebsites.net/#listviewinteractions:progressiveloading

**Comment by pedritin** [comment]
Hi, I'm using sqlite db an I don't know how to make it stop when search is done. I mean, I'm limiting results by 10 items on the query but how to end if all results are already loaded.
