### ISSUE TITLE
Automatically generated AngularJS directives

### ISSUE THREAD

**Issue by ChristianWeyer** [winjs/winjs#696]
Wouldn't it be nice to have AngularJS directives automatically generated for WinJS?
Do you guys have any plans to provide a solution here?

Thanks.

**Comment by ChristianWeyer** [comment]
@xirzec Do you guys have any news on the ng integration story? Thx!

**Comment by xirzec** [comment]
@ChristianWeyer We're close to posting the revitalized version of this project, just going through some final updates and reviews on our side. It will live here if you want to watch it for updates: https://github.com/winjs/angular-winjs

**Comment by ChristianWeyer** [comment]
Very nice. Thx!

**Comment by jayrenn** [comment]
We have updated angular-winjs for WinJS 4.0. Please visit the [GitHub repo](https://github.com/winjs/angular-winjs) for more information.
