### ISSUE TITLE
Using FlipView with server side HTML code

### ISSUE THREAD

**Issue by blustemy** [winjs/winjs#699]
Hi,

I'd like to know how I can use the FlipView component without JSON and without the client side template. I'd like to use it like this by completely removing the client side bindings:

```html
<div class="flipView" data-win-control="WinJS.UI.FlipView">
    <div class="overlaidItemTemplate">
        <img class="image" src="image1.jpg" alt="Title 1" />
        <div class="overlay">
            <h2 class="ItemTitle">Title 1</h2>
        </div>
    </div>

    <div class="overlaidItemTemplate">
        <img class="image" src="image2.jpg" alt="Title 2" />
        <div class="overlay">
            <h2 class="ItemTitle">Title 2</h2>
        </div>
    </div>

    ...
</div>
```

The loop of items would be generated server side. Then for the JavaScript part just starting WinJS:

```javascript
WinJS.UI.processAll();
```

Thanks!

Frédéric Perrin

**Comment by jayrenn** [comment]
Thank you for your request! This is an interesting idea, but I think it is a fairly simple concept of which there are numerous examples. For instance, check out [Bootstrap Carousel](http://www.w3schools.com/bootstrap/bootstrap_carousel.asp).
