### ISSUE TITLE
Linux/Android 4.4: No tests are working

### ISSUE THREAD

**Issue by rigdern** [winjs/winjs#701]
Looks like this has been happening since: http://try.buildwinjs.com/?r=Automated%202014-11-04%2020:49:26%20UTC#status

![image](https://cloud.githubusercontent.com/assets/199935/4958444/da047060-66ae-11e4-850a-d814bcdd4888.png)

**Comment by xirzec** [comment]
We're still having other run problems, but it seems like Android is running now?

http://try.buildwinjs.com/?r=Automated%202015-01-05%2018:30:59%20UTC%20(partial)#status
