### ISSUE TITLE
Make Pivot header size configurable

### ISSUE THREAD

**Issue by xirzec** [winjs/winjs#703]
With the new Pivot header size being significantly, it would be nice to have a way to style or set the size in case app developers would like larger headers.

The adaptive sample is also in need of an update: http://try.buildwinjs.com/#pivot

**Comment by pke** [comment]
Is there a way to cut overlength pivot header with "..." so that they do not reach into the next header?

**Comment by jayrenn** [comment]
The workaround @limefrogyank suggested is one possible solution. You can also add an id to your `body` tag so your styles will be more descriptive, thus removing the need for `!important` flags. We are also considering making the Pivot header items accept custom content, especially to enable a Tab scenario.
