### ISSUE TITLE
Menu / Flyout : Focus rect is visible when it shouldn't be

### ISSUE THREAD

**Issue by pag3** [winjs/winjs#707]
Feature: Menu
Environment: Mozilla/5.0 (Windows NT 6.3; WOW64; Trident/7.0; .NET4.0E; .NET4.0C; InfoPath.3; rv:11.0) like Gecko
Source: http://try.buildwinjs.com

SUMMARY:
The focus rect shows up on the button in the flyout by default, but it shouldn't be visible unless the user starts to tab.

REPRO STEPS:
1. Go to http://try.buildwinjs.com/#menu
2. Select Output tab
3. Click "show menu"
4. Click "flyout option"

OBSERVE:
The focus rect is visible on the button on the flyout by default

EXPECTED:
Focus isn't shown by default.

**Comment by AmazingJaze** [comment]
Not going to be investing in this area at this time.

**Comment by AmazingJaze** [comment]
We believe we can live with the discrepancy described above. If this becomes problematic in the future, we can reconsider.
