### ISSUE TITLE
Documentation: Roadmap on the Wiki is horribly outdated

### ISSUE THREAD

**Issue by MarkStega** [winjs/winjs#713]
The Wiki entry for the roadmap is outdated and does a dis-service to what appears to be a phenomenal project. It needs to reflect the existence of version 3 and actually look towards future releases.An updated roadmap would also be a great blog post to attract more attention to WinJS.

**Comment by xirzec** [comment]
I updated the Roadmap doc today. Sorry for the delay, @MarkStega. We're currently heads down trying to get a preview of 4.0 out so we can get more developer feedback.
