### ISSUE TITLE
Feature Request: Allow SearchBox results view to allow usage of symbols/icons in addition to images

### ISSUE THREAD

**Issue by pgills** [winjs/winjs#714]
This came out of the discussion on this issue: #673

**Comment by jayrenn** [comment]
The SearchBox control is now deprecated. Please refer to the [AutoSuggestBox control](https://msdn.microsoft.com/en-us/library/windows/apps/dn919949.aspx).

**Comment by jayrenn** [comment]
Added this to our internal tracking.
