### ISSUE TITLE
Feature Request: Guide for showing invalid input

### ISSUE THREAD

**Issue by borgdylan** [winjs/winjs#741]
I am filing this issue as instructed by @spankyj . Currently there is no suggested scheme to view invalid input. Will there be a recommended way that plays along with the current style sheets (both light and dark)?.

Aside:
As an experiment in an app I am building I found the following CSS to play well enough with the dark stylesheet. The css depends on angular validation classes and is why I may PR this css with the angular-winjs repo.

```
input[type="text"].ng-invalid.ng-dirty,
input[type="password"].ng-invalid.ng-dirty,
input[type="email"].ng-invalid.ng-dirty,
input[type="number"].ng-invalid.ng-dirty,
input[type="tel"].ng-invalid.ng-dirty,
input[type="url"].ng-invalid.ng-dirty,
input[type="search"].ng-invalid.ng-dirty,
textarea.ng-invalid.ng-dirty,
.win-textarea.ng-invalid.ng-dirty {
	border-color: red;
}
```

If any one experienced in WInJS design suggests a better color scheme, I will give it a try.

**Comment by jayrenn** [comment]
Thanks for the request! We have since created a [separate angular-winjs repo](https://github.com/winjs/angular-winjs). Please resubmit this request there.
