### ISSUE TITLE
Improve GridLayout to be able to auto-balance extra space

### ISSUE THREAD

**Issue by xirzec** [winjs/winjs#75]
When using the GridLayout with a ListView any extra space in the container is on the bottom. If your item template sizes are such that one extra row barely doesn't fit, you have potentially a very large blank space that looks bad on certain screen resolutions.

Proposal: Have an option in GridLayout that attempts to center items inside of the layout container by introducing top padding equal to half the leftover space. Similarly, in vertical mode, this should center using left padding so that leftover space is again distributed on either side of the items.

**Comment by jayrenn** [comment]
We are looking to pursue this in the future.
