### ISSUE TITLE
Achieve tilt effect on listview items like on Windows Phone

### ISSUE THREAD

**Issue by pke** [winjs/winjs#760]
Is there a way to achieve this nice tilt effect of list items when they are touched on the right/left side instead of the current push down animation?

The one described here: http://blogs.msdn.com/b/ptorr/archive/2010/03/23/tilt-effect-for-windows-phone-controls.aspx

**Comment by jayrenn** [comment]
You can now achieve this behavior today. Visit our ListView [selection sample](http://try.buildwinjs.com/#listviewinteractions:selection) on the Try Site and choose the 'single' selection scenario. You can achieve the tilt effect using a mouse on your desktop.
