### ISSUE TITLE
feature: Add minDate/maxDate to WinJS.UI.DatePicker

### ISSUE THREAD

**Issue by pke** [winjs/winjs#763]
instead of minYear and maxYear.
Or provide a finer grained "beforechange" event to prevent certain dates from being selected.

**Comment by jayrenn** [comment]
Thank you for the suggestion! For Windows 10, you can use the HTML `input` tag, which sports the new DatePicker design. With this tag, you can use the `min` and `max` attributes to achieve the behavior you are looking for.
```html
<input type="date" min="2000-01-01" max="2005-12-31" />
```

![image](https://cloud.githubusercontent.com/assets/7266075/8313606/ad3aa624-1998-11e5-81c7-659f7ee8001d.png)

**Comment by pke** [comment]
Great! Finally IE/Edge supports this.
