### ISSUE TITLE
WinJS.Binding.Template.renderItem is undocumented

### ISSUE THREAD

**Issue by pke** [winjs/winjs#764]
Or isn't it?

**Comment by AmazingJaze** [comment]
We've opened a bug internally on the Doc writers. Thanks.

**Comment by pke** [comment]
Is there a way to improve the docs by pull-requests? Most of the MSDN docs (about WinJS) are sub-par and I often wonder how to use a certain function/argument. For instance the default values are almost never clearly explained so one has to dig into the source code to see what the default value for a setting is supposed to be.

The rare samples attached to the docs are most of the time just plain wrong and promote bad coding style.

I'd like to help to improve this situation, which always bugged me in the Win32 MSDN docs years and years ago.
