### ISSUE TITLE
Why bottom margins for buttons in settings flyouts

### ISSUE THREAD

**Issue by pke** [winjs/winjs#773]
```
.win-settingsflyout .win-content .win-settings-section button,
.win-settingsflyout .win-content .win-settings-section select,
.win-settingsflyout .win-content .win-settings-section input[type=button],
.win-settingsflyout .win-content .win-settings-section input[type=text] {
  margin-bottom: 25px;
  margin-left: 0;
  margin-right: 20px;
```

Whats the reason for the huge bottom margin?

**Comment by pke** [comment]
And what's the solution for this? Overriding the margin using an id'ed (body) element?

**Comment by xirzec** [comment]
@pke That should work. I don't anticipate we'll make changes to SettingsFlyout CSS in the near future. I'm not aware of any design updates for that control.
