### ISSUE TITLE
Pivot:  ListView inside Pivot in iOS won't touch scroll?

### ISSUE THREAD

**Issue by limefrogyank** [winjs/winjs#775]
Feature: Pivot
Environment: Mozilla/5.0 (iPhone; CPU iPhone OS 10_10_1 ilke Mac OS X) AppleWebKit/600.1.4 (KHTML, like Gecko) Version/8.0 Mobile/12B411 Safari/600.1.4
Source: http://try.buildwinjs.com

If you've got an actual iPhone, can you check to see if scrolling inside the ListView in a Pivot still works?  http://try.buildwinjs.com/#pivot

I've been using the iOS emulator exclusively with WinJS 3.0.1 (the Nuget package) and it's been working OK.  However, any of the more recent versions (even WinJS 4.0) don't respond to scrolling in a ListView when it's in a Pivot.  The Pivot still moves sideways, but the ListViews they contain don't scroll vertically.  

It DOES work in WP8.

**Comment by freedomson** [comment]
Hi fix for v3: https://github.com/freedomson/guganews/commit/756eff4c50668c8b0bdcd5fdd9ce2a4d21d1876b#diff-34cbebba0a8e64f842cbc5d8725b7977
