### ISSUE TITLE
How to prevent cursor move when input value changes due to data-binding and input listener?

### ISSUE THREAD

**Issue by pke** [winjs/winjs#781]
I have a data-bound input control: `<input data-win-bind='value:model.value">`
I attach a listener to this input

```
input.oninput = function() {
  model.value = input.value;
}
```

Setting the `model.value` will trigger a data binding update on the input element. Which sets its `value` to the `model.value`. This moves the cursor in the input field after the last character, making continous changes between the first character and the last one impossible.

Any idea how to prevent this behaviour?

**Comment by pke** [comment]
A fixed version of `setIfChanged" can be found here https://github.com/winjs/winjs/issues/962#issuecomment-79214175

**Comment by jayrenn** [comment]
Thanks for the suggestion! See my comments on this other thread: https://github.com/winjs/winjs/issues/417#issuecomment-111624953
