### ISSUE TITLE
WinJS.xhr with responseType 'json' returns wrong type on iOS

### ISSUE THREAD

**Issue by bryan-phelps** [winjs/winjs#785]
Running a Cordova App on iOS 8.1.1, using WinJS 3.1, WinJS.xhr with responseType of 'json' is returning a response object that is a JavaScript object, instead of a string per the documentation here:
http://msdn.microsoft.com/en-us/library/windows/apps/br229787.aspx

It looks like responseType is just a pass-through to the underlying XHR object.

The spec says that responseType of 'json' should return a response that is the result of invoking the value of JSON.parse(..) with the responseText. So it seems like in this case, the iOS UIWebView implementation is actually compliant with the spec here:
https://dvcs.w3.org/hg/xhr/raw-file/tip/Overview.html#json-response-entity-body

It might be worth updating the documentation to reflect this specification, or, customizing WinJS so that it behaves consistently across platforms (to have it adhere to the documentation, you could always have it act as responseType 'text' behaves).

**Comment by xirzec** [comment]
Filed the documentation issue and confirmed that IE on Windows 10 preview follows the specification as expected.
