### ISSUE TITLE
Changing AppBar layout property from "menu" to "commands" places WinJS.UI.MenuCommand objects into the primary row of the AppBar

### ISSUE THREAD

**Issue by AmazingJaze** [winjs/winjs#792]
The AppBar Commands with section: "secondary" show up as menu commands in the AppBar DOM and in the UI presentation after switching from "menu" layout to "commands" layout. 
1) Go to http://winjs-jessesh.azurewebsites.net/AppBar/
2) Press the [Commands Layout] button.
3) Open the AppBar

__Expected:__ There are two AppBarCommands in the AppBar
__Actual:__ There is one AppBarCommand and one MenuCommand in the AppBar (the Dom inspector verifies this)

__Impact:__ The Menu command never displays an icon. If you switch back to "menu" layout in this bad state, we duplicate the secondary command such that you now have the secondary MenuCommand appearing in the AppBar twice. 3 visible commands overall instead of the 2 that the user declared.

**Comment by xirzec** [comment]
Another bug that didn't get closed by Git?

**Comment by AmazingJaze** [comment]
This was only checked into a private branch, so it still repro's in today's master. However this scenario shouldn't be possible after we finish implementing the proposed design changes.

**Comment by AmazingJaze** [comment]
No longer applies to the new AppBar design. Changing layouts is no longer a supported scenario.
