### ISSUE TITLE
proposal: WinJS.Promise.always()

### ISSUE THREAD

**Issue by pke** [winjs/winjs#794]
I have this sample code. The audio output should be stopped regardless of the result of the `myLongRunningPromise`. Please not that is a much simplified version of my promise chain. The console logs are merely placeholders for nested chains.

```
var pleaseWaitPromise = playAudioAsync("please wait");

myLongRunningPromise().then(function tempSuccessHandler(result) {
  pleaseWaitPromise.cancel();
  return result;
}, function tempErrorHandler(error) {
  pleaseWaitPromise.cancel();
  return WinJS.Promise.wrapError(error);
}).done(function realSuccessHandler(result) {
  console.info(result);
}, function realError(error) {
  console.error(error);
});
```

So what I would like to propose is an `.always` continuation function, that exists alongside `.then` and `.error`. Then my code would look like this:

```
myLongRunningPromise().always(function () {
  pleaseWaitPromise.cancel();
}).done(function realSuccessHandler(result) {
  console.info(result);
}, function realError(error) {
  console.error(error);
});
```

Note that the always function does not get the promise result/error. It gets no parameters in.

Would such a function be helpful to have for others? If so, how could it be patched on `WinJS.Promise`?

**Comment by pke** [comment]
The way `WinJS.Promise` is implemented internally makes it very hard to monkeypatch this kind of functionality on top of it.

**Comment by pke** [comment]
Before I start hacking this into the WinJS promise code, would you accept a PR on this? ES6 does not seem to have support for this, as well as no support for cancellation or progress reporting. So WinJS Promise looks more advanced ;)

**Comment by jayrenn** [comment]
@pke, we'd be happy to consider a PR if you submit one!
