### ISSUE TITLE
Audit and update flexbox code to ensure that percentage height works

### ISSUE THREAD

**Issue by rigdern** [winjs/winjs#802]
As described in #636, there's a flexbox bug in Chrome/Safari which causes percentage heights (e.g. `height: 100%` to behave unexpectedly when used within a flex item.

We should:
  - Audit all usages of flexbox. If the flexbox can hold custom app HTML, then we should make sure percentage heights work properly in the custom HTML in Chrome/Safari. If they don't work, we should fix it.
  - In our flexbox mixin, update the [default basis of `.flex`](https://github.com/winjs/winjs/blob/2809cd378d9d67c1355d4402b7c04a4c30aae8fd/src/less/mixins.less#L113) to be `0%` instead of `auto`.
    - This will align our mixin with the [flexbox spec](http://www.w3.org/TR/css3-flexbox/#flex-property)
    - The current value of `auto` is considered to be [indefinite](http://www.w3.org/TR/css3-flexbox/#definite-sizes) which means that, per the spec, percentage heights **will not work** inside that flex item. The new value of `0%` is considered to be [definite](http://www.w3.org/TR/css3-flexbox/#definite-sizes) which means that, per the spec, percentage heights **will work** inside that flex item.
  - Find everywhere that uses the [`.flex` mixin](https://github.com/winjs/winjs/blob/2809cd378d9d67c1355d4402b7c04a4c30aae8fd/src/less/mixins.less#L113) and depends on the default value. Evaluate whether a basis of `auto` or `0%` is more appropriate for that particular flex item. Here are the most common scenarios of `.flex`:
    - Size to content. When a flex item should size to its content and its size should not be influenced by the size of the flexbox, it should use: `flex-grow: 0; flex-shrink: 0; flex-basis: auto;`. This can be expressed more concisely as `.flex(none);`.
      - A `flex-basis` of `auto` means that the flex item will size to its content along the flex axis. Because `flex-grow` and `flex-shrink` are `0`, the size of this flex item will not be adjusted at all based on the flexbox's size.
    - Flex. When a flex item should grow and shrink as its flexbox changes size and its size should not be influenced by the size of its content, it should use `flex-grow: 1; flex-shrink: 1; flex-basis: 0%;`. This can be expressed more concisely as `.flex(@grow: 1; @shrink: 1);`.
      - A flex-basis of `0%` essentially means that the flex item wants to have a size of `0` on its flex axis. Because `flex-grow` and `flex-shrink` are `1`, the flex item's size will be entirely determined by the size of its flexbox.

Here's what is known so far:
  - SplitView is affected (#801).
  - Hub is affected. Already fixed (#636).
  - Pivot **is not** affected.

**Comment by xirzec** [comment]
@rigdern Is there still any work needed to be done here?
