### ISSUE TITLE
WinJS should normalize all error objects given to WinJS.Application.onerror handlers

### ISSUE THREAD

**Issue by pke** [winjs/winjs#807]
Its quite a lot of work to grab the needed information from the various error objects that can be handed into this handler. Instead of every app developer implementing her own property extraction, WinJS should normalize the potential error objects to a specific one that always has at leas a `message` property.

optional (when extractable from originating error object):
* `sourceFile`
* `sourceLine`
* `sourceCharacter`
* `stack`
* `exception` (not sure if that could go into the `message` already)

The object should also override the toString() method and compose a reasonable default textual representation of the error object for easy logging.

The object should be able to be used with the `MSApp.terminateApp(error) API`

My current version does not handle all the possible incoming error objects but it could be a start for the normalizeError method:
```
WinJS.Application.onerror = function(error) {
      var normalizeError;
      normalizeError = function(error) {
        var result;
        result = {
          message: error.errorMessage || error.message,
          file: error.errorUrl,
          detail: error
        };
        if (error.errorLine) {
          result.filePos = [error.errorLine, error.errorCharacter];
        }
        result.toString = function() {
          if (this.file) {
            return "" + this.file + " at line " + this.filePos[0] + ", " + this.filePos[1] + ": " + this.message;
          } else {
            return "" + this.message;
          }
        };
        return result;
      };
      logger.error("Ouch!", error = normalizeError(error.detail));
      WinJS.Navigation.navigate("/pages/500.html", {
        error: error,
        message: error.toString()
      });
      return true;
    };
```

**Comment by jayrenn** [comment]
This is a great idea! I have added the request to our internal tracking.
