### ISSUE TITLE
ContentDialog: Cannot tab to browser's controls while dialog is open

### ISSUE THREAD

**Issue by TheWrathOfConst** [winjs/winjs#809]
Repro steps:
1) Open a content dialog
2) Hold down tab

Expected: Tab cycles through dialog box and wraps back to browser controls (eg, the searchbox, address bar, etc)
Actual: Tab is trapped inside of the dialog box until it is dismissed. A keyboard user is forced to acknowledge and use the dialog box in some way before full control of their browser is returned to them.

**Comment by xirzec** [comment]
I believe this is expected. No different than how the 'save' dialog traps tab.
