### ISSUE TITLE
ContentDialog+Flyout: Can get a flyout stuck on screen using keyboard

### ISSUE THREAD

**Issue by TheWrathOfConst** [winjs/winjs#810]
Repro steps:
1) Have a button that opens content dialog
2) Have a button inside the content dialog, which opens a flyout when clicked. Make sure this button gets focused automatically when the dialog is opened
3) Set focus on the button that opens the content dialog, press ESC+Enter a couple times in rapid succession

Results: Every now and then you'll get a flyout stuck onscreen that can't be dismissed by tapping outside of it

Video: http://1drv.ms/1skaWV9

**Comment by xirzec** [comment]
@rigdern How common is putting a flyout into a contentdialog? Seems like a weird UX. Modal UI should be simple, right?

**Comment by rigdern** [comment]
I suspect the fix for #1256 also fixed this.
