### ISSUE TITLE
WinJS public site uses version 4.0 and current release is 3.0.1 and this is confusing

### ISSUE THREAD

**Issue by giggio** [winjs/winjs#827]
The current samples on http://try.buildwinjs.com/ is version 4.0 (an alpha, I believe) and when we download we get version 3.0 and the samples don't work anymore.
This should be more explicit. Either you use 3.0 on the try site or you use 4.0 and explain how to get it and also explain it's current state and roadmap (alpha, expected release date, etc).
Also, there is no public try site for 3.0. And there is no milestone for 4.0 on github. This is all very confusing.

**Comment by xirzec** [comment]
We eventually want to add an ability to the try site so that you can pick what version you want to work with.

**Comment by pke** [comment]
I still think think the build script should compile a current version of WinJS downloadable as nuget package. That shouldn't be so hard to do.

**Comment by ThomasShaped** [comment]
Come on guys, it's been 2 months. Are you telling me you don't have a back up of the 3.0 documentation that you can put up somewhere? That would at least solve this issue until the 4.0 release.

**Comment by xirzec** [comment]
@ThomasShaped 3.0 didn't add any new features over 2.1, just cross-platform support. You can find the old docs on MSDN. e.g. [ListView](https://msdn.microsoft.com/en-us/library/windows/apps/br211837.aspx) 

We're currently working on getting things updated for 4.0.

**Comment by jayrenn** [comment]
WinJS 4.0 has been [released](http://try.buildwinjs.com/#get).

**Comment by giggio** [comment]
Great! For the next updates please keep the samples working with v4, and maybe offer a different place to try vnext while it is being worked on.
