### ISSUE TITLE
Menu: Text can shift as you hover in IE

### ISSUE THREAD

**Issue by rigdern** [winjs/winjs#829]
1. Download the repro page http://1drv.ms/139xdhE
2. In IE, open repro\index.html
3. Click "Show Menu"
4. Hover over the first command
5. Hover over the last command

As you repeat steps 4 and 5, the text appears to move upwards and downwards.

![menutextshift](https://cloud.githubusercontent.com/assets/199935/5460761/60b1b53a-851a-11e4-935b-f00cdd85ca00.gif)

**Comment by mkjunior19** [comment]
Depending on the location of the anchor element and menu placement (left, right, top or bottom), this bug can repro with any number of menu commands, not just 4 commands as it is shown in the repro page.
