### ISSUE TITLE
WinJS.UI.Pages "ready" called before Hub contents loaded

### ISSUE THREAD

**Issue by ras0219** [winjs/winjs#837]
I have a simple page with a declarative hub control and some static sections. I'd like to perform some initial configuration/setup once the entire page is loaded, however the "ready" function is called before the Hub's children are fully loaded. I expected the "ready" function to be called when the _entire page_ is loaded, not just the top level elements.

In order to work around this, I'm using code like the following:

``` javascript
WinJS.UI.Pages.define("/pages/home.html", {
    ready: function (element, options) {
        this._hub = element.querySelector(".win-hub").winControl;
        var that = this;
        function delayLoad(evt) {
            if (that._hub.loadingState !== "complete") return;
            // infinite loop without this line
            that._hub.removeEventListener("loadingstatechanged", delayLoad);
            // Main loading code here
        }
        this._hub.addEventListener("loadingstatechanged", delayLoad);
    }
}
```

This seems like a poor choice for the default -- if you wanted to work upon a partially loaded page, it seems that you would use the "init" function. The ready function, as I understand it, is for fully loaded pages.

It could be that I'm not using the tools as intended, but it would seem I'm not alone in this:
From #736 

> Then it seems that not all content in the sections is available immediately in the  ready  page control callback. When I try to  querySelector  certain controls that should have been processed by WinJS.UI.process all by WinJS.UI.Pages  processed  method already, I get null values back. I have to wait for the hub control to change its state to  complete  before I can operate on the WinJS controls in the different hub sections.

If the functionality cannot be changed, at least some additional documentation about this particular quirk would be appreciated!

**Comment by colouredFunk** [comment]
Is there an example for this?
