### ISSUE TITLE
Property changes to AppBarCommand in the overflow area do not take hold.

### ISSUE THREAD

**Issue by AmazingJaze** [winjs/winjs#841]
AppBarCommand has an onclick property which is necessary to set if you want a Command's behavior in the AppBar main action area to be the same as when it appears in the AppBar's overflow menu.

This works today as long as you set the onclick property on the command before it gets places in the AppBar overflow menu. This is because we aren't keeping the mirrored commands in the overflow area in sync when the original AppBar commands in the main action area whenever the onclick property on the AppBar command is set.

**Comment by AmazingJaze** [comment]
Updating the title to reflect that it is all properties, not just "onclick".   The changes will eventually take hold whenever the AppBar or ToolBar re-lays out commands, such as resizing the window.

**Comment by rigdern** [comment]
As a workaround, developers could call `notifyReload` on `toolBar.data`.

If `ToolBar` listened to `itemmutated`, developers would be able to call `notifyMutated` on `toolBar.data`. But `ToolBar` doesn't listen to `itemmutated`. `Hub` and `Repeater` also don't listen to it.

**Comment by AmazingJaze** [comment]
They can also call ```forceLayout()``` on the ToolBar control itself.

**Comment by quanglam2807** [comment]
#1020 I think the bug is still there. Would you mind to check it again?
