### ISSUE TITLE
ListView items don't have pressed down visual with touch in Firefox

### ISSUE THREAD

**Issue by rigdern** [winjs/winjs#844]
### Repro

1. In Firefox, go to the ListView data source edits example on the [Try site](http://try.buildwinjs.com/#listview)
2. Press down on a ListView item with your finger

**Expected:** Item shrinks when you press it.

**Actual:** Item doesn't change appearance when you press on it.

### Cause
It looks like the synthetic WinJS pointerdown event isn't firing until the finger is lifted from the sceen. I wonder if other controls are affected by a similar problem.

**Comment by xirzec** [comment]
So mousedown only fires when you remove your finger?

**Comment by jseanxu** [comment]
Correct. Mousedown and mouseup fire back to back after lifting your finger.
________________________________

**Comment by jseanxu** [comment]
Opened a bug on mozilla, closing this issue:
https://bugzilla.mozilla.org/show_bug.cgi?id=1124484
