### ISSUE TITLE
Appbar commands are not visible after invoking the overflow menu and resizing the screen

### ISSUE THREAD

**Issue by xirzec** [winjs/winjs#849]
Repro: http://winjs-jessesh.azurewebsites.net/AppBar

1. Resize the browser window so all AppBarCommands are hidden and only the overflow ellipsis button remains
1. Click the ellipsis to open the overflow menu
1. Click the ellipsis to close the overflow menu
1. Resize the browser window wide enough so that the AppBarCommands should be visible again

Expected: Commands are visible

![image](https://cloud.githubusercontent.com/assets/639216/5512769/355f888e-8796-11e4-8044-9443eb40adb6.png)

Actual: Commands are still invisible as if there were not enough room:

![image](https://cloud.githubusercontent.com/assets/639216/5512776/458be8b0-8796-11e4-9433-13b29729aa25.png)

**Comment by AmazingJaze** [comment]
Unable to repro with current bits.
