### ISSUE TITLE
Hub: no inertia when panning on iOS

### ISSUE THREAD

**Issue by rigdern** [winjs/winjs#851]
1. On an iOS device, open the "Basic Hub" sample on the [Try Site](http://try.buildwinjs.com/#hub)
2. Use your finger to pan horizontally

**Unexpected result:** There's no scroll inertia. When you lift your finger, the pan stops immediately.

**Comment by xirzec** [comment]
Inertia seems to work in ListView samples on the try site, but not Hub.
