### ISSUE TITLE
SearchBox footprint needs adjusting

### ISSUE THREAD

**Issue by nizh914** [winjs/winjs#853]
The searchbox glyph looks vertically misaligned. The issue is more obvious when you click on the buddy button.  

Chrome:
![searchchrome](https://cloud.githubusercontent.com/assets/1942825/5599386/44b747ce-927a-11e4-9635-d8ce87d5670f.PNG)

IE: 
![searchie](https://cloud.githubusercontent.com/assets/1942825/5599395/48667b06-927a-11e4-8995-461d7dfbfc12.PNG)

**Comment by jseanxu** [comment]
Fixed via f4f924f3eec8186105fe3448e73cd9f4c09e65fc
