### ISSUE TITLE
Flyout/Menu stays open on mouse scrolling and gets detached from its anchor element (only in IE)

### ISSUE THREAD

**Issue by mkjunior19** [winjs/winjs#854]
Repro steps: 
1. Go to http://try.buildwinjs.com/#flyout
2. Open flyout 
3. Start scrolling using the mouse wheel 

Expected: Flyout/Menu closes on mouse scrolling 
Actual: Flyout/Menu stays open and gets detached from its anchor element. In the picture below, flyout is overlapping its anchor button. 

![flyout_detached_bug](https://cloud.githubusercontent.com/assets/6732783/5617641/ac8dc0ba-94c5-11e4-8071-c8f448fbea28.png)

This bug does not repro in Chrome since mouse-scrolling gets blocked when flyout/menu is open.

**Comment by AmazingJaze** [comment]
This has been present since WinJS 1.0. Not going to be investing in a fix at this time.
