### ISSUE TITLE
Starting a Windows Universal app, should I be using WinJS 3.0 instead of the 2.0/2.1 that's baked in?

### ISSUE THREAD

**Issue by upta** [winjs/winjs#855]
Title says it all, really, but is there any reasons I should/shouldn't be switching to 3.0 for a brand new universal app?

Thanks!

**Comment by SPDoctor** [comment]
I have noticed that the WinJS3.0 AppBar falls well short of the native look/feel you get if you use WinJS2.1 on Windows Phone. I believe that WinJS2.1 calls through to WinRT to create a native app bar and this has not yet made it into WinJS3.0 (or may not be technically possible for all I know).

**Comment by xirzec** [comment]
@upta - 3.0 is a cross-platform release for non-Windows platforms. So if you want to do something like Cordova, 3.0 is the way to go. If you are targeting Windows 8.1 desktop and phone, then 2.0 and 2.1 will work just fine.

@SPDoctor - You are correct that the AppBar is no longer using phone-specific APIs as of 3.0. This reflects our desire to converge the AppBar across platforms.

**Comment by upta** [comment]
Perfect, thanks for the answers!
