### ISSUE TITLE
XYFocus optimization

### ISSUE THREAD

**Issue by jayrenn** [winjs/winjs#858]
Instead of grabbing all the elements, then discarding the ones that do not fit the criteria, you can use a selector for just the focusable elements. This results in a 30% improvement in performance.

**Comment by jseanxu** [comment]
Adding more info:
Instead of
`document.querySelectorAll("*")`
then filtering by going thru each item and checking their tagNames and tabIndices, we could just
`document.querySelectorAll("BUTTON, INPUT, DIV:not(tabIndex='1'")`

**Comment by jseanxu** [comment]
Iceboxed
