### ISSUE TITLE
AppBar: AppBar Menu layout resizes unexpectedly when invoking an item

### ISSUE THREAD

**Issue by jseanxu** [winjs/winjs#859]
Opening per @AmazingJaze request:

Repro
* Go to http://winjs-jessesh.azurewebsites.net/toolbar
* Open the AppBar at the top of the page
![bug1](https://cloud.githubusercontent.com/assets/6741017/5638843/e78b50a4-95c1-11e4-91d8-0c0e3abdfaab.png)

* Tap/click and hold on any item in the overflow area and observe the resize
![bug2](https://cloud.githubusercontent.com/assets/6741017/5638852/123e6b88-95c2-11e4-97f5-23256729c80b.png)

This issue only occurs on IE and on that particular page only. The AppBars at 
http://winjs-jessesh.azurewebsites.net/AppBar do not exibit that behavior.

**Comment by mkjunior19** [comment]
This issue does not repro on this page: http://winjs-jessesh.azurewebsites.net/toolbar in the latest IE.

**Comment by xirzec** [comment]
It does repro on Win 8.1 IE11 though.

**Comment by AmazingJaze** [comment]
I did some investigation and found that the issue will repro when you have at least one primary button primary command in the primary row of the AppBar and enough commands overflowing to create a scroll bar in the overflow area.

Finally, the command in the primary row of the AppBar needs to have this css style:
```CSS
.win-command {
    outline:none
}
```
There may be more factors at work, but removing that style causes the problem to go away.

**Comment by xirzec** [comment]
Weird that this didn't get auto-closed.

**Comment by AmazingJaze** [comment]
Also just a private branch. This should be reopened.  I have a CR with a unit test that will fix this. It may go away with the design change, but we should consider fixing the current version for preview

**Comment by AmazingJaze** [comment]
Fixed.
