### ISSUE TITLE
Find appropriate location for XYFocus in the source tree

### ISSUE THREAD

**Issue by rigdern** [winjs/winjs#860]
Currently XYFocus is located in the file `Utilities/_XYFocus.ts`. There are a few strange things about this:
- It's private (underscored). Should it be public instead?
- It's in the `Utilities` folder but publishes itself on the `WinJS.UI` namespace.
- Most modules in the `Utilities` folder are included in the `Utilities.js` wrapper module but `_XYFocus` is included directly in the `WinJS.js` module.

We should figure out the correct path and file name for `XYFocus` and figure out which wrapper module should require it. In doing so, we should keep in mind how we want users to be able to include/exclude `XYFocus` when doing a modular build.

**Comment by xirzec** [comment]
Put in the root of the WinJS folder and remove the _ from the filename.

**Comment by xirzec** [comment]
Remove happened but not the add

**Comment by jseanxu** [comment]
Fixed
