### ISSUE TITLE
'Menu' AppBar and ToolBar (both full and reduced) are broken in the latest IE

### ISSUE THREAD

**Issue by mkjunior19** [winjs/winjs#861]
This bug only reproes in IE and it's a recent regression. AppBarCommand separators are not getting drawn and the right-most AppBarCommand overlaps '...' button. 

Build 9908.fbl_awesome1501.141212
IE Version: 11.0.9800.0
![appbarlayout_broken](https://cloud.githubusercontent.com/assets/6732783/5639436/24f5cba0-95cb-11e4-80ea-c8da7c8888c2.png)

Chrome: 
![appbarlayout_notbroken](https://cloud.githubusercontent.com/assets/6732783/5639437/28cd0ea0-95cb-11e4-82f7-e91154b2ced0.png)

**Comment by xirzec** [comment]
To reproduce, go to about:flags and make sure "Enable Experimental Web Platform Features" is set to "enabled"

**Comment by mkjunior19** [comment]
This bug reproes with ToolBar as well.

**Comment by xirzec** [comment]
No repro on latest bits.

**Comment by AmazingJaze** [comment]
@mkjunior19 Can you update the status of this bug?

**Comment by mkjunior19** [comment]
Confirmed that this issue is fixed in the latest build.
