### ISSUE TITLE
Animation bug where content is shown as black in IE Edge

### ISSUE THREAD

**Issue by xirzec** [winjs/winjs#866]
http://try.buildwinjs.com/#pivot

Quickly swipe to the side with touch. The content will disappear when the slide animation begins and sometimes will stay gone after it completes:

![image](https://cloud.githubusercontent.com/assets/639216/5651383/cf7e4210-965b-11e4-8cb1-6760f7953a16.png)

**Comment by xirzec** [comment]
Repros in Edge mode, also seems to affect the SeZo sample occasionally.

**Comment by jseanxu** [comment]
I was not able to get a reduced repro of this issue. Here are the findings by playing with the DOM tree on the try-site directly:

This is the original reported bug, simply go to the Pivot sample and click the "all" header
![1-origbug](https://cloud.githubusercontent.com/assets/6741017/5656283/0053ac80-968f-11e4-8f07-27b7cabefa99.png)

Sample edited: reduced PivotItem count to 1
![2-removedpivotitems](https://cloud.githubusercontent.com/assets/6741017/5656292/15232f14-968f-11e4-91a8-2bc7f235989e.png)

Removed every DOM element except for the iframe and its parent
![3-trimmedtree](https://cloud.githubusercontent.com/assets/6741017/5656348/a3b71466-968f-11e4-897e-0ce48a8fb01b.png)


At this point it may look like the issue disappeared, however, if we absolutely position the content away from the top left, we get this
![4-offsetissue](https://cloud.githubusercontent.com/assets/6741017/5656317/4dcbf1de-968f-11e4-9f48-7b811cc871c3.png)

Notice the 1:1 ratio between the displacement of the iframe and the contents of the pivot
![5-offsetissueratio1](https://cloud.githubusercontent.com/assets/6741017/5656321/5cc46c34-968f-11e4-912e-d96390720ea4.png)

To prove that it was no fluke, here is a different displacement
![5-offsetissueratio2](https://cloud.githubusercontent.com/assets/6741017/5656324/65b7fef0-968f-11e4-81f3-54e669c27850.png)

**Comment by xirzec** [comment]
Bug is filed on IE, waiting for fix.
