### ISSUE TITLE
Ratings: Rendering issue for average rating when no user rating is set

### ISSUE THREAD

**Issue by pgills** [winjs/winjs#867]
Feature: Ratings
Environment: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/36.0.1985.143 Safari/537.36 Edge/12.0
Source: http://try.buildwinjs.com
IE - Edge Mode On

The rendering of the average rating when set to 3.4 is off when there is no user rating set.

![image](https://cloud.githubusercontent.com/assets/5951792/5651583/701638e4-965d-11e4-9738-1614e89382ee.png)

**Comment by phosphoer** [comment]
This seems to be caused by IE ignoring the inline width style set on the average star. It gets set to `14.4px` but the computed layout is still `24px`.

**Comment by phosphoer** [comment]
This appears to not repro anymore.
