### ISSUE TITLE
Input Type Text Element: Cannot enter text into input type text element on Binding sample

### ISSUE THREAD

**Issue by pgills** [winjs/winjs#869]
Feature: Binding
Environment: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/36.0.1985.143 Safari/537.36 Edge/12.0
Source: http://try.buildwinjs.com
IE Edge Mode On

There appears to be an issue with typing text into input fields.

Expected:
Text can be entered into input fields

Actual:
Text cannot be entered into input fields

**Comment by xirzec** [comment]
Inconsistent repro
