### ISSUE TITLE
SplitView is broken in the lateset IE

### ISSUE THREAD

**Issue by mkjunior19** [winjs/winjs#871]
In the latest IE, Splitview with default settings (inline hiddenDisplayMode & overlay shownDisplayMode) is not working correctly:
- the default width of opened pane (320px) is getting ignored 
- the default with of closed inline pane (48px) is getting ignoerd

Default Pane closed 
Expected 
![splitviewopen_noedge](https://cloud.githubusercontent.com/assets/6732783/5652121/44c66eb6-9662-11e4-9943-c905298a33b2.png)
Actual - closed pane is wider
![splitview_edge](https://cloud.githubusercontent.com/assets/6732783/5652105/3af6c5b6-9662-11e4-88ca-e128d16c416a.png)

Default pane opened 
Expected
![splitviewactuallyopen_noedge](https://cloud.githubusercontent.com/assets/6732783/5652123/47b27cfa-9662-11e4-9af9-b868c7d61af1.png)
Actual - the content is still getting overlayed
![splitviewopen_edge](https://cloud.githubusercontent.com/assets/6732783/5652115/40489f3a-9662-11e4-967b-a098ff7534db.png)

**Comment by rigdern** [comment]
Filed an IE bug. The bug is that if the flex-basis is auto then the size in the flex dimension (e.g. width for a flexbox with flex-direction row) will be ignored. This can be worked around by styling `flex-basis` instead of `width`/`height`.

**Comment by xirzec** [comment]
No repro on latest builds.
