### ISSUE TITLE
Add Pips to Pivot for UX Enhancement.

### ISSUE THREAD

**Issue by chrissp26** [winjs/winjs#873]
I've built a few WinJS apps utilising the Pivot control and one thing that always comes back during UAT and feedback channels is that users don't know how many PivotItems there are in a Pivot Control and it's easy to lose track of where you are within them (if there are many items).

A system of pips (one for each PivotItem) integrated into the control's header would solve this issue and would provide a visual map of where the user is currently and where they can go.

![pivotmap](https://cloud.githubusercontent.com/assets/2758144/5662211/2755191e-972e-11e4-8bdf-17b0f188e962.jpg)

This is a fairly easy thing to implement on it's own using the Pivot's events, but I think it would be a nice UX enhancement if it were built into the WinJS library, perhaps with the option of turning it on and off with a parameter.

**Comment by xirzec** [comment]
Thanks for the feedback!

There is a similar visual in the NavBar, though it reflects 'pages' of NavBarCommands instead of the count of NavBarCommands themselves.

What would happen if you had a large number of PivotItems? Currently the headers carousel, but there is only so much space for the pips.

**Comment by xirzec** [comment]
Hi Chris,

I'm saving this as a feature request, but I was able to get your feedback to a designer. The current UX thinking is that Pivot will be used as more of a "tab pattern" with a smaller number of options whereas primary navigation will be handled by the [SplitView](https://github.com/winjs/winjs/blob/master/src/js/WinJS/Controls/SplitView/_SplitView.ts). We're still working on getting some SplitView samples up on the Try site.

**Comment by jayrenn** [comment]
Thank you for your suggestion, @chrissp26! We relayed your message to the design team. As @xirzec  mentioned, the current thinking is that there should not be a large number of Pivot items. Instead, you can use the [SplitView control](http://try.buildwinjs.com/#splitview) to better organize your UI.
