### ISSUE TITLE
Text reflow when List View enters multiple selection

### ISSUE THREAD

**Issue by nizh914** [winjs/winjs#874]
When the list view is in filled selection mode (win-selectionstylefilled) and enters multiple selection from extended or single selection, the desired behavior is that the text reflows and clips. Today it just clips.

**Comment by xirzec** [comment]
Is there a screenshot of the desired behavior?

**Comment by xirzec** [comment]
This can be worked around by the developer by styling their item differently when .win-selectionmode is present

**Comment by jayrenn** [comment]
@xirzec suggested a viable remedy.
