### ISSUE TITLE
AppBar overflow area does not get resized appropriately when secondary commands get hidden programmatically

### ISSUE THREAD

**Issue by mkjunior19** [winjs/winjs#875]
This reproes in IE and Chrome. 
Repro steps: 
1. Go to http://winjs-jessesh.azurewebsites.net/AppBar/
2. Expand AppBar (and you'll see secondary commands) 
3. Uncheck 'Secondary Command' checkbox to programmatically hide secondary commands
4. Expand AppBar again

Expected: 
Only see primary commands with labels
![appbar_nosecondary_expected](https://cloud.githubusercontent.com/assets/6732783/5673548/323d06a6-9752-11e4-87f2-902e5ff532c5.PNG)
Actual 
AppBar has an empty area for hidden secondary commands. 
![appbar_nosecondary_actual](https://cloud.githubusercontent.com/assets/6732783/5673540/18e36178-9752-11e4-9107-1ad2db3822ca.PNG)

**Comment by rigdern** [comment]
This should be fixed by the new implementation of `Animations._resizeTransition` that will be included in the change that updates the `SplitView` to its new animation.

**Comment by xirzec** [comment]
@rigdern What's the status of the SplitView change? Can you port just the `_resizeTransition` work to close this bug?

**Comment by rigdern** [comment]
Closing bug. `_resizeTransition` was updated by https://github.com/winjs/winjs/commit/044b50b7ad575c467b33e6d3c33566bf41a5ad45 and AppBar animation code is being rewritten so this bug is no longer relevant.
