### ISSUE TITLE
AppBar primary commands are temporarily hidden or misplaced when one switches from minimal to compact 

### ISSUE THREAD

**Issue by mkjunior19** [winjs/winjs#876]
This reproes only with bottom AppBar. It reproes both in Chrome and IE. 
Repro steps: 
1. Go to http://winjs-jessesh.azurewebsites.net/AppBar/ 
2. Press 'minimal' to switch to minimal closedDisplayMode
3. Press 'compact' to switch back to compact closedDisplayMode

Expected: 
![appbar_mc_switch_expected](https://cloud.githubusercontent.com/assets/6732783/5673607/6b301600-9753-11e4-9c63-a0e33db7851b.PNG)

Actual: 
![appbar_mc_switch_actual](https://cloud.githubusercontent.com/assets/6732783/5673623/90a62938-9753-11e4-99f5-5c6e676a2568.PNG)
OR
![appbar_mc_switch_actual2](https://cloud.githubusercontent.com/assets/6732783/5673616/74d41558-9753-11e4-8e17-bacdd8a6551b.PNG)

**Comment by AmazingJaze** [comment]
No longer applies, this was based off of the original redesign.
