### ISSUE TITLE
ListView inside a SplitView doesn't resize outside IE

### ISSUE THREAD

**Issue by rigdern** [winjs/winjs#879]
### Impact

When showing/hiding, the SplitView resizes its content area. Outside of IE, controls such as the ListView will not render correctly because they will not know that they've been resized.

### Repro Steps
1. Create a SplitView with `shownDisplayMode="inline"`, `panePlacement="left"`.
2. Put a ListView into the SplitView's content area
3. Set the ListView's width to 100% (of the SplitView's content area)
4. Open the page outside of IE
5. Call `showPane` on the SplitView

**Expected:** ListView resizes in response to the SplitView's content area resizing:
![image](https://cloud.githubusercontent.com/assets/199935/5732014/e72f87d2-9b3f-11e4-96b8-8f6d75d9b2f6.png)

**Actual:** ListView doesn't realize it has been resized and clips its items:
![image](https://cloud.githubusercontent.com/assets/199935/5732006/dc6d7156-9b3f-11e4-92c1-f2b28716dd7e.png)

### Cause

This bug is caused by the absence of an element resize event in browsers other than IE. A couple of solutions come to mind:
  - Extend the [`ResizeNotifier`](https://github.com/winjs/winjs/blob/53e121766e7bb8d6bbf41c112ccfed723797eaaa/src/js/WinJS/Utilities/_ElementUtilities.js#L730) (which is used to inform elements of a window resize) so that the SplitView can use it to inform all of its descendants that a resize has occurred. One concern is that this may not work well when there are nested controls that care about resize (e.g. this doesn't allow a child control to wait for its parent control to finish resizing before resizing itself).
  - Create a resize model (like we have a dispose model) for our controls. A control will inform its child controls after it is done resizing.

**Comment by xirzec** [comment]
Let's try the first suggested fix of using `ResizeNotifier`
