### ISSUE TITLE
Creating a ToolBar with commands using binding list is very different from creating an AppBar using bindinglist

### ISSUE THREAD

**Issue by mkjunior19** [winjs/winjs#880]
ToolBar.data property takes a BindingList of type ICommand which expects an object with a "element" property. In contrast, AppBar can take a BindingList of undefined type, call new WinJS.UI.AppBarCommand(null, item) and then append the element of the newly created AppBarCommand to the element of the AppBar. 

So ToolBar requires the following code to add commands using a binding list: 
```
var commands = [ 
   new WinJS.UI.AppBarCommand(null, {section: "primary", type: "button", label: "Add", icon: "add"}),            
   new WinJS.UI.AppBarCommand(null, {section: "primary", type: "content", label: "textbox" }),
];
	window.commandList = new WinJS.Binding.List(commands); 
```

AppBar can take either the above code or the code below: 

```
var commands = [ 
   {section: "primary", type: "button", label: "Add", icon: "add"},
   {section: "primary", type: "content", label: "textbox" },
];
	window.commandList = new WinJS.Binding.List(commands); 
```

Is it our goal to ensure that ToolBar aligns with AppBar for this case?

**Comment by xirzec** [comment]
This is consistent with Pivot and Hub, the distinction is that there is no renderer passed from the user.
