### ISSUE TITLE
Is ContentDialog seems to be missing in 3.0.1

### ISSUE THREAD

**Issue by arcadiogarcia** [winjs/winjs#886]
It seems that the recommended build (3.0.1) doesn't include the ability to create contentDialogs, while it works with previous versions and the try.buildwinjs.com site. I havent been able to find any info about it, so I wanted to ask: Has it been deprecated or will it be included in 4.0? I'm using WinJS for a website, so previous versions are not an option for me, should I implement my own solution, or do you have any replacement in the works? Thanks in advance!

**Comment by xirzec** [comment]
ContentDialog is a new control for 4.0. It will be available in the next package release.
