### ISSUE TITLE
Refine the Pivot animations to properly scale with screen size and content

### ISSUE THREAD

**Issue by jayrenn** [winjs/winjs#887]
Screen size:
When there are a sufficient number of Pivot sections, and one of the last Pivot sections is currently selected, re-sizing the screen width causes the headers to animate horizontally quite faster than if one of the first Pivot sections were currently selected. The header sliding animation should ideally scale with the number of Pivot sections.

Content:
If the screen width is sufficiently wide, the content entrance and exit animations suffer a similar problem with the above issue -- they fly in much faster than they would if the screen width was much smaller.

**Comment by jseanxu** [comment]
Iceboxed
