### ISSUE TITLE
It's hard for developers to get the recommended look of SplitView showbutton 

### ISSUE THREAD

**Issue by mkjunior19** [winjs/winjs#888]
We need a public CSS that developers can use to style their custom div with the recommend look & feel which can expand or close the SplitView pane . Potential CSS name .win-splitview-showbutton
![splitview_showbutton](https://cloud.githubusercontent.com/assets/6732783/5764360/496138c6-9ca6-11e4-9d71-bedd3014adb9.PNG)

**Comment by xirzec** [comment]
@rigdern Do we have the icon for this right now? I'm thinking that we don't.

**Comment by sondreb** [comment]
Music (WinJS), Calendar, Sports... all different on Windows 10 build 10074:

![image](https://cloud.githubusercontent.com/assets/309938/7445964/71fa1778-f17c-11e4-9972-257f293bf670.png)
