### ISSUE TITLE
AppBar: animations are ugly for closedDisplayMode:none

### ISSUE THREAD

**Issue by rigdern** [winjs/winjs#894]
Video: http://1drv.ms/1xNNFMo

1. Create an AppBar with closedDisplayMode: none
2. Call appBar.show() and appBar.hide() to see the animations

Problems:
  1. The animations are ugly because you can tell that 2 animations are being played at the same time (one on the AppBar and one on the AppBar's content).
    - In the top AppBar, you can tell that the AppBar itself is sliding out. Simultaneously, the AppBar's content is resizing.
    - In the bottom AppBar, you can tell that the AppBar itself is sliding out. Simultaneously, the AppBar's content is also sliding out.
    - Possible fix: Instead, the animation should probably just be a slide animation like we had in Win8.
  2. It's ugly how the labels in the top AppBar hang outside of the bar that takes up the width of the screen. Instead, the bar should probably be tall enough to accommodate the labels in this AppBar configuration (assuming it would work well with the animations).

**Comment by AmazingJaze** [comment]
fixed by new open/close animations
