### ISSUE TITLE
Try site: styling of text editor's search field is incorrect

### ISSUE THREAD

**Issue by rigdern** [winjs/winjs#897]
1. Go to http://try.buildwinjs.com/#listview
2. Click the "HTML" tab
3. Click inside of the editor and hit Ctrl+F to search

**Unexpected result**: Search field and its controls hang too low.

![image](https://cloud.githubusercontent.com/assets/199935/5823220/d50f848a-a08f-11e4-97bb-1f2c7b159be9.png)

**Comment by xirzec** [comment]
This is because we are including ui-light in the try site frame which is too aggressively overriding the styles on the editor. We should think about if we want to make intrinsics opt-in instead

**Comment by jayrenn** [comment]
This has been resolved [since we made](https://github.com/winjs/winjs/wiki/Styling-HTML-Controls) the intrinsic styling opt-in.
