### ISSUE TITLE
reference

### ISSUE THREAD

**Issue by gleborgne** [winjs/winjs#902]
WinJS is notre referenced here :
https://github.com/showcases/front-end-javascript-frameworks

**Comment by xirzec** [comment]
@gleborgne I saw this before, but there doesn't seem to be any way to nominate a new framework or edit the page. 

I submitted a support request to GitHub on the off chance they can route it to the right place.

**Comment by xirzec** [comment]
My request was forwarded to the showcases team, fingers crossed!
