### ISSUE TITLE
extension points and syntax improvements

### ISSUE THREAD

**Issue by gleborgne** [winjs/winjs#903]
WinJS is a great framework but it misses some extension / flexibility points.

Just some examples :

Defining some mixins added to all fragments/pages (injecting custom behaviors/helpers to all pages for logging, page tracking, ...)
Having some options on animations (duration, item delay, ...)
Being able to extend binding syntax (add custom pseudo function like 'select')

Another area of improvement is about reducing the amount of boilerplate code we write in WinJS apps : binding interactive elements (click or tap) to page function, or auto-create properties on fragment/page for DOM elements or controls.

Most of those points are available in WinJS Contrib, but core implementation would benefit all.

**Comment by jayrenn** [comment]
Thank you for your suggestions! We will look to evaluate all the areas where we can improve extensibility and automation to make your life as a developer easier.
