### ISSUE TITLE
Use JavaScript "class" for fragment definition

### ISSUE THREAD

**Issue by gleborgne** [winjs/winjs#904]
For now fragment/page is defined using an object literal. It makes it hard to work with Typescript, or ES6 classes, or use object oriented approach for pages.

It could be great to use a constructor function as a fragment definition.

**Comment by xirzec** [comment]
I'm confused, what is the advantage of using a constructor? Why would you want multiple instances of a  page descriptor?

**Comment by gleborgne** [comment]
for the application runtime : nothing 
It's all about developper adoption : it's easier to understand and it provides a better separation of concerns.

I have trained several people on WinJS, and for those who are not core JavaScript developpers, the mixin approach is not intuitive and hard to catch. The class approach if more familiar and allows for patterns like base classes for pages and so on (I know you could call WinJS.UI.Pages.define multiple times to inject multiple mixins but again, it's not what looks logic or familiar to many developpers, especially those coming from a C# or Java background).

Last but not least, it would makes using Typescript and/or ES6 class way easier, and help a lot for unit testing pages.

You could have all that today (composition, Typescript, unit test, ...) but with a lot of frictions.

I really love WinJS being a low level framework. It allows for making blazing fast and fluid apps. But some improvements should happen on developper experience. Otherwise, WinJS may die by lack of adoption.

**Comment by xirzec** [comment]
So you want to be able to share implementation functions across pages. What's stopping you from instantiating your custom class and then passing it to `Pages.define`?

```js
WinJS.Pages.define("/path/to/page.html", new MyPage());
```

Or if you just want to have one constructor for a 'base' page type that takes arguments:

```js
WinJS.Pages.define("/path/to/page.html", new MyBasePage({
   ready: function(element, options) {
       // do something custom here
   }
}));
```

`WinJS.Pages.define` takes an object. There's nothing stopping you from using a class pattern to construct that object.

**Comment by gleborgne** [comment]
Well, what is stopping me is simple : it won't work...
WinJS.UI.Pages.define creates a constructor and use the object as a mixin. Only instance members get passed to the page. You will lose everything in the prototype chain, thus all benefits of using OO approach, Typescript, ...

**Comment by xirzec** [comment]
Ah yes, I see the problem now. This bit here in Pages.js:

```js
if (members) {
    Page = _Base.Class.mix(Page, members);
}
```

In general I'm not a big fan of how _BasePage works today, the interaction between Page/BasePage is a bit convoluted. Also we've been trying to back away from mixins.

So the option you are suggesting is we migrate Pages to an inheritance model (perhaps something like BasePage <- Page <- UserPage).

Not an unreasonable feature request, but a bit tricky since it'd be a pretty big breaking change to the existing code and having both might be confusing.

Do you think Pages are a sufficient model for navigation? Or would you prefer a more MVVM pattern for loading templates and routing?

**Comment by gleborgne** [comment]
If considering only features, current implementation is quite good. You have a good composition mecanism. However, current page implementation lacks some extension points, and a development approach more compatible with modern javascript (ES6 will probably make things even worse as time goes on). 

The page lifecycle could also benefit from a little more steps, and a better orchestration of building it's own content. Controls in a page are built independantly, forcing us to use external synchronisation like the Scheduler, or loadingstate events (like the Hub). It's enougth for simple screens but it starts to get really painful when you want to build efficiently a page composed of multiple fragments and controls (the Pivot is probably the worst control in WinJS for that matter). I tried an approach for that in WinJS Contrib but I'm still not fully happy with it. I have a couple other ideas that I must try but they may require some adaptations in WinJS.UI.processAll (an extension point on this would also be great for us to experiment, for example trying to use custom elements instead of "data-win-control", mixing WinJS with other libraries, etc).

What is really tricky about using constructor for pages is that, on first load, WinJS creates the page instance before having the page "definition", and injects the mixin on the fly (after the javascript file is loaded for the first time). That's the point that could break compatibility if you try to use constructors or change page behavior.

One possible solution is swaping the prototype on the fly (using __proto__). It's not the cleanest JavaScript programming but it might work in all browsers supported by WinJS. In that case WinJS.Pages.define could just check if argument is an object or a function and work accordingly without breaking compatibility.

Concerning the pages, I love having the choice of using MVVM or not, depending on context. MVVM is good for some scenarios and very bad in others (not a good fit for meta-programmation, or when you have a lot of data to display). If you enforce MVVM, you will also have to provide a datacontext mecanism, which is tricky and can cause serious performance challenges.

**Comment by xirzec** [comment]
Technically Pages already come with a datacontext (it's the state passed to the navigation system) so we are more or less in that model today though you don't have to provide anything and it will default to an empty object.

I think we need to spend more time on revisiting the design of Pages and a better way to encapsulate different app components. In the mean time it seems like you could do a couple things to work around the mixin problem:

1. Change to having a factory pattern where you have a function assemble the the mixin for you (so you can share functions in a manner similar to prototypical inheritance.)
1. Create a helper function that walks the prototype chain (probably stopping at Object.prototype) to flatten the chain into an object compatible with mixin.

**Comment by gleborgne** [comment]
I really do understand that you would like to take time to rethink this. 

In the meantime, could you at least publicly expose the object used for storing the fragment constructors in the page module ?  For now it is sealed within the module. It is a 1 line change, no impact from your side. But if you expose it, third parties (like me) could try other ways of defining fragments without relying on a custom build of WinJS.

**Comment by xirzec** [comment]
@gleborgne - Are you talking about this object?

https://github.com/winjs/winjs/blob/master/src/js/WinJS/Pages/_BasePage.js#L25

**Comment by gleborgne** [comment]
Yes exactly
________________________________

**Comment by xirzec** [comment]
Hey @gleborgne, sorry for the delay in getting back to you. I made the change you requested locally, but when I thought about it, are you really getting any benefit from the Pages infrastructure once you go down the path of manually messing around in the viewMap? 

It seems to me you could just replace Pages all up with your own feature built on top of Fragments, and still hook up to Navigation/Application just like how Pages is set up today.

**Comment by gleborgne** [comment]
I could override all page namespace, or use a fork of winjs but I don't want to be intrusive, or hide winjs. I just want to provide additional features. Exposing the container might also provide interesting features like listing loaded pages, define page aliases, ...

**Comment by xirzec** [comment]
@gleborgne - I exposed it as a private member of Pages, so you should be unblocked.

**Comment by gleborgne** [comment]
Thanks a lot

**Comment by gleborgne** [comment]
You were right on the fact that exposing viewMap was not enough to use classes (due to current page implementation). I'm still glad to have it for other use cases. I made a small implementation that replaces WinJS.UI.Pages functions with custom code. It is available at https://github.com/gleborgne/winjscontrib. You could find it in the experiments folder in scripts/winjscontrib/winjscontrib.ui.pages. 

95% of the implementation is in 2 small functions : "merge" and "addMembers", and the good news is that it does not break compatibility.

**Comment by gleborgne** [comment]
any chance that it find its way to 4.0 ? with Windows 10's usage of ES6 at the corner it should be great...

**Comment by gleborgne** [comment]
For those interested in that subject, you could look at this 
http://mcnextpost.com/2015/04/23/winjs-and-es6/

The small update exposing viewMap allows us to reference the page constructor in the proper place, otherwise, controls like SettingsFlyout or HtmlControl does not work perfectly well

**Comment by staxmanade** [comment]
Hey All - stumbled on this thread and also wanted to mention that I'm finding it challenging to work with WinJS while trying to use ES6.

What I'm thinking I'd like to do is define my page as an ES6 Class, but I'm totally hacking the process at the moment.

# How I'm currently creating pages

```
import PageBase from "../PageBase";

export default class Hub extends PageBase {
    constructor() {
        return super("/pages/hub/hub.html");
    }
    ready(element, options) {
        // wire up page
    }
}
```

To accomplish the above, I'm totally abusing the system and below is my `PageBase` hack to make it work (thinking square peg in round hole)
<img src="https://voicesofglass.files.wordpress.com/2012/02/square-peg-in-a-round-hole.jpg" width="100">.

```
export default class PageBase {
    constructor(page) {
        var me = {}
        var that = this;
        Object.getOwnPropertyNames(this.__proto__).forEach(function (key) {
            me[key] = that.__proto__[key];
        });
        return WinJS.UI.Pages.define(page, me);
    }
}
```

The result of the above doesn't actually do anything until you `new` it up once which triggers the `WinJS.Pages.define(...)`.

`new Hub();`

I have't pushed this idea very far yet - just hacked on it recently.

## Why do I want to use classes?

1. As described earlier, it's just easier to reason about.
2. I've been playing with Aurelia's DI container and loving it, so to be able to use to construct page objects with a container would be ideal. Would enable unit testing of a page. While it may be possible in the current WinJS, it's not all that clear to me how I'm going to do it. I may post more here when I get there an figure it out...

Anyway, Just wanted to give some other perspectives to the discussion.

**Comment by jayrenn** [comment]
Thanks for the great dialogue @gleborgne and @staxmanade! We will certainly investigate this for future releases. I have added the request to our internal tracking.

**Comment by gleborgne** [comment]
It' actually easy to implement, and without breaking backward compatibility. I would have made a pull request if I could feel like it has a chance to be accepted

**Comment by jayrenn** [comment]
I'll have a chat with my team, and let you know. Thanks for the offer!
