### ISSUE TITLE
Q: Has anyone created a multi DatePicker with SeZo/GridView ?

### ISSUE THREAD

**Issue by omnoms** [winjs/winjs#905]
I'm about to try to make a multi datepicker with Semantic Zoom (with zoomed out being months and zoomed in is representing days) where a user can select multiple dates for registering an item multiple times on selected days..

Has anyone done this? Best practices to consider? UX guidelines when having selected a few dates in a month; Should the month be semi or fully lit up in the SeZo Out-view when partials of a month has been selected?

**Comment by jseanxu** [comment]
I think this relates to #908.
