### ISSUE TITLE
Binding.List/Namespace: Catch 22 with CreateGrouped ? Also Date() Issue?

### ISSUE THREAD

**Issue by omnoms** [winjs/winjs#906]
I have the following namespace defined... and it seems like I enter a catch 22... the allDays Binding.List has not yet been initialized when the namspace is created and the grouped/projected list, and it throws that allDays is undefined. I tried having [] instead of null as initial data, but that made no difference. I even tried having [new Date()] instead of null, but that made no difference...

```javascript
SCRIPT5009: Unhandled exception at line 5, column 5 in ms-appx://atea.tidforwindows/pages/calendar/calendar.js
0x800a1391 - JavaScript runtime error: 'allDays' is undefined
```

```javascript
    WinJS.Namespace.define("calendarView", {
        allDays: new WinJS.Binding.List(null, { binding: true }),
        groupedDays: allDays.createGrouped(
            function (item) { return new Date(item).getMonth() },
            function (item) { return new Date(item).toLocaleDateString("sv-se", { month: "long"}) },
            function (left, right) { return Date(right) - Date(left) }
            ),
        getAllDays: function () {
            calendarView.allDays.length = 0;
            var s = new Date(new Date().getFullYear(), 0, 1);
            var e = new Date(new Date().getFullYear(), 11, 31);
            calendarView.allDays.push(new Date(new Date().getFullYear(), 0, 1));
            while (s < e) {
                calendarView.allDays.push(s);
                s = new Date(s.setDate(
                    s.getDate() + 1
                ))
            }
        },
        initCalendar: WinJS.Utilities.markSupportedForProcessing(function () {
            calendarView.getAllDays();
            console.log(calendarView.allDays);
            //console.log(calendarView.groupedDays);
        })
    });
```

**Comment by omnoms** [comment]
I'm circumventing this by putting the grouped projection in a different namespace for now... however, a funny thing showed up doing so..

```javascript
    WinJS.Namespace.define("calendarData", {
        groupedDays: calendarView.allDays.createGrouped(
            function (item) { return new Date(item).getMonth() },
            function (item) { return { Month: new Date(item).toLocaleDateString("sv-se", { month: "long" }) } },
            function (left, right) { return Date(right) - Date(left) }
            )
    })
```

Uncommenting the log for calendarData.groupedDays and calling calendarView.initCalendar ... Doing that in the ready-statement of the page I notice that february is listed as the first month, and that december is listed as second, then mars.... Not sure how that is possible?...

**Comment by omnoms** [comment]
![image](https://cloud.githubusercontent.com/assets/7261863/5917416/9d85af8e-a61c-11e4-9142-bbb0546c99b1.png)

**Comment by xirzec** [comment]
To reply to your original issue, you can reference object keys from other values in an object:

```js
var obj = {
   key1: 42,
   key2: key1 // key1 is not a valid identifier
};
```

Nor can you reference the value of obj before it is assigned:

```js
var obj = {
   key1: 42,
   key2: obj.key1 // obj is undefined
};
```

But you could do this:

```js
var obj = {
   key1: 42
};

obj.key2 = obj.key1;
```

So you could use WinJS.Namespace.define multiple times:

```js
WinJS.Namespace.define("calendarView", {
    allDays: new WinJS.Binding.List(null, { binding: true })
});

WinJS.Namespace.define("calendarView", {
    groupedDays: calendarView.allDays.createGrouped(...);
});
```

**Comment by omnoms** [comment]
So basically the way I "circumvented" the issue is the correct way more or less :) Thanks.

Also, since then, I've kept on going, and it seems that the output to the javascript console just seems to misrepresent the array, because when I bind a ListView to it, there are no duplicate month headers, january is there and all that... so it seems to be a glitch in the VS2013 IDE javascript console.
