### ISSUE TITLE
Customizing GridLayout to look more like a calendar that we're accustomed to?

### ISSUE THREAD

**Issue by omnoms** [winjs/winjs#908]
How can I change the order of how the gridlayout starts from top to down and left to right to... left to right and top to down? Like a regular calendar so to speak...

And how can I access the numberOfItemsPerBlock so that each month looks correct and in combination with above, i.e. limit the number of columns per month so that each row is a week.

```javascript
WinJS.Namespace.define("calendarView", {
        allDays: new WinJS.Binding.List(null, { binding: true }),
        allMonths: [],
        getAllDays: function () {
            var days = ['söndag', 'måndag', 'tisdag', 'onsdag', 'torsdag', 'fredag', 'lördag'];
            calendarView.allDays.length = 0;
            calendarView.allMonths.length = 0;
            var s = new Date(new Date().getFullYear(), 0, 1);
            var e = new Date(new Date().getFullYear(), 11, 31);
            var month="";
            var a = []
            while (s < e) {
                month = s.toLocaleString("sv-se", { month: "long" });
                calendarView.allDays.push({ Date: s, DayNum: s.getDate(), DayLoc: days[s.getDay()], Month: month });
                if (calendarView.allMonths.indexOf(month) === -1) calendarView.allMonths.push(month);
                s = new Date(s.setDate(
                    s.getDate() + 1
                ))
            }
        },
        initCalendar: WinJS.Utilities.markSupportedForProcessing(function () {
            calendarView.getAllDays();
            console.log(calendarView.allDays);
            console.log(calendarData.groupedDays);

        })
    });
    WinJS.Namespace.define("calendarData", {
        groupedDays: calendarView.allDays.createGrouped(
            function (item) { return item.Month },
            function (item) { return { Month: item.Month } },
            function (left, right) { return calendarView.allMonths.indexOf(right) - calendarView.allMonths.indexOf(left) }
            )
    });
```

```HTML
        <section class="page-section" aria-label="Main content" role="main">
            <div class="monthTemplate" data-win-control="WinJS.Binding.Template">
                <div style="width: 282px; height: 70px; padding: 5px; overflow: hidden; display: -ms-grid;">
                    <div style="margin: 5px; -ms-grid-column: 2">
                        <h6 data-win-bind="innerText: Month"></h6>
                    </div>
                </div>
            </div>
            <div class="dayTemplate" data-win-control="WinJS.Binding.Template">
                <div style="width: 70px; height: 70px; padding: 5px; overflow: hidden; display: -ms-grid;">
                    <div style="margin: 5px; -ms-grid-column: 2">
                        <h6 data-win-bind="innerText: DayNum"></h6>
                        <h4 data-win-bind="innerText: DayLoc"></h4>
                    </div>
                </div>
            </div>
            <div class="dayHeaderTemplate" data-win-control="WinJS.Binding.Template">
                <div class="simpleHeaderItem">
                    <h1 data-win-bind="innerText: Month"></h1>
                </div>
            </div>
            <div class="customGridLayout" data-win-control="WinJS.UI.GridLayout" data-win-options="{ numberOfItemsPerItemsBlock: 7 }"></div>
            <div data-win-control="WinJS.UI.SemanticZoom">
                <div class="cl_ZoomedIn"
                     data-win-control="WinJS.UI.ListView"
                     data-win-options="{itemDataSource : calendarData.groupedDays.dataSource,
                        itemTemplate: select('.calendar .dayTemplate'),
                        groupDataSource: calendarData.groupedDays.groups.dataSource,
                        groupHeaderTemplate: select('.dayHeaderTemplate'),
                        layout : {type: select('.customGridLayout')}}">
                    >
                </div>
                <div class="cl_ZoomedOut"
                     data-win-control="WinJS.UI.ListView"
                     data-win-options="{itemDataSource : calendarData.groupedDays.groups.dataSource,
                        itemTemplate: select('.monthTemplate'),
                        layout : {type: WinJS.UI.GridLayout}}"></div>
            </div>
        </section>
```

![image](https://cloud.githubusercontent.com/assets/7261863/5921779/a2175136-a646-11e4-8a35-89fb4d52e6a6.png)

**Comment by jseanxu** [comment]
Using the ListView and GridLayout to build a calendar hasn't been one of our targeted use-cases in the past. Here are a few things you could try:

>>How can I change the order of how the gridlayout starts from top to down and left to right to... left to right and top to down? Like a regular calendar so to speak...

You could change the order of your `itemDataSource` so that the layout appears correctly, for example, [1, 4, 7, 2, 5, 8, ...]. You also would need to fix the width of the ListView to be 7 times the size of your item templates.

**Comment by omnoms** [comment]
So if I set the listview width to a specific size, it will fix the number of columns? How about the number of rows?

**Comment by omnoms** [comment]
I first adjusted the .win-semanticzoom height to 600px and that made it look like it would fit it to 7 columns... but since the rendering order is still "top to down, left to right".... even if I would change the internal order of the dates, a month with less than stellar amount of days will show up wrong because the last item will be rendered on it's own on the top right.

I.e. for january, without changing the internal order, the last item is 31:st on the top right... if I had changed the internal order I would have had the 7th there, but the 14th would never be rendered underneath it because it's still rendering them in the wrong order.

![image](https://cloud.githubusercontent.com/assets/7261863/5954038/4487ab04-a792-11e4-8620-a32d48bd597f.png)

**Comment by omnoms** [comment]
I think I'll resolve it by padding the start and end of each month to reach a full week (like Outlook does). Then I guess I'll do some array-mapping to sort each month internally based on Date().getDay(a) - Date().getDay(b)

**Comment by omnoms** [comment]
There is a certain performance hit with the padding, so I'll keep it to a minimum and not pad the end of the month and thus also keeping the top-to-bottom-left-to-right rendering and not emulate the other way around...

So far...

![image](https://cloud.githubusercontent.com/assets/7261863/5954666/c621faa4-a79a-11e4-96a7-1f347beb18c4.png)

**Comment by omnoms** [comment]
I tried changing the flex-flow from column wrap to row wrap, but encountered issues since it still creates itemblocks that don't fit together in that mode. And changing the artificial order of the weekdays per month to make it look like it's being rendered the other way around took a serious performance hit so it's not viable on the phone. So it will have to be like this, for now.
