### ISSUE TITLE
ListView: Keyboard focus indicator doesn't appear on ListViews in try site

### ISSUE THREAD

**Issue by TheWrathOfConst** [winjs/winjs#913]
Repro steps:
1) Click a ListView item in any ListView on the try site
2) Press left/right/up/down arrow key

Expected: White border should appear around item
Actual: No item appears

I couldn't repro this locally, so it may be an issue with styles on the try site.

**Comment by xirzec** [comment]
The problem appears to be here: https://github.com/winjs/winjs/blob/9bcb0eb6b93aee2e59cc8be7636370ab58bbbeab/src/less/styles-listview.less#L97-L106

Changing this to `calc(100% - 4px)` and left/top of `2px` seems to fix the behavior.
