### ISSUE TITLE
Q: WinJS.Binding.converter not updating when list is notifying changes... ?

### ISSUE THREAD

**Issue by omnoms** [winjs/winjs#921]
So I have this little list...

```javascript
    WinJS.Namespace.define("newLogView", {
        selectedDates: new WinJS.Binding.List([new Date()], { binding: true }),
        ...
    });
```

and it's little helper converter

```javascript
    WinJS.Namespace.define("newLogView", {
        datesConv: WinJS.Binding.converter(function (item) { console.log(item); return item.sort().map(function(item) { return Windows.Globalization.DateTimeFormatting.DateTimeFormatter("shortdate", ["sv-SE"]).format(new Date(item)); }).join(", ") })
    })
```

Basically, I'm trying to flatten a list of dates into a string for representation in a simple &lt;input&gt;

The converter works for the initial value that is set on selectedDates, but any changes to the list/array and it doesn't update the UI... not even if I run notifyReload()

```HTML
<input class="datePicker" type="text" data-win-bind="value: view.selectedDates newLogView.datesConv" readonly style="width: 96.3%" />
```

What am I doing wrong?

Also I had to explicitly write newLogView.datesConv instead of using the view.datesConv that the WinJS.Binding.processAll method's context is for some reason... ?

```
            var context = {
                data: Data.NewLog,
                view: newLogView
            }
            //console.log(element, context);
            WinJS.Binding.processAll(element,context).then(function (item) {
                ...
            }).bind(this);
```

**Comment by omnoms** [comment]
I have, for now, resorted to running another WinJS.Binding.processAll() on the entire page which updates the input.

**Comment by xirzec** [comment]
If you remove the binding converter, do the bindings update as expected? Or is it only when you have a custom converter that they stop updating when you update the source Binding.List?

A reduced repro with actual and expected results would help us to diagnose this.

**Comment by omnoms** [comment]
I wouldn't know if it updated since binding a list without a converter to a simple input-element it will always print out [object Object].

**Comment by rigdern** [comment]
@omnoms, can you share a small page or Visual Studio solution which reproduces the bug and describe the expected and actual behavior you are seeing in this reduced repro? You can upload your page/solution to OneDrive as described on [our wiki](https://github.com/winjs/winjs/wiki/How-to-share-repros-of-issues-with-WinJS#sharing-videos-and-full-code-samples).

**Comment by omnoms** [comment]
Here's a reduced repro;

http://1drv.ms/1FRrBHg

**Comment by rigdern** [comment]
Thanks for the repro app. It was very helpful!

It seems the problem you are running into is that `WinJS.Binding.List` does not work with the declarative data binding of `data-win-bind`.

When using a `WinJS.Binding.List`, you typically want to render each of its items into your UI. The typical way to do that is to use a control such the `Repeater`, `FlipView` or `ListView` which knows how to render a collection and monitor it for modifications.

If your example doesn't require the `Binding.List` to be rendered into an `input` field, you can use a `Repeater` to render it into a `div` like this (paste the snippets into the [Try Site Playground](http://try.buildwinjs.com/#play)):

```js
// JavaScript

var Person = WinJS.Class.define(function (date) {
	this.date = date;
}, {
	formattedDate: {
		get: function () {
			//return Windows.Globalization.DateTimeFormatting.DateTimeFormatter("day", ["sv-SE"]).format(this.date);
            return this.date.getDate();
		}
	}
});

var myArray = new WinJS.Binding.List([new Person(new Date())]);
WinJS.Namespace.define("simpleView", {
    myArray: myArray.createSorted(function (a, b) {
        a = new Date(a.date);
        b = new Date(b.date);
        if (a > b) {
            return 1;
        } else if (a < b) {
            return -1;
        } else {
            return 0;
        }
    }),
    addContentToArray: WinJS.Utilities.markSupportedForProcessing(function () {
        var tArr = [];
        var tDate = new Date();
        for (var i = 0; i < Math.floor(Math.random() * 10) + 1; i++) {
            myArray.push(new Person(new Date(tDate.setDate(tDate.getDate() + i))));
        }
    })
});

WinJS.UI.processAll();
```

```html
<!-- HTML -->

<button onclick="simpleView.addContentToArray();">Add items</button>
<div class="date-repeater" data-win-control="WinJS.UI.Repeater" data-win-options="{ data: simpleView.myArray }">
	<span class="date"><span data-win-bind="textContent: formattedDate"></span><span class="comma">, </span></span>
</div>
```

```css
/* CSS */

/* Hide the last comma */
.date-repeater > .date:last-child > .comma {
    display: none;
}
```

**Comment by omnoms** [comment]
It's a form that to keep things in line with "how they used to be", it has to stay looking like a form. 
They input dates, times, SLAs, descriptions, etc. for a resource log so it's sort of vital that the user understands that they can edit/change the content by clicking at it.

Having repeating div-elements that seem like just random text on the display not showing that they can either change or push it does nothing for the user. So it's either rebuilding a layout/controller to simulate something that fits into a form with a repeater or use the input so that it's inline and understandable for the users.

**Comment by rigdern** [comment]
I see, so you want to bind the contents of a `Binding.List` to an `input` element.

Data contexts are meant to hold objects which only hold data. They are not meant to hold objects which contain behavior (e.g. methods). A `Binding.List` has behavior/methods on it so it shouldn't be put into a data context.

One solution to your problem is to listen to the `Binding.List`'s change events and use those as a cue for updating your `input` element. In the snippet below, I created `simpleView.BoundInput` as a control that does just that. You can try the following snippets out on the [Try Site Playground](http://try.buildwinjs.com/#play).

```js
// JavaScript

var myArray = new WinJS.Binding.List([new Date()]);
WinJS.Namespace.define("simpleView", {
    flattenArrayMapper: WinJS.Utilities.markSupportedForProcessing(function (arr) {
        return arr.map(function (obj) {
            //return Windows.Globalization.DateTimeFormatting.DateTimeFormatter("day", ["sv-SE"]).format(obj.date);
            return obj.getDate();
        }).join(", ");
    }),
    myArray: myArray.createSorted(function (a, b) {
        a = new Date(a.date);
        b = new Date(b.date);
        if (a > b) {
            return 1;
        } else if (a < b) {
            return -1;
        } else {
            return 0;
        }
    }),
    addContentToArray: WinJS.Utilities.markSupportedForProcessing(function () {
        var tArr = [];
        var tDate = new Date();
        for (var i = 0; i < Math.floor(Math.random() * 10) + 1; i++) {
            myArray.push(new Date(tDate.setDate(tDate.getDate() + i)));
        }
    }),
    BoundInput: WinJS.Class.define(function (element, options) {
        var data = options.data;
        var mapper = options.mapper;

        var dataListeners = [
            "itemchanged",
            "iteminserted",
            "itemmoved",
            "itemremoved",
            "reload"
        ];
        var updateInput = function () {
            element.value = mapper(data);
        };

        var pendingUpdatePromise;
        dataListeners.forEach(function (eventName) {
            data.addEventListener(eventName, function () {
                if (!pendingUpdatePromise) {
                    // Use Promise.timeout to batch multiple Binding.List notifications into
                    // a single call to updateInput.
                    pendingUpdatePromise = WinJS.Promise.timeout().then(function () {
                        pendingUpdatePromise = null;
                        updateInput();
                    });
                }
            });
        });
        updateInput();
    })
});

WinJS.UI.processAll();
```

```html
<!-- HTML -->

<button onclick="simpleView.addContentToArray();">Add items</button>
<input data-win-control="simpleView.BoundInput" data-win-options="{
    data: simpleView.myArray,
    mapper: simpleView.flattenArrayMapper
}" />
```

**Comment by omnoms** [comment]
That looks quite interesting. I'll have to keep that in mind. I have a few places where I would need to listen to the change-events of lists which would be a better way to fire off certain functions.

Are there any pros/cons to how I've done my workaround now with a processAll for the simple use-case we have here? Performance hits? Other bugs I might invoke?

**Comment by rigdern** [comment]
### Calling processAll multiple times
Yes, the major downside to the workaround of calling `WinJS.Binding.processAll` every time your list changes is that you are hooking up duplicate bindings. Here's an experiment you can do to see this:
  - Call `WinJS.Binding.processAll` 5 times on the same data bindings
  - Put a `console.log` in your converter
  - Change some data to cause your converter to run
  - You'll see that for a single data change, the converter will run 5 times

To avoid this, you can use a different technique for getting the bindings to update. Instead of calling `WinJS.Binding.processAll`, you can make use of the [`observableMixin`'s `notify` method](https://msdn.microsoft.com/en-us/library/windows/apps/hh701045.aspx). Whenever you edit your `WinJS.Binding.List`, you can call it like this (assuming `context` is your data context and `myArray` is your `Binding.List`):
  ```js
context.view.notify("myArray", context.view.myArray, context.view.myArray);
  ```

### Methods in your data context
As I stated in an earlier post, data contexts should only contain data. They should not contain behavior/methods. The reason is that `this` will not be bound to the expected object within the method. It'll be bound to the observable version of the object rather than the original object. This is especially problematic when the original object has non-enumerable properties because those are ignored by `Binding.as` and do not get copied over to the observable version of the object.

**Comment by omnoms** [comment]
Not entirely sure how I should split up/modify the project to suit the observableMixin method of handling all of this. Could you modify the simpleView accordingly? And considering your statement about not having methods/behaviours in datacontexts, should I then split out from my viewModels, that I bind to in the WinJS.Binding.processAll context, all the converters, helper functions, etc. ?

**Comment by rigdern** [comment]
> Not entirely sure how I should split up/modify the project to suit the observableMixin method of handling all of this. Could you modify the simpleView accordingly?

Anytime your `Binding.List` is modified, the data context which references it needs to be notified of the change. Anytime you create a data context which references a `Binding.List`, you can register for the `Binding.List`'s modification events (itemchanged, iteminserted, etc.) and call the `notify` method in each of the event handlers.

> And considering your statement about not having methods/behaviours in datacontexts, should I then split out from my viewModels, that I bind to in the WinJS.Binding.processAll context, all the converters, helper functions, etc. ?

Yes, I would avoid putting converters and helper functions in your data contexts.

**Comment by omnoms** [comment]
So basically;

```javascript
WinJS.Namespace.define("simpleContext", { 
   myArray: new WinJS.Binding.List([])
});

WinJS.Namespace.define("simpleUtils", {
   notifyHandler: WinJS.Utilities.markSupportedForProcessing(function() {
      simpleContext.notify("myArray", simpleContext.myArray, simpleContext.myArray);
   })
});
```

and in the ready statement;

```javascript
["itemchanged","iteminserted",...].forEach(function(item) {
   simpleContext.myArray.addEventListener(item, simpleUtils.notifyHandler, false);
});
```

but I recon I also would have to do this (?)

```javascript
WinJS.Binding.mixin(simpleContext, WinJS.Binding.observableMixin);
```

**Comment by rigdern** [comment]
> but I recon I also would have to do this to add the "notify" method to the context (?)
> `WinJS.Binding.mixin(simpleContext, WinJS.Binding.observableMixin);`

Instead of this, you should use [`WinJS.Binding.as`](https://msdn.microsoft.com/en-us/library/windows/apps/br229801.aspx) on the context. Like this:

```js
// This makes simpleContext observable.
var simpleContext = WinJS.Binding.as({
   myArray: new WinJS.Binding.List([])
});

WinJS.Namespace.define("App", {
  simpleContext: simpleContext
});
```

and then:

```js
WinJS.Binding.processAll(element, { view: simpleContext });
```

**Comment by omnoms** [comment]
Alright! I'll go at it when time opens up for that project again :)
