### ISSUE TITLE
How to style for high contrast black theme?

### ISSUE THREAD

**Issue by pke** [winjs/winjs#923]
I wonder how we should use styles in our WinJS apps to be ready for users that use high contrast colour themes in their Windows environment? It seems that WinJS CSS is almost ready for it, yet my custom style rules do not adapt correctly. For instance I have a `canvas` element that should have a white background and black pen colour. When I switch to a high contrast theme the canvas gets black and the pen colour remains black. Why is that so?

**Comment by xirzec** [comment]
Interesting, I'm not familiar with how the canvas tag works in high contrast. I'm surprised the default background color changes. You should be able to re-style it with a -ms-high-contrast rule though:

https://msdn.microsoft.com/en-us/library/windows/apps/hh700340.aspx

**Comment by AmazingJaze** [comment]
@pke are you sure that the canvas pen color is style-able through CSS? 
This thread on stackoverflow may be relevant: http://stackoverflow.com/questions/14082669/set-html5-canvas-font-color-using-css
