### ISSUE TITLE
App bar eclipse button doesn't have specified type.

### ISSUE THREAD

**Issue by andrii-morozov** [winjs/winjs#925]
Because different browsers have different default type for html tag 'button' it causes specific issues when type is not specified. For example in chrome default type is submit so clicking on eclipse app bar button which should just hide app bar causes form submit.

Is is recommended to always specify button type because specification doesn't contains definition for the default type.

References:
https://github.com/winjs/winjs/blob/d8b0d2207f4c534484ec0d4c474be7b3da7d8614/src/js/WinJS/Controls/AppBar.js#L378

**Comment by rigdern** [comment]
Let's audit all of our buttons and make sure we specify a `type` for them.

**Comment by xirzec** [comment]
Looks like Toolbar, SemanticZoom, and Pivot are affected.
