### ISSUE TITLE
Listview not properly refreshed when datasource items change for first time

### ISSUE THREAD

**Issue by pke** [winjs/winjs#927]
I have the strange behaviour that my listview is empty despite its datasource containing 2 elements.
This not always happens but my workflow is as follows:
I download a XML file from the web and fill my models BindingList with it. The list gets properly updated but the listview does not show the downloaded data. Only when I force a second refresh of the date it appears in the listview.
The DOM of the listview only contains an empty layout.

![image](https://cloud.githubusercontent.com/assets/164625/6196347/0293ea4e-b3d8-11e4-81ec-306308513f1f.png)

**Comment by rigdern** [comment]
Can you provide a page/app that reproduces this bug? You can attach the reduced repro to OneDrive as described on the [wiki](https://github.com/winjs/winjs/wiki/How-to-share-repros-of-issues-with-WinJS).

**Comment by pke** [comment]
I try to reproduce this in a new project. The bug is not solved.

**Comment by xirzec** [comment]
@pke  Can you share your repro with us?

**Comment by pke** [comment]
@xirzec sure thats the plan, as soon as I have the behaviour reproduced.

**Comment by xirzec** [comment]
@pke Whoops, sorry I originally read your reply as "I reproduced this in a new project. The bug is not solved."
