### ISSUE TITLE
Make ContentDialog control support Narrator scenario

### ISSUE THREAD

**Issue by mkjunior19** [winjs/winjs#928]
Must-have feature: 
* When you put focus on a dialog button using tab key, narrator should say “[button text] button”

Nice-to-have features: 
* Try using header for Dialog title so that narrator says “[Dialog title] header” - either use h2 element or use aria role = header
* Ensure that while the dialog is up, there is no way for a narrator user to be able to go through content behind the dialog -  Adam has already looked into this and there's no good way to solve it. AppBar has the same problem.

**Comment by rigdern** [comment]
> Must-have feature:
> 
> - When you put focus on a dialog button using tab key, narrator should say “[button text] button”
Nice-to-have features:

This doesn't repro.

>
> Nice-to-have features:
> - Try using header for Dialog title so that narrator says “[Dialog title] header” - either use h2 element or use aria role = header

Opened #1176 to track this.

> - Ensure that while the dialog is up, there is no way for a narrator user to be able to go through content behind the dialog - Adam has already looked into this and there's no good way to solve it. AppBar has the same problem.

As stated here, there's no good way to solve this problem.
