### ISSUE TITLE
Audit WinJS CSS for styles that make sense for apps but probably not for the web

### ISSUE THREAD

**Issue by banguero** [winjs/winjs#93]
Following up on the comments on #90, we should go though the WinJS CSS and determine if there are styles that make sense for apps but probably not for the web.

Some examples:
1) It currently disables text selection. Most sites, will end up having to override that.

html,
body {
  -moz-user-select: none;
  -webkit-touch-callout: none;
  -webkit-user-select: none;
  -khtml-user-select: none;
  -ms-user-select: none;
}

2) <a> tags don't show the default cursor:pointer, because WinJS CSS has:

a {
  cursor: default;
  text-decoration: none;
}

Others?

**Comment by jayrenn** [comment]
This is a good idea. We have added it to our internal tracking.
