### ISSUE TITLE
SplitView: I can't make it work

### ISSUE THREAD

**Issue by MartiBravNav** [winjs/winjs#930]
Feature: SplitView
I'm currently trying to make an splitview. I have copied the same code again and again from Winjs web, but the codeo doesn't seems to work. The app opens with the SplitView Pane in full screen and when I click the hamburguer icon, menu doesn't close. And the Content area appears down the Splitview pane

![asfasd](https://cloud.githubusercontent.com/assets/2543510/6200450/3ceb4eac-b479-11e4-9294-12ea38a53a93.PNG)

**Comment by AmazingJaze** [comment]
It looks like you may not be calling Winjs.UI.processAll() to instantiate your "data-win-control" markup.

Sent from my Windows Phone
________________________________

**Comment by MartiBravNav** [comment]
How can I fix it?  @AmazingJaze

**Comment by AmazingJaze** [comment]
To get something running up and quickly in the browser, you can just wire a call to processAll from the DOMContentLoaded event
```js
function initialize() {
    WinJS.UI.processAll();
}
document.addEventListener("DOMContentLoaded", initialize(), false);
```
__More info from MSDN:__ https://msdn.microsoft.com/en-us/library/windows/apps/hh465493.aspx​<
<h2> Adding a WinJS control in markup </h2>
Unlike HTML controls, WinJS controls don't have dedicated markup elements: you can't create a Rating control by adding a <rating /> element, for example. To add a WinJS control, you create a div element and use the data-win-control attribute to specify the type of control you want. To add a Rating control, you set the attribute to "WinJS.UI.Rating".

You must also call the WinJS.UI.processAll function in your JavaScript code. WinJS.UI.processAll parses your markup and instantiates any WinJS controls it finds.

**Comment by pag3** [comment]
Which version of WinJS are you using?  The last official version (3.0) didn't include the SplitView control yet, but it's available in the latest bits you can build following these instructions: https://github.com/winjs/winjs#build-winjs. It will be included by default in the next official release.

**Comment by MartiBravNav** [comment]
I'm using WinJS version 3.0.1.

Enviat des del meu Windows Phone
________________________________
De: Paul A. Gusmorino 3rd<mailto:notifications@github.com>
Enviat el: ‎16/‎02/‎2015 19:15
Per a: winjs/winjs<mailto:winjs@noreply.github.com>
A/c: MartiBravNav<mailto:seormarti@outlook.com>
Tema: Re: [winjs] SplitView: I can't make it work (#930)

Which version of WinJS are you using?  The last official version (3.0) didn't include the SplitView control yet, but it's available in the latest bits you can build following these instructions: https://github.com/winjs/winjs#build-winjs. It will be included by default in the next official release.

---

**Comment by rigdern** [comment]
3.0.1 doesn't include SplitView. As @pag3 mentioned, it'll be included in the next release and if you'd like to use it today, you'll have to checkout our master branch and build it.

**Comment by MartiBravNav** [comment]
Thank you so much, I built WinJS 4.0 and it worked perfectly.
Sent from my Windows Phone
________________________________
De: Adam Comella<mailto:notifications@github.com>
Enviat el: ‎18/‎02/‎2015 19:10
Per a: winjs/winjs<mailto:winjs@noreply.github.com>
A/c: MartiBravNav<mailto:seormarti@outlook.com>
Tema: Re: [winjs] SplitView: I can't make it work (#930)

3.0.1 doesn't include SplitView. As @pag3 mentioned, it'll be included in the next release and if you'd like to use it today, you'll have to checkout our master branch and build it.

---
