### ISSUE TITLE
Pivot on Android device

### ISSUE THREAD

**Issue by AlexFromGPec** [winjs/winjs#931]
I am writing a Cordova app with WinJS, when running the Cordova app on Android device,
I can only slide the Pivot by header area, and can't slide the Pivot elsewhere. But if I run the Cordova app on Windows device, I can slide the Pivot everywhere.

**Comment by pag3** [comment]
Which version of WinJS are you using?  Try against the latest bits off GitHub and you should see it working.

**Comment by AlexFromGPec** [comment]
Thanks. I am using WinJS 3.0.1, and I will try the latest bits off GitHub.

**Comment by AlexFromGPec** [comment]
I just try anainst the latest bits off GitHub, the Pivot in Cordova app is ok on Android device. Thanks a lot.
