### ISSUE TITLE
SplitView: Problem with Splitview / querySelector

### ISSUE THREAD

**Issue by vitorgrs** [winjs/winjs#936]
Here go the project and the code that I trying to create
https://onedrive.live.com/redir?resid=4CC7E33166A7D29!480896&authkey=!AFdTdGMkFyIRpAk&ithint=file%2crar

Feature: SplitView
Environment: Mozilla/5.0 (Windows NT 10.0; WOW64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/41.0.2272.43 Safari/537.36 OPR/28.0.1750.21 (Edition beta)
Source: http://try.buildwinjs.com

**Comment by rigdern** [comment]
The problem here is that `WinJS.UI.processAll` is being called before the DOM is ready so `document.body` is null. You can fix this by waiting for `DOMContentLoaded` before calling `processAll`. WinJS has a helper for this called [`WinJS.Utilities.ready`](https://msdn.microsoft.com/en-us/library/windows/apps/br211903.aspx).

The fix to your app looks like this:

```js
WinJS.Utilities.ready(function () {
    WinJS.Binding.processAll(null, Sample).then(function () {
        WinJS.UI.processAll().done(function () {
            // The problem is here >>>
            Sample.splitView = document.querySelector(".splitView").winControl;
            new WinJS.UI._WinKeyboard(Sample.splitView.paneElement); // Temporary workaround: Draw keyboard focus visuals on NavBarCommands
        });
    })
});
```

**Comment by vitorgrs** [comment]
Thanks! Worked great!

**Comment by litunny** [comment]
Hello, please the same issue here, my javascript is throwing error "0x800a138f - JavaScript runtime error: Unable to get property 'winControl' of undefined or null reference"

Please totally fed up, I have carried out the above solutions, but nothing change and still bringing the same error message, please help, maybe I'm doing some wrong things somewhere else. Thanks in advance.

**Comment by xirzec** [comment]
@litunny - Please open a new issue and provide repro steps.

**Comment by lemessa** [comment]
its not allowed in strict mode to access the function WinJS.UI._WinKeyboard(Sample.splitView.paneElement)? any of u guys have a solution.
