### ISSUE TITLE
AutoSuggestBox Try Site Sample: Result images flicker while typing

### ISSUE THREAD

**Issue by rigdern** [winjs/winjs#937]
1. Go to http://try.buildwinjs.com/#searchbox
2. Start typing in the AutoSuggestBox sample which shows the "Mint" recommendation with an image

**Unexpected result:** As you type, the images in the search results flicker.

Feature: AutoSuggestBox
Environment: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.115 Safari/537.36
Source: http://try.buildwinjs.com

**Comment by jayrenn** [comment]
The SearchBox control has been deprecated. Please use the AutoSuggestBox control

**Comment by rigdern** [comment]
This also repros in the `AutoSuggestBox`. Reopening and rephrased the title/description to be in terms of `AutoSuggestBox`.
