### ISSUE TITLE
Why does isDeclarativeControlContainer appear in the d.ts for SemanticZoom?

### ISSUE THREAD

**Issue by rigdern** [winjs/winjs#938]
[`isDeclarativeControlContainer` appears in the d.ts for SemanticZoom](https://github.com/winjs/winjs/blob/e90b9045342dd5972c6ea9c74464516182b85006/typings/winjs/winjs.d.ts#L7145) but I do not see a reference to `isDeclarativeControlContainer` in the SemanticZoom source code.

Should we delete this reference from the d.ts?

**Comment by rigdern** [comment]
We think it used to be called. Let's look at the history and see if it was deleted at some point.

**Comment by mikewjackson** [comment]
We are tracking this internally as a planned task.
