### ISSUE TITLE
FlipView: Doesn't support touch in iOS (and Android?) browser

### ISSUE THREAD

**Issue by BrandonLive** [winjs/winjs#941]
Feature: FlipView
Source: http://try.buildwinjs.com

I was demonstrating the FlipView control to my team today for possible use in one of our projects (and showing how the same control nicely handles mouse and touch interactions), but was disappointed to find it doesn't support touch interactions (i.e. swipe/pan) in Safari on iOS 8, and instead shows the arrow buttons. I haven't tried Android but suspect the same may be true there. While the lack of pointer events and/or scroller snap points may pose challenges here, the generally high UI thread performance at least on iOS should make a reasonable implementation possible.

**Comment by xirzec** [comment]
@BrandonLive You are correct that it's because of a lack of snap points. We thought about trying to fake it with JS, but we were worried about the performance characteristics of panning as well as creating a lot of complexity in the control that could be a source of hard to fix bugs.

**Comment by BrandonLive** [comment]
Well, that's pretty core functionality for a flipper control, and since it's been solved for the WinJS Pivot control I assume the same solution could be implemented here :-)

**Comment by xirzec** [comment]
It's not solved in Pivot. We detect the swipe gesture and navigate, but we don't try to stick to your finger like FlipView does.

**Comment by BrandonLive** [comment]
Well, that would be a minimal implementation for the FlipView and better than falling back to the buttons, though I'm pretty sure other libraries do the full manipulation (just handling input on the UI thread). Unless you have reason to believe Apple and Google will be supporting snap points soon...

Sent from my Windows Phone
________________________________

**Comment by rigdern** [comment]
If we bring Pivot's technique to FlipView, we should also consider bringing it to NavBarContainer and other similar controls.

**Comment by jayrenn** [comment]
Thank you for your suggestion! This is a reasonable request. I have added this item to our internal tracking.
