### ISSUE TITLE
Snapping a wide gridlayout listview to header positions?

### ISSUE THREAD

**Issue by omnoms** [winjs/winjs#943]
So... back to this giant calendar... a gridlayout listview that contains 408 elements (months with padding) with 12 headers. Each month has either 5 or 6 columns, which means I can't use CSS -ms-scroll-snap* stuff to set a fixed interval.

How can I go about making it userfriendly with snap-points when side-scrolling this calendar? Is there an equivalent to _getItemOffsetPosition for headers?

**Comment by omnoms** [comment]
I've tried with this snippet that I thought would do it, but the snapping points are still off despite how regardless of how much I adjust for margins.

```javascript
                        //Get and set snapppoints
                        var els = document.querySelectorAll(".win-groupheadercontainer");
                        if (els && els.length > 0) {
                            var monthWidths = "0px";
                            for (var i = 0; i < els.length; i++) {
                                var px = Number(els[i].style.maxWidth.substr(0, els[i].style.maxWidth.length - 2));
                                px +=100;
                                monthWidths += "," + px + "px";
                            }
                            var viewport = document.querySelector(".win-listview>.win-horizontal.win-viewport");
                            if (viewport) {
                                console.log(monthWidths);
                                viewport.style.msScrollSnapType = "proximity";
                                viewport.style.msScrollSnapPointX = "snapList(" + monthWidths + ")";
                            }
                        }
```

**Comment by omnoms** [comment]
Encountered another nice little bug which makes my manual snap-point handling moot.... it's when it re-reads the entire page from cache it drops the snapopints and the onloadingstatechanged calls "complete" when only 6 or 5 months have rendered and never when it has added all 12 months... so I can't loop through all the groupheaders....

**Comment by omnoms** [comment]
a final work around was to do this;

```
   if (i < 10) px += 70;
   else px += 44;
```

because it overshot the "last" snap-point by 26 pixels, it wouldn't snap to it at all. And the number 44 or 26 is not found anywhere that I could see in terms of margins, paddings, or offsets or in combination of those. So this is the manual workaround...

But alas... it can only set these snappoints the first time it's rendered, after that it's not re-entered into the CSS by the cache-functionality, and the previous scrolling bug prevents me from setting it once. I don't want to set it each time someone scrolls the list like the "complete"-loadingstate now operates.

**Comment by xirzec** [comment]
@omnoms - This isn't one of the design goals for the ListView, that being said couldn't you add padding to months with 5 columns so that you have a consistent snap-point width?

**Comment by omnoms** [comment]
For quite a few months, I would have to add an entire week if not more at the end that goes into the next month.

But the workaround works for now :) Even if I don't know where 44 pixels comes from, it works.

**Comment by omnoms** [comment]
Also, the reason it's not setting the snap points seems to be related to somehow my listview firing off an indefinite amount of loadingstatechanged events when re-read from cache. Not managed to reproduce it with a clean new project, I've sent it all to @rigdern in #945

**Comment by omnoms** [comment]
Since #945 is now closed/solved, I can live with the workaround :)
