### ISSUE TITLE
WinJS.UI.ListView onloadingstatechanged called indefinitely.

### ISSUE THREAD

**Issue by omnoms** [winjs/winjs#945]
```HTML
                <div class="cl_ZoomedIn"
                     data-win-control="WinJS.UI.ListView"
                     data-win-options="{itemDataSource : calendarData.groupedDays.dataSource,
                        itemTemplate: select('.calendar .dayTemplate'),
                        groupDataSource: calendarData.groupedDays.groups.dataSource,
                        groupHeaderTemplate: select('.dayHeaderTemplate'),
                        onloadingstatechanged : calendarView.calendarLoadingHandler,
                        oniteminvoked: calendarView.calendarSingleClickHandler,
                        selectionMode: 'multi',
                        tapBehavior: 'toggleSelect',
                        layout : {type: select('.customGridLayout')}}">
                    >
                </div>

```

onloadingstatechanged is called quite often, but the one time it's relevant for me is when the state is "complete". so I run a few lines of code everytime it enters the complete state just so the user doesn't have to wait for it to populate with calendarevents and such.

Unfortunately, there's something going off spamming the loadingstatechanged events indefinitely until a user moves the viewport when it has been re-read from cache...

Email with full project is being sent to @rigdern .

**Comment by rigdern** [comment]
I looked into this. The code in the app's `loadingstatechanged` handler is putting the ListView into an infinite loop. It continually sets the `scrollPosition` to the same value which causes the ListView to reload. To avoid this, you could make sure the ListView isn't already at the desired scroll position before setting it.

I also noticed that the app is calling ListView's `_getItemOffsetPosition` method which is a private method (note the underscore) and is not supported. WinJS makes no guarantees about what will happen when you call this method.

**Comment by omnoms** [comment]
that's strange, cuz I am doing the same kind of setting of the scrollPosition in my attempt to recreate the issue but didn't get the same kind of loop and it always scrolled to the right position. I've now added the check...

And yeah, I know it's private. But it's faster than traversing the DOM and figuring out the position of an item that I want to scroll to that way.
