### ISSUE TITLE
Renamed Github account - please change in wiki of approved contributors.

### ISSUE THREAD

**Issue by canalboy** [winjs/winjs#947]
Hey @xirzec, I've once again changed my Github handle. Would it be possible to reflect this on the wiki? I would like to change the line `Panaminion (formerly ericjimenez)` to `canalboy`. Sorry to trouble you.

**Comment by xirzec** [comment]
Hi @canalboy - We're actually going to be updating our CLA process soon to have a fancy robot and automated checking per Pull Request. It should be in place soon (hopefully before your next PR) so no worries! :+1:
