### ISSUE TITLE
ListView selection checkmark misaligned

### ISSUE THREAD

**Issue by TheWrathOfConst** [winjs/winjs#954]
The new checkmark is sized differently than the old one, so now the alignment's all messed up:

![misaligned](https://cloud.githubusercontent.com/assets/6990048/6511268/9578aa6e-c320-11e4-9842-860c1f2c094c.png)

**Comment by phosphoer** [comment]
Do you have a repro page of this? I'm not sure how to get the checkmark on the left side. 

My test page:

![image](https://cloud.githubusercontent.com/assets/3892683/6512709/c6415510-c32a-11e4-9795-7bf492c0c2a2.png)

It looks like it is maybe a pixel or two off to the right, but not nearly as bad as your example.
