### ISSUE TITLE
Pivot header incorrectly rendered when style is applied

### ISSUE THREAD

**Issue by spruzzer** [winjs/winjs#956]
Pivot styling according #703 does not work properly on iOS, Safari, Firefox and Android (Cordova) by using the last winjs build (works instead for winjs3). They are incorrectly displayed. 
![screen shot 2015-03-06 at 15 33 10](https://cloud.githubusercontent.com/assets/11350175/6528367/c8bde7e8-c421-11e4-9a73-38f09a1633f6.png)

**Comment by rigdern** [comment]
Are you trying to style the Pivot headers in your app? This is currently not supported as described in #703.

Are you using the WinJS stylesheet from the build that your WinJS.js file came from?

If none of these questions helps you fix your problem, can you share an app/page which repros the bug with us? You can attach it to OneDrive as described in [our wiki](https://github.com/winjs/winjs/wiki/How-to-share-repros-of-issues-with-WinJS).

**Comment by spruzzer** [comment]
By using the stylesheet from the WinJS build I obtain the predicted result. Thanks.

![screen shot 2015-03-07 at 10 27 55](https://cloud.githubusercontent.com/assets/11350175/6540848/c9091c02-c4b4-11e4-88d0-d1bc3709aba3.png)
