### ISSUE TITLE
What is the standard/best practice for CSS layout when using WinJS on a Windows 8.1 phone?

### ISSUE THREAD

**Issue by mtycholaz** [winjs/winjs#958]
Normally when I code a website, I'd download bootstrap and utilize it's responsive approach for my app. Twitter Bootstrap has lots of CSS put in for formatting, and layout (buttons, forms, panels, etc).

What I'm wondering is how to accomplish all this using the WinJS light/dark themes on a Windows Phone. As a new developer, it would appear that the CSS in WinJS is basically for the components. 

Is there a particular CSS bootstrap library that is compatible with WinJS?
Or are there plans to add layout CSS to WinJS?

Can anyone share what there preferences are when using WinJS on a Windows Phone app?

**Comment by xirzec** [comment]
@mtycholaz We're actually working on a theme for Bootstrap, but it's not quite ready to put up on GitHub yet. You can watch its future repository for updates:

https://github.com/winjs/bootstrap-winjs

**Comment by mtycholaz** [comment]
This sounds exactly what I'm looking for. Good things come to those who wait.
