### ISSUE TITLE
Please add more "under-the-hood" to try.buildwinjs.com

### ISSUE THREAD

**Issue by arangas** [winjs/winjs#959]
I'm not sure if this is the correct place to request this but I couldn't find a repo for the try site. Please let me know if this needs to be changed!

The try site is really awesome, interactive, clear, top stuff. However it seems to be missing more under-the-hood things like bindings, observables, mixins, classes, namespaces like WinJS.Utilities. Well, they are probably there but mixed in with all of the cool UI stuff. These are really important so people learning can see the correct patterns to use, and when to use them.

**Comment by rigdern** [comment]
We really appreciate the feedback to help make the Try Site better! We'll keep this in mind as we move forward.

**Comment by jayrenn** [comment]
Thanks for the request! We'll certainly consider adding this in the future.

Related: https://github.com/winjs/winjs/issues/52#issuecomment-111244093
