### ISSUE TITLE
Promise: resolve one promise from array, ignore the errors

### ISSUE THREAD

**Issue by pke** [winjs/winjs#961]
I was misunderstanding how `WinJS.Promise.any` works. I thought it swallows the errors if at least one promise of the array could be fulfilled? Is there a way currently to do something like this:
```
anyFile = WinJS.Promise.anySwallowErrors([readFileAsync("file1.txt"),readFileAsync("file2.txt")]);
anyFile.then(function(fileContent) {
  // the content of either file1.txt or file2.txt could be read
}, function error(e) {
  logger.error("None of the files could be read");
});
```

If not, would that be a nice addition to the Promise framework?

**Comment by rigdern** [comment]
`WinJS.Promise.any` returns the first promise to complete regardless of whether it completes in a success state or an error state.

There's no function built into WinJS that has this behavior. However, you can build a custom helper that does this for your app.

We don't believe a method with this behavior would be general enough to include in WinJS. Thanks for your feedback.
