### ISSUE TITLE
Win JS and AI integration 

### ISSUE THREAD

**Issue by fidmor89** [winjs/winjs#968]
Hi Jeff,
I know its not an issue, but I couldn't find any other way talk to you.

I'm a Systems and Information engineering student. Me and a group of developers at the university would like to help with the integration of Win JS to Application Insights.  We have been working under Jakub Oleksy guidance to develop a few plugins to integrate the Application Insights PHP SDK to popular CMS.

Please email me if you have any ideas.
We would really appreciate very much your support.

Regards,
Fidel Esteban Morales Cifuentes
fidmor.89@outlook.com

**Comment by xirzec** [comment]
Responded via e-mail, closing this issue.
