### ISSUE TITLE
0x800a138f - JavaScript runtime error: Unable to get property 'winControl' of undefined or null reference

### ISSUE THREAD

**Issue by litunny** [winjs/winjs#972]
Hello, please the same issue here, my javascript is throwing error "0x800a138f - JavaScript runtime error: Unable to get property 'winControl' of undefined or null reference"

Please totally fed up, I have carried out the above solutions, but nothing change and still bringing the same error message, please help, maybe I'm doing some wrong things somewhere else. Thanks in advance.

**Comment by rigdern** [comment]
Can you provide a page/app that repros this bug? You can share the reduced repro on OneDrive as described on our [wiki](https://github.com/winjs/winjs/wiki/How-to-share-repros-of-issues-with-WinJS#sharing-videos-and-full-code-samples) (look at the "Sharing Videos and full Code Samples" section).

**Comment by omnoms** [comment]
My experience when this happens is that at the time of the event is being fired, the winControl has not been attached yet to the element you are querying. Ensure first of all that the element exists and then check that winControl is defined before trying to access it. For instance handling the appbar in the ready-statement, i do the following because of this;

```javascript
            var appbar = document.querySelector("#appbar");
            if (appbar && appbar.winControl) {
               ...
            }
```

**Comment by litunny** [comment]
OneDrive: https://onedrive.live.com/redir?resid=e459a4e92248d572!153&authkey=!AAXaFumFzsNRAOA&ithint=file%2czip


I attached the link to the zip folder of the Project. HELP ME OUT!!!

Thanks.

Emmanuel.

**Comment by omnoms** [comment]
Well.. good news is, I've implemented above solution, but the splitview controller doesn't seem to have a .winControl object... ever... in your project... don't know if splitview should have a winControl or not... if it is supposed to have one, then there's a bug with the rendering/binding of the controller to the element.

Doing a document.querySelector(".splitView") when the app is running and trying to access .winControl then, it will output undefined. No matter how many UI processAll() are run.


This is the main.js I have that isn't crashing.. but .winControl is never defined on the element.

```javascript
(function () {
    "use strict";

    WinJS.Namespace.define("Sample", {
        splitView: null,
        togglePane: WinJS.UI.eventHandler(function (ev) {
            if (Sample.splitView) {
                Sample.splitView.paneHidden = !Sample.splitView.paneHidden;
            }
        })
    });

    WinJS.UI.Pages.define("/pages/main/main.html", {
        // This function is called whenever a user navigates to this page. It
        // populates the page elements with the app's data.
        ready: function (element, options) {
            // TODO: Initialize the page here.z
            WinJS.Binding.processAll(element, Sample).then(function () {
                var sV_element = document.querySelector(".splitView");
                if (sV_element && sV_element.winControl) {
                    Sample.splitView = document.querySelector(".splitView").winControl;
                    new WinJS.UI._WinKeyboard(Sample.splitView.paneElement); // Temporary workaround: Draw keyboard focus visuals on NavBarCommands
                }
            }.bind(this));
        },

        unload: function () {
            // TODO: Respond to navigations away from this page.
        },

        updateLayout: function (element) {
            /// <param name="element" domElement="true" />

            // TODO: Respond to changes in layout.
        }
    });
})();
```

**Comment by rigdern** [comment]
@litunny It looks like your app is using WinJS 2.1 but the SplitView wasn't introduced until WinJS 4.0-preview. You can get WinJS 4.0-preview from various package managers such as NuGet. Our website shows all of the available methods for [getting WinJS 4.0-preview](http://try.buildwinjs.com/#get).

**Comment by litunny** [comment]
Good Day Here,

Thanks for your help, to making understand my mistake, I really appreciate
your effort and the entire Development Team, I just want to know how I can
actually update my WINJS 2.1 to WINJS 4.0-preview.

Thanks so much, looking forward to hearing from you Adam.

**Comment by rigdern** [comment]
@litunny The first thing to do is to obtain WinJS 4.0.0-preview using your preferred method. Our website lists the various ways you can get WinJS 4.0.0-preview: http://try.buildwinjs.com/#get. For example, you can install it thru package managers such as npm and NuGet. Or you can just download a zip containing WinJS 4.0.0-preview and copy that into your project.

Once you've done the step above and WinJS 4.0.0-preview is in your Visual Studio project, you need to update the `link` and `script` tags in your project to reference WinJS 4.0.0-preview instead of WinJS 2.1. For example, in `default.html` you might have some markup that references WinJS 2.1 like this:

```html
<!-- Example of references to WinJS 2.1 -->

<link href="/css/ui-themed.css" rel="stylesheet" /> 
<script src="//Microsoft.Phone.WinJS.2.1/js/base.js"></script> 
<script src="//Microsoft.Phone.WinJS.2.1/js/ui.js"></script> 
```

You'll want to change it to reference WinJS 4.0.0-preview like this (assuming you've put WinJS 4.0.0-preview into a folder called `winjs` at the root of your project):

```html
<!-- Example of references to WinJS 4.0.0-preview -->

<link href="/winjs/css/ui-dark.css" rel="stylesheet" /> 
<script src="/winjs/js/WinJS.js"></script> 
```

Once that is done, you can delete WinJS 2.1 from the references section in Solution Explorer in Visual Studio. With WinJS 4.0.0-preview, your app will look different due to styling changes we've done since WinJS 2.1 in order to match the new Windows 10 visuals.

**Comment by litunny** [comment]
Hello Adam,

I followed all those steps, but I notice that the WinJS global variable was
not found, thereby throwing error during the launching of the app.

I do not know what could cause this error.

The steps I've taken:

1.   I downloaded the WinJS from http://try.buildwinjs.com/#get
2.   Unzipped the folder and added the content of the folder to my project
source code
3.   Added the WinJS.min.js to the default.html page, removed the base.js
and ui.js

Please, I do not know what could go wrong, I've been searching and I'll
keep searching until, I get response from you and from any online developer
community forum.

Hope to hearing from you soon.

Thanks in advance once again.


Emmanuel.

**Comment by AmazingJaze** [comment]
@litunny 
 > I followed all those steps, but I notice that the WinJS global variable was
not found, thereby throwing error during the launching of the app.

From your description, it sounds like the WinJS.js file may not be loaded into your project. 
-When the exception is thrown, are you able to see the WinJS.js file as a loaded source in your debugger? 

If not I would make sure that 
1. The path you are using for your WinJS 4.0 source files accurately points to the location of your WinJS.js file

```html
<!-- Example of references to WinJS 4.0.0-preview -->

<link href="/winjs/css/ui-dark.css" rel="stylesheet" /> 
<script src="/winjs/js/WinJS.js"></script> 
```

2. Your project isn't trying to use WinJS before the sources have been loaded.
