### ISSUE TITLE
Try Site: ListView is jumpy when panning at slow and intermediate speeds on ipad mini

### ISSUE THREAD

**Issue by AmazingJaze** [winjs/winjs#973]
Found on the ipad mini.

http://1drv.ms/1LSXLFz

The problem seems to be exacerbated when the right edge of the listview viewport is clipped off the screen. Which is the default state, because the try site's Nav pane is pushing the right edge of the listview off the edge of the screen.

On other browsers, the listview seems to resize to avoid being pushed out of the window by the navpane.

**Comment by rigdern** [comment]
@AmazingJaze Can you check if this repros when you put a ListView in a scrollable div and the ListView is scrolled partially off screen?
