### ISSUE TITLE
IOS Rating control's tooltip can get stuck on screen.

### ISSUE THREAD

**Issue by AmazingJaze** [winjs/winjs#974]
Found on the Ipad Mini

Go to  the Rating Samples page at try.buildwinjs.com
1. Find the "Number of Stars" rating control. 
2. Press and hold on the 3rd star until the "3" tooltip appears
3. Without releasing your finger, drag up over the "User Rating" Rating control.
4. Without releasing your finger, drag to the right, the tooltip on the original "Number of Stars" Rating control should continue to update 1 or 2 times.
5. Relase your finger.

__Expected:__ The tooltip vanishes when you release your finger.
__Actual:__ Tooltip on the "Number of Stars" rating control disappears then reappears and gets stuck on screen

**Comment by rigdern** [comment]
Might be related to #811. They both seem to have a stuck hover state on iOS.
