### ISSUE TITLE
Try site: SplitView sample on mobile is not wide enough.

### ISSUE THREAD

**Issue by AmazingJaze** [winjs/winjs#975]
On an Ipad mini go to the SplitView trysite page, scroll down to the sample "Change SplitView Pane Display Modes": 

Click the tradio button for "Large Screen" and notice that it creates a smaller screen than the "Medium Screen" radio button option..

**Comment by rigdern** [comment]
I think this is already fixed. Can you confirm?

**Comment by AmazingJaze** [comment]
verified fixed.
