### ISSUE TITLE
Promise: Can the continuation handler .then be called more than once?

### ISSUE THREAD

**Issue by pke** [winjs/winjs#983]
I want to simplify file change notifications like this:

```
StorageFileWatcher.watch(file).then(function(changedFile) {
});
```

But somehow this code looks wrong to me, as the continuation handler would be called whenever the file changes. I don't like the "callback" approach any-more, but maybe its more appropriate here.

```
StorageFileWatcher.watch(file, function(changedFile) {
});
```

`StorageFileWatcher.watch(file)` would do all the plumbing and essential look like this:

```
watch = function(file) {
  return new WinJS.Promise(function(c,e,p) {
    // Register file.parent folder query 
    query.addEventListener("contentschanged", function() {
      // check if the file was changed
      if (file was changed) {
        c();
      }      
    });
  });
}

**Comment by rigdern** [comment]
> Can the continuation handler .then be called more than once?

No, the `then` callback will only be called one time. Promises are designed for one off tasks.

The callback approach is appropriate there. If you are interested in an alternative approach, you can use a library like [RxJS](https://github.com/Reactive-Extensions/RxJS) which is designed to solve this kind of problem. RxJS is describes itself as *a set of libraries to compose asynchronous and event-based programs using observable collections and Array#extras style composition in JavaScript*. In RxJS, you might solve your problem with something like this (I haven't actually tested this code):

```js
Rx.Observable.fromEvent(query, 'contentschanged').forEach(function (changedFile) {
  // Handle changed file
});
```

**Comment by pke** [comment]
Thanks! Yes something felt fishy about this and the callback seems just fine. Will look into rx again though.
