### ISSUE TITLE
WinJS 4.0: Links, Back button, Flyouts, Listview and Hub issues

### ISSUE THREAD

**Issue by pke** [winjs/winjs#984]
## Intro
All of those things mentioned above worked in WinJS 3.x and are now somewhat broken.
Not sure if I should create separate issues for each of them? Or you say: Its still early beta, we know about those glitches then please feel free to close that one.

### Links
In Windows Store Apps links have never been underlined but displayed in a distinct colour. The WinJS 4.x CSS underlines links now and displays them in IE default colours (ui-light).

### Back Button
The back button we used to place on the canvas for multi page navigation, has no border anymore and a dark grey (rectangular) background on hover/click. Rectangular, which is funny, cause the app bar commands also used to be round and are now rectangular. And the toggle control was rectangular and is now round. As the _only_ control, mind you. Those changes are not consistent, imho.

### Flyouts that display another flyout close themself
I have a flyout that displays a listview. When the selects an item a secondary confirmation flyout is displayed. When the user hovers over the secondary flyout it is immediately closed.

### Ugly focus rectangle on first item of listview (in flyouts)
![image](https://cloud.githubusercontent.com/assets/164625/6816123/34a23344-d28f-11e4-92db-771db5d442e8.png)

### Hub is not showing all sections
My hub control displayed 6 sections in WinJS 3.x
With WinJS it displays only 3. Might have to do with snapping styles.

### Summary
In General it seems WinJS 4 breaks a lot of old code/styles. It changes font sizes, line heights, standard control backgrounds, link colours, markup/style for command buttons. I am going to start to work on a fresh app in April based on WinJS 4 but converting a WinJS 3.x app to 4.x seems a lot of work atm.

This is how the app looked in WinJS 3.x CSS
![image](https://cloud.githubusercontent.com/assets/164625/6816164/b7ad95ee-d28f-11e4-82b3-9e1ca316f523.png)

Notice the command button on the top right corner that is completely invisible with WinJS 4 CSS

Mind you that is not the first time I struggle with a version upgrade. WinJS 2 -> 3 was equally painful. I hope for a better migration path in the future from the company that can allows me to run the Windows 1.0 calc.exe in Windows 10 :) All this X-platform effort is great, but I hope you don't forget your Windows Store app developers, for whom WinJS was originally created, along the way.

:+1: Keep up the good work!

**Comment by rigdern** [comment]
Thanks, @pke. We really appreciate the feedback!

> In Windows Store Apps links have never been underlined but displayed in a distinct colour. The WinJS 4.x CSS underlines links now and displays them in IE default colours (ui-light).

This was an intentional change now that WinJS is designed to also be used on webpages. See #893 

> The back button we used to place on the canvas for multi page navigation, has no border anymore and a dark grey (rectangular) background on hover/click. Rectangular, which is funny, cause the app bar commands also used to be round and are now rectangular. And the toggle control was rectangular and is now round.

These changes are all intentional.

> I have a flyout that displays a listview. When the selects an item a secondary confirmation flyout is displayed. When the user hovers over the secondary flyout it is immediately closed.

Can you open an issue about this and include a reduced repro?

> Ugly focus rectangle on first item of listview (in flyouts)

Can you elaborate on this issue? What is the problem exactly? Is it just that you think the ListView's new dashed keyboard focus visual is ugly? Is it that the keyboard focus visual is being drawn even though the user isn't using the keyboard? Is it that the ListView is receiving focus just by showing the Flyout that hosts the ListView?

> Hub is not showing all sections

That is strange. Can you open a new issue and attach a reduced repro?

**Comment by pke** [comment]
> These [visual] changes are all intentional.

I've understood that by now. But they are heavily breaking existing Windows Store apps. We can not just upgrade the codebase to 4.0 without getting a visually impaired app. Was that never a concern when you decided to go x-platform/web? WinJS origins are Windows Store apps. I have yet to see anyone using it in webapps and I fear the focus of development has shifted too far away from (also supporting) Windows Store apps. If I take WinJS 4.0 today and put it in one of the MSDN Store samples or Visual Studio app templates basically everything breaks.

Maybe I am pushing the framework to often to its limits, but backward compatibility was one of MSFT greatest strengths in past Windows versions. Painfully so at times as Raymond Chen documented over the years. But with the current path WinJS is taking I already consider switching to XAML which I always considered inferior to HTML/JS/CSS especially in the styling aspects. *yikes*

The listview focus rectangle is visually ugly, yes, the functionality is just fine. That's 'imho' of course, but we Store app developers are used to a much more reduced style. Less chrome, remember?

I have opened an issue for the disappearing flyouts in combination with listviews here #986

**Comment by xirzec** [comment]
WinJS and Windows 10 does still have back compat. You can deploy a WinJS 1.0/2.0 app as-is from the Store and it will continue to work on Windows 10. 

However, if you want your app to target Windows 10 with its new look and feel (which WinJS 4.0 provides) you have to deal with some breaking changes. So either you can have the new UX or you can have perfect compatibility, but not both.

**Comment by pke** [comment]
I know I can stay on WinJS 3.x forever, just not getting important bug fixes then, cause you do no back-ports do you?

I need to fix my nodejs install and cherrypick what I need myself. Single app breaking WinJS 3.x issue I need to fix: dbc7a96d

Then I will come back to WinJS 4.0 when its done ;)

**Comment by TheWrathOfConst** [comment]
Thanks for your feedback. It's been incorporated into other bugs. Closin' this issue
