### ISSUE TITLE
feature: Add WinJS.version

### ISSUE THREAD

**Issue by pke** [winjs/winjs#991]
It would be nice to have the WinJS version accessible in code to add it to the about dialog/HttpClient User-Agent header.

I am currently parsing it out of 

```
global.msWriteProfilerMark && msWriteProfilerMark('WinJS.3.0 3.0.0.winjs.2014.10.2 WinJS.js,StartTM');
```
but that is highly inefficient.

**Comment by xirzec** [comment]
You should be able to get this from `WinJS.Utilities._version` as per #790

**Comment by rigdern** [comment]
But that is private. Should we make it public so developers can officially take a dependency on it?

**Comment by xirzec** [comment]
Potentially, though using a private can't be any worse than @pke parsing it out of global.msWriteProfilerMark.

**Comment by pke** [comment]
@xirzec true true. That was just a poor man's attempt, cause I am on WinJS 3.0 atm. 
I see no harm making it a read-only public property of WinJS.

**Comment by jayrenn** [comment]
Thanks for the suggestion! I have added this request to our internal tracking.
