### ISSUE TITLE
How to filter items in a WinJS.UI.StorageDataSource?

### ISSUE THREAD

**Issue by pke** [winjs/winjs#993]
We can `createFiltered` on IBindingList but there seems to be no way to create a projection of the items in a `WinJS.UI.StorageDataSource`. The docs also say that you cannot group views. 

Seems I must create my own BindingList based implementation of a file system view?

**Comment by rigdern** [comment]
Yes, it seems like a `Binding.List` might be a good solution.

I looked at the [docs for `StorageDataSource`](https://msdn.microsoft.com/en-us/library/windows/apps/br212651.aspx) a bit. Notice that the `query` argument to the constructor is of type `IStorageQueryResultBase`. Searching further, I [found a page](https://msdn.microsoft.com/en-us/library/windows/apps/br208007.aspx) that describes `IStorageQueryResultBase` queries for filtering based on file type. So it appears that `StorageDataSource` supports limited filtering capabilities.
