### ISSUE TITLE
Context menu placement bad if you open it at the bottom of window

### ISSUE THREAD

**Issue by caseyfaber** [winjs/winjs#995]
If you open a context menu at the bottom of a window, it opens a tiny menu with scrollbars. It should open upwards instead if there is no room for the menu.

![image](https://cloud.githubusercontent.com/assets/2295203/6858719/81f36628-d3ce-11e4-92d9-91b1f1cacf2c.png)

**Comment by rigdern** [comment]
@AmazingJaze Will this be fixed by the cascading menu/flyout positioning work?

**Comment by AmazingJaze** [comment]
@rigdern No it won't.

@caseyfaber can you tell us what value that menu's ```placement``` property set to? If it is set to "bottom" it will do the behavior shown in your screen shot. It needs to be set to "auto" or "autovertical" to get adaptive placement behavior when showing.

**Comment by caseyfaber** [comment]
Ah, yes, it is set to "bottom". Thank you!

**Comment by caseyfaber** [comment]
That fixes it, thanks!
