### ISSUE TITLE
JS Editor from http://try.buildwinjs.com/ available?

### ISSUE THREAD

**Issue by pke** [winjs/winjs#996]
I want to supply my app with a live javascript console that I can use when no debugger is attached to change some state variables or query their values.

The console should have a single/multiline input and an output area to print the results. I like the syntax completion of the JS Editor on the tryout site. I wonder if that code is available for use in my console. I guess it makes a live query on the globally available objects and inspects them while the user is typing to provide the suggestions?

**Comment by rigdern** [comment]
Unfortunately, our editor is not publicly available for use. Here are some editors which have autocomplete demos:
  - [CodeMirror](https://codemirror.net/demo/complete.html)
  - [ACE](http://ace.c9.io/demo/autocompletion.html)
