### ISSUE TITLE
4.0 preview minimized CSS is not working

### ISSUE THREAD

**Issue by nhutquang97** [winjs/winjs#997]
I tested the 4.0 preview (zip) with my app. And when I added the ui-dark.min.css or ui-light.min.css, they don't work properly. ui-dark.css and ui-light.css work just fine. Hope you guys can find out what happened. (I tested with my Windows universal app).

**Comment by rigdern** [comment]
Thanks for the report!

@phosphoer Our minified CSS file has syntax errors in it so it doesn't work. Perhaps the minifier is having trouble with the `-ms-lang` selectors. I extracted this from `ui-dark.min.css`:

```css
.win-textarea:-ms-lang(am,.win-type-large
```

**Comment by phosphoer** [comment]
We use [grunt-contrib-cssmin](https://github.com/gruntjs/grunt-contrib-cssmin) to perform our minification step, which in turn uses [clean-css](https://github.com/jakubpawlowicz/clean-css). We should file an issue on clean-css about the `-ms-lang()` selectors.

For the time being I will remove the css minification step and close this issue.

**Comment by phosphoer** [comment]
After a bit of investigation I found that we were using an old version of grunt-contrib-cssmin, which relied on an even older version of clean-css. Updating the module will fix the bug, so we should re-add the minification step using the new version.
