### ISSUE TITLE
Windows Phone: input element height too small

### ISSUE THREAD

**Issue by pke** [winjs/winjs#998]
In my universal app the input field is always only a 1/3 of its required height on the phone. Easy to reproduce with a blank Universal App project where you put an `input` element in the body.

**Comment by jseanxu** [comment]
I created a blank UAP with just an input tag and it looks fine to me. Could you share a screenshot?

**Comment by pke** [comment]
Sure: 
![wphone tiny input box](https://cloud.githubusercontent.com/assets/164625/6910547/e0dbbe0e-d754-11e4-94fe-95396370c291.png)

**Comment by jseanxu** [comment]
That looks strange indeed. I can't tell the DOM structure from just the picture, could you share the project or a minimal repro?

**Comment by pke** [comment]
Minimal repro easily done. Please see here: http://1drv.ms/1JZUKlN

**Comment by jseanxu** [comment]
You are missing the `type="text"` attribute on your `input` tag. I've reopened the issue, please let us know if this resolves your issue.

**Comment by pke** [comment]
Is this a required attribute? I thought the default is "text"?

**Comment by jseanxu** [comment]
It is required for WinJS to style your `input`.

As to why it is required I'm not 100% sure. I'm guessing that this is to prevent accidentally styling other input types that we do not explicitly style. For example, if we styled all `input` tags as if it was a textbox, then that style would apply to `type="color"` as well even though WinJS does not have a styling story for that particular input type.

**Comment by pke** [comment]
I don't see where the height of the element is set by WinJS CSS?
In any case I think its wrong to require the developer to specify the type if the specs clearly state that the default is text. So in WinJS CSS this should be considered the default too. Since you already style in painful detail every control by its type an additional `[type='']` rule for the default (text) inputs wouldn't hurt and save me and others hours of trying to find the bug in my styles/markup.

**Comment by jseanxu** [comment]
Great suggestion, I'll bring it up during our next issue triage, thanks :)

Just to confirm, though, setting the `type` attribute does fix your original issue right?

**Comment by pke** [comment]
> Just to confirm, though, setting the type attribute does fix your original issue right?

right ;)

Will you report here what you decided during the next issue triage, please?

btw: are you guys at this years //build?

**Comment by jseanxu** [comment]
>>Will you report here what you decided during the next issue triage, please?

Will do

>>btw: are you guys at this years //build?

I can't speak about who will be attending, but I am sure WinJS will be represented :)

**Comment by jseanxu** [comment]
Hey @pke,
We decided to go with a fix, this should cover scenarios where you have `<input />`, `<input type />` or `<input type="" />` but not break scenarios such as `<input type="color" />`

**Comment by pke** [comment]
Very good! Thanks!
